### PR TITLE
remove outdated Undo MagicQuotes function

### PR DESCRIPTION
**Pull request by Flyingmana**
php 7.4 related change, as the used function get_magic_quotes_gpc() is now deprecated

### CODE REVIEW

**Comment by kkrieger85** [comment]
```
/**
 * Gets the current configuration setting of magic quotes gpc
 * @link https://php.net/manual/en/function.get-magic-quotes-gpc.php
 * @return int 0 if magic quotes gpc are off, 1 otherwise.
 * @since 4.0
 * @since 5.0
 * @deprecated 7.4
 */
function get_magic_quotes_gpc () {}
```

@Flyingmana Do we need to test for backward compatibility?

**Comment by colinmollenhour** [comment]
What about changing the first line to:

```php
if (function_exists('get_magic_quotes_gpc') && get_magic_quotes_gpc()) {
```

**Comment by Flyingmana** [comment]
@colinmollenhour do you have a suggestion, when we can retire this code block completely then?

**Comment by colinmollenhour** [comment]
Ahh, my bad, I just noticed this:

> 5.4.0 | Always returns FALSE because the magic quotes feature was removed from PHP.

So it can be removed now since 5.3 is already EOL and not supported and there is no effect on any supported version.

**Pull request merged**
