### PR TITLE
Prevent delete/disable CMS pages used in configuration

### PR DESCRIPTION
**Pull request by sreichel**
### Reproduce

Try to disable/delete configured `no-route` page.

### Related Pull Requests

1. See OpenMage/magento-lts#2979

### CODE REVIEW

**Comment by empiricompany** [comment]
Isn't it better to put it in the controller? 

Resource should not do these checks

**Comment by sreichel** [comment]
There are different checks in resource, e.g. `getIsUniquePageToStores`.

Having it in model allows to use ... `Mage::getModel('cms/page')->load(1)->getUsedInStoreConfigCollection()`

**Comment by ADDISON74** [comment]
Tested an it does what it says. Do you need to add anything to it?

**Comment by sreichel** [comment]
Maybe a unit test for the helper method, but this can be done in another PR.

**Comment by ADDISON74** [comment]
I am testing this PR. For the 404 Not Found page (no-route). 

1. If I delete it the message is "Cannot delete page, it is used in "web/default/cms_no_route".

2. If I disable it I am getting two messages "Cannot disable page, it is used in "web/default/cms_no_route" and "The page has been saved." This can be cofusing.

Another observation changing the URL Key will have negative impact. For example, from no-route to no-route-2.

**Comment by sreichel** [comment]
Having two messages is intended.

The page gets saved, but resets "is active" option to yes.

I have not tested changing url-key ... what happens? (I am not at home to test it)

**Comment by ADDISON74** [comment]
Changing the **URL key** of that page is similar to actions such as delete or disable, because once the URL is changed that page will no longer be used and therefore it will be a problem. My opinion is that it should not be allowed to change the URL as long as it is used.

url_key

**Comment by sreichel** [comment]
Good idea.

I think there are other scenarios to cover ...

- having multiple pages with same identifier for different store
- having different pages configured for different stores

**Comment by sreichel** [comment]
Better leave it for another PR.

**Comment by ADDISON74** [comment]
> Better leave it for another PR.

@sreichel - I agree. What else I would propose for this PR would be a different message, for example

**You cannot delete or disable the page nor change the URL Key as long as it is used as a Default Page in the configuration.**

One message covers all the situations and makes the things clear. Like a general warning what you cannot do.

**Comment by sreichel** [comment]
> One message covers all the situations

This will not work. There is a difference between them.

When deleting an exception is thrown (red message) and the action is aborted.

When disabling the "save action" continues, all other changes are applied, but active state is set back and a warning (yellow message) is left.

**Review by kiatng — APPROVED** [review]
Tested

**Review by ADDISON74 — APPROVED** [review]

**Pull request merged**
