### PR TITLE
Price Alerts unsubscribe - Wrong messages 

### PR DESCRIPTION
**Pull request by ADDISON74**
Wrong messages when you click to unsubscribe from receiving price alerts for that product/all products.

The issue was discussed here #1584.

### CODE REVIEW

**Comment by fballiano** [comment]
is the modification to app/code/core/Mage/ImportExport/Block/Adminhtml/Export/Filter.php really needed for this PR?

**Comment by ADDISON74** [comment]
You are right. By mistake it got caught from another PR that I posted before. The approval of this PR will not affect the code in any way because that change in export file is also in another PR from today.

**Comment by fballiano** [comment]
yes but that PR may not be approved, would it be possible to change this PR removing that modification?

sorry!!

**Comment by ADDISON74** [comment]
Today I worked far away from the office directly on GitHub. I deleted that branch so I can't make any changes in this PR. If a maintainer can do the change it will be perfect, Otherwise I will close this PR next week and post it again. I could change its description as I mentioned before it solves another reported issue which has already been posted in another PR.

**Comment by ADDISON74** [comment]
The change in Filter.php file is also in this PR #1928. The approval of the two PR's will keep the changes.

**Comment by elidrissidev** [comment]
@ADDISON74 Tip: when you make a commit directly from GitHub, there is an option to create it in a new branch, that way you separate your work.

**Comment by elidrissidev** [comment]
Fun fact: even GitHub errors out when trying to review this PR, I think because of the deleted branch.

**Comment by elidrissidev** [comment]
Can you update the translation of the lines you modified? I'm unable to create a review for some reason.

**Comment by ADDISON74** [comment]
I will close this PR and create a new one which will correct all issues, including translations if the strings are missing.

**Comment by fballiano** [comment]
actually, I've been thinking about it and it's probably not a good idea to change the messages in the source code, it would break every language pack already out there, and we can't fix those.

so in my opinion it would be much better to leave the source as it is and "translate" those messages via language CSV file, in this case https://github.com/OpenMage/magento-lts/blob/1.9.4.x/app/locale/en_US/Mage_ProductAlert.csv

**Comment by ADDISON74** [comment]
Don't worry. I've fixed the issue. The correct PR is here #1929. 

I only added one line in Mage_ProductAlert.csv related to price. For stock there was one already. It seems the Magento team missed it.

**Pull request closed without merging**
