### PR TITLE
Updated the existing DDEV documentation

### PR DESCRIPTION
**Pull request by ADDISON74**
This PR aims to update the existing documentation in OpenMage about the DDEV test environment. Please note that this is just a small bag of elementary knowledge to be able to use it.

Those who haven't tried DDEV so far would do well to give it a chance. Since I discovered it a year and a half ago, I haven't tested OpenMage in Linux distributions. It runs quickly in Windows + WSL + Docker and it is so easy to install.

### CODE REVIEW

**Review by fballiano — APPROVED** [review]

**Review by Flyingmana — APPROVED** [review]

**Comment by fballiano** [comment]
@ADDISON74 do you need to add/modify more things or can we merge?

**Comment by ADDISON74** [comment]
Let's give it one more day. I have to make small changes.

**Comment by ADDISON74** [comment]
Thank you for the approvals. 

I made several changes and additions. I will let you know when it can be approved.

**Review by Flyingmana — DISMISSED** [review]

**Comment by ADDISON74** [comment]
It must be checked if the image I used at the end will be displayed after integration in OpenMage.

**Comment by fballiano** [comment]
I don't see anything wrong with the info so I'll merge it right away, the image should work but it's linked to your repo so I'll try to reupload it on the openmage's one.

**Pull request merged**
