### PR TITLE
Bump version to v20.11.0

### PR DESCRIPTION
**Pull request by sreichel**
Release coming :)

### CODE REVIEW

**Review by kiatng — APPROVED** [review]

**Review by addison74 — APPROVED** [review]

**Comment by ajbonner** [comment]
Some great PHP 8.4 fixes here, we're deploying to it in early Jan so very thankful for the timing!

**Comment by sreichel** [comment]
@colinmollenhour can you please confirm composer-plugin works as intented? (adding license files to right places)

**Comment by sreichel** [comment]
@colinmollenhour please update https://cauldron.io/project/4125?from_date=2023-12-19&to_date=2024-12-19&tab=overview too.

**Comment by sreichel** [comment]
@colinmollenhour i am no a maintainer, so i pass it to you, to publish a new release. Thanks.

**Comment by colinmollenhour** [comment]
@sreichel I wasn't planning to write a fancy release page, I just used the auto-generate button and then re-sorted the lines for better readability. It can be re-tagged after this is merged. Did you want to add anything to the release page?

**Comment by sreichel** [comment]
?

**Comment by colinmollenhour** [comment]
> can you please confirm composer-plugin works as intented? (adding TinyMCE license files to right places)

Looks good except there is a typo in the filename `LICENSE_TINYMCE_OPENAMGE.txt`
 
> Can you also please publish the fixed CVE?

I merged but there is some discussion on the advisory.

**Comment by colinmollenhour** [comment]
Regarding TinyMCE, I sent an email to them asking about the agreement - I think we are fully aligned on terms but they were going to make some edits and send it back but never did.

**Comment by sreichel** [comment]
Fixed typo in composer plugin.

**Comment by sreichel** [comment]
@colinmollenhour ... we missed that PR.

**Comment by colinmollenhour** [comment]
Oops.. I deleted and re-tagged after merging.

**Comment by sreichel** [comment]
Not sure if its related, but latest release has not zip-archive attached.

**Pull request merged**
