### PR TITLE
Delete RELEASE_NOTES.txt

### PR DESCRIPTION
**Pull request by fballiano**
This file was already deleted from 1.9.4 branch but not ported to the 20.0. Reference PR is https://github.com/OpenMage/magento-lts/pull/1469

### CODE REVIEW

**Review by colinmollenhour — APPROVED** [review]

**Comment by Flyingmana** [comment]
This will happen automatically as part of the release process during the forward porting from 19 => 20

**Comment by fballiano** [comment]
when will it happen? my previous PR was in february? wouldn't it be better for these kind of merges to happen right away? otherwise the more time passes the more the merge could be problematic.

**Comment by fballiano** [comment]
So sorry, I've seen the 20.0.8 release now. closing this one

**Comment by Flyingmana** [comment]
As for now, the merges have usually no conflict, so waiting till release did work out well.
Maybe we will automate it via a cron based github action at one point

**Pull request closed without merging**
