### PR TITLE
Fix static tests forPHP 7.4

### PR DESCRIPTION
**Pull request by szymonbdeligo**

### CODE REVIEW

**Comment by tmotyl** [comment]
Isnt there already a mr for this https://github.com/OpenMage/magento-lts/pull/1047/files ?
Lets review one and get merged

**Comment by sreichel** [comment]
It looks like a dupe ;)

(OT ...why i am able to merge this w/o reviews?)

**Comment by szymonbdeligo** [comment]
It was not a duplicate because it was not merged to branch 1.9.4.x. This commit was a part of work on branch `functional-test-suite`

**Comment by sreichel** [comment]
The fixes are the same, but I'd prefer this one .... i have change made that was not necessary.

**Pull request merged**
