### PR TITLE
Removed unused variable

### PR DESCRIPTION
**Pull request by midlan**
### Description (*)

Just removed unused variable.

### Fixed Issues (if relevant)

1. Fixes OpenMage/magento-lts#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by kiatng — DISMISSED** [review]

**Comment by Flyingmana** [comment]
could have unintended side effects on internal initialization and also about when the event "adminhtml_init_system_config" is called

**Comment by midlan** [comment]
@Flyingmana you are right about the event `adminhtml_init_system_config`, we should check if there is observers for it

About the init, seems safe to me. It is simple [lazy-loading pattern](https://en.wikipedia.org/wiki/Lazy_loading), I don't see how it may behave differently when lazy-loaded from different model.

**Review by luigifab — DISMISSED** [review]
PayPal use the `adminhtml_init_system_config` event with `paypal/observer::loadCountryDependentSolutionsConfig`.
But I didn't see any emails added with `Mage_Paypal`.

The only configuration about email that I found is: `email_confirmation`, used in API request.

**Comment by Flyingmana** [comment]
I moved it to the 20.0 branch, because even if it looks ok, I want to not risk issues, and its not a bugfix, so not necessarily needed in the 1.9.4.x branch.

**Pull request merged**
