### PR TITLE
Revert "Deprecation errors are not suppressed anymore (#3102)"

### PR DESCRIPTION
**Pull request by sreichel**
### Description (*)

This reverts commit 400c85a55ccc4927b79b379ec19e93b8fea994c9.

`DEVELOPER_MODE` is turned on to see exceptions, but i really dont want to see "Deprecated functionality:" errors for common actions.

### Related Pull Requests

1. See OpenMage/magento-lts#3102

### Manual testing scenarios (*)

1. php 8.1
2. admin -> customer ->select a customer

```
Deprecated functionality: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated  in /var/www/html/app/design/adminhtml/default/default/template/widget/tabs.phtml on line 29

#0 [internal function]: mageCoreErrorHandler(8192, 'preg_match(): P...', '/var/www/html/a...', 29)
#1 /var/www/html/app/design/adminhtml/default/default/template/widget/tabs.phtml(29): preg_match('/\\s?ajax\\s?/', NULL)
#2 /var/www/html/app/code/core/Mage/Core/Block/Template.php(251): include('/var/www/html/a...')
#3 /var/www/html/app/code/core/Mage/Core/Block/Template.php(288): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
```

### Questions or comments

Should be removed in `next` when php81+ is battle tested?

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Comment by fballiano** [comment]
it is very important that the deprecation messages are not hidden, they will become fatal errors very soon since the minimum actively supported php version RIGHT NOW is 8.1

Screenshot 2023-04-14 alle 23 09 57

we should not revert this not even in main.
i'm against this PR.

**Comment by ADDISON74** [comment]
We must not lose sight of the fact that certain Linux distributions have their own LTS.

Debian 9 (PHP 7.0) => LTS June 2022 (I am still using this version with some heavy installations)
Debian 10 (PHP 7.3) => LTS June 2024
Debian 11 (PHP 7.4) => LTS June 2026
Debian 12 (PHP 8.1) => LTS June 2028

Using Debian over the years I didn't need the packages from Sury in the last 10 years. When I saw what happened with CentOS, I congratulated myself for the decision made in the past. Ubuntu is actually Debian but not so stable.

**Comment by sreichel** [comment]
> it is very important that developers start fixing these problems, also, they're only shown in developer mode.

Developer mode is not to be forced to fix deprecated code in core.

The ENV variable was excatly for those who work on php8.1+-support - w/o disturbing others.

**Comment by fballiano** [comment]
we ARE solving those in the core already.

and it is far more important for people to upgrade (PCI compliance) and to fix the problems in the 3rd party code.

anyway, I've spoken already. this makes me tired.

**Comment by sreichel** [comment]
> we ARE solving those in the core already.

... and until its done, it should be possible to turn depreaction errors off!

**Comment by fballiano** [comment]
good idea, let's revert this, hide the errors so that nobody will see them (as it happened until today), nobody will report them and nobody will fix them.

no.

**Comment by luigifab** [comment]
And... a new env `MAGE_IS_DEVELOPER_MODE_NOTICE` to make everyone happy?
From commit 400c85a, why _PEAR specific message handling_ can also be removed?

**Comment by ADDISON74** [comment]
I think that all errors, warnings, must be visible in order to solve them ASAP. This week I reported a lot of errors I am getting in the logs and browser with PHP > 8 and some of them have already been solved and it remains to make a list of the existing ones. 

I wouldn't have known about them if it wasn't for #3102. However, if someone does not want them to be displayed, then they should have the possibility to hide them. Here is the problem, we hide them from the very beginning or we leave it to everyone's discretion to activate them, mentioning this feature in the README file.

**Comment by sreichel** [comment]
> good idea, let's revert this, hide the errors so that nobody will see them (as it happened until today), nobody will report them and nobody will fix them.
> 
> no.

There was a flag for. However ...

**Comment by ADDISON74** [comment]
This PR discussed very well the fact that not everyone wants to see errors. I am not trying to find out the reasons, but there are also such people. This means challenging #3102, but we no longer have the possibility to control the display of errors as it was before this. Am I wrong in saying this?

**Comment by fballiano** [comment]
Developer mode is enough, and we maintainers have to fix all of the deprecations asap

**Comment by fballiano** [comment]
And being in “rc” phase is perfect for showing more error messages instead of huding then

**Comment by sreichel** [comment]
> Developer mode is enough

Thanks.

**Pull request closed without merging**
