### PR TITLE
Added support to specify file upload dir in system configuration

### PR DESCRIPTION
**Pull request by eneiasramos**
Added support to specify filesystem's directory in file upload ...

### CODE REVIEW

**Comment by ADDISON74** [comment]
@eneiasramos - I need more details about this PR. I have some time to test it.

**Comment by eneiasramos** [comment]
@ADDISON74 my dear

The routine here allows a file to be uploaded to a folder different from media.

The idea is to allow the upload of a file, but not to expose the file to the internet (like the media folder does).

A use of case: I use the var folder to store PFX certificates used to communicate with a third party system:

```
<upload_dir allowed_extensions="pfx" config="system/filesystem/var" scope_info="1">brazil/cert</upload_dir>
```

https://github.com/gamuzatech/tolucastore-openmage/blob/f559a0e819a3124599b392fc3c4defe5c3803b68/app/code/local/Gamuza/Brazil/etc/system.xml#L400

**Comment by kiatng** [comment]
Review Notes:
This PR is to allow setting the root dir for file upload in the backend, in which the upload field is configured in the files `system.xml`. An example:

```xml
                        <filename translate="label" module="brazil">
                            <label>Filename</label>
                            <frontend_type>file</frontend_type>
                            <backend_model>adminhtml/system_config_backend_file</backend_model>
                            <upload_dir allowed_extensions="pfx" config="system/filesystem/var" scope_info="1">brazil/cert</upload_dir>
                            <sort_order>20</sort_order>
                            <show_in_default>1</show_in_default>
                            <show_in_website>1</show_in_website>
                            <show_in_store>1</show_in_store>
                            <depends><type_id>1</type_id></depends>
                        </filename>
```

In the above example, the `config`  attribute  of the `upload_dir` node is referenced to this:

https://github.com/OpenMage/magento-lts/blob/ced031d7ed2591f3f418485072d17f9e563dea9e/app/etc/config.xml#L114-L132

Based on the above, the config path is `{{var_dir}}`, which points to the `var` dir at OM root. 

Before this PR, regardless of the attribute `config` value, the upload file always go to the `media` dir. With this PR, it will respect the config, in the example, it will allow upload to the `var` dir.

**Review by kiatng — APPROVED** [review]
Approved based on testing `protected function _getUploadRoot($token)`.

**Comment by eneiasramos** [comment]
@kiatng thank you my dear!

**Comment by fballiano** [comment]
I've modified the PR slightly because if you'd use

`<upload_dir config="system/filesystem/UNEXSTING" scope_info="1">sales/store/logo</upload_dir>`

it would generate a null parameter warning.

tested quite some cases and it seems to work correctly now

**Review by fballiano — APPROVED** [review]

**Comment by eneiasramos** [comment]
@fballiano perfect!

**Comment by fballiano** [comment]
I'll merge it in a couple of days just to see if we get some more feedback, thank you @eneiasramos

**Comment by eneiasramos** [comment]
@fballiano thank you!

**Review by elidrissidev — APPROVED** [review]

**Review by kiatng — APPROVED** [review]

**Pull request merged**
