### PR TITLE
20.0 1095 remove notification survey block

### PR DESCRIPTION
**Pull request by kkrieger85**
Remove block in adminhtml template:
<type="adminhtml/notification_survey" name="notification_survey" template="notification/survey.phtml"/>
Remove survey related code
Remove survey related translation

See also #1267

### CODE REVIEW

**Review by Flyingmana — DISMISSED** [review]

**Comment by Flyingmana** [comment]
I think we should keep the phpstorm metadata thing separated in the future, maybe putting this into a github action which updates this once a month

**Comment by sreichel** [comment]
> 
> 
> I think we should keep the phpstorm metadata thing separated in the future, maybe putting this into a github action which updates this once a month

Is it possible w/o n98 a composer requirement and pre-commit-hook?

**Comment by Flyingmana** [comment]
Yes

**Comment by fballiano** [comment]
I think this will create a conflict when https://github.com/OpenMage/magento-lts/pull/1267 will be ported to the v20 branch. I think it should be closed.

**Comment by luigifab** [comment]
If I remember correctly, it's the same changes.

**Comment by luigifab** [comment]
So, this is the closing day?

**Comment by fballiano** [comment]
exactly, same changes plus some phpstorm metadata, but I'll close this anyway

**Pull request closed without merging**
