### PR TITLE
Fixed currency convert exception

### PR DESCRIPTION
**Pull request by rafdol**
Parameter `$toCurrency` can be `null` or `string` or `Mage_Directory_Model_Currency` object. If `$toCurrency` is `string` and rate doen't exists then we have fatal error (`Call to a member function ... on string` against exception. This is fix for described problem.

### CODE REVIEW

**Comment by colinmollenhour** [comment]
Seems this could have been fixed with impact to only one line of code using something like:

`$toCurrency instanceof Mage_Directory_Model_Currency ? $toCurrency->getCode() : $toCurrency`

**Comment by sreichel** [comment]
Nice, this was on my to-do list, too.

**Comment by dariuszmaciejewski** [comment]
@colinmollenhour class names are pretty long in Magento 1, so I am not sure your suggestion is easier to read. Especially if a method call (getter) occurs.

**Comment by colinmollenhour** [comment]
> @colinmollenhour class names are pretty long in Magento 1, so I am not sure your suggestion is easier to read. Especially if a method call (getter) occurs.

Sure, but the main motivation is +1,-1  lines changed instead of +13,-6. Fewer lines changed, less chance for regression or future conflict.

**Pull request merged**
