### PR TITLE
Replace old magento placeholder images in frontend and adminhtml

### PR DESCRIPTION
**Pull request by empiricompany**
### Description (*)
Replace old placeholder images with magento logo with our official logo

### Manual testing scenarios (*)
frontend:
1. Create product without image
2. Flush Catalog Image Cache
3. Check on frontend new placeholder

backend:
I don't know how to test it, but it's definitely fine.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Review by ADDISON74 — APPROVED** [review]

**Comment by fballiano** [comment]
can't test it at this very moment but I'm already loving this, I don't even know how nobody thought about it :-)

**Comment by empiricompany** [comment]
I have improved the quality of images

**Review by ADDISON74 — APPROVED** [review]

**Comment by fballiano** [comment]
questions:
- are these images 85% optimized as per pagespeed requirements?
- wouldn't it be better to avoid the gray background completely? dunno if they can be made transparent, than would probably be more interesting? or useless since everybody replace those?

Screenshot 2023-09-12 alle 20 42 54

**Comment by ADDISON74** [comment]
If the gray background is removed then it must have a gray border, otherwise the letter "m" remains with a large padding on all sides. But there are themes that apply borders to the product images, so I think it's good the way he replaced them.

If it was up to me, I would chose SVG format.

**Comment by fballiano** [comment]
I don't think it's possible to use SVG for product images :-(

**Comment by ADDISON74** [comment]
@fballiano - I did not refer to the product images in general, but to these placeholders.

**Comment by fballiano** [comment]
@ADDISON74 I know, but placeholder are used as the product image so they fall under the same technical limitations, unless a lot of stuff gets rewritten.

**Comment by fballiano** [comment]
I'll self answer, it doesn't matter if they're not super optimized since they are re-processed with every ->resize()

**Review by fballiano — APPROVED** [review]

**Pull request merged**
