### PR TITLE
Fixed docblock in Mage.php

### PR DESCRIPTION
**Pull request by kiatng**
Minor docblock fixes.

### CODE REVIEW

**Comment by fballiano** [comment]
phpstan became super angry for some reason

**Comment by ADDISON74** [comment]
The same issue related to PHPStan happened here https://github.com/OpenMage/magento-lts/pull/3835.

**Comment by ADDISON74** [comment]
> phpstan became super angry for some reason

Adding "false" to docblock requires a check for not being false. E.g. `if ($param)` ... or something simiar.

**Comment by fballiano** [comment]
I'll close this at the moment, please reopen it if/when you'll be able to continue working on it

**Pull request closed without merging**
