### PR TITLE
Rename Magento Admin to OpenMage Admin

### PR DESCRIPTION
**Pull request by luigifab**
:) the downloader update is probably useless.

### CODE REVIEW

**Comment by colinmollenhour** [comment]
Related: #1014 and #903

**Comment by sreichel** [comment]
Mhhh ... keep php-code and just change translation (to do not break locale packs?)

**Comment by luigifab** [comment]
> Mhhh ... keep php-code and just change translation (to do not break locale packs?)

:'( perhaps we can create a PR that add all "updated" [translations packs](https://github.com/OpenMageModuleFostering?q=locale)? I will very happy to try.

**Comment by sreichel** [comment]
Off-Topic and  just a reminder for me .... https://crowdin.com/project/magento-1 ...

I've no problem to ask for free support for an OS project .... would this be an improvement to handle translations?

**Pull request merged**
