### PR TITLE
Make overrides of Mage_Core_Model_Resource_Db_Abstract::delete respect parent api

### PR DESCRIPTION
**Pull request by midlan**
### Description (*)

I fixed overrides of Mage_Core_Model_Resource_Db_Abstract::delete to respect parent api, which means:
- throw on error
- return `$this`

### Fixed Issues (if relevant)

1. Fixes OpenMage/magento-lts#950
#### Admin panel
1. make some constraint for `admin_user` table that not allow you delete record (e.g. foreign key referencing the table with `RESTRICT` rule `ON DELETE`)
2. go to admin panel and try delete some user, instead of green message that user was deleted, we should get red error message
#### API
There is changes also in API resource model, so we should test it also.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by kkrieger85 — APPROVED** [review]

**Comment by midlan** [comment]
@Flyingmana @sreichel review pls?

**Comment by midlan** [comment]
It is BC break, labeled it and changed base branch to 20.0

**Review by Sekiphp — DISMISSED** [review]
seems ok

for future compatibility, you should consider to replace catch of `Exception` to `Throwable`

**Comment by fballiano** [comment]
> seems ok
> 
> for future compatibility, you should consider to replace catch of `Exception` to `Throwable`

I switched them

**Review by fballiano — DISMISSED** [review]

**Comment by fballiano** [comment]
But we should still add a note to the README in the "differences between v19 and v20"

**Comment by elidrissidev** [comment]
Updated the branch since the README's version was ancient and added the note to the README.

**Review by elidrissidev — APPROVED** [review]

**Pull request merged**
