### PR TITLE
 Removed duplicate and unneeded database indices

### PR DESCRIPTION
**Pull request by fballiano**
All info in https://github.com/OpenMage/magento-lts/issues/2992

I thought about splitting the updates into the single modules, is it ok with everybody?

### Fixed Issues (if relevant)

1. Fixes https://github.com/OpenMage/magento-lts/issues/2992

### CODE REVIEW

**Comment by fballiano** [comment]
these query are still to be inserted in this PR

```
ALTER TABLE `cataloginventory_stock_item` DROP INDEX `IDX_CATALOGINVENTORY_STOCK_ITEM_PRODUCT_ID`;
ALTER TABLE `catalogrule_customer_group` DROP INDEX `IDX_CATALOGRULE_CUSTOMER_GROUP_RULE_ID`;
ALTER TABLE `catalogrule_group_website` DROP INDEX `IDX_CATALOGRULE_GROUP_WEBSITE_RULE_ID`;
ALTER TABLE `catalogrule_product` DROP INDEX `IDX_CATALOGRULE_PRODUCT_RULE_ID`;
ALTER TABLE `catalogrule_website` DROP INDEX `IDX_CATALOGRULE_WEBSITE_RULE_ID`;
ALTER TABLE `catalogsearch_result` DROP INDEX `IDX_CATALOGSEARCH_RESULT_QUERY_ID`;
ALTER TABLE `core_translate` DROP INDEX `IDX_CORE_TRANSLATE_STORE_ID`;
ALTER TABLE `core_url_rewrite` DROP INDEX `IDX_CORE_URL_REWRITE_ID_PATH`;
ALTER TABLE `core_variable_value` DROP INDEX `IDX_CORE_VARIABLE_VALUE_VARIABLE_ID`;
ALTER TABLE `customer_address_entity_datetime` DROP INDEX `IDX_CUSTOMER_ADDRESS_ENTITY_DATETIME_ENTITY_ID`;
ALTER TABLE `customer_address_entity_decimal` DROP INDEX `IDX_CUSTOMER_ADDRESS_ENTITY_DECIMAL_ENTITY_ID`;
ALTER TABLE `customer_address_entity_int` DROP INDEX `IDX_CUSTOMER_ADDRESS_ENTITY_INT_ENTITY_ID`;
ALTER TABLE `customer_address_entity_text` DROP INDEX `IDX_CUSTOMER_ADDRESS_ENTITY_TEXT_ENTITY_ID`;
ALTER TABLE `customer_address_entity_varchar` DROP INDEX `IDX_CUSTOMER_ADDRESS_ENTITY_VARCHAR_ENTITY_ID`;
ALTER TABLE `customer_entity` DROP INDEX `IDX_CUSTOMER_ENTITY_EMAIL_WEBSITE_ID`;
ALTER TABLE `customer_entity_datetime` DROP INDEX `IDX_CUSTOMER_ENTITY_DATETIME_ENTITY_ID`;
ALTER TABLE `customer_entity_decimal` DROP INDEX `IDX_CUSTOMER_ENTITY_DECIMAL_ENTITY_ID`;
ALTER TABLE `customer_entity_int` DROP INDEX `IDX_CUSTOMER_ENTITY_INT_ENTITY_ID`;
ALTER TABLE `customer_entity_text` DROP INDEX `IDX_CUSTOMER_ENTITY_TEXT_ENTITY_ID`;
ALTER TABLE `customer_entity_varchar` DROP INDEX `IDX_CUSTOMER_ENTITY_VARCHAR_ENTITY_ID`;
ALTER TABLE `downloadable_link` DROP INDEX `IDX_DOWNLOADABLE_LINK_PRODUCT_ID`;
ALTER TABLE `downloadable_link_title` DROP INDEX `IDX_DOWNLOADABLE_LINK_TITLE_LINK_ID`;
ALTER TABLE `downloadable_sample_title` DROP INDEX `IDX_DOWNLOADABLE_SAMPLE_TITLE_SAMPLE_ID`;
ALTER TABLE `eav_attribute` DROP INDEX `IDX_EAV_ATTRIBUTE_ENTITY_TYPE_ID`;
ALTER TABLE `eav_attribute_label` DROP INDEX `IDX_EAV_ATTRIBUTE_LABEL_ATTRIBUTE_ID`;
ALTER TABLE `eav_entity_datetime` DROP INDEX `IDX_EAV_ENTITY_DATETIME_ENTITY_ID`;
ALTER TABLE `eav_entity_datetime` DROP INDEX `IDX_EAV_ENTITY_DATETIME_ENTITY_TYPE_ID`;
ALTER TABLE `eav_entity_datetime` DROP INDEX `IDX_EAV_ENTITY_DATETIME_ATTRIBUTE_ID`;
ALTER TABLE `eav_entity_decimal` DROP INDEX `IDX_EAV_ENTITY_DECIMAL_ENTITY_ID`;
ALTER TABLE `eav_entity_decimal` DROP INDEX `IDX_EAV_ENTITY_DECIMAL_ENTITY_TYPE_ID`;
ALTER TABLE `eav_entity_decimal` DROP INDEX `IDX_EAV_ENTITY_DECIMAL_ATTRIBUTE_ID`;
ALTER TABLE `eav_entity_int` DROP INDEX `IDX_EAV_ENTITY_INT_ENTITY_ID`;
ALTER TABLE `eav_entity_int` DROP INDEX `IDX_EAV_ENTITY_INT_ENTITY_TYPE_ID`;
ALTER TABLE `eav_entity_int` DROP INDEX `IDX_EAV_ENTITY_INT_ATTRIBUTE_ID`;
ALTER TABLE `eav_entity_text` DROP INDEX `IDX_EAV_ENTITY_TEXT_ENTITY_ID`;
ALTER TABLE `eav_entity_varchar` DROP INDEX `IDX_EAV_ENTITY_VARCHAR_ENTITY_ID`;
ALTER TABLE `eav_entity_varchar` DROP INDEX `IDX_EAV_ENTITY_VARCHAR_ENTITY_TYPE_ID`;
ALTER TABLE `eav_entity_varchar` DROP INDEX `IDX_EAV_ENTITY_VARCHAR_ATTRIBUTE_ID`;
ALTER TABLE `eav_form_element` DROP INDEX `IDX_EAV_FORM_ELEMENT_TYPE_ID`;
ALTER TABLE `eav_form_fieldset` DROP INDEX `IDX_EAV_FORM_FIELDSET_TYPE_ID`;
ALTER TABLE `eav_form_fieldset_label` DROP INDEX `IDX_EAV_FORM_FIELDSET_LABEL_FIELDSET_ID`;
ALTER TABLE `newsletter_queue_link` DROP INDEX `IDX_NEWSLETTER_QUEUE_LINK_QUEUE_ID`;
ALTER TABLE `sales_order_tax_item` DROP INDEX `IDX_SALES_ORDER_TAX_ITEM_TAX_ID`;
ALTER TABLE `sales_payment_transaction` DROP INDEX `IDX_SALES_PAYMENT_TRANSACTION_ORDER_ID`;
ALTER TABLE `salesrule_coupon_usage` DROP INDEX `IDX_SALESRULE_COUPON_USAGE_COUPON_ID`;
ALTER TABLE `salesrule_customer_group` DROP INDEX `IDX_SALESRULE_CUSTOMER_GROUP_RULE_ID`;
ALTER TABLE `salesrule_label` DROP INDEX `IDX_SALESRULE_LABEL_RULE_ID`;
ALTER TABLE `salesrule_website` DROP INDEX `IDX_SALESRULE_WEBSITE_RULE_ID`;
ALTER TABLE `tag_relation` DROP INDEX `IDX_TAG_RELATION_TAG_ID`;
ALTER TABLE `tag_summary` DROP INDEX `IDX_TAG_SUMMARY_TAG_ID`;
ALTER TABLE `tax_calculation` DROP INDEX `IDX_TAX_CALCULATION_TAX_CALCULATION_RATE_ID`;
ALTER TABLE `tax_calculation_rate_title` DROP INDEX `IDX_TAX_CALCULATION_RATE_TITLE_TAX_CALCULATION_RATE_ID`;
ALTER TABLE `tax_calculation_rule` DROP INDEX `IDX_TAX_CALC_RULE_PRIORITY_POSITION_TAX_CALC_RULE_ID`, ADD INDEX `IDX_TAX_CALC_RULE_PRIORITY_POSITION_TAX_CALC_RULE_ID` (`priority`,`position`);
ALTER TABLE `widget_instance_page_layout` DROP INDEX `IDX_WIDGET_INSTANCE_PAGE_LAYOUT_LAYOUT_UPDATE_ID`;
```

**Comment by loekvangool** [comment]
Is there a way to do this safe/graceful? To not have fatal errors during upgrade.

```sql
SELECT COUNT(1) IndexIsThere FROM INFORMATION_SCHEMA.STATISTICS
WHERE table_schema="prokoeling" AND table_name='eav_entity_varchar' AND index_name='IDX_EAV_ENTITY_VARCHAR_ATTRIBUTE_ID';
```

**Comment by fballiano** [comment]
@loekvangool to check that the index exists before dropping it?

**Comment by fballiano** [comment]
actually I was thinking if it was just better to create a script that can be run manually, instead of forcing this update on everybody.

**Comment by elidrissidev** [comment]
> actually I was thinking if it was just better to create a script that can be run manually, instead of forcing this update on everybody.

Agree, this is the first idea I had. Only remove them from the original installation scripts for people installing OM for the first time, and add a "Performance" section somewhere with the  instructions for existing installations.

**Comment by fballiano** [comment]
it makes much more sense, I'll close this one cause it has to be rewritten completely anyway

**Comment by loekvangool** [comment]
> @loekvangool to check that the index exists before dropping it?

Yes, just a defensive programming thing. Many installations will be 5+ years old etc.

**Pull request closed without merging**
