### PR TITLE
Version bump

### PR DESCRIPTION
**Pull request by fballiano**
Since we just merged pretty important stuff, but at the same time we need more testing-time, what about a next version like 20.1.0-rc1 and 19.5.0-rc1?

Related PRs
- https://github.com/OpenMage/magento-lts/pull/2411
- https://github.com/OpenMage/magento-lts/pull/2827

### CODE REVIEW

**Review by sreichel — APPROVED** [review]

**Comment by sreichel** [comment]
Does upper/lower-case matter?

**Comment by sreichel** [comment]
... but ... we have an error that sould be fixed. If its okay i'd remove latest release from packagist.org.

**Comment by fballiano** [comment]
> Does upper/lower-case matter?

I don't think so, I used lowercase since it was already in the sample (comment next to the "alpha/beta/rc" like)

**Comment by fballiano** [comment]
> ... but ... we have an error that sould be fixed. If its okay i'd remove latest release from packagist.org.

but how can we fix that anyway now?
they only way would be to create a branch from the currently released tag, fix the typo manually and release that, without PRs etc..

**Comment by sreichel** [comment]
Yes. Its not so much to do, but we fix it without enforce to update to 1.9.5/...

**Comment by sreichel** [comment]
You are doing the releases. Is it much work to make that hotfix release?

We could fix this bug w/o enforce to update to Zend-changes.

**Comment by fballiano** [comment]
@sreichel in this case it's pretty easy, I've already created branch https://github.com/OpenMage/magento-lts/tree/19.4.21 with just 2 commits. they're pretty basic so everything should be ok. can you check it out a second and then I'll release?

also, it's a v19 hotfix only because v20 doesn't have the bug with https://github.com/OpenMage/magento-lts/issues/2793

**Comment by sreichel** [comment]
Perfect.

**Comment by Flyingmana** [comment]
> ... but ... we have an error that sould be fixed. If its okay i'd remove latest release from packagist.org.

be very very very careful with removing releases, this is going to break anyone who uses this in their composer.json or composer.lock. 
Replacing it does not work anyway, as it would have a different checksum and cause fails.

**Comment by fballiano** [comment]
We’ll not remove anything don’t worry

**Comment by sreichel** [comment]
> > ... but ... we have an error that sould be fixed. If its okay i'd remove latest release from packagist.org.
> 
> be very very very careful with removing releases, this is going to break anyone who uses this in their composer.json or composer.lock. Replacing it does not work anyway, as it would have a different checksum and cause fails.

Thanks. This is why i asked for.

Is there another propper way to avoid installing "bugged" releases?

Something like a required extension that cant we installed with certain releases?

**Comment by fballiano** [comment]
Tomorrow morning I’ll release the new v19 and there will be no problem anymore 😉

**Comment by fballiano** [comment]
19.4.21 is released, I was afraid of the process but at the end of the day it was pretty easy and I should have done it ealier.. it's done anyway now.

**Comment by Flyingmana** [comment]
> Since we just merged pretty important stuff, but at the same time we need more testing-time, what about a next version like 20.1.0-rc1 and 19.5.0-rc1?

regarding the original question, can you link this very important stuff?
Generally I would say, releasing alpha,beta,rc releases is always okay.

But I wonder what it is, that requires the minor version bump, especially for the 19. release

**Comment by fballiano** [comment]
it's the drop of CM modules and ZF1 moving them to composer

**Comment by fballiano** [comment]
linkedin the PRs in the description. I think the bump should be minor, not your patch version

**Comment by Flyingmana** [comment]
> it's the drop of CM modules and ZF1 moving them to composer

I see, that surely is a good reason for a minor version bump. And also a good reason for RC Tagging.

**Review by Flyingmana — APPROVED** [review]

**Pull request merged**
