### PR TITLE
fix: cast store config (checkout/cart/delete_quote_after) to int to avoid unsupported operand types php error

### PR DESCRIPTION
**Pull request by darinda**
fixes https://github.com/OpenMage/magento-lts/issues/3064

### Description (*)

Fixes https://github.com/OpenMage/magento-lts/issues/3064

### Fixed Issues (if relevant)

1. Fixes OpenMage/magento-lts#3064

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)
 - [ ] Add yourself to contributors list

### CODE REVIEW

**Review by elidrissidev — APPROVED** [review]

**Comment by fballiano** [comment]
auch, didn't notice this was on 20.0, I'll port it to 1.9.4.x

**Comment by elidrissidev** [comment]
Wait why is this targeting `20.0` instead of `1.9.4.x`

**Comment by fballiano** [comment]
cherry picked it to 1.9.4.x

**Comment by sreichel** [comment]
@all-contributors add @darinda code

**Comment by sreichel** [comment]
@all-contributors add @darinda code

**Pull request merged**
