### PR TITLE
Create .htaccess file in js directory

### PR DESCRIPTION
**Pull request by ADDISON74**
I created .htaccess file in /js directory. This change doesn't permit executing PHP and CGI scripts like in /media.

The correct branch is 20.0 because /js/index.php doesn't exist anymore in 1.9.4.x.  I didn't create the changes in OM-20 because something is happening in that branch. When I wanted to create the PR dozens of commits from other users were attached to my modification. I chose to avoid this aspect. After that issue is solved, a rebase can be made to this PR.

### CODE REVIEW

**Comment by fballiano** [comment]
here too I think we shouldn't have all the empty lines

**Comment by fballiano** [comment]
IMHO this should be the file

```
# Disable PHP code execution

<IfModule mod_php7.c>
    php_flag engine 0
</IfModule>

<IfModule mod_php8.c>
    php_flag engine 0
</IfModule>

# Forbid execution of CGI scripts

AddHandler cgi-script .php .pl .py .jsp .asp .sh .cgi
Options -ExecCGI
```

**Comment by ADDISON74** [comment]
I made the change, but I kept the way to comment with ## because # can be confused with a disabled line. It's on the same format as Magento team used in the past for .htaccess root file. Related to the use of the word "permit" or "forbit" I used exactly the description in the Apache manual.

**Comment by elidrissidev** [comment]
For the issue you're having with branches, it probably is because you created the branch from 1.9.4.x instead of 20.0, and that's why you get all the commits that exist in 1.9.4.x but not in 20.0 when you try to create a PR.

**Comment by ADDISON74** [comment]
@elidrissidev - Don't worry I know well in which branch I wanted to do PR from the beginning. I deleted it and created it about 3 times because the issue persisted in 20. Besides my commit I had a long list of other commits and this did not happen in 19. 

I mentioned in the first post this PR **must be taken in 20**. If it remains in 19 that /js/index.php file will no longer be executed.

**Review by fballiano — DISMISSED** [review]

**Comment by fballiano** [comment]
We’ve to recreate this pr because sadly we can’t merge it like this 😞

**Comment by elidrissidev** [comment]
Try running `git pull --rebase upstream 20.0`, the additional commits should go away

**Comment by ADDISON74** [comment]
The issue is that after I do all stuff in my repository when I create the PR other commits are attached to it that are not mine. You can see what happened if you rebased. I have no idea what's going on but branch 20 may have issues.

**Comment by fballiano** [comment]
maybe it's easier to close this pr and redo it from scratch to avoid the unwanted commits

**Comment by ADDISON74** [comment]
In order to avoid any issues I will close it.

**Pull request closed without merging**
