### PR TITLE
Use vanillaJS instead of encodeURI in wishlist add to cart

### PR DESCRIPTION
**Pull request by MarcinNowakMacopedia**

### CODE REVIEW

**Review by ADDISON74 — DISMISSED** [review]

**Comment by Sdfendor** [comment]
If I understand correctly you inline the function call defined in `js.js` which is part of varien thus part of OpenMage, not any of the 3rd party frameworks like prototype or jQuery. To replace the 3rd party frameworks is a concern I fully understand. But why not use a function that is defined in the core. Isn't it cleaner to do so? Especially because the inlined code still uses another function from `js.js`. I'm not aware of an effort to replace and remove the varien js code. The change in this PR doesn't hurt though. 
Can you please elaborate on the motivation for this change?

**Comment by tmotyl** [comment]
@Sdfendor this change and similar one https://github.com/OpenMage/magento-lts/pull/2051#issuecomment-1105634079 is are just  small steps towards reducing custom JS in openmage 

I know that single change alone doesnt make an impact, but its still a step into good direction. One place less to tackle.

in one of our projects we managed to get rid of libraries like js.js and this patch was a part of this effort

**Comment by Sdfendor** [comment]
Alright so if removal of as much custom JS regardless of first or third party is the goal I naturally have nothing against it :-).

**Review by Sdfendor — APPROVED** [review]

**Review by tmotyl — DISMISSED** [review]

**Comment by tmotyl** [comment]
@MarcinNowakMacopedia please rebase the patch, to make the tests go green

**Comment by tmotyl** [comment]
rebased

**Review by tmotyl — APPROVED** [review]

**Review by luigifab — APPROVED** [review]

**Review by Sdfendor — APPROVED** [review]

**Review by fballiano — APPROVED** [review]

**Pull request merged**
