### PR TITLE
Fixed incorrect datetime in block.

### PR DESCRIPTION
**Pull request by kiatng**
### Description (*)

This PR fixes 2 issues:
1. Incorrect datetime in backend customer page, see issue #466.
2. Enable the ability to `formatDate()` in the block without converting to store timezone. A use case is when a datetime is stored in the DB in local timezone (or a date such as birthdate, which is independent of timezone), the method `formatDate()` would convert the datetime and couldn't be used for rendering. This PR fixes that. Now, the same method can be used.

### Fixed Issues (if relevant)

1. Fixes OpenMage/magento-lts#466

### Manual testing scenarios (*)

After:
image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ADDISON74** [comment]
I do not agree changing the code by replacing **if/else** sequences with ternary operator **?**. The code is just fine as it is the only necessary change should be fixing the issue.

Although I understand that you want a compression of the code but it is not beneficial for the reader. It is much easier for me personally to see if/else sequences then ?. If we agree to such changes then we should do so throughout Magento, otherwise we lose the rules initially set.

**Comment by fballiano** [comment]
I also don't like the 1 line functions, but anyways we need this merged asap

**Review by colinmollenhour — APPROVED** [review]

**Comment by sreichel** [comment]
Is this a BC breaking change?

**Comment by kiatng** [comment]
> Is this a BC breaking change?

I think so, due to addition of new param `$useTimezone`  in `public function formatDate($date = null, $format = Mage_Core_Model_Locale::FORMAT_TYPE_SHORT, $showTime = false, $useTimezone = true)`. Existing method without `$useTimezone` that overrides it will run into PHP exceptions.

**Comment by sreichel** [comment]
IMHO ... this change to `formatDate()` method should be reverted.

I'd add a new method that covers `$useTimezone = true` parameter and can be used to fix the issue.

**Pull request merged**
