### PR TITLE
Log PHP session errors and prevent PHP errors

### PR DESCRIPTION
**Pull request by loekvangool**
Fixes https://github.com/OpenMage/magento-lts/issues/3030

### CODE REVIEW

**Comment by fballiano** [comment]
I would rewrite the methods in a different way

```
if (!check) {
  error
  return
}

if (!check) {
  error
  return
}

do what you need to do
```

it seems much more readable to me.

**Comment by fballiano** [comment]
@loekvangool can you rebase this PR on the branch "main", I can't do it on your repo

**Comment by fballiano** [comment]
the app/code/core/Mage/Core/Model/Session/Abstract/Varien.php is now very different from the version you worked on so I think the whole thing has to be rethough

**Comment by ADDISON74** [comment]
This PR is attached to 1.9.4.x branch and there are still about 25 in this situation.

We should do a cleaning and stay with 3 branches in OpenMage repository: v19, main and next. PRs that cannot be edited should be deleted and added again with the edit option. From my estimations around 20 PRs will close issues too, so that we reduce the number of reports below 100. Anyway we are doing well compared to Magento 2, where the number of PRs is around 1K and the reported issues is over 1.5K.

PS - We should rename v19 branch to **lts** because that is the goal, who wants to stay with Magento without BC's this is the place for a while.

**Comment by fballiano** [comment]
@loekvangool could you rebase it on the "main" branch? cause it's different from the one you worked on and it doesn't really match anymore.

**Comment by fballiano** [comment]
I'll close this at the moment cause I can't rebase it since the main branch is now a bit different from the point to where it was when this PR was created.

feel absolutely free to reopen when you're ready to pick it up :-)

**Pull request closed without merging**
