### PR TITLE
[BUGFIX] Replaced cat_index_position with cat_index.position

### PR DESCRIPTION
**Pull request by dbachmann**
Last week a customer told me that couldn't finish the checkout because of an error. After checking the logs I've found the following query 

```sql
SELECT `e`.`entity_id`, `e`.`type_id`, `e`.`attribute_set_id`, `price_index`.`price`, `price_index`.`tax_class_id`, `price_index`.`final_price`,
 IF(price_index.tier_price IS NOT NULL, LEAST(price_index.min_price, price_index.tier_price), price_index.min_price) AS `minimal_price`,
 `price_index`.`min_price`, `price_index`.`max_price`, `price_index`.`tier_price`, `e`.`price`, `e`.`special_from_date`, `e`.`special_to_date`, `_inv`.`stock_status`, 
IFNULL(_inv.stock_status,0) AS `in_stock` FROM `catalog_product_flat_2` AS `e`
 INNER JOIN `catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.website_id = '2' AND price_index.customer_group_id = 1
 LEFT JOIN `cataloginventory_stock_status` AS `_inv` ON _inv.product_id = e.entity_id and _inv.website_id=2 and _inv.stock_id=1 
WHERE (e.status = 1) AND (e.entity_id IN('156')) AND (e.price > final_price) AND (((((e.special_from_date = '2021-09-02 16:53:46') OR (e.special_to_date IS null))))) 
ORDER BY `in_stock` DESC, `cat_index_position` asc, `e`.`entity_id` asc
```
with the error 1054 Unknown column 'cat_index_position' in 'order clause'. After some research I fixed this bug by replacing cat_index_position with cat_index.position. 

It seems, this is a very old bug in magento.

### CODE REVIEW

**Comment by Flyingmana** [comment]
looks good so far.

another usage of `cat_index.position` was introduced in 1.6.0.0 https://github.com/OpenMage/magento-lts/commit/d54fe9303e43fdd9956bc747c5b351e4be8c3f1f#diff-68644849169089f4a07a4457d8ec237f83f1b64533f42f1dcb8c6b17654338bbL1343

need still to actually test it

**Comment by kiatng** [comment]
I cannot replicate the error with this test code:

```php
    Mage::getResourceModel('catalog/product_collection')
            ->addCategoryFilter(Mage::getModel('catalog/category')->load(3))
            ->addAttributeToSort('position')
            ->load();
```

Sample output:
```
    [47] => Array
        (
            [entity_id] => 47
            [type_id] => simple
            [attribute_set_id] => 4
            [cat_index_position] => 1
            [groupscatalog_hide_group] => 0
            [is_salable] => 1
            [stock_item] => Array
                (
                    [is_in_stock] => 1
                )

        )
```

As can be seen, `cat_index_position` is correctly return with value 1.

When the fix in this commit is applied, the output becomes:

```
    [47] => Array
        (
            [entity_id] => 47
            [type_id] => simple
            [attribute_set_id] => 4
            [cat_index.position] => 1
            [groupscatalog_hide_group] => 0
            [is_salable] => 1
            [stock_item] => Array
                (
                    [is_in_stock] => 1
                )

        )
```
 `cat_index_position` is now `cat_index.position`. 

My conclusion is that this commit doesn't seem to fix anything.

**Review by tobihille — APPROVED** [review]
Even if it does not change behavior in the observed case: we do agree, that cat_index_position is not correct, do we?
So I see no point in not approving it.

**Comment by tmotyl** [comment]
Does the issue exisis with flat collection enabled or disabled? Please remember to test patches with both cases

**Comment by sreichel** [comment]
@kiatng can you please test your code with product flat tables = ON?

I can reproduce this error, but this PR does not fix it?!?

**Comment by sreichel** [comment]
Please do NOT approve. Something went wrong when fixing conflict.

**Comment by sreichel** [comment]
New issue here ... #2511

**Pull request closed without merging**
