### PR TITLE
In product list all swatches are always shown even if they are not available when "Display Out of Stock Products" is disabled

### PR DESCRIPTION
**Pull request by empiricompany**
### Description (*)

In the product list, all swatches are always shown even if they are not available.
You can verify this on the PDP because only the available ones are displayed correctly.

Tested with both enabled and disabled stock inventory configuration "Display Out of Stock Products"

inventory_settings

When "Display Out of Stock Products" is enabled shown correctly like this:
show_out_of_stock

When "Display Out of Stock Products" is disabled all swatches are always shown even if they are not available.
With this patch shown correctly like this:

not_out_of_stock

The bug occurs when the " Display Out of Stock Products" configuration is disabled.

### Fixed Issues (if relevant)

https://github.com/OpenMage/magento-lts/issues/3527

### Manual testing scenarios (*)

1. Create configurable product with options as swatch such as color
2. Set stock unavailable for one color option

Example with sample data:
1. In product configurable Name: "Nolita cami" SKU "wbk000c" set all children products with color pink unavailable.

In the product list, all colors are always shown even if they are not available.
You can verify this on the PDP because only the available ones are displayed correctly.

pdp
pl

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Comment by empiricompany** [comment]
Sorry @fballiano you can delete this https://github.com/OpenMage/magento-lts/pull/4099 please?

**Comment by fballiano** [comment]
@empiricompany as of today I'm no longer part of this project

**Comment by empiricompany** [comment]
> @empiricompany as of today I'm no longer part of this project

What?? This is unacceptable, this project would have died without you! What did I miss?

**Comment by sreichel** [comment]
Smart change. :+1: 

What is this flag for? See https://magento.stackexchange.com/questions/106455/get-product-stock-quantity-in-magento/209510#209510.

@ADDISON74 please test for https://github.com/OpenMage/magento-lts/issues/1694, too.

**Comment by ADDISON74** [comment]
@sreichel - I will. 

Please check this one https://github.com/OpenMage/magento-lts/issues/3527. It could be related too.

**Review by kiatng — APPROVED** [review]
Ref https://github.com/OpenMage/magento-lts/blob/5d3af08b6df819c8f6b0160bfd4cd392bcd948b6/app/code/core/Mage/CatalogInventory/Model/Observer.php#L108-L110

**Review by sreichel — APPROVED** [review]

**Pull request merged**
