### PR TITLE
Fix slow url_rewrite query on MySQL 5.7

### PR DESCRIPTION
**Pull request by tmotyl**
Fixes: https://github.com/OpenMage/magento-lts/issues/295

### CODE REVIEW

**Comment by tmotyl** [comment]
I'm planning to test that next days

**Comment by tomekjordan** [comment]
What about 3rd party modules for SEO like Mageworx SEO Ultimate, will it brake anything if they rewrite urls?

**Comment by LeeSaferite** [comment]
If you read the code, it's joining the category entries to the url rewrite table based on the category_id field of the rewrite table. This added WHERE clause is just an optimization to exclude records that wouldn't be joined anyway.

**Comment by tmotyl** [comment]
@tomekjordan I don't expect this to be breaking however
I'm not using this module for 100%, so can't tell. 
If you have access to this module, please test the patch and let us know.

**Comment by darnux** [comment]
any news on that? in which version is this fixed?

**Comment by colinmollenhour** [comment]
While I approve of the change in principle, there is no proof provided that it doesn't break anything and I don't have time to test it thoroughly myself, so perhaps if someone could test it in some capacity and report back that would help get this merged.

We really need some unit tests... 😕

**Comment by darnux** [comment]
@colinmollenhour thanks for your quick reply. 
I am working for a webhosting company and we are using this fix in production for several projects (about 5-10) at the moment due to the need of MySQL 5.7. 
We did not notice any negative impact on this by now.

**Comment by BassemN** [comment]
Thanks allot for that fix

**Comment by wilfriedwolf** [comment]
Thanks a lot from my side too! I had a 7 s load after adding a second web-site to one of our magento installations. When I tested it locally after switching to magento_lts loading time dropped to 0.32s!
Great!

**Pull request merged**
