### PR TITLE
Optimisation for Varien_Object::_addFullNames

### PR DESCRIPTION
**Pull request by AGelzer**
### Description (*)
Optimization for Varien_Object::_addFullNames
- less code
- array_intersect_key with array_flip is faster than  array_intersect with array_values
- avoid array_search
- Tested with PHP8.0 Openmage 19.4.20 => 3x faster (Test Object: Mage_CatalogInventory_Model_Stock_Item)

### Related Pull Requests
-

### Fixed Issues (if relevant)
-

### Manual testing scenarios (*)
-

### Questions or comments
- Thanks 

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)
 - [ ] Add yourself to contributors list

### CODE REVIEW

**Comment by sreichel** [comment]
Can you please add some information about tests or measurement?

Just did a quick test with xhprof on admin product edit page ... before and after change ...

xhp1

Or ... here it is faster before ...

https://onlinephp.io?s=vVVNj9MwFDy3Uv-DiXJIpIV2JZAWSuHEXhB7gdtSWV77pbWa2MF2dhuh_e_YcZqPpmkXCZFLG894PG_8nvLxc77NZ9PZNNSloLccUqa_kRyt0D2aTVGgjaQ7rA0xhcZ0S8QGGCaFkRkxnJI0LQO0-nSGF1w5mUIDplIkfINBkIcU8C9TYi6oggyE0V5klOVFxs84b6G1et7LBRMHq1ZkvXSRzefD0BxigwsZMaQJkRvIMGde__rm5q03kivJCmoa5P3iXbfQZoNftC7q98XizcI-fjnjAjdQF-jU0ePUclxXdTGgPCNpvd1DD4TupGKgdG-5I3jMuG69aOITq4FxQ0fEWoHsj4CxkgbEti4n7hLsrafyya9iezVQQaJI0woT0vCkrOGDYIN2Tj1JbL0LsoHu0adsH3OuX9TbQ6VT89N2ygAaifHUANQqZ-Z00URdtw9m_JEzYD3YlDk0Tax5lqcQHEYnKQQ1XAokUxb1p-gKVcMTz6a_rYp9QthzbYB930plvkKp7VwRpYjzZWwLAjUDCY_vLDnyavHSi_EERa8gy00ZDXTjGNVHuieRCgjdoiEPEY1Cq92jV04T2zOVizuSQWNTA1F0G7kttrie04OtRsGZve_rrK1QvW4V1p0dz_5v_TOfKzCFEp5sac-9pAXA0z-I2oUa-bUk5fmRYnyQ_Ku4J5ezdk3Uj6WX_uRlwU0mbWST03mFdgaV-cGr-8s4VXbkM4iMKsAVNd6vFgxBsJGdyH0UICW5BuZsHZivUXugVQC6lSj4sgdaVJfmFNAH1Oy0NyAF00FD_SmCaqAuGj9z_f_buftyPhKFWZHlESaM3dpbcxemRwyi1WqFesS70WLi5R8%2C&v=7.4.33

**Comment by AGelzer** [comment]
> Can you please add some information about tests or measurement?
> 
> Just did a quick test with xhprof on admin product edit page ... before and after change ...
> 
> xhp1
> 
> Or ... here it is faster before ...
> 
> https://onlinephp.io?s=vVVNj9MwFDy3Uv-DiXJIpIV2JZAWSuHEXhB7gdtSWV77pbWa2MF2dhuh_e_YcZqPpmkXCZFLG894PG_8nvLxc77NZ9PZNNSloLccUqa_kRyt0D2aTVGgjaQ7rA0xhcZ0S8QGGCaFkRkxnJI0LQO0-nSGF1w5mUIDplIkfINBkIcU8C9TYi6oggyE0V5klOVFxs84b6G1et7LBRMHq1ZkvXSRzefD0BxigwsZMaQJkRvIMGde__rm5q03kivJCmoa5P3iXbfQZoNftC7q98XizcI-fjnjAjdQF-jU0ePUclxXdTGgPCNpvd1DD4TupGKgdG-5I3jMuG69aOITq4FxQ0fEWoHsj4CxkgbEti4n7hLsrafyya9iezVQQaJI0woT0vCkrOGDYIN2Tj1JbL0LsoHu0adsH3OuX9TbQ6VT89N2ygAaifHUANQqZ-Z00URdtw9m_JEzYD3YlDk0Tax5lqcQHEYnKQQ1XAokUxb1p-gKVcMTz6a_rYp9QthzbYB930plvkKp7VwRpYjzZWwLAjUDCY_vLDnyavHSi_EERa8gy00ZDXTjGNVHuieRCgjdoiEPEY1Cq92jV04T2zOVizuSQWNTA1F0G7kttrie04OtRsGZve_rrK1QvW4V1p0dz_5v_TOfKzCFEp5sac-9pAXA0z-I2oUa-bUk5fmRYnyQ_Ku4J5ezdk3Uj6WX_uRlwU0mbWST03mFdgaV-cGr-8s4VXbkM4iMKsAVNd6vFgxBsJGdyH0UICW5BuZsHZivUXugVQC6lSj4sgdaVJfmFNAH1Oy0NyAF00FD_SmCaqAuGj9z_f_buftyPhKFWZHlESaM3dpbcxemRwyi1WqFesS70WLi5R8%2C&v=7.4.33

Hi Sven ,
3x faster refer to Function Performance.
New is faster:
https://onlinephp.io?s=xVVdb9MwFH1upf4HE_UhQYO2EkiDUnhiL4i9wNuYLM--Wa06drCdbRHaf58dp_lomm5ISOSlrc_x8bnH9zafvuTbfDadTeemlPSCg2DmO8nRBl2h2RRFxiq6w8YSWxhMt0TeAsOksCojllMiRBmhzecTvOjMyxQGMFUy5bcYJLkRgH_bEnNJNWQgrQkio6wgMn7GaQut1dNenjGxt-pErtc-ssViGJpHXHBzRixpQuQWMsxZ0F-dn78LRnKtWEFtg3xYvu8W2mwIi85F_Xu5fLt0T1jOuMQN1AU6dfQ4tRw3VV0MKM-IqLcH6IbQndIMtOktdwQPGavWiyEhsRoYN3RArBXIwwEwVtKA2NblxX2CvXWh7sMqdlcDFSQLISpMKsvTsob3gg3aOfUosfUuyS10jz5m-5CzelFvD5WOzU_bKQNoJMZjA1CrnJjTZRN13T6Y8TvOgPVgW-bQNLHhWS4g2o9OWkhquZJICRb3p-gMVcOTzKZ_nIp75vDAjQX2Y6u0_QalcXNFtCbel3UtCNQOJAK-c-Q4qCXrIMZTFL-CLLdlPNBNElQf6Z9UaSB0i4Y8RAyaO-0evXKaup6pXFySDBqbBoim29hvccX1nO5tNQre7FVf59oJ1etO4bqz4zF8rT8WCw220DKQHe2xl7QEuP8HUftQ47CWCp4fKCZ7yb-Ke_J81r6J-rH00p-8LLjJpI1scjyvuZtBbX_y6v4yTrUb-QxiqwvwRY33qwPnINnITuRfCiBIboA5OG6ob1B7YoJeI_fvvnRSQLcKRV8fgBbV7Xkp9BE1EhkX3F2HksxEDf2XjKrperaKE73wX8vw79Q7ojErsjzGhLELd5_-Ks2IW7TZbFCPeDlaWbJ-Ag%2C%2C&v=7.4.33

**Comment by AGelzer** [comment]
[Compare: Old/New, Empty/Not empty Map (PHP8.2, PHP8.1, PHP8.0, PHP7.4)](https://onlinephp.io?s=xVVBb9MwFD63Uv-DiXpI0KCdBNKgFE7sghiHcRtT5NkvrTXHCbazLUL777PjNImbpi1oGrm09ff8ve99773m05d8nU_Gk_FUlYKcM-BUfcc5WqIrNBmjQOmM3MZKY12omKyxWAGNcaGzFGtGMOdlgJaf98QFJ5amUBCTTCRsFYPANxzi37qMmSASUhBaOZLBKEcynGO_hFbqfi0HRGykGpLrRWUZpLkuL7d9c-Bs1nfUIsbVKcUaNw4zDWnMqEt-enb2zqnMZUYLohvkw_x914Xmgjs0Euvf8_nbuXncccpE3EBdoFOkF1PTMVUVTYGwFPP6uoNuMLnNJAWpvOMO4XbEaatFYWdnDQwL2gqsGfDDFjBUUi-wrcuSWwe9c57du9PYtAYqSBScV5jINEvKGt4QNmgn687AVrvAK-im3iV7O-b0qMHvM-1arnZSetCAjbu2o2bZs8Tzxup6fGLK7hgF6sG6zKEZYsXSnEOw2aukEESzTKCM09DfohNULU80Gf8xLOaZwgNTGujlOpP6G5TK7BWWEltd2owgEN2jcPitCQ4dW7RwZCxB4atqqcMebxShOqV9kkwCJmvUj0NYoanh9sIrpYmZmUrFBU6hkakAS7IO7RVTnKd0I6thsGKvfJ5rQ1SfG4brzo1H97X-mM0k6EIKF2zCHj2nBcD9IautO7U5vkyvVJdm4SU_ulW2KaE7SzjLtxNtJP1Vu0aHe2WH0LfVK2l0nPGjUWv5aLff9jWrsdQ_WTUBKSPS_GmkEGpZgC1reOIX9n0j6MBN6_EUOM4VUAOHTegb1GaM0Gtk3g9zQwVknaHg6wOQouq_pULhD04j9BE1RCnjzLQlE1QFzaVfIlgcUcmeiXqJUi7g_tlKqZrSf9e_cGdOUCUB2UV43ib939JMp_6ptNnsDsuYFmkexpjSc7Ocdi_VwNCh5XKJvMCLwQGNFk8%2C&v=8.2.0%2C8.1.13%2C8.0.26%2C7.4.33)

XHProf 
PHP 8.0.26
Processor: 24 x AMD Ryzen 9 5900X 12 Core Processor
Screenshot 2022-12-18 at 14-22-36 XHProf Hierarchical Profiler Report
Screenshot 2022-12-18 at 14-23-29 XHProf Hierarchical Profiler Report
screenshot-xhprof age local-2022 12 18-14_21_52

**Review by sreichel — APPROVED** [review]

**Comment by sreichel** [comment]
Dont know why i had different numbers on phponline yesterday, but LGTM.

**Review by fballiano — APPROVED** [review]

**Comment by AGelzer** [comment]
@sreichel @fballiano thanks :)

@sreichel 
scientific notation?

```
Execution time : 1.3113021850586E-5 seconds
Execution time : 4.0531158447266E-6 seconds
```

multiple micro time with 1000 can help

```
Execution time : 0.012874603271484 milliseconds
Execution time : 0.0040531158447266 milliseconds
```

**Comment by sreichel** [comment]
> scientific notation?

Yes. Didn't see it.

Just one question ... did you use some tools for xdebug camparison? (or changed URL manually?)

DDEV provides xhprof support, but only links to current report (if enabled).

Would be nice to get such diff "on click".

(https://github.com/SergeyRock/xhprof-admin)

**Comment by AGelzer** [comment]
I used [phacility/xhprof](https://github.com/phacility/xhprof) with my [quick & dirty changes](https://github.com/AGelzer/xhprof/commit/dca20c7e7b46a76abcfdaf35d81900634c04f55f)

Screenshot 2022-12-25 at 10-52-54 XHProf Hierarchical Profiler Report

**Pull request merged**
