### PR TITLE
Update phpdoc in Collection.php

### PR DESCRIPTION
**Pull request by rubanooo**
Matched the phpdoc with the typehint from call_user_func

### CODE REVIEW

**Review by elidrissidev — DISMISSED** [review]

**Review by Sdfendor — APPROVED** [review]

**Comment by kiatng** [comment]
Question: `Closure` is an object, line 459 tests for string:

https://github.com/OpenMage/magento-lts/blob/4885b20d86bba7aa200007a76620575488e25846/lib/Varien/Data/Collection.php#L452-L460

isn't this inconsistent? Ref https://www.php.net/manual/en/language.types.declarations.php, `callable` is a type, but I am not sure if it is better like this:

```php
     * @param callable $callback
```

**Comment by Sdfendor** [comment]
I'am with @kiatng on this one and will change my review accordingly. Callable is the type that is referenced in https://www.php.net/manual/de/function.call-user-func-array.php which is the method used in `walk` function.

**Review by Sdfendor — CHANGES_REQUESTED** [review]
Callable is the type that is referenced in https://www.php.net/manual/de/function.call-user-func-array.php and https://www.php.net/manual/de/function.call-user-func.php which are the methods used in walk and each functions respectively. I would use `callable` instead of `closure`.

**Comment by rubanooo** [comment]
I also had `callable` in my local branch, but forgot to change this in my fork. I changed it to `callable` now :)

**Review by elidrissidev — APPROVED** [review]

**Review by Sdfendor — APPROVED** [review]

**Review by woutersamaey — APPROVED** [review]

**Review by kiatng — APPROVED** [review]

**Review by luigifab — APPROVED** [review]

**Review by midlan — APPROVED** [review]

**Review by Flyingmana — APPROVED** [review]

**Pull request merged**
