### PR TITLE
Merge v19 -> v20

### PR DESCRIPTION
**Pull request by fballiano**
Since there are new commits since https://github.com/OpenMage/magento-lts/pull/2370 we need another forward port PR before the next release

### CODE REVIEW

**Review by Sdfendor — APPROVED** [review]

**Review by tmewes — DISMISSED** [review]

**Review by Sdfendor — DISMISSED** [review]

**Review by kiatng — DISMISSED** [review]

**Review by ADDISON74 — DISMISSED** [review]

**Comment by fballiano** [comment]
Thanks guys, I'd wait until release day to merge, just in case more PRs get approved.

**Review by elidrissidev — DISMISSED** [review]
Another approval just because :)

**Comment by fballiano** [comment]
updated and had to fix conflicts with https://github.com/OpenMage/magento-lts/pull/2416 so any double check is welcome :-)

**Comment by fballiano** [comment]
Updated, had to fix conflicts with https://github.com/OpenMage/magento-lts/pull/2459

**Comment by fballiano** [comment]
Merging https://github.com/OpenMage/magento-lts/pull/2458 I had to fix a lot of conflicts, there's the need for some double checkin here too!

**Comment by sreichel** [comment]
> Merging #2458 I had to fix a lot of conflicts, there's the need for some double checkin here too!

Tested your branch ... LGTM.

**Comment by fballiano** [comment]
updated, had to fix conflicts with https://github.com/OpenMage/magento-lts/pull/2457 and https://github.com/OpenMage/magento-lts/pull/1525

It's becoming boring and a possible way of too many problems to constantly have to deal with conflicts :-\ It worries me.

**Comment by sreichel** [comment]
> It worries me.

We had a _few_ PRs these days. Time for new release?

**Comment by fballiano** [comment]
for sure, but since only a maintainer can merge everything into v20 I can't do much. I try to keep these kind of PRs updated but it worries me, we constantly have to fix stuff in v20 and our most advanced release is the less tested and more prone to error.

**Comment by sreichel** [comment]
> for sure, but since only a maintainer can merge ....

Just to mention ... README lists five maintainers ...

- [LeeSaferite](https://github.com/LeeSaferite) - Contributor
- [drobinson](https://github.com/drobinson) - Member
- [Daniel Fahlke aka Flyingmana](https://github.com/Flyingmana) - Member
- [Tymoteusz Motylewski](https://github.com/tmotyl) - Contributor
- [Sven Reichel](https://github.com/sreichel) - Collaborator

It seems only two people have access to do releases. :-1:

**Comment by fballiano** [comment]
hmmm I can tag a release (I did it already) but only who has full writing access to the repo can merge stuff without passing through a PR.

**Comment by fballiano** [comment]
updated

**Review by ADDISON74 — APPROVED** [review]

**Comment by fballiano** [comment]
updated and fixed various conflicts

**Review by ADDISON74 — DISMISSED** [review]

**Comment by fballiano** [comment]
@sreichel @ADDISON74 @Flyingmana This PR should be up to date now, if we approve it and merge it I can make a release later today or tomorrow (probably tomorrow, I've a wedding today)

**Review by ADDISON74 — APPROVED** [review]

**Review by sreichel — APPROVED** [review]

**Comment by fballiano** [comment]
waiting for the checks to finish and I'll merge and tag a draft release

**Pull request merged**
