### PR TITLE
Fixed UI bug in Newsletter Templates backend page, filters not saved in session

### PR DESCRIPTION
**Pull request by eneiasramos**
### Fixed Issues (if relevant)

1. Fixes OpenMage/magento-lts#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)
 - [ ] Add yourself to contributors list

### CODE REVIEW

**Comment by ADDISON74** [comment]
Any steps or screenshots to understand the issue?

**Comment by eneiasramos** [comment]
@ADDISON74 

When I filter some information, click on the record and return to the grid later, the filter information is lost.

image

**Review by kiatng — APPROVED** [review]

**Review by fballiano — APPROVED** [review]
tested, works and needed

**Comment by ADDISON74** [comment]
I confirm this bug. Nice catch, it is great it was merged.

**Pull request merged**
