### PR TITLE
Remove admin swf files [SUPEE-8788]

### PR DESCRIPTION
**Pull request by tschifftner**
flex and uploader swf files were removed in patch SUPEE-8788 and therefore also in Magento 1.9.3.0.

### CODE REVIEW

**Comment by infabo** [comment]
@tschifftner 👍 

@drobinson #115

**Comment by drobinson** [comment]
@tschifftner thanks.  I'm also thinking we can remove the moxieplayer.swf, but still haven't heard a yes/no from Magento https://twitter.com/d_rbn/status/786688518705844224

@infabo Did I miss something from your issue?

**Comment by Flyingmana** [comment]
I would handle moxieplayer.swf in a complete separate case, its not used for one of magentos basic features and was probably not reviewed yet properly.

Looks like a general movie player plugin from tiny_mce. (removing it in a separate PR together with its plugin entry is sure a good idea, even if magento itself does not)

**Comment by infabo** [comment]
@drobinson Nothing to add to #115. I guess the review process will make PRs like this one obsolete in the future.

**Comment by infabo** [comment]
Regarding moxieplayer.swf:
It's not done by just removing the swf file and removing addPlayer-function in editor_plugin_src.js.
You have to remove the whole FLASH stuff from the tinymce media plugin (looks a lot and quite cumbersome). Or am I wrong in this regard?

**Comment by tschifftner** [comment]
Could this be merged soon? Anything I could do?

**Pull request merged**
