### PR TITLE
Removed deprecated class Mage_Tag_Block_Customer_Edit

### PR DESCRIPTION
**Pull request by fballiano**
Mage_Tag_Block_Customer_Edit was deprecated in 1.3.2.3 and the functionality was actually completely removed (there's no phtml file about that) so I think it's safe to remove the class completely now.

### CODE REVIEW

**Review by ADDISON74 — APPROVED** [review]

**Review by kiatng — APPROVED** [review]

**Review by tobihille — APPROVED** [review]
Deprecated after 1.3.2.3 - it was about time to remove it :-)

**Review by ADDISON74 — APPROVED** [review]

**Comment by ADDISON74** [comment]
I have a request. When someone makes changes to an open PR after there are approvals, please mark those people again for notification. I don't have a problem doing it again, but it would be a pity not to do it right away.

**Comment by fballiano** [comment]
Sorry, I didn't want to "spam" with review requests, will do next time

**Comment by ADDISON74** [comment]
There is no problem. At this moment there are many PRs that still need a second approval to be merged. In some I added reviewers.

**Pull request merged**
