### PR TITLE
Fix class name and filename for case sensitive filesystems

### PR DESCRIPTION
**Pull request by kdckrs**
### Description (*)
Adds support for "SameSite" cookie property #1246 is throwing some errors on case-sensitive file systems. This PR fixes this.

### Related Pull Requests

- https://github.com/OpenMage/magento-lts/pull/1246

### Fixed Issues (if relevant)

Fixes compatibility with case sensitive file systems see https://github.com/OpenMage/magento-lts/pull/1246

### Manual testing scenarios (*)
In the backend, on General > Web, Magento's autoloader attempts to load Mage_Adminhtml_Model_System_Config_Source_Cookie_Samesite , while the class file is named "SameSite.php" (with an upper "Site" in it). The file is not auto-loaded on case sensitive filesystems, and causes wild errors.
(Taken from @ansgarbecker in the linked PR) 

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by kdckrs** [comment]
@Flyingmana something up with the Github Actions? Unit tests step failed on the "publish results" step:

`github.GithubException.GithubException: 403 {"message": "Resource not accessible by integration", "documentation_url": "https://docs.github.com/rest/reference/checks#create-a-check-run"}`

**Review by sreichel — APPROVED** [review]

**Comment by ansgarbecker** [comment]
@kdckrs Could you retry merging? I'm not sure why that was neccessary but I guess with 59983f91c8bd7c7ba91917823995d889c4c8bd07 this should pass through now.

**Comment by kdckrs** [comment]
> @kdckrs Could you retry merging? I'm not sure why that was neccessary but I guess with [59983f9](https://github.com/OpenMage/magento-lts/commit/59983f91c8bd7c7ba91917823995d889c4c8bd07) this should pass through now.

All good now ;)

**Review by ansgarbecker — APPROVED** [review]

**Review by ansgarbecker — APPROVED** [review]

**Review by tmotyl — APPROVED** [review]

**Comment by sreichel** [comment]
@all-contributors add @kdckrs code

**Pull request merged**
