### PR TITLE
Backport PR #3155 to v19

### PR DESCRIPTION
**Pull request by kiatng**
### Description (*)
Cherry-pick PR #3155 to v19.

### Related Pull Requests
PR #3155

### Fixed Issues (if relevant)
1. Fixes OpenMage/magento-lts#3580

### CODE REVIEW

**Review by Flyingmana — APPROVED** [review]

**Review by elidrissidev — APPROVED** [review]

**Comment by fballiano** [comment]
fine for me to merge but I've a question, we have tens of PRs for php8.2 in v20, why backport only this one?

**Review by sreichel — APPROVED** [review]

**Comment by sreichel** [comment]
> fine for me to merge but I've a question, we have tens of PRs for php8.2 in v20, why backport only this one?

Yes. Why only this one? Most PRs should be backported.

**Comment by fballiano** [comment]
It's time for a new release and I'd like to understand what to do with this PR, it's approved and it should get merged but at the same time why backport one among many many php8.1 PRs?

If we merge one we should merge all of them but v19 should be in security patch only.

**Comment by elidrissidev** [comment]
Since v19 promises PHP 8.1 support, I think it's fine to backport the few PRs and call it a day.

**Comment by fballiano** [comment]
but in the readme it's written "8.1 with some warnings shown", anyway, we'll never get past this discussion so I think who wants to work on v19, mergin this and backporting other PRs, it's obviously free to do that.
I'll stick to v20 and release that one at the moment, at the end of the day we don't have to release both branches at the same time.

**Comment by Flyingmana** [comment]
> fine for me to merge but I've a question, we have tens of PRs for php8.2 in v20, why backport only this one?

because the Person asked only for this part, and we are not "officially" supporting it, right? so there is no need to do more then what is asked for.

**Pull request merged**
