### PR TITLE
Merge 20.0.14 to 20.0 branch

### PR DESCRIPTION
**Pull request by fballiano**
To avoid any conflict and to be absolutely sure that what we're having on the 20.0 branch is exactly the same of what's been relased with 20.0.14, I've merged the v20.0.14 tag into 20.0 branch.

No conflict and perfect alignment, If I'm not missing anything.

Related PR: https://github.com/OpenMage/magento-lts/pull/2131 but I think it's not correct to remerge and manually fix conflicts again, since it was already done before the release and it's important that we have everything perfectly in sync with what was released.

### CODE REVIEW

**Review by Flyingmana — APPROVED** [review]

**Review by kiatng — APPROVED** [review]

**Comment by tmotyl** [comment]
@fballiano this requires a new tag ?

**Comment by fballiano** [comment]
mmm I don't think so since the release has its tag https://github.com/OpenMage/magento-lts/releases/tag/v20.0.14

**Comment by tmotyl** [comment]
so release was from 20.0.14 branch or from 20.0?

**Comment by fballiano** [comment]
the release was from branch called "release-20" created by @Flyingmana (where he fixed the conflicts)

**Comment by tmotyl** [comment]
Please clarify which branch is which and what was released.
I thought that branch 20.0.x-dev was a branch from which 20.0.x releases (e.g. 20.0.14 are done) and we merge branch 1.9.4x to 20.0.x-dev before the release.
So all commits from 1.9.4.x branch are also included in 20.0.x-dev branch.

Is this still the case?

Does the recent 20.0.14 release include all commits from 20.0.x-dev branch? If not we need to fix it asap, as people using 20.0.13 release will be surprise when they start using 20.0.14 and see that some changes are gone.

**Comment by fballiano** [comment]
I don't know, I wasn't in these decisions at that time.

From what I've seen in the discussion area
Schermata 2022-05-19 alle 11 50 10

Daniel merged in the release-20 branch.

so the releases were done from release-19 and release-20 branch

**Comment by tmotyl** [comment]
@fballiano please check whether the release is correct and contains what was in previous 20 releases and in 20.0x-dev branch.

@Flyingmana can you shed some light on it?

**Comment by tmotyl** [comment]
Thanks @fballiano!
The last thing to solve is purpose of the branches 20.0 and 20.0.x-dev.
Which one should developers follow to have the most recent commits in 20 line?

**Comment by fballiano** [comment]
well, I don't know (I think we should have something like a discord meetup to talk about few things altogether) but I would remove them and recreate them before every release

**Comment by fballiano** [comment]
Also, I said it in some discussion, we should merge 19->20 every once in a while to avoid to have 50 PRs to merge before release, this way the v20 branch would be usable and testable during the development cycle

**Comment by Flyingmana** [comment]
> Please clarify which branch is which and what was released. I thought that branch 20.0.x-dev was a branch from which 20.0.x releases (e.g. 20.0.14 are done) and we merge branch 1.9.4x to 20.0.x-dev before the release. So all commits from 1.9.4.x branch are also included in 20.0.x-dev branch.
> 
> Is this still the case?
> 
> Does the recent 20.0.14 release include all commits from 20.0.x-dev branch? If not we need to fix it asap, as people using 20.0.13 release will be surprise when they start using 20.0.14 and see that some changes are gone.

I followed the plan described in https://github.com/OpenMage/magento-lts/issues/2009 where for release we move the current 20.0.x changes into a separate branch so we can prepare a release without possibly disruptions with merged PRs, for cases where we need more then a few hours to prepare a release, which could for example happen, if we want to merge in certain security patches  just before the release, but are not able to exact time it.

**Comment by Flyingmana** [comment]
> Thanks @fballiano! The last thing to solve is purpose of the branches 20.0 and 20.0.x-dev. Which one should developers follow to have the most recent commits in 20 line?

this is a topic which does not belong into here (as this PR is not related to the 20.0.x-dev branch)
and I dont know who started or updated the branch in the past, but its not part of our branch protection rules

**Comment by tmotyl** [comment]
Lest move discyssion to #2009 then

**Pull request merged**
