### PR TITLE
Fix error when calling shell script from browser

### PR DESCRIPTION
**Pull request by Caprico85**
### Description (*)
Running a shell script from browser may cause the PHP warning `Undefined array key "argv"`. This happens because shell/abstract.php tries to read `$_SERVER['argv']` without checking if it exists. `$_SERVER['argv']` is not set when a script is run from browser.

I know running a shell script from browser doesn't make much sense and trying it will result in the message `This script cannot be run from Browser. This is the shell script.`. But nonetheless, the script should exit gracefully and not trigger a PHP warning.

### Manual testing scenarios (*)
1. Open http://example.com/shell/indexer.php or any other shell script in your browser. Depending on your server settings you will see the warning.

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [X] All automated tests passed successfully (all builds are green)
 - [X] Add yourself to contributors list

### CODE REVIEW

**Review by luigifab — DISMISSED** [review]

**Comment by sreichel** [comment]
Why not

```
if (!isset($_SERVER['argv'])) {
    return $this;
}
```

**Review by luigifab — APPROVED** [review]

**Comment by justinbeaty** [comment]
I am not sure empty is correct. What about a custom shell script that extends the abstract class, but has no arguments?

**Comment by fballiano** [comment]
@justinbeaty I created a script and the run() method works correctly also with this patch, so I think the "empty" is not a problem in this context

**Review by fballiano — APPROVED** [review]

**Comment by fballiano** [comment]
but actually... htaccess forbids to call shell/*.php from browser... so do we need this?

**Review by justinbeaty — APPROVED** [review]

**Comment by justinbeaty** [comment]
I read it more carefully and see that it wouldn't cause any problems. 

Regarding htaccess, I suppose it still doesn't hurt in case someone has a misconfigured server.

**Comment by fballiano** [comment]
merged and cherrypicked to v20

**Pull request merged**
