### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by sreichel**
### Description (*)

...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Comment by sreichel** [comment]
Fixed in#2780

**Comment by fballiano** [comment]
that's why I saw it already in my code :-)

**Comment by sreichel** [comment]
Just came home and saw this issue ... and did not update my local branch ... :)

Hotfix release?

**Comment by fballiano** [comment]
I don't know how to do that, now that 1.9.4.x is halfway with the composer/releasebuilder thingy

**Comment by sreichel** [comment]
Releasebuilder lgtm, but the Credis error ... 

Sorry for introducing this error ... :/

Not sure how to fix/release it in "minutes".

**Pull request closed without merging**
