### PR TITLE
Merge v19 -> v20

### PR DESCRIPTION
**Pull request by fballiano**
Cherry picking from https://github.com/OpenMage/magento-lts/compare/v19.4.20...1.9.4.x

### CODE REVIEW

**Comment by fballiano** [comment]
https://github.com/OpenMage/magento-lts/pull/2744 had conflicts

**Comment by sreichel** [comment]
@fballiano CS-error was fixed in #2613.

**Comment by fballiano** [comment]
@sreichel thanks! I have no idea why it wasn't on the list of the differences between branches :-\

anyway, it was a disaster of conflicts, hope I merged it right :-\

**Comment by sreichel** [comment]
@fballiano please diff 19.4.x an 20 ...

I'd did not review PRs that targets v20 ...

... methods got removed instead of mark them deprecated in 19 and not use it in 20. Core methods signatures changes like `formatDate` in MageCoreHelperData ... changes to templates that are not neccesarry ... e.g `getHintHtml()`

Its really hard to diff :(

**Comment by fballiano** [comment]
merged #2810 which had conflicts

**Comment by tmotyl** [comment]
is the change to `$this->_oldFieldsMap = [` reverted on purpose?

**Comment by fballiano** [comment]
> is the change to `$this->_oldFieldsMap = [` reverted on purpose?

which commit is it?

**Comment by tmotyl** [comment]
@fballiano  https://github.com/OpenMage/magento-lts/pull/2766/commits/e2c1169598778658f0ce9290cb569ae3c2bae7f4

This change is already too big for a code review, so I there might be more issues like this. 

In my opinion, we should port changes between branches one by one (the person who merges should do the port right away).
In my pov branch 20 should become our main branch, and changes that should be also applied to 19, should be backported (cherry-picked) after merging to 20. But this is a different conversation.

**Comment by fballiano** [comment]
I'm saying that v20 should be the default branch since months and everybody is against me... we have no clear way to decide this change so we get stuck in this situation.

IMHO it's a totally bad idea continuing to do everything on v19 and porward port everything. merging is hell, I waste far too many hours and nobody really checks v20 anyway.

But it also doesn't make senso to port every PR with another PR, it would take forever to merge, we're far too many people for maintaining two branches.

**Comment by tmotyl** [comment]
@fballiano In my proposal the backport is merged right away by the merger to v20 without an additional code review process. Of course, if the merger sees some severe conflicts or is unsure he can request the review, but by default, it should be backported right away.
This workflow is used by TYPO3 core team since many years and is working fine.
Anyway, I don't want to slow anybody down. It's really amazing to see so many changes being processed last months!

**Comment by fballiano** [comment]
I couldn't do that until a few days ago (didn't have any privilege to do that), now I could do that and I makes sense. but I still think we should get rid of a branch. v19 should not be modified ever, unless there's a severe need for that, we're just wasting resources we could use better.

**Comment by fballiano** [comment]
@tmotyl I've reverted that commit anyway, we'll have to manage it separately

**Comment by fballiano** [comment]
So, I merged some PRs directly in the 20.0 branch, the ones that didn't have any conflicts, to lower the amount of file changed.

The point is that I stopped since almost all of the PRs have conflict, this is a list up to the point when I stopped:
https://github.com/OpenMage/magento-lts/pull/2744
https://github.com/OpenMage/magento-lts/pull/2761
https://github.com/OpenMage/magento-lts/pull/2757
https://github.com/OpenMage/magento-lts/pull/2765
https://github.com/OpenMage/magento-lts/pull/2411
https://github.com/OpenMage/magento-lts/pull/2773
https://github.com/OpenMage/magento-lts/pull/2778
https://github.com/OpenMage/magento-lts/pull/2775
https://github.com/OpenMage/magento-lts/pull/2780
https://github.com/OpenMage/magento-lts/pull/2776
https://github.com/OpenMage/magento-lts/pull/2780
https://github.com/OpenMage/magento-lts/pull/2776
I was probably halfway.

These tasks are exausting and do not provide much value to anybody.

**Comment by fballiano** [comment]
@sreichel can you help merging https://github.com/OpenMage/magento-lts/pull/2810 into this PR?

**Comment by sreichel** [comment]
Can you cherry pick https://github.com/OpenMage/magento-lts/pull/2810/commits/af3a3dca014f3ac9e7fe85967ccb9d14e3086d98?

**Comment by fballiano** [comment]
> Can you cherry pick [af3a3dc](https://github.com/OpenMage/magento-lts/commit/af3a3dca014f3ac9e7fe85967ccb9d14e3086d98)?

to 20.0? it should already be in 20.0, which PR does it come from?

**Comment by sreichel** [comment]
Lets ignore #2810 ... i'll update later.

(btw ... if you're facing issues with phpstan.baseline conflicts .... 1) ignore them (just merge) 2) generate new baseline file 3) append last commit with new baseline 4) push)

If there are (much?) diffs between v19/20, we know something is wrong.

**Comment by fballiano** [comment]
PR is now up-to-date with 1.9.4.x, except we still have to merge https://github.com/OpenMage/magento-lts/pull/2810

**Comment by ADDISON74** [comment]
After you integrate #2810 do you want me to approve it so we can make a surprise for everyone for the holidays? 

The transition to ZF1-Future requires intensive testing at least 3 months. I would recommend caution for a while to those who want to upgrade in production.

**Comment by sreichel** [comment]
> except we still have to merge #2810

Ignore this PR ... it just added some comments and deprecation notes. 

Check my open PRs ... #2831 and #2800 could be added. Everything els can wait.

Btw ... last step: generate new baseline pls. Next thing is to fix issues on both sides to get rid off conflicts or failed tests.

**Comment by sreichel** [comment]
Sonar tests fail ...

`simplexml_load_file(): I/O warning : failed to load external entity "/home/runner/work/magento-lts/magento-lts/lib/Zend/Locale/Data/es_419.xml"`

**Comment by sreichel** [comment]
Looks like a x-mas release :christmas_tree:

**Comment by sreichel** [comment]
> The transition to ZF1-Future requires intensive testing at least 3 months.

Should we add a suffix to this release (`-RC1`)?

**Comment by fballiano** [comment]
> Should we add a suffix to this release (`-RC1`)?

@sreichel https://github.com/OpenMage/magento-lts/pull/2835 ;-)

**Comment by sreichel** [comment]
This phpstan errors "lgtm" ... seems all related to v20 only. Baseline upade and we are ready?

**Comment by sreichel** [comment]
Im not going to update phpstan baseline for v20.

Changes that cause errors like this should be reverted. No is no need to change method signatures ....

```
 ------ ---------------------------------------------------------------------------------------------- 
  Line   app/code/core/Mage/Adminhtml/Helper/Data.php                                                  
 ------ ---------------------------------------------------------------------------------------------- 
  65     PHPDoc tag @param references unknown parameter: $suffix                                       
  80     Method Mage_Adminhtml_Helper_Data::getPageHelpUrl() invoked with 2 parameters, 0-1 required.  
 ------ ---------------------------------------------------------------------------------------------- 
```

Pls revert this in v20.

**Comment by fballiano** [comment]
I can't just revert it but I don't understand why the signature was changed. I'll check it out later.

**Comment by fballiano** [comment]
> Im not going to update phpstan baseline for v20.
> 
> Changes that cause errors like this should be reverted. There is no need to change method signatures .... Just mark them as deprecated (and add PHPMD unsued formal parameter to docs).
> 
> ```
>  ------ ---------------------------------------------------------------------------------------------- 
>   Line   app/code/core/Mage/Adminhtml/Helper/Data.php                                                  
>  ------ ---------------------------------------------------------------------------------------------- 
>   65     PHPDoc tag @param references unknown parameter: $suffix                                       
>   80     Method Mage_Adminhtml_Helper_Data::getPageHelpUrl() invoked with 2 parameters, 0-1 required.  
>  ------ ---------------------------------------------------------------------------------------------- 
> ```
> 
> Pls revert this in v20.

@sreichel https://github.com/OpenMage/magento-lts/pull/2838

**Comment by fballiano** [comment]
> After you integrate #2810 do you want me to approve it so we can make a surprise for everyone for the holidays?

@ADDISON74 it would be nice :-) but I think we'll merge #2810 in a separate PR since the conflict needs to be addressed more carefully :-)

**Comment by fballiano** [comment]
@sreichel what command should I use now to generate the baseline?

**Comment by sreichel** [comment]
`phpstan -b phpstan.dist.baseline.neon`

**Comment by fballiano** [comment]
mmmm

```
/usr/local/opt/php@7.3/bin/php vendor/bin/phpstan -b phpstan.dist.baseline.neon                                                        
Command "phpstan.dist.baseline.neon" is not defined.  
```

**Comment by sreichel** [comment]
> mmmm
> 
> ```
> /usr/local/opt/php@7.3/bin/php vendor/bin/phpstan -b phpstan.dist.baseline.neon                                                        
> Command "phpstan.dist.baseline.neon" is not defined.  
> ```

Forgot composer install? I've a shortcut, complete command should be 'vendor/bin/phpstan -b phpstan.dist.baseline.neon'?

**Comment by fballiano** [comment]
noup, I wouldn't have vendor/bin/phpstan otherwise ;-)

**Comment by sreichel** [comment]
Should i commit it? Generated it one minute ago.

Btw ... on v20 branch there will be a warning:

```
 [WARNING] Baseline generated with 2111 errors.                                                                         
           Some errors could not be put into baseline. Re-run PHPStan and fix them.      
```

This comes from this v19-only related issue ...

```
    ignoreErrors:
      # OpenMage version comparison
      -
        message: "#^Strict comparison using \\=\\=\\= between 19 and 20 will always evaluate to false\\.$#"
        path: app/Mage.php
```

Can be ignored at the moment.

**Comment by fballiano** [comment]
if you want yes, IMHO we could directly disable phpstan on v20 😂

**Comment by sreichel** [comment]
We should remove the diffs between branches ... baseline file should work for v19 and v20.

**Comment by sreichel** [comment]
Not so nice ... phpstan does not ignore non-existing errors. Makes sense, but needs one mor PR to fix ...

**Comment by fballiano** [comment]
I've synced everything, notes:
- https://github.com/OpenMage/magento-lts/pull/2855 seems doesn't have anything to merge
- we still have to merge https://github.com/OpenMage/magento-lts/pull/2810 but I'd do it separately
- we should merge this, it is already too huge to handle

**Comment by sreichel** [comment]
Sync v20 can be move to next release imho.

**Comment by sreichel** [comment]
> CI / Check files / Changed (pull_request)

Think we can ignore it for this release.

Problems:
- workflows should run when files are deleted, but ...
- we deleted lib/Zend at the same time ...

... dont know if it is worth to raise an issue at https://github.com/tj-actions/changed-files

**Comment by fballiano** [comment]
updated this today, still misses https://github.com/OpenMage/magento-lts/pull/2810 that will be handled separately.

please review and let's merge it, it's already too huge.

**Review by sreichel — APPROVED** [review]

**Review by kiatng — APPROVED** [review]

**Comment by fballiano** [comment]
Note: I directly pushed these two

Screenshot 2023-01-03 alle 10 30 25

to 20.0 because there were no conflicts

**Comment by fballiano** [comment]
pushed these directly to v20 since there were no conflicts

Screenshot 2023-01-03 alle 22 50 21

**Comment by fballiano** [comment]
just pushed all the new merged PRs on "20.0" branch

**Comment by luigifab** [comment]
I think there is something wrong on branch 20 for _Mage.php_: `setIsDownloader` is back, `getOpenMageVersion` return 19, `@http_response_code(500);` is removed.
Not sure if other files have problems or not.

**Comment by ADDISON74** [comment]
@luigifab is right. Method setIsDownloader was removed here https://github.com/OpenMage/magento-lts/commit/b1098b29f235d98cefd4484027c647b1af4c26cc but if you check the code in OM 20 is still there.

**Comment by fballiano** [comment]
@luigifab the getOpenMageVersion bug is coming from https://github.com/OpenMage/magento-lts/pull/2839, it should be fixed already on branch 20.0, I've committed the right number for that method to return.

I'm checking the downloader thing now.

**Comment by fballiano** [comment]
So, setIsDownloader was coming from that same PR, this is the commit https://github.com/OpenMage/magento-lts/commit/7c5b68e07900ca1abebbb13ef7d7ce70ef99c1df

The PR was correctly forward ported (it should have been) but we should have modified the v20 version, which we didn't.

I now have removed the setIsDownloader which seems to me the only thing we should have done in v20 with PR #2839.

**Pull request merged**
