### PR TITLE
Fixed whitespace for docblocks

### PR DESCRIPTION
**Pull request by fballiano**
Continuing to fix whitespace and formatting for docblock, also switched http to https for license links.

2650 files to go... 😭

### CODE REVIEW

**Comment by ADDISON74** [comment]
http => https is also in this open PR https://github.com/OpenMage/magento-lts/pull/2295.

**Comment by fballiano** [comment]
I know but I’m using that change to trigger a change on every class so that i can manually check aaaaaallll of the files, which will have poorly formatted docblock anyway

**Comment by fballiano** [comment]
Its more if a way for me to speed up this job which is half automatic but half manual

**Comment by justinbeaty** [comment]
I'll just rebase #2295 when you're done with these rounds of whitespace / http updates. Also, I'm glad you're updating these. It bothered me too, I just figured I'd try a PR after the DISCALIMER & copyright PRs were merged.

**Comment by fballiano** [comment]
better to merge how it is now, then I'll create a new one (just not to go too much past 1000 files)

**Review by sreichel — APPROVED** [review]

**Review by ADDISON74 — APPROVED** [review]

**Pull request merged**
