### PR TITLE
Implement the possibility to search for null in backend grids

### PR DESCRIPTION
**Pull request by digitalpianism**
### Description (*)

This modification will let users search for NULL entries in the backend grids.

### Fixed Issues (if relevant)

1. Fixes OpenMage/magento-lts#1189

### Manual testing scenarios (*)

1. Access a backend grid where an entry has a NULL value
2. Filter the grid searching for NULL in the column input
3. Enjoy the result

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by luigifab** [comment]
I tried but it does not work on our websites, I did that:

```php
$filtered = array_map(static function ($value) {
    return is_object($value) ? $value->__toString() : $value;
}, array_values($cond));
if (in_array('\'%NULL%\'', $filtered, true) || in_array('NULL', $filtered, true)) {
    $this->getCollection()->addFieldToFilter($field, ['null' => true]);
} else {
    $this->getCollection()->addFieldToFilter($field, $cond);
}
```

**Comment by luigifab** [comment]
I still using my version, but not really used because I forgot that now I can search with NULL :)

**Comment by fballiano** [comment]
done, hope correctly :-)

**Review by luigifab — DISMISSED** [review]

**Comment by ADDISON74** [comment]
This one is failing again with PHPStan.

**Comment by luigifab** [comment]
PHPStan is wrong! Where is the support? 😸

**Comment by ADDISON74** [comment]
This PR is useful only when there are no data on a column of a Backend grid. I can get this information by one click on column title. Of course is a difference between a sort and a filtering action. It is easier to do mass-actions with filtered information (Select All).

**Review by tobihille — DISMISSED** [review]

**Review by kiatng — DISMISSED** [review]
Tested and worked. @tobihille Thanks for the bump.

**Comment by fballiano** [comment]
somebody understands what phpstan is complaining about?

**Comment by kiatng** [comment]
@fballiano It's caused by the docblock here:

https://github.com/OpenMage/magento-lts/blob/fb601b07077a8ab3073bbdc582641f14906d45a3/app/code/core/Mage/Adminhtml/Block/Widget/Grid.php#L286-L294

It should be

```php
     * @return Mage_Core_Model_Resource_Db_Collection_Abstract|Varien_Data_Collection_Db
```

But I am not sure what should be done to fix that in this PR.

**Comment by sreichel** [comment]
> It should be
> 
> ```
>      * @return Varien_Data_Collection_Db
> ```

This would work, but not sure if its a good idea ... will check tomorrow

- `     * @param Varien_Data_Collection|Varien_Data_Collection_Db $collection`
- `     * @return Varien_Data_Collection|Varien_Data_Collection_Db`

**Comment by fballiano** [comment]
@sreichel did you have time to check this?

**Comment by sreichel** [comment]
Yes, fix phpstan-baseline.neon ... change count 1 to 2 for now. Its just a workaround, but removing this supressed errors is what i frequently do ... it will be fixed later ....

```
		-
			message: "#^Call to an undefined method Varien_Data_Collection\\:\\:addFieldToFilter\\(\\)\\.$#"
			count: 1
			path: ../app/code/core/Mage/Adminhtml/Block/Widget/Grid.php
```

**Review by kiatng — DISMISSED** [review]

**Comment by sreichel** [comment]
This feature should be mentioned at README, b/c in a few days nobody will remember that has been added and how it works.

**Comment by ADDISON74** [comment]
The author has been inactive on GitHub for a long time. If you want to mention it in the README, one of us must do it. I would propose that those PRs in which the authors are no longer active be closed and create new ones by those who are active.

**Comment by sreichel** [comment]
I'll update readme when its merged.

**Comment by digitalpianism** [comment]
@ADDISON74 I'm quiet but I'm still there. Is there anything you need me to do?

**Comment by sreichel** [comment]
@digitalpianism can you please fix phpstan-baseline? If you want, please add some lines to README.

**Comment by digitalpianism** [comment]
@sreichel so Im confused about phpstan (never used it before), it seems like you made a commit changing the count from 1 to 2. What you expect me to fix here exactly ?

**Comment by sreichel** [comment]
Problem found: https://github.com/OpenMage/magento-lts/pull/1203/commits/2214b1711f7a0291689565ae000f552256b7e5c3 reverted all changes. I'll fix this in the evening ... (reapply fix)

**Comment by sreichel** [comment]
@kiatng i dont know. I guess you just used the "Update branch" button.

**Review by fballiano — DISMISSED** [review]
test on customer grid, works

**Comment by fballiano** [comment]
(but we should add something to the README)

**Comment by sreichel** [comment]
> (but we should add something to the README)

You successfully tested it, its your job :P

**Comment by fballiano** [comment]
> > (but we should add something to the README)
> 
> You successfully tested it, its your job :P

fair enough 🤣

**Review by fballiano — APPROVED** [review]

**Review by kiatng — APPROVED** [review]

**Comment by luigifab** [comment]
The committed version is wrong if I remember correctly (not tested again).

We need: `is_array($cond) ? array_values($cond) : [$cond]`
because `$cond` is also a int when we filter reviews in backend on type customer.

**Comment by kiatng** [comment]
I have this in production. I have searched for `NULL`, `int` ranges, string, and date ranges. All work correctly. Can you see a test case where it fails?

**Comment by kiatng** [comment]
> because $cond is also a int when we filter reviews in backend on type customer

I cannot test the above because I do not have customer reviews.

But filtering for `store_id` in order grid and `customer_group` in customer grid work fine.

**Comment by kiatng** [comment]
Looking at the code:

https://github.com/OpenMage/magento-lts/blob/712a3eecf33bf16435d8089244dbf115341c468d/app/code/core/Mage/Adminhtml/Block/Widget/Grid.php#L499-L503

If `$cond` is of type `int`, then it will throw on line 503

> Warning: array_values() expects parameter 1 to be array

When searching for all the `function getCondition()` in folder https://github.com/OpenMage/magento-lts/tree/1.9.4.x/app/code/core/Mage/Adminhtml/Block/Widget/Grid/Column/Filter

The function return either `null` or `array` as far as I can see, except for

https://github.com/OpenMage/magento-lts/blob/712a3eecf33bf16435d8089244dbf115341c468d/app/code/core/Mage/Adminhtml/Block/Widget/Grid/Column/Filter/Checkbox.php#L53-L65

and `Radio.php`. All other filters return an array. 

But I have not seen a grid column that uses checkbox or radio. So what do we do?

**Comment by sreichel** [comment]
> I cannot test the above because I do not have customer reviews.

Tested with sample data and @luigifab is right. PR incoming.

**Comment by sreichel** [comment]
> If `$cond` is of type `int` or not an array, then it will throw on line 503
> 
> > Warning: array_values() expects parameter 1 to be array

This is what happens on customer review page + filter. :)

**Comment by kiatng** [comment]
I overlooked that it is possible to define your own filter:

https://github.com/OpenMage/magento-lts/blob/5d9036e35d29be5c172501cd5a550b9c4764667a/app/code/core/Mage/Adminhtml/Block/Review/Grid.php#L147-L153

And it returns `int`:

https://github.com/OpenMage/magento-lts/blob/5d9036e35d29be5c172501cd5a550b9c4764667a/app/code/core/Mage/Adminhtml/Block/Review/Grid/Filter/Type.php#L41-L51

**Comment by sreichel** [comment]
Maybe this could have been easier with correct phpdocs .... I'm working on this :)

**Pull request merged**
