### PR TITLE
Fixes different width of input fields, see #3716

### PR DESCRIPTION
**Pull request by sreichel**
### Description (*)

- changed width to 330px for textarea, text & select fields
- updated README.md

### Fixed Issues (if relevant)

1. Fixes OpenMage/magento-lts#3716

### Questions or comments

Only tested with modern admin theme. Maybe can improved for all other SCSS files (untested).

### CODE REVIEW

**Comment by sreichel** [comment]
Note: i only chaned the SCSS-file. Everything else (order selectors was made autotically)

**Comment by fballiano** [comment]
tested, seems to me to work fine, I wouldn't add the filewatcher section to the readme tho since it's used by an extreme minority or people

**Comment by sreichel** [comment]
Added readme section to provide to provide some basic information to work with scss files.

Which tool do you use?

**Comment by pquerner** [comment]
I acutually like the comment in the readme. Its for developers, afterall.

**Comment by sreichel** [comment]
@fballiano i've used compass in the past to, but faced problems with different ruby packages.

1. different tools may cause different css-output
2. i had to setup new PhpStorm and struggeld with correct config  to write css to the right place (thats why i added it - just as a reminder)

IMHO the readme is already to large ... maybe consider https://github.com/OpenMage/magento-lts/pull/3659 to be merged.

**Comment by sreichel** [comment]
> I acutually like the comment in the readme. Its for developers, afterall.

Wd like to keep it to.

Btw ... also fixes system-config fields.

**Pull request closed without merging**
