### PR TITLE
Fix for catalog_product_relation not being deleted when bundle option deleted.

### PR DESCRIPTION
**Pull request by dannydnz**
### Description (*)

Patch for when a Bundle option or selection is deleted. Previously product would have to be saved twice to remove the catalog_product_relation row. This messes with some indexes.

### Fixed Issues (if relevant)

1. Fixes OpenMage/magento-lts#<issue_number>

### Manual testing scenarios (*)

1. Remove an option from a bundle and save.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)
 - [ ] Add yourself to contributors list

### CODE REVIEW

**Comment by kiatng** [comment]
I can replicate this in DDEV with sample product ID 447 and monitoring the table `catalog_product_relation`. 
image

When a child product is deleted, the product needs to save twice for the table to be refreshed. With this PR, the table is refreshed on product save.

**Comment by kiatng** [comment]
Sorry for accidentally closing the PR. @dannydnz Is your change in production, have you tested it and is satisfied that it has no side-effect?

**Comment by sreichel** [comment]
Testing it, but please upgrade the description/title. Only your branch name tells its about bundle items.

**Review by sreichel — APPROVED** [review]
Tested.

**Comment by dannydnz** [comment]
Have updated PR. Yes is in production. No issues so far.

**Review by kiatng — APPROVED** [review]

**Comment by kiatng** [comment]
@all-contributors please add @dannydnz for code

**Comment by sreichel** [comment]
> @all-contributors please add @dannydnz for code

https://github.com/OpenMage/magento-lts/issues/1126

**Pull request merged**
