### PR TITLE
Use short array syntax

### PR DESCRIPTION
**Pull request by luigifab**
### Description

I found this great tool: [php-short-array-syntax-converter](https://github.com/thomasbachem/php-short-array-syntax-converter)
So I converted to short array syntax some directories with:

```
find app/ dev/ errors/ shell/ lib/Varien/ lib/Magento/ lib/Mage/ lib/Zend/ lib/Unserialize/ ./*.php -name "*.php" -exec php convert.php -w "{}" \;
find app/ dev/ errors/ shell/ lib/Varien/ lib/Magento/ lib/Mage/ lib/Zend/ lib/Unserialize/ -name "*.phtml" -exec php convert.php -w "{}" \;
```

_I tested this tool with [zf1-future](https://github.com/Shardj/zf1-future), already converted to short array syntax.
I reverted library/Zend/ directory to traditional syntax, then I converted to short array syntax, result: no differences._

_I added our lib/Zend directory to reduce number of changes of #1832._

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by elidrissidev** [comment]
The amount of labels looked scary for a bit. Good one 👍

**Comment by luigifab** [comment]
I think we have reached the limit here.

**Comment by sreichel** [comment]
👍

**Comment by tmotyl** [comment]
Can we also have a php-cs-fixer configuration to enforce this styling rule at commit/pr level?

**Comment by elidrissidev** [comment]
Achievement unlocked: Reach max labels in a Pull Request

**Comment by luigifab** [comment]
I pushed this PR to our production environment some days ago (except for `app/`, only `app/code/core/`).
It's pura vida!

**Comment by elidrissidev** [comment]
@luigifab I can provide some help when I get some time this weekend

**Comment by elidrissidev** [comment]
@luigifab You will need the tool itself to be added via composer. I also saw from the documentation that it includes some default rules, you'd want to run it locally first to check.

**Comment by luigifab** [comment]
@elidrissidev I not sure to understand what you mean because a new action is started when I add new commit:

image
image
 
I also added a phtml file not displayed in the previous diff error log...

**Comment by elidrissidev** [comment]
@luigifab Oh nvm. The docker image for the Action already includes the php-cs-fixer tool. But aren't we gonna need to run it locally too, to spot violations before creating a PR?

**Comment by luigifab** [comment]
I'm so sorry, up? 🐈

**Review by elidrissidev — APPROVED** [review]

**Comment by luigifab** [comment]
Conflict + Rebase.
Second achievement unlocked: +50,000 changes

**Comment by luigifab** [comment]
Dear people, conflict + rebase.

**Review by elidrissidev — DISMISSED** [review]
I still think it's a good idea to include php cs fixer as a composer dependency to be able to run it locally, but i'll wait for someone else to agree first.

**Comment by tmotyl** [comment]
@elidrissidev for me having php-cs-fixer as dev-dependency is not a blocker from my POV

**Comment by tmotyl** [comment]
@luigifab this change is too big for a review.
As I also need phpcsfixer rule in some other PR, I propose the following:
Can you provide a phpcsfixer configuration, composer and action which doesn't change anything in the code yet, or with some really small rule.
this patch can be quickly merged
and then have a change which just adds a new rule and changed files?

**Comment by luigifab** [comment]
Yes, but for all PR, one of the checks will fail every time.
To check, I think you can run the two commands in your repository, then diff -r your_repo/ my_branch/.

**Comment by luigifab** [comment]
So, I remove commit [Use short array syntax](https://github.com/OpenMage/magento-lts/pull/1835/commits/28541bf090a5f274c51ec96e5514f21f56157936) or I rebase and commit again to fix conflict?

**Comment by tmotyl** [comment]
@luigifab i suggest following:
1) in a separate PR add a php cs fixer config and github action which goes green without much (or any) code change
2) lets merge pr from 1) to 1.9.4.x
3) tag a new 1.9.4.x release and 20.x release
4) rebase / redo this change and merge it
5) tag and release a new versions

this change is huge thus has a potential of breaking stuff (automated code conversion tool can make a mistake too), so for easier debugging and release handling I would not like to add this change to the current pendig release (which is huge already)

**Comment by luigifab** [comment]
I removed code change for this PR.
But... what's next... I'm not sure what to do.

**Comment by fballiano** [comment]
Am I missing something or the "action" doesn't actually do anything to the actual repo?

**Comment by fballiano** [comment]
> Am I missing something or the "action" doesn't actually do anything to the actual repo?

I'll rephrase, does this action actually modify the files and commit them to the repo?

**Comment by luigifab** [comment]
No, only [checks](https://github.com/OpenMage/magento-lts/runs/6377076665?check_suite_focus=true).
There is an option to add a commit, I don't remember it.

**Comment by fballiano** [comment]
So the purpose is to add a check and get an error if the user didn’t use short syntax for arrays?

**Comment by tmotyl** [comment]
Looks good by reading, I would just exclude zend from the check, as this would make harder to spot differences between zend versions (there is a separate discussion around zend).

from my pov ideal scenario to move topic forward:
1) release new 19 and 20 releases
2) add code changes to this commit (to actually change array syntax)
3) merge it to both 19 and 20 branches

why this scenario? To limit impact of possible regressions and have less merge conflicts.

however im also ok if code changes are added here and merged.

**Comment by sreichel** [comment]
@luigifab

> This step has been truncated due to its large size. Download the full logs from the menu once the workflow run has completed. 

:smile: 

I'd leave out everything from lib/ ... maybe this helps?!?

**Comment by luigifab** [comment]
dry-run because this check don't do the job for you.
I added lib/Zend to reduce number of changes between magento zend and [zf1-future](https://github.com/Shardj/zf1-future).

**Comment by sreichel** [comment]
> No, only [checks](https://github.com/OpenMage/magento-lts/runs/6377076665?check_suite_focus=true). There is an option to add a commit, I don't remember it.

Got it (to late).

**Pull request closed without merging**
