### PR TITLE
Update and rename custom.css to custom.css.template

### PR DESCRIPTION
**Pull request by seansan**
Useless during upgrades

### CODE REVIEW

**Comment by seansan** [comment]
rename + add .template

**Comment by Flyingmana** [comment]
is this file not referenced somewhere? I would guess its needed for a proper default fallback

**Comment by sreichel** [comment]
It is referenced ... https://github.com/OpenMage/magento-lts/blob/1.9.3.1/app/design/adminhtml/default/default/layout/main.xml#L84

Nice idea, but vote 4 close ;)

**Comment by colinmollenhour** [comment]
Agreed it should be left alone. There are other ways to override it if needed.

**Pull request closed without merging**
