### PR TITLE
Fixed truecolor detection for WebP images

### PR DESCRIPTION
**Pull request by fballiano**
Fixes https://github.com/OpenMage/magento-lts/issues/3400

### CODE REVIEW

**Review by kiatng — APPROVED** [review]
Tested.

**Review by ADDISON74 — APPROVED** [review]
Tested. I confirm it solves the issue.

**Comment by ADDISON74** [comment]
One more thing, what I reported here https://github.com/OpenMage/magento-lts/issues/3400#issuecomment-1647440002 it seems to be fixed.

If someone wants to test and confirm here are the files I used for checking the quality on the edges of the product (JPG, WebP formats).

quality

[image_quality.zip](https://github.com/OpenMage/magento-lts/files/12149450/image_quality.zip)

**Comment by sreichel** [comment]
Maybe make it more readable ... https://inthedigital.co.uk/use-phps-in_array-to-compare-a-variable-to-multiple-values/

**Pull request merged**
