### PR TITLE
Do not autoload captcha class when disabled

### PR DESCRIPTION
**Pull request by luigifab**
### Description

With Blackfire, I found when captcha is disabled in configuration, a class is autoloaded.
I dislike.

captcha

OpenMage 20.0.16 / PHP 8.0.25

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by kiatng — APPROVED** [review]

**Comment by fballiano** [comment]
@luigifab does this work for you with latest @sreichel modification?

**Comment by luigifab** [comment]
Yes.

**Comment by fballiano** [comment]
is it ok if we release before merging this? since I got enough reviews to merge https://github.com/OpenMage/magento-lts/pull/2571?

**Comment by luigifab** [comment]
Yes, this is not really important.

**Review by sreichel — APPROVED** [review]

**Comment by fballiano** [comment]
@sreichel I made a mistake and merged without squashing (since I changed the default merge strategy while merging the whole v19 -> v20 PR) and now the diff looks awful: https://github.com/OpenMage/magento-lts/compare/v19.4.19...1.9.4.x 

Is it possible to fix it without reverting?

sorry :-(

**Pull request merged**
