### PR TITLE
Ensure $price and $rate are both numeric types

### PR DESCRIPTION
**Pull request by m-overlund**
Ensures price and rate are of type floatval (and not string).

Fixes this TypeError
"TypeError: Unsupported operand types: string * int"

### Fixed Issues (if relevant)

1. Fixes OpenMage/magento-lts#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)
 - [ ] Add yourself to contributors list

### CODE REVIEW

**Comment by fballiano** [comment]
how do you reproduce the error?

```php
    public function convert($price, $toCurrency = null)
    {
        $price = (float) $price;
        if (is_null($toCurrency)) {
            return $price;
        } else {
            $rate = (float) $this->getRate($toCurrency);
            if ($rate) {
                return $price * $rate;
            }
        }
```

but it still lacks a default return statement... the original method doesn't seem to be super well written...

**Comment by m-overlund** [comment]
I'll revert the change and reproduce.
I think it's a custom code issue - due hiding the price on products out of stock / products we do not sell anymore.

Despite custom code, I don't like the missing "validation" of input.

**Comment by fballiano** [comment]
yep sure, that's why I added the casting (changing from the floatval function because casting is more widely used in our code)

**Comment by fballiano** [comment]
but that method expect floats and it's stated in the docbloc, I don't think it's possible to check every input of every method

**Comment by joshua-bn** [comment]
If you're getting an error you're sending it the wrong data. PHP is already trying to cast it to a number to make the arithmetic work but it fails because of some other character(s) in there. You want it to break in that case.

**Comment by elidrissidev** [comment]
Agree with @joshua-bn, better to get the full stack-trace and find out where the string is coming from.

**Comment by sreichel** [comment]
> The best solution would be a type on the args.

Y, but does v20 "allow" changes method sigantures (adding types)?

**Comment by fballiano** [comment]
@joshua-bn @elidrissidev are we closing this one? let's just not leave it hanging here forever.

**Comment by m-overlund** [comment]
Maybe not 100% related but #3135 is also a case of typecasting / string/int issues.
decisions need to be made :)

**Comment by m-overlund** [comment]
non-issue.
Casted string to Mage::helper('core')->currency()

Closing.

**Pull request closed without merging**
