### PR TITLE
Fix missing method in Mage_Downloadable_Adminhtml_Downloadable_Product_EditController::linkAction()

### PR DESCRIPTION
**Pull request by Sekiphp**
### Issue: #719 

Currently untested, but should work :-)

### CODE REVIEW

**Comment by Sekiphp** [comment]
> Either it's `customer/session` for customer session, or `_getSession()` for admin session.

I don't think so.... This class is in adminhtml scope - so I think, that `admin/session` is correct way. Now I see, that this is more complicated.....but I have an idea how to fix this.

**Comment by sreichel** [comment]
> > Either it's `customer/session` for customer session, or `_getSession()` for admin session.
> 
> I don't think so.... This class is in adminhtml scope - so I think, that `admin/session` is correct way.

You got me wrong. Sorry. Next time i'll be more clear :)

If we follow **wrong** naming it "**should**" be `customer/session` . Your first commit was nearly right, but instead of 

    Mage::getSingleton('admin/session')

use helper method (from Mage_Adminhtml_ControllerAction)

    $this->_getSession()

**Comment by Sekiphp** [comment]
@sreichel I think, that is correct solution now. You have right with existing `_getSession()` method, but we need to conserve overriding this method in child (because this is not used in admin scope)

**Comment by Sekiphp** [comment]
Someone to re-check @sreichel ?

**Comment by Sekiphp** [comment]
Issue was closed by colinmollenhour on 15 Jun 2020

**Pull request closed without merging**
