### PR TITLE
Update Autolabeler Config to Version 5.0.0

### PR DESCRIPTION
**Pull request by Sdfendor**
### Description (*)

[Github Autolabeler](https://github.com/actions/labeler) updated to version 5.0.0 three days ago which breaks existing configuration files.
image

This PR adjusts the config so that it works again. No other changes regarding e.g. orphaned entries or new capabilities of new version of Autolabeler are part of this PR. 

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by Flyingmana — DISMISSED** [review]

**Review by tobihille — APPROVED** [review]
Looks good.
Since you're contributing at least on a semi-regular basis to open mage: do you want to take the opportunity to add you to the contributors?
(Just a thought, I don't know if there are rules for this and if you really want to 😅)

**Comment by Sdfendor** [comment]
@tobihille I always assumed I've added myself already. Doesn't seem like it though.

**Review by fballiano — APPROVED** [review]

**Comment by fballiano** [comment]
I'll merge since I consider @Flyingmana's review still valid

**Comment by fballiano** [comment]
@Sdfendor should it be this way?

Screenshot 2023-12-07 alle 13 29 12

**Comment by Sdfendor** [comment]
@fballiano This is the old state, the current run - as it is my understanding - uses the main autolabeler config not the one from PR. So only if this is merged new PRs will use the new config.

**Review by fballiano — DISMISSED** [review]

**Comment by fballiano** [comment]
I've tested locally with `act` (which took me a good half hour to setup) and I still get 

[Labeler/Add labels]   ❗  ::error::Error: found unexpected type for label 'Environment' (should be array of config options)

**Comment by fballiano** [comment]
```
[Labeler/Add labels] [DEBUG] Working directory '/Users/fab/Projects/magento-lts'
[Labeler/Add labels]   💬  ::debug::looking for pr #3695
[Labeler/Add labels]   💬  ::debug::fetching changed files for pr #3695
[Labeler/Add labels]   💬  ::debug::found changed files:
[Labeler/Add labels]   💬  ::debug::  .github/labeler.yml
[Labeler/Add labels]   💬  ::debug::  README.md
| The configuration file (path: .github/labeler.yml) was not found locally, fetching via the api
[Labeler/Add labels]   ❗  ::error::Error: found unexpected type for label 'Environment' (should be array of config options)
[Labeler/Add labels]   ❗  ::error::found unexpected type for label 'Environment' (should be array of config options)
```

I don't understand why it says that it can't find the labeler.yml when it's there...

anyway, i'm not opposed to merging this one and see what happens

**Comment by Sdfendor** [comment]
I'm also not sure why this is the case. We encountered the same behavior on our current shop repo here on Github though. After merge it started to label once again. We made the same kind of adjustments (just less of them) that are present in this PR to our labeler.yml.

**Comment by sreichel** [comment]
https://github.com/actions/labeler/issues/712

**Comment by fballiano** [comment]
since the current state of the main branch is broken anyway, and we already use "pull_request" as trigger (as people are talking about in https://github.com/actions/labeler/issues/712) I think we should merge this one and see what happens, I can't be worse than the actual state.

**Review by fballiano — APPROVED** [review]

**Comment by fballiano** [comment]
I think we should merge this and see if it works on the other PRs

**Review by kiatng — APPROVED** [review]

**Comment by fballiano** [comment]
it's merged and I run it on https://github.com/OpenMage/magento-lts/pull/3707 but I think it still doesn't work

Screenshot 2023-12-26 alle 00 34 06

what should we do?

**Comment by Sdfendor** [comment]
In which way didn't it work? I can't see an error in the run in #3707 which was the main goal of this PR. The "fetching via the api" info line has been there before and is still there.

**Comment by fballiano** [comment]
ah! sorry but when I ran it it didn't seem to have added the javascript label, which it's actually added.. maybe I didn't see it at that time for some reason 😅 it's solved then, thank you!

**Pull request merged**
