### PR TITLE
Removed LICENSE.html in favor of LICENSE.txt

### PR DESCRIPTION
**Pull request by sreichel**
### Description (*)

osl3

At my fork output is different ... only see content from that html file ...

Lets try and see, or revert it ... ?

### Related Pull Requests
1. Fixes OpenMage/magento-lts#1545

Maybe it should not be prefixed w/ license?

### CODE REVIEW

**Comment by fballiano** [comment]
can't we just remove that file altogether?

**Comment by sreichel** [comment]
It is used by web installer.

**Comment by sreichel** [comment]
... the txt file is mentioned in every copyright block ...

**Comment by fballiano** [comment]
I know but couldnt we use the txt for the web installer?

Il giorno sab 3 feb 2024 alle 17:48 Sven Reichel ***@***.***>
ha scritto:

**Comment by sreichel** [comment]
Not tested, but I think it's for (html) formatting.

**Comment by fballiano** [comment]
yep, but I think that something like an nl2br would kinda be enough for that use case ;-)

**Comment by sreichel** [comment]
Tested. Looks okay. Only one special char in LICENSE.txt that i wont change,.

**Review by fballiano — APPROVED** [review]

**Review by kiatng — APPROVED** [review]

**Pull request merged**
