### PR TITLE
Make Prototype Validator optional

### PR DESCRIPTION
**Pull request by loekvangool**
### Description (*)
I'm removing `prototype/validation.js` from some of my pages, but some shared JavaScript libs assume it's still there and start to generate errors.

The validator is not necessary on every page, hence it should be possible to remove it without running into errors.

In the slightly longer term, I'd like to see the whole thing removed and instead switch to the new HTML5 validation options, which are plenty: https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation.

### CODE REVIEW

**Comment by loekvangool** [comment]
Related to #3054

**Comment by fballiano** [comment]
at a first glance it should be ok

**Review by fballiano — APPROVED** [review]
why not

**Comment by fballiano** [comment]
merged and 20ed

**Pull request merged**
