### PR TITLE
Code style (endif endforeach endfor and more)

### PR DESCRIPTION
**Pull request by luigifab**
### Description

This PR updates code style of PHP code (#1027).

For express review, perhaps you can:
- git clone 1.9.4.x in base/
- git clone endif-endwhile-endforeach in changes/

Then, open all modified files of base/ directory in your text editor, search and replace (case sensitive) in all files (from bottom to top):
```
<?php endfor; ?>      by  <?php endfor ?>
<?php endfor;?>       by  <?php endfor ?>
<?php else :?>        by  <?php else: ?>
<?php else : ?>       by  <?php else: ?>
<?php else:?>         by  <?php else: ?>
<?php endforeach; ?>  by  <?php endforeach ?>
<?php endforeach;?>   by  <?php endforeach ?>
<?php endforeach?>    by  <?php endforeach ?>
<?php endif; //       by  <?php endif //
<?php //endif; ?>     by  <?php //endif ?>
<?php endif; ?>       by  <?php endif ?>
<?php endif;?>        by  <?php endif ?>
<?php endif?>         by  <?php endif ?>
```

Then, `diff -r -U0 base/ changes/`

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by colinmollenhour** [comment]
> **Need to discuss:** We should change the review workflow for this kind of PR. Nobody want's to review 800 files manually and it's very time consuming (for me: 2 1/2hours for 300 files => estimated 6-7hours for all files)

@luigifab If you applied the change with a command line tool perhaps you could supply the command used so we could easily reproduce it?

**Comment by luigifab** [comment]
Sorry, no command used, I search all files, open all files, search/replace string with my text editor, save and commit.

**Comment by colinmollenhour** [comment]
@luigifab Sorry about the conflicts, can you merge the latest to resolve?

**Comment by luigifab** [comment]
I repushed without xmlconnect changes.
For express review, perhaps you can:
- git clone 1.9.4.x in base/
- git clone endif-endwhile-endforeach in changes/

Then, open all modified files in your text editor to search and replace (case sensitive) in all files of base/ directory:
```
):?>                  by  ): ?>
' while('             by  ' while ('
' foreach('           by  ' foreach ('
' for('               by  ' for ('
' elseif('            by  ' elseif ('
' if('                by  ' if ('
<?php endfor; ?>      by  <?php endfor ?>
<?php endfor;?>       by  <?php endfor ?>
<?php else :?>        by  <?php else: ?>
<?php else : ?>       by  <?php else: ?>
<?php else:?>         by  <?php else: ?>
<?php endforeach; ?>  by  <?php endforeach ?>
<?php endforeach;?>   by  <?php endforeach ?>
<?php endforeach?>    by  <?php endforeach ?>
<?php endif; //       by  <?php endif //
<?php //endif; ?>     by  <?php //endif ?>
<?php endif; ?>       by  <?php endif ?>
<?php endif;?>        by  <?php endif ?>
<?php endif?>         by  <?php endif ?>
```

Then, `diff -r -U0 base/ changes/`
I hope it is better.

**Comment by kkrieger85** [comment]
@luigifab Please stop to add more commits here ;) 

I think it would be better to create separate PR for different Code Style changes. 
That would be improve the code review process.

**Comment by kkrieger85** [comment]
See discussion about PHPCSFIXER in https://github.com/OpenMage/magento-lts/issues/947

**Review by luigifab — COMMENTED** [review]
Yes, so sorry, I rebased and repushed only *endxyz* changes to get a diff.

**Comment by luigifab** [comment]
I try to apply the diff but no... so I made a script to do the job:

```php
<?php

$todo = [
	'<?php endfor; ?>'     => '<?php endfor ?>',
	'<?php endfor;?>'      => '<?php endfor ?>',
	'<?php else :?>'       => '<?php else: ?>',
	'<?php else : ?>'      => '<?php else: ?>',
	'<?php else:?>'        => '<?php else: ?>',
	'<?php endforeach; ?>' => '<?php endforeach ?>',
	'<?php endforeach;?>'  => '<?php endforeach ?>',
	'<?php endforeach?>'   => '<?php endforeach ?>',
	'<?php endif; //'      => '<?php endif //',
	'<?php //endif; ?>'    => '<?php //endif ?>',
	'<?php endif; ?>'      => '<?php endif ?>',
	'<?php endif;?>'       => '<?php endif ?>',
	'<?php endif?>'        => '<?php endif ?>',
];

foreach ($todo as $search => $replace) {

	echo $search,"\n";

	$files = [];
	exec('grep -Hlrn "'.$search.'" app/', $files);

	foreach ($files as $file) {
		echo '  ',$file,"\n";
		file_put_contents($file, preg_replace('/\s+$/m', '', str_replace($search, $replace, file_get_contents($file))));
		// system(git add app/ ; git commit -m "")
	}
}
```

**Review by fballiano — APPROVED** [review]

**Review by kkrieger85 — APPROVED** [review]

**Review by colinmollenhour — APPROVED** [review]
I used the PHP script on the same base commit and the result was slightly different but no material differences so I approve so this can get merged sooner than later. Attached is the diff that was generated.
[diff.patch.txt](https://github.com/OpenMage/magento-lts/files/6399575/diff.patch.txt)

**Comment by ADDISON74** [comment]
Once this will be released with a new OM version I recommend a revision of the code looking for some parts unchanged. I will do that too.

A script (e.g. PHP, bash) will be useful to change any custom theme by everyone interested. I guess the one provided by @luigifab is just fine.

**Comment by ADDISON74** [comment]
What is your opinion about ```<?php break; ?>``` ?

Should it be ```<?php break ?>```?

**Comment by fballiano** [comment]
@ADDISON74 you've a great eye, I added "break" as a new PR https://github.com/OpenMage/magento-lts/pull/1577

**Pull request merged**
