### PR TITLE
Head.php to HTML5

### PR DESCRIPTION
**Pull request by loekvangool**
Remove unneeded closing tags, javascript and css types, proper line endings

### CODE REVIEW

**Review by kiatng — APPROVED** [review]

**Review by tmewes — APPROVED** [review]

**Review by ADDISON74 — APPROVED** [review]

**Review by elidrissidev — APPROVED** [review]

**Comment by fballiano** [comment]
thanks @elidrissidev, I'm sick these days so I'm super slow but I'll do it :-)

**Comment by elidrissidev** [comment]
@fballiano get well soon man ♥️

**Comment by fballiano** [comment]
I ported this one to 20.0 but there were conflicts (since that file has a lot of IE related stuff), can you give a check to https://github.com/OpenMage/magento-lts/commit/54e2072ac559a940685c304bde7364c175db4cfd please?

**Comment by elidrissidev** [comment]
Looks good 👍

**Pull request merged**
