### PR TITLE
make fulltext search separator (OR/AND) configurable from backend

### PR DESCRIPTION
**Pull request by sreichel**
### Description (*)

https://magento.stackexchange.com/a/84312/46249

> The biggest inexplicably nonsensical move by Magento is to use "OR" search instead of "AND". If you search "red cars" you will get everything red (including cars, dogs, forks, mountainsides, etc), and every kind of car (including red, blue, green, yellow, etc). With "AND", you get only items that contain "red" AND "car", which is how search should work!

Just added a config option to change from OR to AND.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Comment by ADDISON74** [comment]
Nice work Sven. I am glad to see you posting again.

**Review by fballiano — APPROVED** [review]
tested and working, nice PR and needed feature!

**Comment by fballiano** [comment]
@ADDISON74 would you add a code review?

**Review by Flyingmana — APPROVED** [review]

**Comment by luigifab** [comment]
I wake up today, but new configuration values use beginning and ending space.
I dislike 😢. Not sure but perhaps this is the first configuration value with required space.

**Comment by fballiano** [comment]
hehehe you're the master of syntax, it makes sense tho and we can always change it :-)

**Comment by Flyingmana** [comment]
personally I also think the config without spaces would be better, and adding them where the config is applied.
Still possible to change, its merged but not inside a release yet.

**Comment by sreichel** [comment]
Whats wrong with that spaces?

Just tried to make it as simple as possible.

**Comment by luigifab** [comment]
I think the fate of these spaces is to be trimmed.

**Pull request merged**
