### PR TITLE
Adding useful feedback to Gd2.php exceptions

### PR DESCRIPTION
**Pull request by loekvangool**
### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by colinmollenhour** [comment]
Are these exceptions ever visible to users or are they just logged?

**Comment by loekvangool** [comment]
I got this thrown at the admin user by an extension that creates a product feed for a SaaS search solution. The exception caused complete failure of the feed generation job. A message like does not contain enough information to be called "actionable" imo, and thus has to be expanded and we shoule probably consider not creating exceptions for this at all (all that happened was that there were a few stray BMP and TIFF images in the `media` dir). Also, the Mage frontend did not display these images for the accompanying products. There actually was no message logged in any of these cases, maybe we should add `Mage::logException()` calls as well.

Lastly, we might consider merging https://github.com/magento-hackathon/Perfect_Watermarks for imagemagick support (I see you have forked that repo already).

**Comment by ADDISON74** [comment]
> Lastly, we might consider merging https://github.com/magento-hackathon/Perfect_Watermarks for imagemagick support (I see you have forked that repo already).

This project was not updated for more than 6 years. It is based on imaginemagick which had security issues. Just read a issue posted in 2016 here https://github.com/magento-hackathon/Perfect_Watermarks/issues/24.

**Comment by loekvangool** [comment]
> > Lastly, we might consider merging https://github.com/magento-hackathon/Perfect_Watermarks for imagemagick support (I see you have forked that repo already).
> 
> This project was not updated for more than 6 years. It is based on imaginemagick which had security issues. Just read an issue posted in 2016 here [magento-hackathon/Perfect_Watermarks#24](https://github.com/magento-hackathon/Perfect_Watermarks/issues/24).

The code could be updated.

The security issue is easily mitigated, for instance for CentOS see https://access.redhat.com/security/vulnerabilities/ImageTragick.

**Review by fballiano — APPROVED** [review]

**Review by ADDISON74 — APPROVED** [review]
Even if I don't consider the wording "was" appropriate the change is useful to identify where the error comes from.

**Comment by loekvangool** [comment]
> Even if I don't consider the wording "was" appropriate the change is useful to identify where the error comes from.

Yeah agreed, made a new PR

**Pull request merged**
