### PR TITLE
Updated copyright blocks

### PR DESCRIPTION
**Pull request by sreichel**
### Description (*)

I took me some hours to go though all files that changes and updated copyright blocks .... not.

Just used https://github.com/OpenMage/magento-lts/pull/2295 :+1: 

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Review by ADDISON74 — APPROVED** [review]

**Review by fballiano — APPROVED** [review]
love it

**Comment by Flyingmana** [comment]
just, why?
why do we need to update the year in the copyright headers? what is the benefit for anyone?

**Comment by ADDISON74** [comment]
If I remember correctly the script created by @justinbeaty makes changes only in the files that have been changed in the meantime. There is a long discussion why we need to change the copyright header in a few places (#2276, #2297) and here for legal aspects (#2295).

**Comment by sreichel** [comment]
@Flyingmana we started this with #2297. Now we can/could/should keep it up to date? Are there any downsides?

**Comment by fballiano** [comment]
in the old times they were updating every single file at every release. we're just updating the files that were actually modified, which makes 78% more sense ;-)
anyway it was a very long discussion and it was decided to accept that PR.

**Comment by sreichel** [comment]
> which makes 78% more sense

82% ... at least.

**Comment by ADDISON74** [comment]
Changing the header can also be seen as useful information. For example, a file had its last changes in the year 2022. Not that it would help much, but there are files that we have never touched inherited from Magento.

**Pull request merged**
