### PR TITLE
add ReturnTypeWillChange to various Files catched by code style checker

### PR DESCRIPTION
**Pull request by Flyingmana**
### Fixed Issues (if relevant)

1. Fixes OpenMage/magento-lts#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)
 - [ ] Add yourself to contributors list

### CODE REVIEW

**Comment by fballiano** [comment]
IMHO we should stop touching lib/Zend

**Comment by Flyingmana** [comment]
its either this or accepting we cant reach compatibility with future php versions without replacing it fully with an alternative.

**Comment by fballiano** [comment]
zf1-future is php8.1 compatible. actually i'm testing OM19 on php8.1 with no problems

**Comment by ADDISON74** [comment]
I confirm that ZF1-Future is compatible with PHP8.1. In my case I had to keep the 2 files in /app/code/core/Zend/Db so I could run OM.

Not only this compatibility should interest us, but also other aspects that are maintained by those who strive to continue with this framework. For example, in OM the TLS protocol is supported up to version 1.0 while ZF1-Future has support for version 1.2. I tested extensions that no longer work in the our current configuration, but that work without issues with ZF1-Future.

**Review by Sdfendor — APPROVED** [review]

**Review by tmewes — APPROVED** [review]

**Pull request merged**
