### PR TITLE
Fixes undefined classes

### PR DESCRIPTION
**Pull request by sreichel**
`Mage_Sales_Order_Item` and `Mage_Sales_Model_Quote_Total` does not exist ...

### CODE REVIEW

**Comment by seansan** [comment]
+1 are there any known problems because of this

**Comment by edannenberg** [comment]
`Mage_Sales_Model_Order_Item` does exist though, shouldn't it be included in the checks or is it not used?

**Comment by sreichel** [comment]
@edannenberg  `Mage_Sales_Model_Order_Item` isn't same as `Mage_Sales_Order_Item` ;)

**Comment by edannenberg** [comment]
Yea, but to me this signaled a typo for `Mage_Sales_Model_Order_Item`, in which case the real class should have been included in the fixed checks. Doesn't matter in this case though as `$this->getItem()->getOrderItem();` is returned anyways, sorry for the noise. :)

**Comment by Antcef11** [comment]
I've been getting errors since this change.
```
Error: Call to a member function formatPrice() on null
#50 Mage/Bundle/Block/Adminhtml/Sales/Order/Items/Renderer.php(203): getValueHtml
#49 app/design/adminhtml/default/default/template/bundle/sales/invoice/create/items/renderer.phtml(73): include
#48 Mage/Core/Block/Template.php(241): fetchView
#47 Mage/Core/Block/Template.php(273): renderView
#46 Mage/Core/Block/Template.php(287): _toHtml
#45 Mage/Adminhtml/Block/Template.php(81): _toHtml
#44 Mage/Core/Block/Abstract.php(923): toHtml
#43 Mage/Adminhtml/Block/Sales/Items/Abstract.php(177): getItemHtml
#42 app/design/adminhtml/default/default/template/sales/order/invoice/create/items.phtml(63): include
#41 Mage/Core/Block/Template.php(241): fetchView
#40 Mage/Core/Block/Template.php(273): renderView
#39 Mage/Core/Block/Template.php(287): _toHtml
#38 Mage/Adminhtml/Block/Template.php(81): _toHtml
#37 Mage/Core/Block/Abstract.php(923): toHtml
#36 Mage/Core/Block/Abstract.php(641): _getChildHtml
#35 Mage/Core/Block/Abstract.php(585): getChildHtml
#34 app/design/adminhtml/default/default/template/sales/order/invoice/create/form.phtml(96): include
#33 Mage/Core/Block/Template.php(241): fetchView
#32 Mage/Core/Block/Template.php(273): renderView
#31 Mage/Core/Block/Template.php(287): _toHtml
#30 Mage/Adminhtml/Block/Template.php(81): _toHtml
#29 Mage/Core/Block/Abstract.php(923): toHtml
#28 Mage/Core/Block/Abstract.php(641): _getChildHtml
#27 Mage/Core/Block/Abstract.php(585): getChildHtml
#26 Mage/Adminhtml/Block/Widget/Form/Container.php(145): getFormHtml
#25 app/design/adminhtml/default/default/template/widget/form/container.phtml(37): include
#24 Mage/Core/Block/Template.php(241): fetchView
#23 Mage/Core/Block/Template.php(273): renderView
#22 Mage/Core/Block/Template.php(287): _toHtml
#21 Mage/Adminhtml/Block/Template.php(81): _toHtml
#20 Mage/Adminhtml/Block/Widget/Container.php(308): _toHtml
#19 Mage/Core/Block/Abstract.php(923): toHtml
#18 Mage/Core/Block/Text/List.php(43): _toHtml
#17 Mage/Core/Block/Abstract.php(923): toHtml
#16 Mage/Core/Block/Abstract.php(641): _getChildHtml
#15 Mage/Core/Block/Abstract.php(585): getChildHtml
#14 app/design/adminhtml/default/default/template/page.phtml(74): include
#13 Mage/Core/Block/Template.php(241): fetchView
#12 Mage/Core/Block/Template.php(273): renderView
#11 Mage/Core/Block/Template.php(287): _toHtml
#10 Mage/Adminhtml/Block/Template.php(81): _toHtml
#9 Mage/Core/Block/Abstract.php(923): toHtml
#8 Mage/Core/Model/Layout.php(555): getOutput
#7 Mage/Core/Controller/Varien/Action.php(390): renderLayout
#6 Mage/Adminhtml/controllers/Sales/Order/InvoiceController.php(187): newAction
#5 Mage/Core/Controller/Varien/Action.php(418): dispatch
#4 Mage/Core/Controller/Varien/Router/Standard.php(254): match
#3 Mage/Core/Controller/Varien/Front.php(172): dispatch
#2 Mage/Core/Model/App.php(365): run
#1 app/Mage.php(691): run
```

Shouldn't the typo just be fixed? From Mage_Sales_Order_Item to Mage_Sales_Model_Order_Item.

This would also keep it the same as the getOrderItem function in the default renderer (/app/code/core/Mage/Sales/Block/Order/Item/Renderer/Default.php).

**Pull request merged**
