### PR TITLE
Remove allcontributors

### PR DESCRIPTION
**Pull request by luigifab**
### Description

This is an old idea/bug. Each day I go to the [home](https://github.com/OpenMage/magento-lts) of the repository, my browser download 10 MB of avatars images. This is not acceptable.

I suggest to redirect to [pulse](https://github.com/OpenMage/magento-lts/pulse).

avatars

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by elidrissidev** [comment]
An alternate solution could be to [load images lazily](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-loading) by overriding `contributorTemplate` in `.all-contributorsrc` file.

**Comment by Flyingmana** [comment]
how about moving it out of the readme onto the website?

**Comment by fballiano** [comment]
> An alternate solution could be to [load images lazily](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-loading) by overriding `contributorTemplate` in `.all-contributorsrc` file.

it seems a great idea, I think I found the original template here: https://allcontributors.org/docs/en/cli/configuration and it seems to be   `"contributorTemplate": "<a href=\"<%= contributor.profile %>\">\" width=\"<%= options.imageSize %>px;\" alt=\"\"/><br /><sub><b><%= contributor.name %></b></sub></a>"` right?

**Comment by elidrissidev** [comment]
Yes, that's true @fballiano

**Comment by luigifab** [comment]
So I closing and create a new one with `contributorTemplate` update.

**Pull request closed without merging**
