### PR TITLE
Do not load root category for isCategoryActive

### PR DESCRIPTION
**Pull request by luigifab**
### Description

With Blackfire, I found that when we call `isCategoryActive`, the root category is loaded.

Not sure why, but I have disabled that two months ago.
Perhaps it's not a good idea, but for me it's working.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Comment by kiatng** [comment]
I also think it's not a good idea, this PR will mess up `getCurrentCategory()`, and possibly make some developers unhappy.

**Comment by fballiano** [comment]
mmm it seems to me the original code is correct, at least the getCurrentCategory() method.

I mean, how are you calling isCategoryActive() and the category object is not loaded?

**Comment by luigifab** [comment]
For example on home page, on cms page, on login page, on cart page...
Add `echo 'load root';` on line 159 to see this text on your frontend.

**Comment by fballiano** [comment]
closing because of https://github.com/OpenMage/magento-lts/pull/2732#issuecomment-1319495873

**Pull request closed without merging**
