### PR TITLE
Use php8 string functions

### PR DESCRIPTION
**Pull request by sreichel**
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Comment by elidrissidev** [comment]
Should also drop the PHP 8 polyfills to use the native functions instead?

**Comment by sreichel** [comment]
Maybe got your wrong, but we need te polyfills as long we support php7 (?)

**Comment by fballiano** [comment]
we could remove the polyfills in `next`, but not in `main` ;-)

**Comment by elidrissidev** [comment]
My bad I thought `main` was where php 7 support was dropped!

**Comment by fballiano** [comment]
was this PR generated with rector or manually? just to know the level of detail we've to go in reviewing it.

**Comment by sreichel** [comment]
Manual regex search & replace.

**Review by elidrissidev — APPROVED** [review]
Reviewed all files manually. LGTM.

**Review by fballiano — APPROVED** [review]
also reviewed all the lines by eyes and seems everything is ok 🤞

**Review by fballiano — APPROVED** [review]
also reviewed all the lines by eyes and seems everything is ok 🤞

**Pull request merged**
