### PR TITLE
Update Mage_SalesRule_Model_Quote_Discount

### PR DESCRIPTION
**Pull request by Hanmac**
### Description (*)

* DiscountDescription should only be string or null (not array)
* strlen needs a type check for string before
* sales_quote_address_discount_item needs to be done after calculator->process

### Fixed Issues (if relevant)

1. Fixes OpenMage/magento-lts#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Comment by hirale** [comment]
About DiscountDescrption, check this file
 https://github.com/OpenMage/magento-lts/blob/main/app%2Fcode%2Fcore%2FMage%2FSalesRule%2FModel%2FValidator.php#L1039

**Comment by sreichel** [comment]
Wouldnt it be better to dispatch an `_after` event?

**Comment by Hanmac** [comment]
> Wouldnt it be better to dispatch an `_after` event?

The problem right now is that the existing event is either called before or after the calculator process

If you want a new event, you probably want one before process

**Comment by kiatng** [comment]
I agree with the change.

**Review by sreichel — APPROVED** [review]

**Review by kiatng — APPROVED** [review]

**Pull request merged**
