### PR TITLE
Version bump in preparation for next release

### PR DESCRIPTION
**Pull request by fballiano**
This is just a version bump for next release, I'm doing this at the beginning of the development cycle instead of right before release, in order not to forget at last minute.

Also, with this PR, I propose to have the same "minor" number for both v19 ad v20.
I know it's a bit weird to jump a couple of numbers but it's a bit uncomfortable, during release time, to have manage very similar but different numbers. What do you think about that?

### CODE REVIEW

**Comment by Flyingmana** [comment]
minor versions have a meaning, and if we would have a system to take them more serious, having them in sync would not make sense, and older major versions would always have higher minor versions, while they likely do not increase when the one for newer major versions do increase. Also its maybe not a good idea to start such a discussion in a PR

**Comment by fballiano** [comment]
I agree to the theory but I think whatever we can make to make our job easier we should do.

Anyway I'll switch it back

**Comment by Flyingmana** [comment]
in the best case we have automated it via a script anyway at one point as planed with the automated release process

**Comment by Flyingmana** [comment]
oh, also, as you were talking about minor version number, not patch-version, patch-version is even more likely to be asyncron, as soon as we have a bugfix which is only needed for the higher major version. Like sometimes it happens a release is broken. Should we then also for the other major version do a new (empty)release? do we skip one?

**Comment by fballiano** [comment]
ye sorry i was meaning patch number your right!

let's keep it as it is, it's not a big problem, but I noticed that when preparing the release I was like 19, 4, 16, 20, 0, 14 all the time and I was getting confused :-D

**Comment by luigifab** [comment]
Next release Next month? 😹

**Comment by fballiano** [comment]
> Next release Next month? 😹

why not :-)

**Comment by fballiano** [comment]
since @luigifab note about the phpstorm metadata i'm closing this PR, it will be done before release altogether

**Pull request closed without merging**
