### PR TITLE
Install composer dependencies in gitpod

### PR DESCRIPTION
**Pull request by elidrissidev**
### Description (*)

This PR adds a new container to the local and gitpod docker-compose files to be able to install composer dependencies in the `install.sh` script. I also fixed a couple of container names in gitpod script, since gitpod uses different names prefixed with `gitpod-`.

Local docker installation not tested.

### Fixed Issues (if relevant)
1. Fixes OpenMage/magento-lts#2961

### Manual testing scenarios (*)
1. Creating a new workspace in gitpod should install composer dependencies before trying to install openmage.
2. Composer dependencies should also get installed when running with locally with docker using `dev/openmage/install.sh`.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Comment by elidrissidev** [comment]
Also, does anyone know why gitpod link is no longer showing in CI checks?

**Comment by Flyingmana** [comment]
> Also, does anyone know why gitpod link is no longer showing in CI checks?

I dont know about it, but I use the browser extension which adds a button in the top right
image

**Review by Flyingmana — APPROVED** [review]
works again after a bit of waiting :)

**Review by fballiano — APPROVED** [review]

**Comment by fballiano** [comment]
merged and cherrypicked to v20

**Pull request merged**
