### PR TITLE
Show coupon code on order view in adminhtml

### PR DESCRIPTION
**Pull request by seansan**
…view)

solve longstanding order shortcoming (so actual coupon code on order view in adminhtml)
now our logistics see the description @ totals overview: but have to ask the customer: which code was it? esp. handy when using generated codes
simple fix: please improve if you think this can be done better. 
Breaks nothing, quickwin for admin users

### CODE REVIEW

**Comment by seansan** [comment]
ideas? downsides? 

+1

**Comment by tmotyl** [comment]
I had the same issue once. So i'm in favor of getting it in.

**Comment by blopa** [comment]
+1

**Comment by seansan** [comment]
+1 have tested in production works fine over here (and backend people very happy with it)

**Comment by seansan** [comment]
Close and move to https://github.com/OpenMage/magento-lts/pull/447

**Pull request closed without merging**
