### PR TITLE
Remove DISCLAIMER and change Magento -> OpenMage in header

### PR DESCRIPTION
**Pull request by justinbeaty**
### Description (*)

From discussion #2276

Updated file headers to change Magento -> OpenMage and remove the DISCLAIMER about modifying core files. This removed about 1.9MB in disk space.

### Manual testing scenarios (*)

Check out this branch and run:

```console
git diff -U0 HEAD~1 | grep '^[+-]' | grep -Ev '^(--- a/|\+\+\+ b/)' | awk '!x[$0]++'
```

That will print all unique changes made in this PR. You should only see comment changes. I will post the output in a follow up comment.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Comment by justinbeaty** [comment]
Here's the output of the git diff line to verify only comment changes were made in this PR:

```console
$ git diff -U0 HEAD~1 | grep '^[+-]' | grep -Ev '^(--- a/|\+\+\+ b/)' | awk '!x[$0]++'

- * Magento
+ * OpenMage
- * DISCLAIMER
- *
- * Do not edit or add to this file if you wish to upgrade Magento to newer
- * versions in the future. If you wish to customize Magento for your
- * needs please refer to http://www.magento.com for more information.
-# Magento
+# OpenMage
-# DISCLAIMER
-#
-# Do not edit or add to this file if you wish to upgrade Magento to newer
-# versions in the future. If you wish to customize Magento for your
-# needs please refer to http://www.magento.com for more information.
-// Magento
+// OpenMage
-// DISCLAIMER
-//
-// Do not edit or add to this file if you wish to upgrade Magento to newer
-// versions in the future. If you wish to customize Magento for your
-// needs please refer to http://www.magento.com for more information.
```

**Comment by justinbeaty** [comment]
Here is the script I used to create this PR in case anyone is interested: https://gist.github.com/justinbeaty/9e34aaa02958f14127288c930ea2ea7f

Pretty similar to the script included in #2295

**Comment by ADDISON74** [comment]
I agree with this PR but to approve it I have to go through all the 5000 files. The bad part is that in the browser GitHub only loads 3000 files and it takes time. In the future such big changes should be limited to a number of files in order to be browsed.

**Comment by justinbeaty** [comment]
@ADDISON74 I think your eyes will bleed if you try to manually check all 8,416 files and your computer will melt if you try and load it in the browser.

This is why I provided the command to condense the changes to only unique lines. I used these two StackOverflow links for the command: https://stackoverflow.com/a/26622262 and https://stackoverflow.com/a/11532197

**Comment by justinbeaty** [comment]
Rebased after #2296 and all checks are green! ✅

**Comment by fballiano** [comment]
checked it and everything seems ok, @justinbeaty do you want me to fix the conflict or you prefer rebasing it?

**Comment by justinbeaty** [comment]
@fballiano I've rebased and fixed the conflict.

**Review by fballiano — APPROVED** [review]
checked the diff and looks fine

**Review by sreichel — APPROVED** [review]

**Pull request merged**
