### PR TITLE
Preview PR in gitpod

### PR DESCRIPTION
**Pull request by sreichel**
_This is work in progress ..._

Needs to be merged for further tests.

PR should show a "open in gitpod" button, to preview current PR with installed OpenMage.

### CODE REVIEW

**Review by colinmollenhour — APPROVED** [review]
Can you provide a screenshot of where the button appears?

**Comment by sreichel** [comment]
I have no screenshot right now. I'll provide one later ... or take a look at DDEV repo that uses gitpod too.

**Comment by sreichel** [comment]
Give it a try?

We can roll back if it does not work.

**Review by ADDISON74 — APPROVED** [review]

**Comment by sreichel** [comment]
@colinmollenhour is there something to configure/enable in github admin ?

**Comment by colinmollenhour** [comment]
It's already configured and enabled, someone else must have a while back. I think maybe the addBadge option only applies to new PRs so please check on the next new PR.

**Comment by colinmollenhour** [comment]
I'm not sure how to reach Project Settings..
image

In my GitPod dashboard I seem to only be able to do anything related to private repos, I don't see how to do anything with an organization repo.

It does "work" with prefixing a PR repo URL with https://gitpod.io/# as far is it launches a workspace, but the url gets a 404 although it does look like an nfinx 404 if that means anything.. 
image

**Comment by colinmollenhour** [comment]
I uninstalled and re-installed and it opened a page in Gitpod dashboard with this:
image
So I think you just use the prefix or the browser extension.. Seems like the addBadge and addComment are no longer supported?

**Comment by colinmollenhour** [comment]
The startup script is broken
image

**Comment by sreichel** [comment]
@colinmollenhour thanks.

For some reason i used nun-existing php8.3-image.

I have

- changed it to 7.4
- added an action to create the gitpod link

This works so far, gitpod opens w/o error, but port 8000 (required for preview?) isn't available.

Can you please take a look at it?

Test here: https://github.com/openmage-strict/openmage-future/pull/55

**Comment by sreichel** [comment]
As said, I am not so firm with docker ... i'd appriciate your help. (o/c i can change the image, but i guess it still needs some adjustments)

What about https://github.com/OpenMage/docker-php?

**Comment by colinmollenhour** [comment]
I can't push to your repo but this should "work" (without sendmail or xdebug for now):
image

**Comment by sreichel** [comment]
You should have write permissions now.

**Comment by colinmollenhour** [comment]
I see that 33333 is the Gitpod user id so that makes sense..

I still can't push though according to Gitpod.. Here is the patch file:


```
From 5a32b9edaf5ecbe70a80e8d76872cfcb7006106e Mon Sep 17 00:00:00 2001
From: Colin Mollenhour <colin@mollenhour.com>
Date: Fri, 27 Sep 2024 00:59:54 +0000
Subject: [PATCH] Use a different not broken image. Disable sendmail and xdebug
 as there are permission errors. Fix hostname.

---
 .gitpod.yml                   | 9 ++++++---
 dev/gitpod/docker-compose.yml | 6 +++---
 2 files changed, 9 insertions(+), 6 deletions(-)

diff --git a/.gitpod.yml b/.gitpod.yml
index 3330a5b0d4..894068fe88 100644
--- a/.gitpod.yml
+++ b/.gitpod.yml
@@ -4,9 +4,12 @@ tasks:
     command: echo 'start script'
   - name: Install OpenMage
     init: |
-      BASE_URL="$(echo "$GITPOD_WORKSPACE_URL" | sed s~https://~https://8000-~)"
-      HOST_PORT=8000 BASE_URL=$BASE_URL bash dev/gitpod/install.sh
-    command: docker ps
+      cd dev/gitpod
+      echo "# Generated by .gitpod.yml - edit as needed" > .env
+      echo "HOST_NAME=8000-$GITPOD_WORKSPACE_ID.$GITPOD_WORKSPACE_CLUSTER_HOST" >> .env
+      echo "HOST_PORT=8000" >> .env
+      echo "BASE_URL=https://8000-$GITPOD_WORKSPACE_ID.$GITPOD_WORKSPACE_CLUSTER_HOST/" >> .env
+    command: bash dev/gitpod/install.sh
     openMode: tab-after
   - name: prepare git
     init: git config core.fileMode false
diff --git a/dev/gitpod/docker-compose.yml b/dev/gitpod/docker-compose.yml
index 9261658b44..dac7295f15 100644
--- a/dev/gitpod/docker-compose.yml
+++ b/dev/gitpod/docker-compose.yml
@@ -2,7 +2,7 @@ version: "3.7"
 
 services:
   apache:
-    image: openmage/php-dev:7.4-apache
+    image: ghcr.io/colinmollenhour/docker-openmage:8.2-apache
     hostname: ${HOST_NAME:-openmage-7f000001.nip.io}
     user: "33333:33333"
     ports:
@@ -10,8 +10,8 @@ services:
     volumes:
       - ../..:/var/www/html
     environment:
-      - ENABLE_SENDMAIL=true
-      - XDEBUG_CONFIG=remote_connect_back=1 remote_enable=1 idekey=phpstorm
+      - ENABLE_SENDMAIL=false
+      - XDEBUG_CONFIG=
       - MAGE_IS_DEVELOPER_MODE=1
     links:
       - mysql
-- 
2.46.0
```

Pipe that to `git apply`

**Comment by sreichel** [comment]
> I still can't push

Strange.

... to my fork or (strict) test-project?

Its 3:40am now ... going to sleep. Will test it tomorrow/later. Thanks for help.

**Comment by sreichel** [comment]
Thanks @colinmollenhour . Changing the docker-images worked and gitpod now starts w/o erros, BUT preview still does not work (port 8000) isnt availabe.

I would appreciate any help.

**Pull request merged**
