### PR TITLE
Fixed Magento not detecting HTTPS behind a proxy.

### PR DESCRIPTION
**Pull request by wexo-team**
This fix adds a check for the "HTTP_X_FORWARDED_PROTO" header to determine if the scheme is HTTPS or HTTP.

### CODE REVIEW

**Comment by kkrieger85** [comment]
As far as i can see, both classes inherit from Zend_Controller_Request_Http. So it might be better to do these changes in this class to avoid duplicate code.

**Comment by wexo-team** [comment]
Thank @kkrieger85,

I have now moved the fix into the class that you suggestet :-)

**Comment by sreichel** [comment]
@kkrieger85 is it possible to use "squash merge" option for unified commit log?

**Comment by kkrieger85** [comment]
Of course, it is

Am Do., 23. Juli 2020 um 15:53 Uhr schrieb sv3n <notifications@github.com>:

**Comment by Flyingmana** [comment]
can confirm of one case, where this did work and solve related Issues, thank you for providing the patch 😀

**Pull request merged**
