### PR TITLE
Added dependabot config

### PR DESCRIPTION
**Pull request by sreichel**
### Description (*)

Weekly updates for all composer deps ...

### Questions or comments

@Flyingmana @fballiano please check config ... this has to be enabled in repo settings ...

depbot

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Review by ADDISON74 — APPROVED** [review]

**Comment by fballiano** [comment]
we already have them enabled:

Screenshot 2022-12-24 alle 11 48 13

**Comment by sreichel** [comment]
"Version updates" have to be enabled to update composer dependencies.

**Comment by fballiano** [comment]
do we want to auto enable composer dependencies?

**Comment by fballiano** [comment]
it seems it will be enabled automatically when adding the dependabot.xml, cause when i click "Dependabot version updates" it opens a new window with a textarea to edit the dependabot.xml...

let's merge this one and see ;-)

**Review by fballiano — APPROVED** [review]

**Review by ADDISON74 — APPROVED** [review]

**Comment by fballiano** [comment]
I think it’s enabled now 😉
D93A1456-7498-41EB-86E5-2A4D7E56EF58

**Pull request merged**
