### PR TITLE
Minor fixes on 'filter_condition_callback' method _filterStoreConditi…

### PR DESCRIPTION
**Pull request by kiatng**
…on().

Minor code fixes.

### CODE REVIEW

**Review by Sdfendor — DISMISSED** [review]

**Review by luigifab — DISMISSED** [review]

**Review by fballiano — APPROVED** [review]

**Review by ADDISON74 — APPROVED** [review]

**Comment by fballiano** [comment]
@kiatng could you check the conflict? sorry :-(

**Comment by sreichel** [comment]
Damn, had to remove all lines ... please reapply change to baseline (instead of resolving conflicts :P)

**Comment by kiatng** [comment]
As I'm not any good with git CLI, I rely on TortoiseGit, it seems ok now.

**Review by sreichel — APPROVED** [review]

**Comment by sreichel** [comment]
> As I'm not any good with git CLI, I rely on TortoiseGit, it seems ok now.

OT: why TortoiseGit? Not using phpStorm?

**Comment by kiatng** [comment]
> > As I'm not any good with git CLI, I rely on TortoiseGit, it seems ok now.
> 
> OT: why TortoiseGit? Not using phpStorm?

Way way back then, I couldn't afford phpStorm; I used free tools. Now that I can afford it but the habit stuck. I do not know what I am missing but VS Code is good enough for me. Plus, I can represent those 3rd-world developers, or other devs, for whatever reasons, use free tools like me.

**Comment by sreichel** [comment]
> Way way back then, I couldn't afford phpStorm

Erm ... if you activly contribute to an unpaid, open source projects like OM, you can get a free license.

Always had a paid one for paid projects and a free one for OM/open-soure ...

**Review by luigifab — APPROVED** [review]

**Pull request merged**
