### PR TITLE
adding total variable to available variables for order email templates

### PR DESCRIPTION
**Pull request by f1-outsourcing**
### Description (*)

I am not entirely sure why I had to add this in the past. I think that currency formatting is not available in the order email templates, that is why I put this in the variable.
I am using the total to highlight what needs to be paid more at the top of the email without any other amounts close to it. So eg. blind people do not accidentally pay without VAT.

### Fixed Issues (if relevant)

1. Fixes OpenMage/magento-lts#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)
 - [ ] Add yourself to contributors list

### CODE REVIEW

**Review by luigifab — APPROVED** [review]

**Review by kiatng — APPROVED** [review]

**Comment by fballiano** [comment]
mmm I thought I commented this already (but actually I didn't because the comment is not here) but isn't it as easy to just use {{order.getGrandTotal()}} in the template?

**Comment by kiatng** [comment]
> mmm I thought I commented this already (but actually I didn't because the comment is not here) but isn't it as easy to just use {{order.getGrandTotal()}} in the template?

Yes, it can. But that doesn't have currency formatting.

**Comment by fballiano** [comment]
right, but I still don't know about adding just one formatted grand total, what about the other properties of the order?

for example, in another template I've found this:

`{{var order.billing_address.format('html')}}`

which would be more correct as an approach, or maybe something like `{{ var order.formatPriceTxt('grand_total') }}`

**Comment by ADDISON74** [comment]
This PR has 2 green approves. Convert it to draft if you have any doubts.

**Comment by kiatng** [comment]
> which would be more correct as an approach, or maybe something like `{{ var order.formatPriceTxt('grand_total') }}`

From this:
https://github.com/OpenMage/magento-lts/blob/bd0cb12cb1c084e714e8e282f8d4f6a5431bb089/app/code/core/Mage/Sales/Model/Order.php#L2014-L2023

To this?
```php
    /**
     * Retrieve text formated price value includeing order rate
     *
     * @param   float|string $price
     * @return  string
     */
    public function formatPriceTxt($price)
    {
        $price = (float) (is_numeric($price) ? $price : $this->_getData($price));
        return $this->getOrderCurrency()->formatTxt($price);
    }
```

**Comment by fballiano** [comment]
@kiatng :-) that's great! yes I meant something like that, this way it's more general and it can be used for other prices too, what do you think?

**Pull request closed without merging**
