### PR TITLE
Merge v19 into v20

### PR DESCRIPTION
**Pull request by fballiano**
This time I cherry picked the single commits using https://github.com/OpenMage/magento-lts/compare/v19.4.17...1.9.4.x as a reference.

Notes:
- I had to fix a conflict with https://github.com/OpenMage/magento-lts/pull/2342
- I didn't merge https://github.com/OpenMage/magento-lts/commit/35acb46f0385484ec45397cc53b379ecf1434ea6 since it's already in 20.0

If you know a better way of knowing which commits still need cherry-picking please let me know

### CODE REVIEW

**Comment by fballiano** [comment]
I updated this and I had to solve a lot of conflicts since the mass updates collided with the deleted folders in v20.

**Comment by fballiano** [comment]
more updates and had to fix 2 conflicts

**Comment by fballiano** [comment]
@sreichel can you help me check what's phpstan complaining about?

**Review by sreichel — APPROVED** [review]

**Review by kiatng — APPROVED** [review]

**Comment by fballiano** [comment]
guys I'm wondering, what's the best way to merge this: rebase or merge? squash for sure not, that's easy :-D

**Comment by sreichel** [comment]
Ahhh ... fu** smartph...

**Comment by ADDISON74** [comment]
@sreichel - did you forget to merge with squash?

**Pull request merged**
