### PR TITLE
Backend: Improved "copy button" style in legacy admin theme

### PR DESCRIPTION
**Pull request by ma4nn**
### Description (*)

With the latest addition of the [copy button feature](https://github.com/OpenMage/magento-lts/pull/4029), the order header in the legacy admin theme looks a bit broken:
Bildschirmfoto 2024-07-03 um 08 59 10

This PR improves the styling of the button in that section:
Bildschirmfoto 2024-07-03 um 08 58 31

### Manual testing scenarios (*)

1. Copy button looks nice in legacy and openmage admin theme
2. Copy button functionality is still present

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Comment by ADDISON74** [comment]
I just wanted to make an observation on this topic because I saw the change with the new v20 version. 

First of all, maybe **the color** should be white for the order and orange for the email. 

Then **the vertical alignment** must be related to the text. 

A **margin/padding on the left** of the icon is requeste, especially for the email address.

**Comment by ADDISON74** [comment]
In CSS you should your ```position: absolute``` then you can arrange the icon into the right position.

**Comment by ma4nn** [comment]
@ADDISON74 I would not recommend using `position: absolute`, especially without any relative container outside.
Your proposed color changes are already part of this PR 🙂

**Comment by fballiano** [comment]
I've tested your PR and it's needed so I'll merge it right away.

Personally I'd still keep the code in a "admin" related file but further improvements can be done for sure in a separate PR.

**Review by fballiano — APPROVED** [review]

**Pull request merged**
