### PR TITLE
Rename mysql4 sql files

### PR DESCRIPTION
**Pull request by luigifab**
### Description

This (useless) PR rename ~95% of sql/mysql4-* files (620 files renamed without changes).
Script used to rename files:
```php
$files = [];
exec('find app/ -name "mysql4-*.php"', $files);

foreach ($files as $file) {
	echo $file,"\n";
	$newfile = str_replace('mysql4-', '', $file);
	if ((stripos($newfile, 'data-upgrade') === false) && !is_file($newfile)) {
		if (stripos(file_get_contents($file), '$installFile') === false)
			rename($file, $newfile);
	}
}
```

Files not renamed:
```
fabrice@mario:/var/www/magento-lts$ php a.php 
app/code/core/Mage/Bundle/sql/bundle_setup/mysql4-upgrade-1.6.0.0-1.6.0.0.1.php
app/code/core/Mage/Bundle/sql/bundle_setup/mysql4-data-upgrade-0.1.13-0.1.14.php
app/code/core/Mage/Catalog/sql/catalog_setup/mysql4-upgrade-1.6.0.0.8-1.6.0.0.9.php
app/code/core/Mage/Catalog/sql/catalog_setup/mysql4-data-upgrade-0.7.57-0.7.58.php
app/code/core/Mage/Catalog/sql/catalog_setup/mysql4-data-upgrade-0.7.63-0.7.64.php
app/code/core/Mage/Catalog/sql/catalog_setup/mysql4-data-upgrade-1.4.0.0.28-1.4.0.0.29.php
app/code/core/Mage/Catalog/sql/catalog_setup/mysql4-data-upgrade-1.4.0.0.42-1.4.0.0.43.php
app/code/core/Mage/Core/sql/core_setup/mysql4-data-upgrade-1.6.0.2-1.6.0.3.php
app/code/core/Mage/Customer/sql/customer_setup/mysql4-data-upgrade-1.4.0.0.11-1.4.0.0.12.php
app/code/core/Mage/Customer/sql/customer_setup/mysql4-data-upgrade-1.4.0.0.13-1.4.0.0.14.php
app/code/core/Mage/Customer/sql/customer_setup/mysql4-data-upgrade-1.4.0.0.7-1.4.0.0.8.php
app/code/core/Mage/Customer/sql/customer_setup/mysql4-data-upgrade-1.4.0.0.8-1.4.0.0.9.php
app/code/core/Mage/Directory/sql/directory_setup/mysql4-upgrade-1.6.0.1-1.6.0.2.php
app/code/core/Mage/Paygate/sql/paygate_setup/mysql4-data-upgrade-0.7.0-0.7.1.php
app/code/core/Mage/Reports/sql/reports_setup/mysql4-install-1.5.0.0.php
app/code/core/Mage/Reports/sql/reports_setup/mysql4-install-1.6.0.0.php
app/code/core/Mage/Downloadable/sql/downloadable_setup/mysql4-upgrade-1.6.0.0.1-1.6.0.0.2.php
```
If I rename `mysql4-data-upgrade`, two files are not executed. I not checked why.

### Manual testing scenarios

- Create two empty databases: `before` and `after`.
- Update your local.xml to use `before` database.
- Clear `var/` directory and go to home page with your browser.
- Wait during database regeneration...
- Apply PR (or run php snippet)
- Update your local.xml to use `after` database.
- Clear `var/` directory and go to home page with your browser.
- Wait during database regeneration...
- Run: `mysqldump --skip-comments --skip-extended-insert -u root -p before > file1.sql`
- Run: `mysqldump --skip-comments --skip-extended-insert -u root -p after > file2.sql`
- Run: `diff -I "20[0-9][0-9]-" file1.sql file2.sql`
- Result: no differences

### Contribution checklist
- [x] Pull request has a meaningful description of its purpose
- [x] All commits are accompanied by meaningful commit messages
- [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by kkrieger85** [comment]
At first a big thank you for this super nice description of the PR and how to easily check this huge PR. 

Thank you for these "step by step". It makes reviewing this PR much easier.

**Comment by luigifab** [comment]
I downloaded [Magento 1.4.1.0](https://codeload.github.com/OpenMage/magento-mirror/tar.gz/refs/tags/1.4.1.1). I created an empty database, updated the local.xml, cleared var/ directory and go to home page with my browser to regenerate database.

_(I also removed ROW_FORMAT=FIXED in sql files, I also installed php5-6 from [sury](https://deb.sury.org/))_

Then I...
* Create two databases: `before` and `after`.
* Import the Magento 1.4 database into `before` and `after`.
* Update your local.xml to use `before` database.
* Clear `var/` directory and go to home page with your browser.
* Wait during database regeneration...
* Apply PR
* Update your local.xml to use `after` database.
* Clear `var/` directory and go to home page with your browser.
* Wait during database regeneration...
* Run: `mysqldump --skip-comments --skip-extended-insert -u root -p before > file1.sql`
* Run: `mysqldump --skip-comments --skip-extended-insert -u root -p after > file2.sql`
* Run: `diff -I "20[0-9][0-9]-" file1.sql file2.sql`
* Result: no differences

**Comment by luigifab** [comment]
Without -I:
```
fabrice@mario:/var/www$ diff before.sql  after.sql 
159,160c159,160
< INSERT INTO `api2_acl_role` VALUES (1,'2021-07-23 13:36:44',NULL,'Guest');
< INSERT INTO `api2_acl_role` VALUES (2,'2021-07-23 13:36:44',NULL,'Customer');
---
> INSERT INTO `api2_acl_role` VALUES (1,'2021-07-23 13:39:07',NULL,'Guest');
> INSERT INTO `api2_acl_role` VALUES (2,'2021-07-23 13:39:07',NULL,'Customer');
2749,2750c2749,2750
< INSERT INTO `cms_block` VALUES (5,'Footer Links','footer_links','<ul>\r\n<li><a href=\"{{store direct_url=\"about-magento-demo-store\"}}\">About Us</a></li>\r\n<li><a href=\"{{store direct_url=\"customer-service\"}}\">Customer Service</a></li>\r\n<li class=\"last privacy\"><a href=\"{{store direct_url=\"privacy-policy-cookie-restriction-mode\"}}\">Privacy Policy</a></li>\r\n</ul>','2021-07-23 13:28:18','2021-07-23 11:36:47',1);
< INSERT INTO `cms_block` VALUES (6,'Cookie restriction notice','cookie_restriction_notice_block','<p>This website requires cookies to provide all of its features. For more information on what data is contained in the cookies, please see our <a href=\"{{store direct_url=\"privacy-policy-cookie-restriction-mode\"}}\">Privacy Policy page</a>. To accept cookies from this site, please click the Allow button below.</p>','2021-07-23 11:36:47','2021-07-23 11:36:47',1);
---
> INSERT INTO `cms_block` VALUES (5,'Footer Links','footer_links','<ul>\r\n<li><a href=\"{{store direct_url=\"about-magento-demo-store\"}}\">About Us</a></li>\r\n<li><a href=\"{{store direct_url=\"customer-service\"}}\">Customer Service</a></li>\r\n<li class=\"last privacy\"><a href=\"{{store direct_url=\"privacy-policy-cookie-restriction-mode\"}}\">Privacy Policy</a></li>\r\n</ul>','2021-07-23 13:28:18','2021-07-23 11:39:09',1);
> INSERT INTO `cms_block` VALUES (6,'Cookie restriction notice','cookie_restriction_notice_block','<p>This website requires cookies to provide all of its features. For more information on what data is contained in the cookies, please see our <a href=\"{{store direct_url=\"privacy-policy-cookie-restriction-mode\"}}\">Privacy Policy page</a>. To accept cookies from this site, please click the Allow button below.</p>','2021-07-23 11:39:09','2021-07-23 11:39:09',1);
2806c2806
< INSERT INTO `cms_page` VALUES (6,'Privacy Policy','one_column',NULL,NULL,'privacy-policy-cookie-restriction-mode','Privacy Policy','<p style=\"color: #ff0000; ....le>','2021-07-23 11:36:47','2021-07-23 11:36:47',1,0,NULL,NULL,NULL,NULL,NULL,NULL);
---
> INSERT INTO `cms_page` VALUES (6,'Privacy Policy','one_column',NULL,NULL,'privacy-policy-cookie-restriction-mode','Privacy Policy','<p style=\"color: #ff0000; ....le>','2021-07-23 11:39:09','2021-07-23 11:39:09',1,0,NULL,NULL,NULL,NULL,NULL,NULL);
2896,2900c2896,2900
< INSERT INTO `core_config_data` VALUES (1,'default',0,'catalog/category/root_id','2','2021-07-23 13:34:50');
< INSERT INTO `core_config_data` VALUES (2,'default',0,'advanced/modules_disable_output/Mage_Backup','1','2021-07-23 13:34:50');
< INSERT INTO `core_config_data` VALUES (3,'default',0,'general/region/display_all','1','2021-07-23 13:36:45');
< INSERT INTO `core_config_data` VALUES (4,'default',0,'general/region/state_required','AT,CA,CH,DE,EE,ES,FI,FR,LT,LV,RO,US','2021-07-23 13:36:45');
< INSERT INTO `core_config_data` VALUES (5,'default',0,'payment/paypal_express/skip_order_review_step','0','2021-07-23 13:36:47');
---
> INSERT INTO `core_config_data` VALUES (1,'default',0,'catalog/category/root_id','2','2021-07-23 13:37:18');
> INSERT INTO `core_config_data` VALUES (2,'default',0,'advanced/modules_disable_output/Mage_Backup','1','2021-07-23 13:37:18');
> INSERT INTO `core_config_data` VALUES (3,'default',0,'general/region/display_all','1','2021-07-23 13:39:08');
> INSERT INTO `core_config_data` VALUES (4,'default',0,'general/region/state_required','AT,CA,CH,DE,EE,ES,FI,FR,LT,LV,RO,US','2021-07-23 13:39:08');
> INSERT INTO `core_config_data` VALUES (5,'default',0,'payment/paypal_express/skip_order_review_step','0','2021-07-23 13:39:09');
6606c6606
< INSERT INTO `log_visitor` VALUES (2,'bqll2cb1vj42sjjihpg8sfkdsm','2021-07-23 11:36:47','2021-07-23 11:36:47',0,1);
---
> INSERT INTO `log_visitor` VALUES (2,'bqll2cb1vj42sjjihpg8sfkdsm','2021-07-23 11:39:09','2021-07-23 11:39:09',0,1);
6783c6783
< INSERT INTO `newsletter_template` VALUES (1,'Example Newsletter Template','{{temp....email/footer\"}}',NULL,NULL,2,'Example Subject','Owner','owner@example.com',1,'2021-07-23 11:36:47','2021-07-23 11:36:47');
---
> INSERT INTO `newsletter_template` VALUES (1,'Example Newsletter Template','{{temp....email/footer\"}}',NULL,NULL,2,'Example Subject','Owner','owner@example.com',1,'2021-07-23 11:39:09','2021-07-23 11:39:09');
```

**Comment by fballiano** [comment]
> Without -I:
> 
> ```
> fabrice@mario:/var/www$ diff before.sql  after.sql 
> 159,160c159,160
> < INSERT INTO `api2_acl_role` VALUES (1,'2021-07-23 13:36:44',NULL,'Guest');
> < INSERT INTO `api2_acl_role` VALUES (2,'2021-07-23 13:36:44',NULL,'Customer');
> ---
> > INSERT INTO `api2_acl_role` VALUES (1,'2021-07-23 13:39:07',NULL,'Guest');
> > INSERT INTO `api2_acl_role` VALUES (2,'2021-07-23 13:39:07',NULL,'Customer');
> 2749,2750c2749,2750
> < INSERT INTO `cms_block` VALUES (5,'Footer Links','footer_links','<ul>\r\n<li><a href=\"{{store direct_url=\"about-magento-demo-store\"}}\">About Us</a></li>\r\n<li><a href=\"{{store direct_url=\"customer-service\"}}\">Customer Service</a></li>\r\n<li class=\"last privacy\"><a href=\"{{store direct_url=\"privacy-policy-cookie-restriction-mode\"}}\">Privacy Policy</a></li>\r\n</ul>','2021-07-23 13:28:18','2021-07-23 11:36:47',1);
> < INSERT INTO `cms_block` VALUES (6,'Cookie restriction notice','cookie_restriction_notice_block','<p>This website requires cookies to provide all of its features. For more information on what data is contained in the cookies, please see our <a href=\"{{store direct_url=\"privacy-policy-cookie-restriction-mode\"}}\">Privacy Policy page</a>. To accept cookies from this site, please click the Allow button below.</p>','2021-07-23 11:36:47','2021-07-23 11:36:47',1);
> ---
> > INSERT INTO `cms_block` VALUES (5,'Footer Links','footer_links','<ul>\r\n<li><a href=\"{{store direct_url=\"about-magento-demo-store\"}}\">About Us</a></li>\r\n<li><a href=\"{{store direct_url=\"customer-service\"}}\">Customer Service</a></li>\r\n<li class=\"last privacy\"><a href=\"{{store direct_url=\"privacy-policy-cookie-restriction-mode\"}}\">Privacy Policy</a></li>\r\n</ul>','2021-07-23 13:28:18','2021-07-23 11:39:09',1);
> > INSERT INTO `cms_block` VALUES (6,'Cookie restriction notice','cookie_restriction_notice_block','<p>This website requires cookies to provide all of its features. For more information on what data is contained in the cookies, please see our <a href=\"{{store direct_url=\"privacy-policy-cookie-restriction-mode\"}}\">Privacy Policy page</a>. To accept cookies from this site, please click the Allow button below.</p>','2021-07-23 11:39:09','2021-07-23 11:39:09',1);
> 2806c2806
> < INSERT INTO `cms_page` VALUES (6,'Privacy Policy','one_column',NULL,NULL,'privacy-policy-cookie-restriction-mode','Privacy Policy','<p style=\"color: #ff0000; ....le>','2021-07-23 11:36:47','2021-07-23 11:36:47',1,0,NULL,NULL,NULL,NULL,NULL,NULL);
> ---
> > INSERT INTO `cms_page` VALUES (6,'Privacy Policy','one_column',NULL,NULL,'privacy-policy-cookie-restriction-mode','Privacy Policy','<p style=\"color: #ff0000; ....le>','2021-07-23 11:39:09','2021-07-23 11:39:09',1,0,NULL,NULL,NULL,NULL,NULL,NULL);
> 2896,2900c2896,2900
> < INSERT INTO `core_config_data` VALUES (1,'default',0,'catalog/category/root_id','2','2021-07-23 13:34:50');
> < INSERT INTO `core_config_data` VALUES (2,'default',0,'advanced/modules_disable_output/Mage_Backup','1','2021-07-23 13:34:50');
> < INSERT INTO `core_config_data` VALUES (3,'default',0,'general/region/display_all','1','2021-07-23 13:36:45');
> < INSERT INTO `core_config_data` VALUES (4,'default',0,'general/region/state_required','AT,CA,CH,DE,EE,ES,FI,FR,LT,LV,RO,US','2021-07-23 13:36:45');
> < INSERT INTO `core_config_data` VALUES (5,'default',0,'payment/paypal_express/skip_order_review_step','0','2021-07-23 13:36:47');
> ---
> > INSERT INTO `core_config_data` VALUES (1,'default',0,'catalog/category/root_id','2','2021-07-23 13:37:18');
> > INSERT INTO `core_config_data` VALUES (2,'default',0,'advanced/modules_disable_output/Mage_Backup','1','2021-07-23 13:37:18');
> > INSERT INTO `core_config_data` VALUES (3,'default',0,'general/region/display_all','1','2021-07-23 13:39:08');
> > INSERT INTO `core_config_data` VALUES (4,'default',0,'general/region/state_required','AT,CA,CH,DE,EE,ES,FI,FR,LT,LV,RO,US','2021-07-23 13:39:08');
> > INSERT INTO `core_config_data` VALUES (5,'default',0,'payment/paypal_express/skip_order_review_step','0','2021-07-23 13:39:09');
> 6606c6606
> < INSERT INTO `log_visitor` VALUES (2,'bqll2cb1vj42sjjihpg8sfkdsm','2021-07-23 11:36:47','2021-07-23 11:36:47',0,1);
> ---
> > INSERT INTO `log_visitor` VALUES (2,'bqll2cb1vj42sjjihpg8sfkdsm','2021-07-23 11:39:09','2021-07-23 11:39:09',0,1);
> 6783c6783
> < INSERT INTO `newsletter_template` VALUES (1,'Example Newsletter Template','{{temp....email/footer\"}}',NULL,NULL,2,'Example Subject','Owner','owner@example.com',1,'2021-07-23 11:36:47','2021-07-23 11:36:47');
> ---
> > INSERT INTO `newsletter_template` VALUES (1,'Example Newsletter Template','{{temp....email/footer\"}}',NULL,NULL,2,'Example Subject','Owner','owner@example.com',1,'2021-07-23 11:39:09','2021-07-23 11:39:09');
> ```

so, excluding some datetime differences the database seems exactly the same no?

what benefit do we have from this massive rename?

**Comment by luigifab** [comment]
Yes, for me, no differences in database.
Benefit? 620x7 characters saved!

**Review by fballiano — APPROVED** [review]

**Review by tmewes — DISMISSED** [review]

**Review by kiatng — APPROVED** [review]

**Comment by fballiano** [comment]
conflict impeding merge

**Comment by sreichel** [comment]
> This (useless) PR rename ~95%

**Pull request closed without merging**
