### PR TITLE
New event "order_status_changed_before_save"

### PR DESCRIPTION
**Pull request by woutersamaey**
### Description (*)
New event "sales_order_state_change" allows custom modules to detect an order state/status change and trigger appropriate actions. I've seen modules rewrite the order model because this was missing.

Very handy improvement.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by kiatng** [comment]
I actually need this event in some of my projects. However, I fire it from `_beforeSave`:

```php
    protected function _beforeSave()
    {
        // ...
        // Just before existing the function.
        if ($this->getStatus() != $this->getOrigData('status')) {
            Mage::dispatchEvent('order_status_changed_before_save', ['order' => $this]);
        }
        return $this;
    }
```

It doesn't check for state changes as condition of firing, which is less granular; a state may not have changed while status changes. However, you can easily check state changes in the observer. 

I like firing in `_beforeSave` because I know at this point the states of the `order` model have settled, ie, the states of its attributes, the order items, order history, etc., have settled and are ready to be saved.

**Comment by woutersamaey** [comment]
Updated this PR to reflect @kiatng example. This is indeed better.

**Review by luigifab — COMMENTED** [review]
Could you add the new event into [EVENTS.md](https://github.com/OpenMage/magento-lts/blob/1.9.4.x/EVENTS.md).
Personally I would have used `!=`, but never mind.

**Review by theroch — APPROVED** [review]

**Review by fballiano — APPROVED** [review]

**Comment by fballiano** [comment]
I think this one could be merged as it is (since it's not modifiable by other admins) and then I'll modify EVENTS.md in another PR.

**Comment by fballiano** [comment]
oops, it's not mergeable because of conflicts and only @woutersamaey can fix them

**Comment by fballiano** [comment]
completed via https://github.com/OpenMage/magento-lts/pull/2927

**Pull request closed without merging**
