### PR TITLE
Patch SUPEE-10570 / Upgrade 1.9.3.8

### PR DESCRIPTION
**Pull request by spinsch**
**Release Notes**
http://devdocs.magento.com/guides/m1x/ce19-ee114/ce1.9_release-notes.html#ce19-1938

**Security Patch-Notes**
https://magento.com/security/patches/supee-10570

### CODE REVIEW

**Comment by akira28** [comment]
Their obsession for copyright years causes this kind of issues. Impossible to see the changelog easily :(
The solution would be to get rid of it on every file, and just put a LICENSE file in the root directory

**Comment by andreasemer** [comment]
@akira28 This makes sense

**Comment by colinmollenhour** [comment]
Or just two separate commits and pull requests. I don't think we'll ever remove the license notice from every file.

**Comment by colinmollenhour** [comment]
I cut up your commit and created a new PR #460. Cherry-pick was used to preserve your authorship of the final commit.

**Pull request closed without merging**
