### PR TITLE
Commits on 1.9.3.x that are not on 1.9.4.x

### PR DESCRIPTION
**Pull request by fballiano**
Since github doesn't allow to dismiss the "compare & pull request" button I've to create this PR. I will close it right away since no commit in the 1.9.3.x branch should be ported to 1.9.4.x at this point in time.

We should probably freeze old branches if possible

### CODE REVIEW

**Comment by ADDISON74** [comment]
Nice find but you closed the PR. Are those commits merged in latest OM? Did we miss others?

**Comment by ADDISON74** [comment]
Can we revert and leave them open for discussions? Or shall we recreate them?

**Comment by fballiano** [comment]
anyone can cherry-pick one any comment into another branch

**Comment by ADDISON74** [comment]
I will let someone more advanced in Git to do this task. If you can do it would be great because you know what it's about. The most important thing is not to lose them and to capitalize the efforts made in the past if they are still relevant.

**Pull request closed without merging**
