### PR TITLE
Import Magento Release 1.9.3.6

### PR DESCRIPTION
**Pull request by drobinson**

### CODE REVIEW

**Comment by colinmollenhour** [comment]
Hey they finally added a check for `..` in the template paths!  However, I noticed it is actually `../`. I wonder if this leaves Magento on Windows vulnerable, or is Magento on Windows even supported (I've never tried it)?  Also it seems kinda redundant to check the paths both in layout updates and right before actually loading the template (the horrid Allow Symlinks functionality), no? Odd..

**Comment by drobinson** [comment]
Running `grep -r '\.\./' . | less` on the codebase shows a few other places where this is used, but only some of them also mention the "..\" notation.  ¯\_(ツ)_/¯

**Comment by fheyer** [comment]
Your first commit contains a .rej file with changes that were rejected for app/code/core/Mage/Shipping/Model/Carrier/Tablerate.php

**Comment by drobinson** [comment]
Sorry about that, removed in #344

**Pull request merged**
