### PR TITLE
Fixed bug with backend dashboard about graph chart months calculations

### PR DESCRIPTION
**Pull request by fballiano**
Seems like Zend_Date has some bug calculating time differences when using timezones, for this reason the backend dashboard graph, when selecting `1Y` or `2Y` miscalculates the months to show and for this reason the graph is missing data.

More detailed explanation in bug report https://github.com/OpenMage/magento-lts/issues/3593

This PR rewrites the whole thing using `DateTime`, which seems more correct to me.

Fixes https://github.com/OpenMage/magento-lts/issues/3593

### CODE REVIEW

**Comment by fballiano** [comment]
I preferred not to change the variables names, did you have the chance to test this PR?

**Comment by elidrissidev** [comment]
@fballiano Can you try setting your timezone in configuration to Etc/GMT-12, cause for me it's still skipping some months.

download

**Comment by fballiano** [comment]
@kiatng mmm interesting, since your TZ is `-12`, the first generated day becomes `2022-12-31 12:00:00` instead of `2023-01-01` so everything gets messed up.

I think that for `1Y` and `2Y` we shouldn't use the timezone at all, what do you think?

**Comment by fballiano** [comment]
but I think timezone is needed for the hourly/24h reports, no?

**Review by empiricompany — APPROVED** [review]

**Review by boesbo — APPROVED** [review]

**Review by boesbo — APPROVED** [review]

**Comment by Hanmac** [comment]
@fballiano are you going to revive this issue?

**Comment by fballiano** [comment]
@Hanmac I left openmage as of today, I will maybe write a statement in the next days.

**Comment by Hanmac** [comment]
@sreichel should we try to revive this MR?

**Pull request closed without merging**
