### PR TITLE
suggested improvement - everybody does it why not add it

### PR DESCRIPTION
**Pull request by seansan**
suggested improvement - everybody does it why not add it

### CODE REVIEW

**Comment by drobinson** [comment]
One reason would be that it won't work universally - many projects are behind some kind of load balancer or a firewall like Cloudflare - in both cases REMOTE_ADDR won't be the end-user.

Even if you changed it so that it first checked HTTP_X_FORWARDED_FOR it still probably isn't a great idea - the maintenance flag serves more of a purpose than just not showing the frontend when something  is happening.  You could for instance trigger install scripts before they should be triggered, causing all sorts of issues.

**Comment by seansan** [comment]
Agree - but then it would just not work and not break anything. Also
wouldnt they use EE?

**Comment by drobinson** [comment]
IMO "It won't break anything" is not a good enough reason to add code.

EE isn't universally adopted by merchants who this would not work for.

I'm curious - what purpose does this change serve for your projects?

**Comment by seansan** [comment]
none - just a simple - possible - addition. Not necessary at all

**Comment by LeeSaferite** [comment]
I have done similar in the past, but I agree with @drobinson here that it's not a change I can see the value in. The possibility that it introduces a bug in someone's setup is enough reason to at least look at it critically.

**Comment by Flyingmana** [comment]
Possible Bug Case:

1. you activate maintainance
2. your local monitoring/Nagios/Icinga/anything accesses pages
3. tears :crying_cat_face:

**Comment by LeeSaferite** [comment]
Based on the feedback I think it's appropriate to close this PR.  Thank you for the PR in any case.

**Pull request closed without merging**
