### PR TITLE
Remove legacy media uploader / editor remnants

### PR DESCRIPTION
**Pull request by justinbeaty**
### Description (*)

Removed a few javascript files related to `lib/flex` which was previously removed in #2271

However I also removed some blocks, controllers, and phtml files which seem like they are not used anywhere.

Maybe the only removal I'm not sure about is `app/code/core/Mage/Adminhtml/Block/Media/Uploader.php` because maybe some extension adds this block to a layout.

The two controllers seem useless. 

https://store.example.com/index.php/admin/media_uploader
https://store.example.com/index.php/admin/media_editor

### Manual testing scenarios (*)

1. Perhaps a good idea to pull both this and #2433 into your local tree
2. Try to upload media files in various places in the backend. I'm not sure of the complete list of places you can normally upload files, I know of uploading images or downloadable files in manage products... Where else can we upload?

### Questions or comments

~~This is a draft because I think it needs to be tested by others before merging.~~ **Edit:** Marked ready for review, although let's please still test it. It seems fine for me, but maybe someone else knows if those controllers I deleted were ever used. I honestly don't think they were anymore and are just cruft.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Comment by fballiano** [comment]
I was about to write you about FABridge :-D

**Review by fballiano — APPROVED** [review]
tested and found no problems, there's nothing about those 2 controllers anywhere in the code and the uploads still work

**Review by luigifab — DISMISSED** [review]
I like this idea!

**Comment by justinbeaty** [comment]
Fixed conflicts

**Review by fballiano — APPROVED** [review]

**Review by luigifab — APPROVED** [review]

**Pull request merged**
