### PR TITLE
Enable virtual products paypal express

### PR DESCRIPTION
**Pull request by wilfriedwolf**
### Description (*)
The pull requests alters review.js in order not to disable checkout of virtual products with paypal express

### Related Pull Requests
none

### Fixed Issues (if relevant)
1. Fixes OpenMage/magento-lts#1237

### Manual testing scenarios (*)
See Issue

### Questions or comments
As described here https://magento.stackexchange.com/questions/62398/place-order-button-disabled-with-virtual-products-paypal-express-and-terms-and/69815#69815 but in the core rather than in a theme.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by colinmollenhour — CHANGES_REQUESTED** [review]
I don't know the details of this fix and have never used PayPal Express, but it seems odd to be registering an event listener inside the observer of the same event listener.. Can you explain how/why this fixes the issue?

Also `input` is not defined in this context.. Did you perhaps mean for these lines to be added to the function above?

**Comment by wilfriedwolf** [comment]
Hi Colin,

You are perfectly right, my mistake. In my project used a theme overload of the function and wanted it to become core stuff...
I'll push the corrected branch right away...

Best regards and thanks for the review,

Willi

**Comment by colinmollenhour** [comment]
Ahh, the diff makes much more sense now. However, can you explain why the 'change' event should not be observed in these specific cases? Is there risk that this will affect other checkout methods?

**Comment by wilfriedwolf** [comment]
Ok, thanks for letting me look it over again, actually I just took the references / the fix from the internet without too much understandig what was going on. 

So now I understand whats going on:

Basically the implementation of the PayPal-Express-Review form is just crap!

Case A: There is a shipping address. Then in 

https://github.com/OpenMage/magento-lts/blob/18739f107de21144a578c8143557f8d2ac6969b3/skin/frontend/base/default/js/checkout/review.js#L63

the Treatment of the submit form is just skipped. That's why it works.

Case B: There is no shipping address. Then in Line 

https://github.com/OpenMage/magento-lts/blob/18739f107de21144a578c8143557f8d2ac6969b3/skin/frontend/base/default/js/checkout/review.js#L77

the event listener is bound to the agreements checkbox disabling the submit button when changing an agreement checkbox.

I guess, what the author of these lines ment to do is to disabling the submit button unless all agreements are checked.

So my PR just disables this implementation in a rather weird way :/ 

What actually shoud be done is to rewrite this crap in order to check if agreements are checked, preventing submission of the order otherwise just like in the normal checkout.

Don't know when or if I'll find time to write this PR.

For now, just forget about this...

**Pull request closed without merging**
