### PR TITLE
Fixed missing/wrong admin `_setActiveMenu()`

### PR DESCRIPTION
**Pull request by sreichel**
### Description (*)

Some sections are not correctly highlighted when active.

### CODE REVIEW

**Review by kiatng — APPROVED** [review]

**Comment by fballiano** [comment]
when you take PRs from other repos you should at least mention them: https://github.com/MahoCommerce/maho/pull/12

@sreichel fo you remember that you were accusing somebody of this same thing?

**Comment by sreichel** [comment]
Dear @fballiano,

this changes are based on this issue https://github.com/OpenMage/magento-lts/issues/4207 and aren't identical to yours.

Btw ... i can see a lot of "OM PR xyz" at https://github.com/MahoCommerce/maho/commits/main/.

Have you left any credits?

For sure i'll leave credits when I should pick up your or anybody else work.

**Comment by fballiano** [comment]
> Have you left any credits?

YES! you should be better!
there are always credits and you perfectly know since you are strictly monitoring our repo

my god you can contraddict yourself in one single sentence 😂

this project left to people like this it's a shame.

> For sure i'll leave credits when I should pick up your or anybody else work.

you would be funny, but you are not. I know what person you are.

**Review by ADDISON74 — APPROVED** [review]

**Comment by fballiano** [comment]
probably same when you use the same rector rules I committed on my repo, when a few months ago you were saying "let's leave the docblock"

unbelievable

**Comment by sreichel** [comment]
> > Have you left any credits?
> 
> YES!

Where? I cant see it. However ...

> probably same when you use the same rector rules I committed on my repo

I can't see any rector.php at your repo.

I have used Rector far befor your fork was created. (https://github.com/OpenMage/magento-lts/pulls?q=is%3Apr+rector+author%3Asreichel+)

I only continue what i have started - step by step.

---

Please stop that. Thanks.

**Comment by fballiano** [comment]
oh you don't see them?? again, you would be funny if the level wasn't so low.

and the fact that you used the word rector before doesn't mean anything, since you specifically were
- against copyright udates: you now do it yourself, weird
- against removing docblock, which I did on my repo and now apparently you changed opinion

**Comment by sreichel** [comment]
> oh you don't see them??

No. Can you please point me there?

> against removing docblock, which I did on my repo and now apparently you changed opinion

- https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#deadcode

or 

- https://github.com/sreichel/openmage-rector/blob/main/rector.php

Is it possible that you picked up my work? ;)

**Comment by fballiano** [comment]
I will refrain myself cause I don't want to break the COC that you broke an infinite number of times.

it is sad.

**Comment by sreichel** [comment]
> I will refrain myself 

Thanks.

**Comment by sreichel** [comment]
Removed offtopic. Backuped screenshot.

**Comment by kiatng** [comment]
As a reviewer of this PR, I acknowledge that this PR should credit @tmewes original https://github.com/MahoCommerce/maho/pull/12, which is precedent to this one.  @fballiano Thanks for pointing this out.

**Comment by sreichel** [comment]
Why? I wanted to fix the missing highlighting (#4207, #4208) and manually reviewed every link after i have seen that even with changed SCSS not all links were correct. Of course it looks similiar, b/c it cant be fixed in another way.

**Comment by kiatng** [comment]
I can explain my opinion: both issues (https://github.com/OpenMage/magento-lts/issues/4207, https://github.com/OpenMage/magento-lts/pull/4208) were dated Sep 18, which is later than https://github.com/MahoCommerce/maho/pull/12, dated Sep 1. Even though you may have the same idea earlier, I and others do not know about it until Sep 18. I didn't know @tmewes PR, but now that I know, I acknowledge and credit him for his **idea**. 

Further, you wrote
> ... manually reviewed every link ...

It seems @tmewes PR inspired this PR. If this is true, I am not an expert on ethic, but in my heart, I feel crediting the original work should be made in this case.

**Comment by sreichel** [comment]
I leave credits when a use others work ...

- https://github.com/OpenMage/magento-lts/pull/4203 (used Hanmacs suggestion)
- https://github.com/OpenMage/magento-lts/pull/4200 (used another tool)
- https://github.com/OpenMage/magento-lts/pull/4210 (refered to original PR)

If i had picked up @tmewes PR or got inspired by it, i'd at least leave a "thanks".

No Kia, I have no need to adorn myself with borrowed plumes.

**Comment by sreichel** [comment]
> I am sorry for incorrectly interpreting “manually reviewed every link”.

My bad, sorry for misleading wording ... "every admin menu link".

**Pull request merged**
