### PR TITLE
Added "googleanalytics_ga4_send_data_before" to customize GA4 data

### PR DESCRIPTION
**Pull request by fballiano**
This PR adds the `googleanalytics_ga4_send_data_before` event to the GoogleAnalytics4 implementation in order to allow users to customize the data that will be sent to analytics.

Closes https://github.com/OpenMage/magento-lts/discussions/3432

### CODE REVIEW

**Review by ADDISON74 — DISMISSED** [review]

**Review by empiricompany — APPROVED** [review]

**Comment by ioweb-gr** [comment]
I will give it a run and let you know.

**Comment by fballiano** [comment]
@ioweb-gr in case it works for you please leave a review so that we can merge it

**Comment by ioweb-gr** [comment]
Yeah sure, just waiting on confirmation from my customer to apply the upgrade and patch to test it but they're giving me some delays due to ongoing marketing campaigns for back to school :(

**Comment by fballiano** [comment]
This has to be retested because of the changes due to the conflicts I had to solve with the main branch.

**Review by S0FTWEX — APPROVED** [review]

**Review by ADDISON74 — APPROVED** [review]

**Review by empiricompany — APPROVED** [review]

**Comment by fballiano** [comment]
I've also retested and seems fine. merging per 1green+2gray

**Pull request merged**
