### PR TITLE
Fixed calls to static methods

### PR DESCRIPTION
**Pull request by sreichel**

### CODE REVIEW

**Comment by sreichel** [comment]
How to re-run checks?

**Comment by colinmollenhour** [comment]
It passed after merging. :)

**Comment by boesbo** [comment]
Questo ha generato un bug: https://github.com/OpenMage/magento-lts/issues/1135

**Comment by tmotyl** [comment]
FYI the error @boesbo mentions is related to usage of "self::" instead of "static::".
I think this patch should be revisited to see if in other places we should also use.

**Comment by sreichel** [comment]
@boesbo yes i did. This changes were made manually and i've checked for this, but missed that one. Sorry.

@tmotyl already reviewed this PR and found nothing else.

**Comment by boesbo** [comment]
> @boesbo yes i did. This changes were made manually and i've checked for this, but missed that one. Sorry.
> 
> 
> 
> @tmotyl already reviewed this PR and found nothing else.
> 
> 
> 
> 

!thank you so much!

**Pull request merged**
