### PR TITLE
Merge v19 -> v20

### PR DESCRIPTION
**Pull request by fballiano**
Cherry picking from https://github.com/OpenMage/magento-lts/compare/v19.4.19...1.9.4.x

### CODE REVIEW

**Comment by fballiano** [comment]
actually https://github.com/OpenMage/magento-lts/pull/2714 has to be merged first

**Review by elidrissidev — DISMISSED** [review]
Thanks 🙌

**Comment by fballiano** [comment]
> actually #2714 has to be merged first

done

**Review by elidrissidev — DISMISSED** [review]

**Review by kiatng — APPROVED** [review]

**Review by elidrissidev — DISMISSED** [review]

**Review by kiatng — APPROVED** [review]

**Comment by fballiano** [comment]
sorry guys, I had to merge last PRs from today :-(

and https://github.com/OpenMage/magento-lts/pull/2697 had some conficts I hope I merged correctly, these were the files:
```
CONFLICT (content): Merge conflict in app/code/core/Mage/Adminhtml/Block/Store/Switcher.php
CONFLICT (content): Merge conflict in app/code/core/Mage/Core/Model/Abstract.php
CONFLICT (content): Merge conflict in app/code/core/Mage/Page/Block/Html/Head.php
CONFLICT (content): Merge conflict in app/code/core/Mage/Sales/Model/Api2/Order/Comment/Rest.php
CONFLICT (content): Merge conflict in lib/Varien/Object.php
```
expecially lib/Varien/Object.php was tricky, there were a lot of conflicts

**Comment by sreichel** [comment]
Something went wrong. E.g. https://github.com/OpenMage/magento-lts/pull/2697/commits/d889083a9a9b1d149b3cad128b2e54e40852fdce has been removed.

**Comment by fballiano** [comment]
@sreichel that "phpVersion: 80000" line is included in the 1.9.4.x branch: https://github.com/OpenMage/magento-lts/blob/1.9.4.x/.github/phpstan.neon and in this PR: https://github.com/OpenMage/magento-lts/pull/2697/files, am I missing something?

**Comment by sreichel** [comment]
Sorry, i was on wrong branch.

**Comment by fballiano** [comment]
updated, didn't port https://github.com/OpenMage/magento-lts/pull/2745 since it's a backport from v20

**Comment by sreichel** [comment]
@fballiano i've added a PR to your repo.

**Comment by fballiano** [comment]
@sreichel merged!

**Comment by sreichel** [comment]
Waiting for #2759, #2750 and #2744?

**Comment by fballiano** [comment]
merged the new ones, https://github.com/OpenMage/magento-lts/pull/2697 had conflicts, hope the merge is ok :-)

**Review by sreichel — APPROVED** [review]

**Review by elidrissidev — APPROVED** [review]

**Comment by fballiano** [comment]
@sreichel @kiatng question, these kind of PR should be merged with "create a merge commit" right? for sure they shouldn't be squashed, but what about "rebase and merge"?

Also (calling @Flyingmana here too), I'd merge and do a release, since the 2 PRs that have been merged in 1.9.4.x are not really about the code but only about the workflows, is that ok?

**Comment by sreichel** [comment]
> @sreichel @kiatng question, these kind of PR should be merged with "create a merge commit" right? for sure they shouldn't be squashed, but what about "rebase and merge"?
> 
>  I'd merge and do a release, since the 2 PRs that have been merged in 1.9.4.x are not really about the code but only about the workflows, is that ok?

I'd merge them normaly to avoid differences between branches. (My next step would be to fix phpstan to work on both)

**Pull request merged**
