### PR TITLE
Array to string conversion when adding reviews from backend

### PR DESCRIPTION
**Pull request by fballiano**
This PR fixes issue https://github.com/OpenMage/magento-lts/issues/741 simply forcing a unique ID for the review_products_grid in order to avoid conflicts with the main products grid

### Fixed Issues (if relevant)
1. https://github.com/OpenMage/magento-lts/issues/741

### Manual testing scenarios (*)
All is explained in the issue

### CODE REVIEW

**Review by elidrissidev — APPROVED** [review]

**Review by ADDISON74 — APPROVED** [review]

**Review by luigifab — APPROVED** [review]

**Review by midlan — APPROVED** [review]

**Comment by luigifab** [comment]
Shame on us! This break the possibility to add new comment from backend (v19 and v20).
After choosing a product, the review form appear and at the end of the page, products list is still present.

v20.0.13
image

v20.0.14
image

**Comment by ADDISON74** [comment]
I confirm the issue reported by @luigifab. It is obvious that this implementation was not tested enough although the list of those who approved about a year ago is unusually long (which includes me as well). It can be reverted or fixed in another PR.

**Comment by ADDISON74** [comment]
I confirm the issue reported by @luigifab. It is obvious that this implementation was not tested enough although the list of those who approved about a year ago is unusually long (which includes me as well). It can be reverted or fixed in another PR.

The issue reported in #741 was that if you set a filter in the product grid, for example Price From 160 to 160 and you go to add a new review, after pressing the [Add New Review] button, the grid from which you select products was identical to the one previously filtered in Catalog > Products, and on the Price column, filtered, were the price values set at 160.

This PR was supposed to return the full grid, unfiltered, which it does, but after selecting the product, the changes on the page can no longer be saved because there is only the [Back] button.

I have analyzed whether a Review can be added to at least one of the filtered products in the Catalog > Products grid and I confirm that it is not possible. Practically all products are affected by the new issue.

**Comment by ADDISON74** [comment]
The modification not only removes the buttons but adds the product grid at the bottom

screenshot

**Comment by fballiano** [comment]
mmm the buttons are there but get hidden via some javascript...

**Comment by fballiano** [comment]
ok I think I got it

**Comment by ADDISON74** [comment]
Good observation. The two buttons have inline css "display:none". If I make them visible I can save the review. The product grid at the bottom of the screen would also have to be removed. I don't understand how it appeared there, it was probably hidden before this PR.

**Comment by fballiano** [comment]
done: https://github.com/OpenMage/magento-lts/pull/2415

**Pull request merged**
