### PR TITLE
Improving query performance for coupon code check

### PR DESCRIPTION
**Pull request by luigifab**
### Description

After #1110 (or before for me), I found a problem in cart.
Before this PR and before #1110, with ~220,000 coupons, in checkout/cart:

image

before-global-sql

With #1110:

image

After both PR:

image

See [comment](https://github.com/OpenMage/magento-lts/pull/1110#issuecomment-1385265157).

My solution is to create a sub query.
For us this is working, or we haven't yet found the new problem / side effect.

### SQL query before

```sql
SELECT `main_table`.*, `rule_coupons`.`code`
FROM `salesrule` AS `main_table`
INNER JOIN `salesrule_customer_group` AS `customer_group_ids`
  ON main_table.rule_id = customer_group_ids.rule_id
  AND customer_group_ids.customer_group_id = 0
LEFT JOIN `salesrule_coupon` AS `rule_coupons`
  ON main_table.rule_id = rule_coupons.rule_id
  AND main_table.coupon_type != 1
  AND rule_coupons.code = 'abc' # PR 1110
WHERE (EXISTS
         (SELECT 1
          FROM `salesrule_website` AS `website`
          WHERE (website.website_id IN ('1'))
            AND (main_table.rule_id = website.rule_id)))
  AND (from_date IS NULL OR from_date <= '2023-01-19')
  AND (to_date IS NULL OR to_date >= '2023-01-19')
  AND (`is_active` = '1')
  AND (
    main_table.coupon_type = 1
    OR (
      (
        (main_table.coupon_type = 3 AND rule_coupons.type = 0)
        OR (main_table.coupon_type = 2 AND main_table.use_auto_generation = 1 AND rule_coupons.type = 1)
        OR (main_table.coupon_type = 2 AND main_table.use_auto_generation = 0 AND rule_coupons.type = 0)
      )
      AND rule_coupons.code = 'abc'
    )
  );
```

### SQL query after

```sql
SELECT `main_table`.*, `rule_coupons`.`code`
FROM `salesrule` AS `main_table`
INNER JOIN `salesrule_customer_group` AS `customer_group_ids`
  ON main_table.rule_id = customer_group_ids.rule_id
  AND customer_group_ids.customer_group_id = 0
LEFT JOIN `salesrule_coupon` AS `rule_coupons`
  ON main_table.rule_id = rule_coupons.rule_id
  AND main_table.coupon_type != 1
  AND rule_coupons.code = 'abc' # PR 1110
WHERE (EXISTS
         (SELECT 1
          FROM `salesrule_website` AS `website`
          WHERE (website.website_id IN ('1'))
            AND (main_table.rule_id = website.rule_id)))
  AND (from_date IS NULL OR from_date <= '2023-01-19')
  AND (to_date IS NULL OR to_date >= '2023-01-19')
  AND (`is_active` = '1')
  AND (
    main_table.coupon_type = 1
    OR main_table.rule_id IN
       (SELECT DISTINCT `main_table`.`rule_id`
        FROM `salesrule` AS `main_table`
        INNER JOIN `salesrule_customer_group` AS `customer_group_ids`
          ON main_table.rule_id = customer_group_ids.rule_id
          AND customer_group_ids.customer_group_id = 0
        LEFT JOIN `salesrule_coupon` AS `rule_coupons`
          ON main_table.rule_id = rule_coupons.rule_id
          AND main_table.coupon_type != 1
          AND rule_coupons.code = 'abc' # PR 1110
        WHERE (EXISTS
                 (SELECT 1
                  FROM `salesrule_website` AS `website`
                  WHERE (website.website_id IN ('1'))
                    AND (main_table.rule_id = website.rule_id)))
          AND (from_date IS NULL OR from_date <= '2023-01-19')
          AND (to_date IS NULL OR to_date >= '2023-01-19')
          AND (`is_active` = '1')
          AND (
            (
              (main_table.coupon_type = 3 AND rule_coupons.type = 0)
              OR (main_table.coupon_type = 2 AND main_table.use_auto_generation = 1 AND rule_coupons.type = 1)
              OR (main_table.coupon_type = 2 AND main_table.use_auto_generation = 0 AND rule_coupons.type = 0)
            )
            AND rule_coupons.code = 'abc'
          )
        ORDER BY `sort_order` ASC)
   )
GROUP BY `main_table`.`rule_id`;
```

Like @kiatng says, we can replace:
```sql
OR (main_table.coupon_type = 2 AND main_table.use_auto_generation = 1 AND rule_coupons.type = 1)
OR (main_table.coupon_type = 2 AND main_table.use_auto_generation = 0 AND rule_coupons.type = 0)
```
with:
```sql
OR (main_table.coupon_type = 2 AND main_table.use_auto_generation <= 1 AND rule_coupons.type <= 1)
```

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Review by matteotestoni — APPROVED** [review]

**Comment by kyrena** [comment]
With https://github.com/OpenMage/magento-lts/discussions/2102, maybe this PR is good, but it can be better.
Not sure about real impact.

But with this PR `ANALYZE` say:
image

With the SQL of the discussion, `ANALYZE` say:
image

**Comment by fballiano** [comment]
I did some tests (creating 500.000 coupons), I don't know if I did something wrong but both this PR and https://github.com/OpenMage/magento-lts/discussions/2102 where slower than the code that's already in the core.

I measured the time of the select with
```php
                $time = microtime();
                $connection->fetchAll($select);
                echo microtime() - $time;
```

code from this PR (microtime difference):
Screenshot 2023-09-19 alle 00 09 21

code from without the PR:
Screenshot 2023-09-19 alle 00 10 35

* I lost the code from https://maxchadwick.xyz/blog/scaling-magento-sales-rule-to-20-million-coupons-and-beyond and I can't retest and but remember it was still slower than without any modification

The difference is negligible but...

Am I making any mistake?

**Comment by luigifab** [comment]
Strange, sadly our Sentry instance is dead for now, I can't test again.

**Comment by luigifab** [comment]
Close as can't test it again.

**Pull request closed without merging**
