### PR TITLE
docs: added ddev snippets

### PR DESCRIPTION
**Pull request by sreichel**
### Description (*)

I'v seen @ADDISON74 plays around with DDEV ... just want to share this.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Review by fballiano — DISMISSED** [review]

**Comment by ADDISON74** [comment]
You can mention a few lines about using Magento 1 Sample Data.

```
## Use Magento 1 Sample Data

Get in your working directory the Magento 1 Sample Data package from here https://pubfiles.nexcess.net/magento/sample-data/magento-sample-data-1.9.1.0.tar.gz then extract the files using the tar command.

Import to database the dump file "magento_sample_data_for_1.9.1.0.sql" with ddev import-db --src=magento_sample_data_for_1.9.1.0.sql before running OpenMage installation.

Please note that OpenMage is a huge codebase and using mutagen_enabled: true is recommended for performance on macOS and traditional Windows.
```

I did not mention the link to Vinai's repository like in the DDEV source because it is only 80 MB, while the original from Nexcess is 415 MB.

**Comment by sreichel** [comment]
I'd use @Vinai repo. It's complete and just uses better compressed images.

**Comment by ADDISON74** [comment]
You can change the link to Vinai's repository (as DDEV also recommends) based on you arguments.:
https://raw.githubusercontent.com/Vinai/compressed-magento-sample-data/1.9.1.0/compressed-magento-sample-data-1.9.1.0.tgz

Please check my inline comments. You can add this tip:

```
## Enable Developer Mode
Edit .ddev/config.yaml file and add the following lines:

web_environment: 
    MAGE_IS_DEVELOPER_MODE=1
```

**Comment by sreichel** [comment]
> You can change the link to Vinai's repository (as DDEV also recommends) based on your arguments.:
> https://raw.githubusercontent.com/Vinai/compressed-magento-sample-data/1.9.1.0/compressed-magento-sample-data-1.9.1.0.tgz

This link is outdated ... opened PR at ddev to use latest versions.

**Comment by sreichel** [comment]
__Thanks__ to @kkrieger85 for issues/PRs at DDEV :+1:

**Review by fballiano — APPROVED** [review]

**Comment by ADDISON74** [comment]
@sreichel - I created a few comments in the code days ago. Please let me know your opinion.

**Comment by sreichel** [comment]
@ADDISON74 Have i missed something? I've added dev-mode, but did not add sample-data, b/c its mentioned at ddev-docs.

**Comment by ADDISON74** [comment]
I will revise it these days and add what is missing, but not before letting you know.

**Review by Flyingmana — APPROVED** [review]

**Comment by ADDISON74** [comment]
Even if it was approved those phrases in English deserved more attention.

**Comment by ADDISON74** [comment]
I have not checked whether DDEV automatically creates an administrator account for the Backend, but I am tending to believe that it does not.

In the case of the dev script created by @colinmollenhour, he provided that the Backend needs a user. If a database is imported through the command ```ddev import-db --src=file_name.sql```, it most likely has an administrator account and it is no longer necessary to create it.

We have to check if the ```ddev config``` command also creates an account for Backend. If not, then this account must be created in the database with UPDATE command. Deleting the file ```/etc/local.xml``` would make creation possible, but reinstallation is necessary in this case and thus time will be lost.

I would also recommend this addon https://github.com/drud/ddev-browsersync. There is an open PR for dealing with HTTPS connections. A feature which was missing and which is extremely important if mkcert is used (DDEV detects automatically the SSL files).

**Comment by ADDISON74** [comment]
In the case of the dev script created by @colinmollenhour located in **/dev** directory, he provided that the Backend needs a user. If a database is imported through the command ```ddev import-db --src=file_name.sql```, it most likely has an administrator account and it is no longer necessary to create it.

**Please note DDEV is not creating a user for Backend.** 

The issue is that by running the ```ddev config``` command the **/etc/local.xml** file will be created, which means the OM instance doesn't need installation, but it will not have an account to access the Backend. In this case there are two options:

1. Run ```ddev describe``` to get information about accessing phpMyadmin. Once you access the interface select the **db** database and run the SQL query from bellow (it creates a username: admin with password: admin):

```sql
INSERT INTO `admin_user` (`user_id`, `firstname`, `lastname`, `email`, `username`, `password`, `created`, `modified`, `logdate`, `lognum`, `reload_acl_flag`, `is_active`, `extra`, `rp_token`, `rp_token_created_at`) VALUES
(1, 'Open', 'Mage', 'contact@ddev.site', 'admin', '17ef9b5a13acc91cc8f7bfe49a90e01f1e04ad6c885616a07d2ad7229617992c:MKZ25yJs32F11JWKvbVbDqebeB35NV4n', '2022-10-04 16:26:46', '2022-10-04 17:16:57', '2022-10-04 17:16:57', 0, 0, 1, 'N;', NULL, NULL);
```

2. Rename the **/etc/local.xml** file to initiate the installation from scratch. It can be done in browser (Host: db, Database Name: db, User Name: db, User Password: db) or in CLI.

I hope that those who want to try DDEV will not encounter any issue that will cause them to abandon evaluating this quick possibility to create a test environment based on Docker. After testing last night in a VM with Ubuntu 22.04 (Docker + DDEV + Phpstorm) I was left with a pleasant impression regarding the consumption of resources and especially the speed of the work environment.

**Comment by ADDISON74** [comment]
I reported the above issue here https://github.com/drud/ddev/issues/4259 but it seems that we will have to find a solution to it.

**Comment by ADDISON74** [comment]
I will complete this README with several solutions in different situations. For example, how to import a database and files, how to take a snapshot, how to use Composer and many others. 

Also, a link must be added in the README file of OpenMage located in the root to this file. DDEV must be promoted because it represents a much better and more flexible solution in Windows than XAMPP/WAMPP, being preferable to a VM provided that you are familiar with Docker at an average level.

**Pull request merged**
