### PR TITLE
Updated MAG-1.9.3.10.patch

### PR DESCRIPTION
**Pull request by fballiano**
Fixed a typo and made it a bit smaller, in order to facilitate its submission to the ZF1Future repository.

### CODE REVIEW

**Review by ADDISON74 — APPROVED** [review]

**Comment by sreichel** [comment]
Its already merged into ZF1F .... https://github.com/Shardj/zf1-future/pull/310

**Comment by fballiano** [comment]
it's also in 1.22.0 https://github.com/Shardj/zf1-future/commits/release-1.22.0 so we should remove the patch

**Comment by sreichel** [comment]
You already it did in #2960 ;)

**Comment by fballiano** [comment]
🤦🏻‍♂️ i didn't recognise that wasn't merged yet

**Pull request closed without merging**
