### PR TITLE
Allow soap v2 without rewrites

### PR DESCRIPTION
**Pull request by luigifab**
### Description

This PR add the possibility to access API SOAP v2 without server rewrites, because:

- this URL work: _http://.../openmage/public/api-secret.php/soap/?wsdl_
- this URL do not work: _http://.../openmage/public/api-secret.php/v2_soap/?wsdl_

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Review by fballiano — APPROVED** [review]
I see why this could be useful

**Comment by Flyingmana** [comment]
why is it working for `soap` but not `v2_soap`? might be better to handle it on a different place. Also I wonder if we should check if any APIs get exposed which were not previously.

**Comment by elidrissidev** [comment]
There is some confusion here. First of all, the second URL in the description (`/api-secret.php/v2_soap/?wsdl`) does not work because `api.php` accepts the type from the query parameter `?type=<adapter>`. The reason why you get an XML response from the first URL (`/api-secret.php/soap/?wsdl`) is because the `soap` adapter is the default if no type is provided.

Here is a list of the available `type`s (`v2_soap` is only an alias to `soap_v2`):

https://github.com/OpenMage/magento-lts/blob/ebabcf8499dccef5d2e9241a3df27e00535e6e8a/app/code/core/Mage/Api/etc/api.xml#L25-L70

I try connecting with the URL `http://om19.localhost/api.php/?type=soap_v2&wsdl=1` and it works fine, therefore I think this change might not be necessary.

**Comment by fballiano** [comment]
Wow great find @elidrissidev

**Comment by sreichel** [comment]
ping @luigifab

**Comment by luigifab** [comment]
So as you want. @elidrissidev is right.

**Pull request closed without merging**
