### PR TITLE
Restored parent::save() on a few classes (fixing PHPStan) ref #3988

### PR DESCRIPTION
**Pull request by fballiano**
check https://github.com/OpenMage/magento-lts/pull/3988#issuecomment-2137828337

### CODE REVIEW

**Comment by F1Red5** [comment]
@fballiano thank you.

I got feedback from our developer. Hetried a bit to get rid of this warning. He wrote the error is gone when he replaced @return Mage_Catalog_Model_Product_Type_Abstract with @return $this in that abstract class. Can you verify this?

**Comment by fballiano** [comment]
@F1Red5 I didn't understand

**Comment by F1Red5** [comment]
In Mage_Catalog_Model_Product_Type_Abstract

    /**
     * Save type related data
     *
     * @param Mage_Catalog_Model_Product $product
     * @return $this <- he changed that line
     */
    public function save($product = null)
    {
        /* custom code */
        return $this;
    }

**Comment by fballiano** [comment]
@F1Red5 they changed a comment and fixed a problem?

**Comment by F1Red5** [comment]
He sent me this link: https://phpstan.org/r/f830ef1d-d81a-46fb-8ae1-2a5902672020

I'll ask him for more information tomorrow.

**Comment by fballiano** [comment]
tell them to test this PR because I can't understand these messages

**Comment by F1Red5** [comment]
Okay. Thank you.

**Comment by F1Red5** [comment]
I cant explain, but I have tested the linked code and changed `@return A` to `@return $this` and the error is gone.

**Comment by fballiano** [comment]
it should be exactly what this PR does, please test this one so that, if it fixes the problem, we can merge it

**Review by kiatng — APPROVED** [review]

**Comment by fballiano** [comment]
do you people need a .1 release for this?

**Pull request merged**
