### PR TITLE
Removed @deprecation on Mage::getBlockSingleton()

### PR DESCRIPTION
**Pull request by kiatng**
It is referenced in [23 files](https://github.com/search?q=repo%3AOpenMage%2Fmagento-lts+Mage::getBlockSingleton&type=code). The comment stated that it should be replaced by `Mage::helper()`, but that is a totally different function.

### CODE REVIEW

**Comment by kiatng** [comment]
I have no idea how to fix the PHPStan errors. I never tried to run it locally. But when I tried, I encountered this:

> PS D:\Work\Magento\OpenMage\magento-lts> vendor/bin/phpstan analyse --memory-limit 1G --debug
Note: Using configuration file D:\Work\Magento\OpenMage\magento-lts\phpstan.dist.neon.
D:\Work\Magento\OpenMage\magento-lts\api.php
Uncaught Error: Class "Mage_Core_Model_Config_Base" not found in D:\Work\Magento\OpenMage\magento-lts\vendor\macopedia\phpstan-magento1\src\Config\MagentoCore.php:13
#0 phar://D:/Work/Magento/OpenMage/magento-lts/vendor/phpstan/phpstan/phpstan.phar/vendor/composer/ClassLoader.php(576): include()
...
#32 D:\Work\Magento\OpenMage\magento-lts\vendor\phpstan\phpstan\phpstan(8): require('...')
#33 {main}

Not sure how to fix the autoload in phpstan. Any idea?

**Comment by fballiano** [comment]
@kiatng I don't know windows much but I think using something like ddev makes this kind of things much easier

**Comment by ADDISON74** [comment]
> @kiatng I don't know windows much but I think using something like ddev makes this kind of things much easier

We have to make available to anyone interested a quick way to convince themselves of the advantages of OpenMage. I will update the DDEV documentation in OpenMage when I have some time and show everyone how to create a test environment in Windows. It is really fast and efficient. It is also valid in Linux distributions, skipping a few steps.

**Comment by kiatng** [comment]
I was trying to install DDEV the other day and spent a few hours on it but encountered an error and didn't pursue further. I will try again when I have the time.

**Comment by ADDISON74** [comment]
I recommend using a VM with Windows 10.

In Windows
- you need WSL2
- install Ubuntu 20 or 22 using Microsoft Store
- install Docker and configure it to use WSL2
- install mkcert

In Ubuntu
- install DDEV
- for a secure connection, you must take the Windows certificates created by mkcert and copy them to Ubuntu. I described the procedure in /docs/DDEV.md.

Open a terminal window for Ubuntu. Go to /home/ubuntu and create an openmage directory. Clone the repository in openmage/. Enter the openmage directory and run the following commands

ddev config
ddev composer install
ddev openmage -install -d -k
ddev start

In Windows configure PHPStorm to read your directory from WSL. I created a permanent Z path.

In general, it doesn't take me more than 3-5 minutes to get an OpenMage for testing (including the sample pack). In the .ddev/config.yaml file you can change the web server (apache or nginx), you can change the db server, you can change the PHP version. After saving, run ```ddev restart```. Since I discovered it I haven't used the previous test mode. DDEV is not only for OpenMage, it has a lot of projects like WordPress, Magento 2. There is a plugin for PHPStorm but I removed it.

**Review by fballiano — APPROVED** [review]

**Pull request merged**
