### PR TITLE
Fixed documentation link for "store scope" in store switcher (backend)

### PR DESCRIPTION
**Pull request by fballiano**
Everything is explained in ISSUE https://github.com/OpenMage/magento-lts/issues/2255, this PR only fixes the URL of the documentation that got broken during the years

### CODE REVIEW

**Comment by ADDISON74** [comment]
All [?] should be removed by now from OpenMage. I posted a comment here https://github.com/OpenMage/magento-lts/issues/2255#issuecomment-1166514972

**Comment by fballiano** [comment]
I don't see it on  20.0.14 but I see in on my dev environment from 1.9.4.x branch, could you confirm?

**Comment by fballiano** [comment]
As you can see in https://github.com/OpenMage/magento-lts/pull/1536 the functionality was only removed in v20 branch, not in v19 :-(

**Comment by ADDISON74** [comment]
I never used those links. Probably like me many others. When Adobe shut down the Magento help website a discussion ensued to establish either the removal of those links or a new website to link to. In my opinion, the effort to maintain this help is not justified, so the solution to remove those links from OM was the best solution. 

Indeed it was only wanted to be merged in OM-20 but I don't see the point in OM-19 either. If this PR goes into OM-19 it will have to be excluded from OM-20. A personal opinion would be to remove those [?] from the OM-19 too, as long as they no longer have valid links, To make an effort to update even the Internet Archive is not worth it. If someone still wants to get help they can download the Magento 1 User Manual, but after so many years I don't think there are any novices in using the interface.

**Comment by fballiano** [comment]
I guess it was decided to merge in v20 only cause it could be a small breaking change.

It's one like, so it won't be a hard conflict to solve (also I'll solve it in my v19->v20 merge PR anyway)

**Comment by ADDISON74** [comment]
I do not use OM-19, as long as this feature does not return in OM-20 does not affect me in any way. If several decide to keep Help links in OM-19, then this PR must be approved.

If we got that website from Magento.com that had all the help sections and hosted it somewhere, it wouldn't have been necessary to remove it from the OM-20. We were replacing the URL and the functionality still exists today.

**Comment by fballiano** [comment]
It won't come back to v20, the patch is a single line of xml, can't add anything also if it wanted to :-D At the same time we can't just leave v19 broken.

You know I'm all about disruptive change, if it was for me many more things would be removed...

**Comment by ADDISON74** [comment]
We should ask those who read our posts if there is still the possibility to get this website http://merch.docs.magento.com/ce/user_guide/. Last year we removed the feature without analyzing this aspect. If we get it we would talk to @Flyingmana to host it on openmage.org. Once this is done we can do a revert in OM-20 of that PR then change the URL in file /app/code/core/Mage/Adminhtml/etc/config.xml.

If we can't get it, the Internet Archive is not a solution because provides an incomplete version of the user guide. Rather than using it remove it from 19 seems to be a fair solution.

**Comment by fballiano** [comment]
I wouldn't re-enable this thing in v20, if a user needs a guide it reads the guide, we don't need to have links to the guide all over the backend.

**Comment by ADDISON74** [comment]
This is a screeshot from the latest OM-19 version:

help

In my opinion it is useless to add that link to the Internet Archive to solve the documentation for "Store Scope" since in OM-19 there is still a major issue related to the documentation of each section. In the absence of that website identical to the one offered in the past by Magento, keeping this online help is useless. It was removed from the OM-20 and I understand that it is not wanted to be brought back even if we find the original Magento website, so it must be removed from the OM-19 without any resentment.

**Review by luigifab — APPROVED** [review]

**Comment by ADDISON74** [comment]
Why are you approving this PR? On one hand it fixes the store scope with a link to IA and the loaded page doesn't look good. But on the other hand all help links are still there without proper links.

The help feature must be removed from OM-19 as we did for OM-20. We should close this PR.

**Comment by fballiano** [comment]
I think it should be fixed anyway or removed but it wasn't removed because it was BC (if you check the original thread). so at the moment let's merge it at least we don't have a broken link in all v19 installations :-)

**Comment by ADDISON74** [comment]
We worry too much about BC which obviously involves a lot of effort to actually maintain a custom version of the OM-20.

This PR solves the help issue for the store scope but the issue of the other help links remains and it cannot be solved because there is no Internet Archive pages for them and no clone of the Magento website. This is why I said that the change is useless. I am wondering how many will click on that icon at least out of curiosity. They will most likely cry because they do not see the icon they are used to.

**Comment by fballiano** [comment]
as you know i would remove a lot of things from v19 too, but not eveybody things the same, what can i tell you.

**Comment by ADDISON74** [comment]
Today someone asked me to get rid of the Magento help links because none of them work. I remembered our discussions from here, but considering that I was not allowed to upgrade to OpenMage and I did not have time to search through files, I edited the CSS file and made a display: none for all. Obviously the code for them remained but I solved his visual issue quickly. In addition he was glad that he got rid of them :)

**Pull request merged**
