### PR TITLE
Fix supplied resource is not a valid stream resource for Varien_Io_File

### PR DESCRIPTION
**Pull request by eneiasramos**
bugfix: HP Fatal error:  Uncaught TypeError: fclose(): supplied resource is not a valid stream resource in /opt/lampp/htdocs/lib/Varien/Io/File.php:255

### CODE REVIEW

**Comment by tmotyl** [comment]
@eneiasramos what php version are you running?

**Comment by eneiasramos** [comment]
@tmotyl PHP 8.0.15 the error happens when I try to export a CSV

**Review by luigifab — APPROVED** [review]

**Comment by iamniels** [comment]
Just ran into this issue. Happy to see the MR is already here :+1:

**Comment by fballiano** [comment]
> Just ran into this issue. Happy to see the MR is already here 👍

Can you let us know if it the fix works for you?

**Comment by iamniels** [comment]
Yes it works. 

In general for PHP 8, the use of the error suppression operator is problematic since it doesn't work anymore AFAIK.

**Review by fballiano — APPROVED** [review]

**Comment by luigifab** [comment]
My bad, there is a problem with `is_countable`! See #2162.

**Comment by ADDISON74** [comment]
It is interesting how this PR reached the OM, although the function used is_countable() required PHP version 7.3 as a minimum to work. This would no longer be an issue today, because the new OM versions require at least version 7.3 and probably there are few who still use this version (Debian 10 default).

**Pull request merged**
