### PR TITLE
RWD: removed enquire.js and converted to window.matchMedia

### PR DESCRIPTION
**Pull request by fballiano**
Enquire.js is an old js library, last updated 6 years ago:
https://github.com/WickyNilliams/enquire.js

It was used to run js code based on the size of the viewport.

This is not necessary anymore since window.matchMedia is now widely available:
https://caniuse.com/?search=window.matchMedia

This PR removed enquire.js and replace all the calls with matchMedia API calls. It also includes https://github.com/OpenMage/magento-lts/pull/3207

From my tests it works fine.

### CODE REVIEW

**Comment by ADDISON74** [comment]
My only concern is related to existing extensions. If any of them use the libraries that we are removing, issues will arise. Here I can give the example of jscolor, which was removed at some point and brought back because the MageWorx Advanced Product Option is based on it.

**Comment by fballiano** [comment]
Yes but some developer can readd the js or fix it in a different way 😊
La latest version of enquire is 6 years old and google hates too much javascript and old javascript libraries, we’ve to clean it up sometimes 😊

**Review by elidrissidev — COMMENTED** [review]
Missing declaration keyword (`var`/`let`) for all the newly added functions.

**Comment by fballiano** [comment]
@elidrissidev done!

**Comment by fballiano** [comment]
@justinbeaty @empiricompany @Sdfendor would you mind checking this one out? thank you!

**Comment by Sdfendor** [comment]
JS is not my greatest forte. While this looks good and harmless enough, I would give the others mentioned give the advantage here.

**Review by empiricompany — APPROVED** [review]

**Comment by ADDISON74** [comment]
I have analyzed this PR and I agree with it, but it must be rebased to the main branch. I don't consider it will create problems, in the worst case I would keep the js file in the distribution for a while.

**Comment by fballiano** [comment]
I don't know, because strictly speaking this is a breaking change although it is true that almost nobody will have problems with this. If moving the PR to `main` will make it go forward then let's change it.

**Comment by fballiano** [comment]
what are your doubts about this PR?

**Review by Piralein — APPROVED** [review]

**Comment by tmotyl** [comment]
looks good to me. but should this also be documented as breaking change to watch out when updating?

**Comment by fballiano** [comment]
> looks good to me. but should this also be documented as breaking change to watch out when updating?

@tmotyl absolutely, I'll put it here: https://github.com/OpenMage/magento-lts/pull/3388 as soon as it's merged ;-) although I think we can't continue to add things to README, we've to find another way IMHO

**Comment by fballiano** [comment]
@tmotyl I've added info to the README in this PR already.

**Review by tmotyl — APPROVED** [review]

**Comment by fballiano** [comment]
thank you! merging per 1green+2gray!

**Pull request merged**
