### PR TITLE
Block access to various project files

### PR DESCRIPTION
**Pull request by colinmollenhour**
Note, this blocks access to files of these types in directories other than the root directory as well.

### CODE REVIEW

**Review by fballiano — APPROVED** [review]

**Comment by ADDISON74** [comment]
If we keep modifying .htaccess let's insert the missing piece for PHP8 as it has already been done in other files, less in this one. That it is in this PR or another, I have no problem with that.

**Comment by colinmollenhour** [comment]
> If we keep modifying .htaccess let's insert the missing piece for PHP8 as it has already been done in other files, less in this one. That it is in this PR or another, I have no problem with that.

Sorry, wasn't trying to interfere with the other .htaccess file PR, just addressing some minor security issues that were reported/noticed. I think it is a lot easier to make changes when broken up into separate PRs though with specific fixes instead of major overhauls. Surely there is no reason a PR for the PHP8 update alone would not be accepted.

**Comment by ADDISON74** [comment]
@colinmollenhour - Please check my comments to this PR. What I posted before and you answered was just a reminder of another unresolved issue.

**Comment by elidrissidev** [comment]
Not sure about JSON files (other than composer.json of course), I've seen many extensions with that provide such files that are loaded from the frontend.

**Comment by fballiano** [comment]
@elidrissidev is totally right, we should block every json, we could have a manifest.json for pwa support.

**Comment by colinmollenhour** [comment]
> we should block every json

I assume you meant *not* block?
I see no problem with allowing common files like `manifest.json`

**Comment by colinmollenhour** [comment]
I added a negative lookbehind for `manifest.json` specifically. Is that good or would you prefer to explicitly block only certain files?

I think in a production environment it is likely the user will need to modify this file anyway...

**Comment by ADDISON74** [comment]
1) I would add **sh** to the list of extensions. So that it can no longer check the existence of the file cron.sh, used internally within the cronjob. Other extensions that can be found in OpenMage should also be analyzed, for example csv (exports), log. Even if some directories have protections in their own .htaccess files, an extra measure is welcome.

2) And a harmless proposal **O**rder and **D**eny with a capital letter. The initial Magento file complied with this requirement, but the RELEASE_NOTES chunk was added later in OpenMage and someone introduced lowercases.

**Comment by fballiano** [comment]
> I assume you meant _not_ block? I see no problem with allowing common files like `manifest.json`

yes sorry for the mistake.

**Review by fballiano — DISMISSED** [review]

**Comment by colinmollenhour** [comment]
Changed capitalization and added .sh and .yaml to list of blocked extensions.

**Review by ADDISON74 — APPROVED** [review]

**Review by fballiano — APPROVED** [review]

**Pull request merged**
