### PR TITLE
Increased composer platform config to PHP 8.1

### PR DESCRIPTION
**Pull request by Flyingmana**
I noticed the configured Platform was still on php 7.4

### CODE REVIEW

**Review by kiatng — DISMISSED** [review]
Seems fair for next branch.

**Comment by sreichel** [comment]
So "next" does not support 7.4 anymore?

**Comment by fballiano** [comment]
@sreichel since https://github.com/OpenMage/magento-lts/pull/3160

**Review by fballiano — APPROVED** [review]

**Comment by Flyingmana** [comment]
one Review missing, any reasons against it?

**Comment by fballiano** [comment]
@kiatng's review I think it could be considered still valid, I just had to commit a fix to the composer.lock and that invalidated his review

**Review by luigifab — APPROVED** [review]

**Pull request merged**
