### PR TITLE
Downgraded composer dependencies to also fit php7.3

### PR DESCRIPTION
**Pull request by sreichel**
### Description (*)

Current composer.lock file was made for "half-supported" php8.1 and some dependencies rely on php8.1.

This PR changes all requirements to work with php7.3+ (and 8.1).

- no need to run `composer update` when not on 8.1
- gitpod example should work (not tested)
- (keep composer.lock?)

`composer install` should work for every php-version.

(also updated phpstan/ecg-standard)

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Review by fballiano — DISMISSED** [review]

**Comment by fballiano** [comment]
so now we've to use php7.3 when we update composer.lock?

**Comment by sreichel** [comment]
> so now we've to use php7.3 when we update composer.lock?

Yes. (?)

**Comment by fballiano** [comment]
guess I'll have to re-have that mega old version just for that

**Comment by sreichel** [comment]
> guess I'll have to re-have that mega old version just for that

https://github.com/OpenMage/magento-lts#development-environment-with-ddev :sunglasses:

**Comment by fballiano** [comment]
That’s not the point 😉

**Comment by sreichel** [comment]
Maybe it works to 

- set `platform` in composer.json to 7.3
- run `composer update`
- remove `platform` from composer.json
- run `composer update --lock`

**Comment by sreichel** [comment]
> so now we've to use php7.3 when we update composer.lock?

No. Tested ... if you want to update composer dependencies for lower php versions try this ...

```
composer config platform.php 7.3
composer update
composer config platform --unset
```

**Review by fballiano — APPROVED** [review]

**Review by ADDISON74 — APPROVED** [review]

**Pull request merged**
