### PR TITLE
Fix validateHttpVersion to be RFC 1945 and RFC 7230 compliant

### PR DESCRIPTION
**Pull request by leissbua**
### Description (*)

`Mage_HTTP_Client_Curl` is expecting the HTTP Response Header to have 3 elements.

1. HTTP-Version 
2. Status-Code
3. Reason-Phrase

However, the Reason-Phrase is optional, e.g. Apple Pay does not return OK Reason-Phrase on the current `validationURL()`endpoint which is HTTP 1.1. I fixed the code to allow 2 or 3 elements as it does for HTTP 2.0 in the current version

### CODE REVIEW

**Review by sreichel — COMMENTED** [review]
.

**Comment by leissbua** [comment]
What does "." mean @sreichel

**Comment by sreichel** [comment]
@leissbua was a comment on your first commit. The change you have reverted,

**Review by kiatng — APPROVED** [review]
Ref https://www.rfc-editor.org/rfc/rfc7230#section-3.1.2:

> The reason-phrase element exists for the sole purpose of providing a textual description associated with the numeric status code, mostly out of deference to earlier Internet application protocols that were more frequently used with interactive text clients. A client SHOULD ignore the reason-phrase content.

**Comment by sreichel** [comment]
Thanks for that info.

**Review by sreichel — APPROVED** [review]

**Comment by sreichel** [comment]
For HTTP 1.0

https://datatracker.ietf.org/doc/html/rfc1945#section-6.1.1

**Pull request merged**
