### PR TITLE
Merge v19 to v20

### PR DESCRIPTION
**Pull request by fballiano**
Forward port all 1.9.4.x commits into v20.

Note: I fixed a small conflict generated by https://github.com/OpenMage/magento-lts/pull/2256

### CODE REVIEW

**Comment by elidrissidev** [comment]
The PHPStan error is originating from my last PR 🙈 but it didn't show up because the composer error made the workflow not run fully.

**Comment by elidrissidev** [comment]
The merge commits make the history look really ugly. Maybe we could instead start rebasing PRs that sync 19 with 20 branches if that won't cause another problem?

**Comment by fballiano** [comment]
this is what github does when:

Schermata 2022-07-15 alle 22 27 55

**Comment by fballiano** [comment]
mmm i kinda don't know how to avoid the "merge commits" so I'll close this and reopen it when I'll be able to fix that properly.

**Pull request closed without merging**
