### PR TITLE
GitHub Actions - `check-files` workflow - split into steps as a workaround for step template size limit

### PR DESCRIPTION
**Pull request by gorbunovav**
### Description (*)

Splits `check-files` job into more steps to workaround the template size limit issue.

### Fixed Issues (if relevant)

Fixes OpenMage/magento-lts#3275

### Manual testing scenarios (*)

1. Create a PR with several thousands of changed files
2. Check that `check-files` job has completed succesfully and emits relevant output values

### Contribution checklist (*)

 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Comment by fballiano** [comment]
hi @gorbunovav and thanks for your PR, could you rebase it on the "main" branch?

**Comment by gorbunovav** [comment]
@fballiano done

**Comment by ADDISON74** [comment]
You may add yourself to the list of contributors, if your name doesn't appear yet.

**Review by elidrissidev — APPROVED** [review]
LGTM from the output of this PR.

**Comment by fballiano** [comment]
everything seems ok but I don't have the knowledge on this topic to test it properly

**Review by sreichel — APPROVED** [review]
Thought error came from previous step ...

Split grep commands into steps does not hurt hurt ... untested,

**Comment by fballiano** [comment]
I guess we've no real way to test it so let's merge it, since it is approved, and see

**Pull request merged**
