### PR TITLE
Patch SUPEE-10888 / Upgrade to 1.9.3.10

### PR DESCRIPTION
**Pull request by spinsch**
**release notes:** 
https://devdocs.magento.com/guides/m1x/ce19-ee114/ce1.9_release-notes.html

**patch notes:** 
https://magento.com/security/patches/supee-10888

i hope this time i made all things correctly :)

### CODE REVIEW

**Comment by seansan** [comment]
Thanks! (not an expert on merges ... )

Does this include the php 7.2 patch? #449

**Comment by tomlankhorst** [comment]
LGTM

**Comment by spinsch** [comment]
> Thanks! (not an expert on merges ... )
> 
> Does this include the php 7.2 patch? #449

the upgrade made no changes from our community codebase. #499 (PR #450) is still there.

**Comment by Flyingmana** [comment]
Please add Patches and new Releases provided from Magento only via the OpenMage Mirror, else it is duplicating the Review efforts, and we clearly dont have enough Reviewers currently

**Comment by spinsch** [comment]
> Please add Patches and new Releases provided from Magento only via the OpenMage Mirror, else it is duplicating the Review efforts, and we clearly dont have enough Reviewers currently
> 
> see: [OpenMage/magento-mirror#69](https://github.com/OpenMage/magento-mirror/pull/69)

I made it from this PR, but i know what you mean. Next time I will wait till the OpenMage Mirror is reviewed and merged before using it.

**Comment by edannenberg** [comment]
The review process for OpenMage Mirror is trivial, a diff with the latest Magento release in a separate dir and it's done. We do need to review properly before merging anything from OpenMage Mirror though.

**Comment by Flyingmana** [comment]
have created a new PR directly from the OpenMage Mirror, see #539

**Pull request closed without merging**
