### PR TITLE
Fix a bug where using "group by" clause in a backend grid file will display a wrong count.

### PR DESCRIPTION
**Pull request by digitalpianism**
### Description (*)

This provides a fix to get the right total count when using group by in backend grids.

### Fixed Issues (if relevant)

1. Fixes OpenMage/magento-lts#1195

### Manual testing scenarios (*)

1. Create the following script
```
<?php

require_once 'app/Mage.php';

Mage::app();

$collection = Mage::getResourceModel('sales/order_collection');
$collection->getSelect()->group("customer_group_id");

echo $collection->getSize();
```
2. Check the result
3. Apply the fix and run it again to find the good count.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by kkrieger85 — APPROVED** [review]
Make sense

**Comment by ADDISON74** [comment]
Based on @dbachmann message in issue #1195, this issue was fixed by PR #1404 which is already merged. In this case what shall we do with this one?

**Comment by sreichel** [comment]
> In this case what shall we do with this one?

Wait for @digitalpianism feedback :)

**Comment by digitalpianism** [comment]
@sreichel his commit looks very similar to mine so yeah I'm closing this one thanks for the heads up

**Pull request closed without merging**
