### PR TITLE
Fixed incompatible interface deprecations in DB Session Adapter

### PR DESCRIPTION
**Pull request by elidrissidev**
### Description (*)

Small fix to make the methods in DB session adapter compatible with `SessionHandlerInterface`.

### Fixed Issues (if relevant)

1. Fixes OpenMage/magento-lts#3496

### Manual testing scenarios (*)

1. Switch `<session_save>` in `local.xml` to `db`.
2. Clean the cache and check `system.log`.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Comment by elidrissidev** [comment]
I tried adding the type hints following [`SessionHandlerInterface`](https://www.php.net/manual/en/class.sessionhandlerinterface.php) signature and only adding `ReturnTypeWillChange` to the methods with union types which aren't supported pre-PHP 8, but PHPStan keeps complaining 🤷‍♂️

**Comment by colinmollenhour** [comment]
I didn't see your PR and made an attempt to ignore these errors here: #3498 but it seems yours actually works. 😄 

What do you think about changing:
```
class Mage_Core_Model_Resource_Session implements Zend_Session_SaveHandler_Interface
```
to
```
class Mage_Core_Model_Resource_Session implements SessionHandlerInterface
```
?

**Comment by elidrissidev** [comment]
@colinmollenhour I've switched it. `Zend_Session_SaveHandler_Interface` wasn't referenced anywhere anyways.

**Comment by fballiano** [comment]
if we change the interface of a public class, shouldn't we have this PR in the next branch?

**Comment by elidrissidev** [comment]
The interface is unused in the core and the only reference I found was commented out 15 years ago.

**Comment by fballiano** [comment]
😂 ok then, it seems enough

some of our code is really old

**Comment by fballiano** [comment]
on my local machine phpstan runs without errors also without the `ReturnTypeWillChange` now that we're using the `SessionInterface`, should we still keep the `ReturnTypeWillChange`?

**Comment by elidrissidev** [comment]
The issue this PR was meant to be fixing is PHP deprecation errors related to incompatible types with the interface. PHPStan never complained about them in `main`, but I think it should fix it in `next`.

**Comment by fballiano** [comment]
sure, that's why I'm running phpstan on my local machine with php8, which is the difference that triggers the error in next ;-)

(actually i've to admin I ran it with php8.2 instead of 8.1)

**Comment by elidrissidev** [comment]
In `next` proper types could be added to this class. Here it's either you remove `ReturnTypeWillChange` which causes PHP deprecation messages, or you try to introduce types and but PHPStan's expectations do not conform with what's in PHP documentation, it seems to expect the methods to have `mixed` type which is not available in PHP 7.x.

**Comment by fballiano** [comment]
true, [this version](https://github.com/fballiano/openmage/blob/testphpstan/app/code/core/Mage/Core/Model/Resource/Session.php) works correctly but it would have to be committed only on the `next` branch

**Comment by colinmollenhour** [comment]
Does this patch also fix the next branch? My only goal was to get the PHPStan action passing again - if this does that then I am for it. :)
What is the difference between main and next that causes next to fail in the first place?

**Review by colinmollenhour — APPROVED** [review]
Looks good to me. The change of which interface class is implemented should be benign.

**Comment by fballiano** [comment]
I would have preferred the proper fix on the next branch :-\

**Comment by elidrissidev** [comment]
@fballiano Feel free to open one for `next` to introducing proper types :)

**Comment by fballiano** [comment]
done, but I think this one should be merged too, right?

**Comment by elidrissidev** [comment]
Yeah. The PR for `next` should wait until this one is merged and forward-ported so you can rebase it and remove the `ReturnTypeWillChange` since it won't be needed there.

**Review by fballiano — APPROVED** [review]

**Comment by fballiano** [comment]
then I guess it's time ;-)

**Comment by fballiano** [comment]
merged, forward ported and updated https://github.com/OpenMage/magento-lts/pull/3499 ;-)

**Pull request merged**
