### PR TITLE
Fixed array_merge TypeError on missing disabled module dependency

### PR DESCRIPTION
**Pull request by Tomasz-Silpion**
### Description (*)

This PR fixes PHP 8.x  ```Uncaught TypeError: array_merge(): Argument #2 must be of type array, null given``` when disabled module A depends on non existing module B.

### Fixed Issues (if relevant)

1. Fixes OpenMage/magento-lts#3714

### Manual testing scenarios (*)

1. Add Vendor_Module.xml to app/etc/modules folder with following file content:

```
<?xml version="1.0"?>
<config>
    <modules>
        <Vendor_Module>
            <active>false</active>
            <codePool>local</codePool>
            <depends>
                <Other_Module/>
            </depends>
        </Vendor_Module>
    </modules>
</config>
```
2. Check various scenarios before&after the patch with active tag set as false or true in combination with not existing, or existing Other_Module.xml:

```
<?xml version="1.0"?>
<config>
    <modules>
        <Other_Module>
            <active>false</active>
            <codePool>local</codePool>
        </Other_Module>
    </modules>
</config>
```

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [X] All automated tests passed successfully (all builds are green)
 - [X] Add yourself to contributors list

### CODE REVIEW

**Review by kiatng — DISMISSED** [review]
Prior to PHP8, the result was

> Warning: array_merge(): Expected parameter 2 to be an array, null given

It throws a fatal error in PHP8.

**Comment by luigifab** [comment]
On dev mode I got: `ErrorException: Warning Undefined array key "Other_Module"` or `ErrorException: Notice Undefined index: Other_Module` depending on PHP version installed with only _Vendor_Module.xml_ (with or without the PR).

**Comment by sreichel** [comment]
Tested.

**Comment by Tomasz-Silpion** [comment]
@luigifab, sorry, you are right. I didn't even test it under DeveloperMode in my hurry. The proper solution then would need a more complex approach https://github.com/OpenMage/magento-lts/pull/3715/files

I've reverted previous change and wrapped both loops in if `($moduleProps['active']) {` check

**Review by luigifab — APPROVED** [review]
Yes, Working!

**Review by fballiano — APPROVED** [review]
read and tested, works as expected

**Comment by sreichel** [comment]
@all-contributors add @Tomasz-Silpion code

**Pull request merged**
