### PR TITLE
Moved patch files to repo

### PR DESCRIPTION
**Pull request by sreichel**
### Description (*)

https://github.com/OpenMage/magento-lts/pull/2960#issuecomment-1397590914

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Review by elidrissidev — APPROVED** [review]

**Review by ADDISON74 — APPROVED** [review]

**Comment by justinbeaty** [comment]
Note: there's still some discussion on if a separate repo is the best solution starting with [this comment](https://github.com/OpenMage/magento-lts/pull/2960#issuecomment-1398435127).

**Comment by fballiano** [comment]
It's ok with me but referencing the commit hash could be done also from the external repo, just to be sure that the patches are immutable in case of modifications (that will almost never happen but still...)

**Review by elidrissidev — APPROVED** [review]
Should be good now

**Review by fballiano — APPROVED** [review]

**Comment by fballiano** [comment]
merged and cherrypicked to v20

**Comment by elidrissidev** [comment]
Ops composer.lock was not updated

**Comment by fballiano** [comment]
we'll have to do it in a new PR

**Comment by fballiano** [comment]
I updated the composer lock directly on the branches

**Pull request merged**
