### PR TITLE
Move orig data to abstract model (according to Magento 2.x)

### PR DESCRIPTION
**Pull request by Sekiphp**
### Description (*)
Move `origData` property and related methods to `mage_Core_Model_Abstract` according to Magento 2.x.

Related M2 file: https://github.com/magento/magento2/blob/fbfac3e51730abe2b79c6072544bc9742fcf7606/lib/internal/Magento/Framework/Model/AbstractModel.php#L56

**These methods are not used in any direct child of `Varien_Object`:**
`$ grep -R -B10000 -A10000 -P 'OrigData|dataHasChangedFor' . | grep -F "extends Varien_Object"`

**Output:**
`./app/code/core/Mage/Core/Model/Abstract.php-abstract class Mage_Core_Model_Abstract extends Varien_Object`

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by kiatng — DISMISSED** [review]
I'm OK.

**Comment by Flyingmana** [comment]
did move it to the 20.0 branch, as it has possible BC breaks

**Comment by midlan** [comment]
The branch was forked from 1.9.x, now changed files shows diff of 1.9.x to 20.x

This PR should be closed and cherry picked to proper forked branch.

**Comment by Sekiphp** [comment]
#1325

**Pull request closed without merging**
