### PR TITLE
PHPCS: applied rules space_after_semicolon and no_spaces_inside_parenthesis

### PR DESCRIPTION
**Pull request by fballiano**
The subject said it all.

**Note:**
I couldn't fine a rule to change this:

`if(intval($roleId) > 0) {`

into this:

`if (intval($roleId) > 0) {`

(adding the space between "if" and "("), if you know one please let me know

### CODE REVIEW

**Comment by sreichel** [comment]
Boys with toys ... 😂👌

**Comment by fballiano** [comment]
> Boys with toys ... 😂👌

somebody discovered a new one 😂

**Comment by sreichel** [comment]
This PR isnt complete ... there are different types of wrong spaces, but this PR fixes only a few of them ...

Before:
```
                if ( ! ($extension = pathinfo($file, PATHINFO_EXTENSION)) || ! in_array($extension, $_allowedFileExtensions)) {
```

After:
```
                if (! ($extension = pathinfo($file, PATHINFO_EXTENSION)) || ! in_array($extension, $_allowedFileExtensions)) {
```

___

Last days i worked on a phpcs-rulset with sniffs that can be fixed with `phpcbf` ... not finished.

```
<?xml version="1.0"?>
<ruleset name="Fixable errors">
    <description>Fixable errors</description>

    <rule ref="Generic.Arrays.DisallowLongArraySyntax.Found"/>
    <rule ref="Generic.Formatting.MultipleStatementAlignment.IncorrectWarning"/>
    <rule ref="Generic.Formatting.MultipleStatementAlignment.NotSame"/>
    <rule ref="Generic.PHP.LowerCaseKeyword.Found"/>
    <rule ref="Generic.WhiteSpace.LanguageConstructSpacing.IncorrectSingle"/>
    <rule ref="Generic.WhiteSpace.ScopeIndent.IncorrectExact"/>

    <rule ref="PEAR.Functions.FunctionCallSignature.SpaceAfterCloseBracket"/>

    <!--    <rule ref="PSR2.Classes.ClassDeclaration.CloseBraceAfterBody"/>-->

    <rule ref="PSR2.Classes.ClassDeclaration.OpenBraceNewLine"/>
    <rule ref="PSR2.Classes.ClassDeclaration.SpaceAfterKeyword"/>
    <rule ref="PSR2.ControlStructures.ControlStructureSpacing.SpacingAfterOpenBrace"/>
    <rule ref="PSR2.ControlStructures.ControlStructureSpacing.SpaceBeforeCloseBrace"/>
    <rule ref="PSR2.ControlStructures.SwitchDeclaration.SpacingAfterCase"/>
    <rule ref="PSR2.ControlStructures.SwitchDeclaration.SpaceBeforeColonCASE"/>
    <rule ref="PSR2.Methods.FunctionCallSignature.ContentAfterOpenBracket"/>
    <rule ref="PSR2.Methods.FunctionCallSignature.Indent"/>
    <rule ref="PSR2.Methods.FunctionCallSignature.SpaceAfterOpenBracket"/>
    <rule ref="PSR2.Methods.FunctionClosingBrace.SpacingBeforeClose"/>
    <rule ref="PSR2.Methods.FunctionCallSignature.SpaceBeforeCloseBracket"/>

    <rule ref="PSR12.Operators.OperatorSpacing.NoSpaceAfter"/>

    <rule ref="Squiz.Arrays.ArrayDeclaration.NoSpaceBeforeDoubleArrow"/>
    <rule ref="Squiz.Arrays.ArrayDeclaration.SpaceInEmptyArray"/>
    <rule ref="Squiz.Commenting.InlineComment.WrongStyle"/>
    <rule ref="Squiz.ControlStructures.ControlSignature.SpaceAfterCloseBrace"/>
    <rule ref="Squiz.ControlStructures.ControlSignature.SpaceAfterCloseParenthesis"/>
    <rule ref="Squiz.ControlStructures.ControlSignature.SpaceAfterKeyword"/>
    <rule ref="Squiz.ControlStructures.ForEachLoopDeclaration.NoSpaceAfterArrow"/>
    <rule ref="Squiz.Functions.FunctionDeclarationArgumentSpacing.NoSpaceBeforeArg"/>
    <rule ref="Squiz.Functions.FunctionDeclarationArgumentSpacing.SpacingAfterOpen"/>
    <rule ref="Squiz.Functions.FunctionDeclarationArgumentSpacing.SpacingBeforeClose"/>
    <rule ref="Squiz.Functions.FunctionDeclarationArgumentSpacing.SpaceBeforeComma"/>
    <rule ref="Squiz.Functions.MultiLineFunctionDeclaration.BraceOnSameLine"/>
    <rule ref="Squiz.Functions.MultiLineFunctionDeclaration.BraceIndent"/>
    <rule ref="Squiz.Functions.MultiLineFunctionDeclaration.SpaceAfterFunction"/>
    <rule ref="Squiz.Functions.MultiLineFunctionDeclaration.SpaceBeforeOpenParen"/>
    <rule ref="Squiz.WhiteSpace.ControlStructureSpacing.SpacingAfterOpen"/>
    <rule ref="Squiz.WhiteSpace.ControlStructureSpacing.SpacingBeforeClose"/>
<!--    <rule ref="Squiz.WhiteSpace.FunctionClosingBraceSpace.SpacingBeforeClose"/>-->
    <rule ref="Squiz.WhiteSpace.FunctionSpacing.AfterLast"/>
    <rule ref="Squiz.WhiteSpace.ObjectOperatorSpacing.After"/>
    <rule ref="Squiz.WhiteSpace.ObjectOperatorSpacing.Before"/>
    <rule ref="Squiz.WhiteSpace.OperatorSpacing.NoSpaceBefore"/>
    <rule ref="Squiz.WhiteSpace.OperatorSpacing.SpacingAfter"/>
    <rule ref="Squiz.WhiteSpace.ScopeClosingBrace.Indent"/>
    <rule ref="Squiz.WhiteSpace.SuperfluousWhitespace.EmptyLines"/>
</ruleset>
```

```
<?php

class  Test  {
    public function   test  (  $a, $b   , $c  )
    {
        # array
        $array1  =  ARRAY  (


        );
        $array1  =      array( 1=>'abc' );

        # string
        if($a === '1'){
            $r   =   1;
        }
        else
        {
            $c;
        }

        $o  =   new   Varien_Object();
        $o  ->  setA(   $a )  ;

        $i = 0;
        switch   ( is_string(  $test  ) )   {
            case true  :
                $i = 1;
                break;
            case    false  :
                $i = 2;
                break;
            default:
                return    $i  =  2;


        }

        switch   ( is_string(  $test  ) )
        {

        }

    }


}
```

**Comment by fballiano** [comment]
yes it really didn't work all that well... but if I run phpcsfixer again it doesn't fix it :-(

**Comment by fballiano** [comment]
ah, let's close this, you'll do a much better job with the new ruleset

**Comment by sreichel** [comment]
Feel free to pick it up ... this is just work in progress.

All i've done is ...

- run `phpcs --standard=PSR2 -s` <test-file> (`-s` to show sniff-names)
- added everything to could be automatically fixed to `phpcs-fixable.xml`
- run `phpcbf --standard=phpcs-fixable.xml <test-file>` to check
- added new "errors/misalignment" to testfile ...

At the end this git-pre-commit (`.git/hooks/pre-commit`) should fix all changed files in a commit ...

```
#!/bin/sh

PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`

# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
    oIFS=$IFS
    IFS='
    '
    SFILES="$1"
    IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}

echo "Checking PHP Lint..."
for FILE in $SFILES
do
    php -l -d display_errors=0 $PROJECT/$FILE
    if [ $? != 0 ]
    then
        echo "Fix the error before commit."
        exit 1
    fi
    FILES="$FILES $PROJECT/$FILE"
done

if [ "$FILES" != "" ]
then
    echo "Running Code Fixer"
    ./vendor/bin/phpcs --standard=.github/phpcs-fixable.xml --encoding=utf-8 -n -p $FILES
    if [ $? != 0 ]
    then
        ./vendor/bin/phpcbf --standard=.github/phpcs-fixable.xml $FILES
    fi
fi

status=$?

[ $status -eq 1 ] && exit 0 || exit $status
```

**Comment by fballiano** [comment]
If I run `vendor/bin/phpcbf --standard=PSR2 app/Mage.php` it doesn't fix this:

```diff
-                if ( ! ($extension = pathinfo($file, PATHINFO_EXTENSION)) || ! in_array($extension, $_allowedFileExtensions)) {
+                if (! ($extension = pathinfo($file, PATHINFO_EXTENSION)) || ! in_array($extension, $_allowedFileExtensions)) {
```

so I think it likes it that way :-\

**Comment by sreichel** [comment]
mhh, then reopen please.

**Comment by fballiano** [comment]
I can't since I deleted the branch, I'll open a new one asap

**Pull request closed without merging**
