### PR TITLE
Small improvements in Manage Attributes grid

### PR DESCRIPTION
**Pull request by ADDISON74**
This PR comes with small improvements in Manage Attributes grid page. 

Here is the grid before

before

And here is the grid after

after

1. Column 2 (Attribute Label) and Column 1 (Attribute Code) are switched now.  In no other Magento grid the code is on the first column (see CMS sections).

2. The default sorting is no longer done by attribute_code but by the frontend_label.

### CODE REVIEW

**Comment by Flyingmana** [comment]
I suggest moving this to 20.x

**Comment by ADDISON74** [comment]
@Flyingmana - I changed the branch to 20.x as you suggested.

**Comment by elidrissidev** [comment]
@ADDISON74 you will need to rebase or merge `20.0` to your own branch

**Comment by ADDISON74** [comment]
@elidrissidev - The change comes from my 1.9.4.x repository and is now redirected to OpenMage 20.0. If it is merged, will it not got in 20.0 branch?

**Comment by elidrissidev** [comment]
Changing the base branch to `20.0` caused a conflict, to fix it you will have to bring the changes from `20.0` to your current branch either by doing a rebase (`git pull --rebase upstream 20.0`) or a try to resolve them from GitHub which will create a merge commit.

**Comment by ADDISON74** [comment]
I will try that. I am vacation only with a tablet and GitHub account :)

**Comment by Flyingmana** [comment]
just waiting for the next release should also help to have these conflicts automatically resolved

**Comment by ADDISON74** [comment]
This is good. Tthe important thing is that PR exists and can be discussed. These days I've been looking at the Backend interface looking to put on paper everything I didn't like in those almost 11 years of Magento. 

I wish everyone a happy new year and I hope that this project brings our ideas together for as long as possible. I enjoyed discussing my ideas with many of you this year. Be healthy and strong that's what matters most. Happy New Year!

**Comment by ADDISON74** [comment]
By changing the branch to 20.0 around 409 modified files were added. I will keep the branch as I set it up initially for 1.9.4.x. 

I consider this PR to be a real improvement for version 1.9.4 as well.

**Review by luigifab — APPROVED** [review]

**Review by Sdfendor — APPROVED** [review]

**Review by fballiano — APPROVED** [review]

**Pull request merged**
