### PR TITLE
Drop LTS csv files

### PR DESCRIPTION
**Pull request by luigifab**
### Description

This is a suggestion, to drop LTS csv files, to use only original csv files.
I also removed some unused translations (with the Magento word).

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Flyingmana** [comment]
what is the benefit you see here?

Also droping existing translations is always a major BC break, as its impossible to know which themes or extensions may use them

**Comment by luigifab** [comment]
No benefit, but Magento is now OpenMage, so it's useless to have two translation files for Mage_Adminhtml..., no?
Translations removed are unused in _app/_ (rebranding commits), and even if a custom theme or anything else use them, there is no impact 😕 .

**Comment by fballiano** [comment]
I agree, but on the 20.x branch

**Comment by ADDISON74** [comment]
I agree with these changes.

**Comment by sreichel** [comment]
They are there to not break local packs.

I'd keep them.

**Comment by luigifab** [comment]
<troll>there are no language pack with theses files</troll>

**Comment by luigifab** [comment]
Be happy :)

**Review by fballiano — DISMISSED** [review]

**Review by ADDISON74 — DISMISSED** [review]

**Review by kiatng — APPROVED** [review]

**Comment by elidrissidev** [comment]
So what are we doing with this?

**Comment by luigifab** [comment]
We are dropping the LTS files! 😹

**Comment by elidrissidev** [comment]
If it's not a breaking change, I'm approving.

**Comment by ADDISON74** [comment]
I will keep them for a while. We need to evaluate more before merging. If someone added phrases in the past in these files they will be lost. 

I am not a fan of locale files. I choose to translate the frontend only in just one file.

**Review by fballiano — APPROVED** [review]

**Review by kiatng — APPROVED** [review]
Agree that it is OpenMage now. In the unlikely event that this mess up the translations on someone website, it's not like it's "breaking" the site, it can be easily fixed in many methods, so more like a nuisance.

**Comment by ADDISON74** [comment]
A lot of custom phrases were added in these files. PR #1727 is one example. All these files need to be integrated in Magento translations. I do not approve it without this task checked.

**Comment by elidrissidev** [comment]
> A lot of custom phrases were added in these files. PR #1727 is one example.

I already moved the phrases I added to LTS files back to the core ones before that PR was merged.

**Review by fballiano — APPROVED** [review]

**Comment by ADDISON74** [comment]
It is fine. I approved it.

**Review by ADDISON74 — DISMISSED** [review]

**Comment by ADDISON74** [comment]
Very strange. He did all steps correctly by removing all references to these LTS files from config.xml files then moved all the sentences to the Magento files and finally deleted the LTS files. I don't see anything wrong especially a conflict between Mage_Core_LTS.csv and Mage_Core.csv.

**Comment by luigifab** [comment]
Resolved!

**Review by ADDISON74 — APPROVED** [review]

**Review by fballiano — APPROVED** [review]
finally we drop these!

**Pull request merged**
