### PR TITLE
Missing variables and functions added

### PR DESCRIPTION
**Pull request by syamvilakudy**

### CODE REVIEW

**Comment by LeeSaferite** [comment]
Can you please explain this PR?

What is the bug?
Does this break current behaviour?

**Comment by syamvilakudy** [comment]
Check the below file
app/design/frontend/base/default/template/page/template/linksblock.phtml

Undefined functions
1. $this->getLiParams()
2. $this->getAParams()

**Comment by drobinson** [comment]
@LeeSaferite looks like this block isn't used by Magento Core anywhere.  
@syamvilakudy Diff looks good, but can you create a pull request with just the relevant commit (dd054c6)?

**Comment by syamvilakudy** [comment]
Ok , I will create a new pull request

**Comment by syamvilakudy** [comment]
I have created a PR with latest file ( Copyright (c) 2006-2015 X.commerce )

**Pull request closed without merging**
