### PR TITLE
Removed deprecated and unused files from lib/Mage

### PR DESCRIPTION
**Pull request by fballiano**
**THIS PR TARGETS V21**

These files seem to be unused (unreferenced anywhere).
lib/Mage/Cache/Backend/Redis.php is also deprecated since many years (I've tested redis cache without this file and it works perfectly)

### CODE REVIEW

**Comment by kiatng** [comment]
There may be local.xml with this setting:

```xml
<backend>Mage_Cache_Backend_Redis</backend>
```

That needs to change to this after this PR:
```xml
<backend>Cm_Cache_Backend_Redis</backend>
```

Ref https://github.com/colinmollenhour/Cm_Cache_Backend_Redis.

**Comment by fballiano** [comment]
I'll make sure to write that in the release notes for v21

**Comment by kiatng** [comment]
Found this: https://github.com/OpenMage/magento-lts/blob/304a23c4509c863b7f7784b535d294d93e78dd94/lib/Mage/DB/Mysqli.php#L77-L77

**Comment by fballiano** [comment]
note that the PR targets `next`

**Review by kiatng — APPROVED** [review]

**Pull request merged**
