### PR TITLE
advertise firegento_logger

### PR DESCRIPTION
**Pull request by fballiano**
As per https://github.com/OpenMage/magento-lts/issues/569 let's help people find a better logging solution.

It's not in composer suggest but I (now) think this is the best (and less intrusive, and more easily findable) way to advertise important 3rd party modules

### CODE REVIEW

**Comment by colinmollenhour** [comment]
One impediment to having this section grow will be the fact that it is part of the main repo that has requirements for multiple code reviews, etc. It creates noise for code reviewers and then the maintainer managing releases has to mess with porting commits between branches and the commit log gets cluttered with README updates.

What about instead starting a "OpenMage/awesome-openmage" project and letting a few people such as yourself maintain it much more freely and referencing this project prominently in the README? This will be less busy-work for the reviewers and maintainers and allow it to grow much more rapidly and keep non-code commits out of the main repo.

**Comment by fballiano** [comment]
totally makes sense, when we'll have the new repo I'll change the PR ;-)

**Comment by fballiano** [comment]
any chance we can create the repo so to close this and move it forward?

**Comment by Flyingmana** [comment]
maybe thats more something for the (way to empty) documentation.
We have an area for Modules there, see https://openmage.readthedocs.io/en/latest/modules/index.html

The related repository is https://github.com/OpenMage/documentation/tree/master/modules

**Comment by fballiano** [comment]
@Flyingmana you're totally correct, I'll PR on that repo and I'll link it in https://github.com/OpenMage/magento-lts/issues/569

**Pull request closed without merging**
