### PR TITLE
Fix config bug in Cm_RedisSession

### PR DESCRIPTION
**Pull request by henrykbrzoska**
so, we make working proper config values break_after_frontend & break_after_adminhtml from
https://github.com/OpenMage/magento-lts/blob/1.9.4.x/app/etc/local.xml.additional

### CODE REVIEW

**Comment by joshua-bn** [comment]
Can you explain what this is for? What the issue is that you're fixing?

Unless you changed the name of the sessions, they should be frontend and adminhtml (afaik). Your method is fragile.

**Comment by colinmollenhour** [comment]
Is `session_name()` in this context not holding the proper session name?

**Comment by henrykbrzoska** [comment]
@colinmollenhour maybe i've something wrong in php ini settings, but on load session i have try to load 'break_after_PHPSESSID' by default
@joshua-bn yes, there should be check if admin uri is set in backoffice.

**Comment by henrykbrzoska** [comment]
nvm

**Pull request closed without merging**
