### PR TITLE
Add a message calling for an end to the Russian invasion of Ukraine

### PR DESCRIPTION
**Pull request by luigifab**
### Description

This is a basic text for README and backend.

def

om

image

### Related Pull Requests

🇺🇦 #2038

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Review by elidrissidev — APPROVED** [review]

**Review by Flyingmana — APPROVED** [review]

**Review by sreichel — APPROVED** [review]

**Comment by fballiano** [comment]
To add a line in the README would be one thing, to add a line in out customer's backend, without a dismiss possibility, it's a mistake and a disservice.

**Comment by elidrissidev** [comment]
@fballiano I am sorry that you didn't like this change, I merged this PR seeing that it had enough approvals for more than a week.

**Comment by Flyingmana** [comment]
I see it differently and think its at maximum a minor disturbance and acceptable to keep it this way till the territory of the Ukraine got restored. Which is why I gave my approval.

**Comment by ADDISON74** [comment]
Where I work important donations of money for Ukrainians were made. I saw this PR but I did not approve it for one reason, ignoring the message of solidarity that most of us feel we have about the aberrant war of Putler that leads to an even greater destabilization of the world from all points of view economic, sanitary, energetic, it can not be removed. It is basically an imposed message and I think there is an issue here. If we had used the OpenMage feed like we did for "Thank you for using OpenMage!" message, a notification on that line and a message in the Inbox that could be marked as read or removed was perfect. If a user does not agree with the message he will have to change the code.

**Comment by imaphpdev** [comment]
Can we just keep this stuff out of the code, please?
What would be next? Support for LGBTQ? Blame Trump and Putin? ... 
Imho all the political stuff needs to stay out of a software project.

**Comment by fballiano** [comment]
> Can we just keep this stuff out of the code, please?

Please check https://github.com/OpenMage/magento-lts/pull/2325

**Comment by Flyingmana** [comment]
@imaphpdev I make you aware of our Code of Conduct https://github.com/OpenMage/magento-lts/blob/33dfa269fa60d56f4d7af19a393179e3ae927fab/.github/CODE_OF_CONDUCT.md#our-standards

which includes 

> Showing empathy towards other community members

A notable part of our community is based or related to people in The Ukraine.
And as you name it, also a part of our community is belonging to the group of LGBTQ.

I request you to be more carefully with your words, respecting our Code of Conduct and show empathy towards our community members

**Pull request merged**
