### PR TITLE
phpstan: Sitemap, Newsletter, ...

### PR DESCRIPTION
**Pull request by sreichel**
### Description (*)

Some small updates.

Edit: ignore some errors and remove them from baseline.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Review by fballiano — DISMISSED** [review]

**Review by ADDISON74 — APPROVED** [review]

**Review by fballiano — APPROVED** [review]

**Comment by tmotyl** [comment]
What is the gain from ignoring errors?
Are they all false positives?

**Comment by sreichel** [comment]
@tmotyl its to much noise at the moment.

Some are false positive or go away when underlying errors are fixed.

I'll re-add them later.

**Comment by tmotyl** [comment]
Roger!
Thanks for taking care!

**Review by ADDISON74 — APPROVED** [review]

**Comment by fballiano** [comment]
can't auto merge to 20.0 because of conflicts

**Comment by sreichel** [comment]
What is auto-merge?

(Btw ... if you have conflicts with baseline file ... ignore them and merge, then rebuild baseline and amend last commit.)

**Comment by fballiano** [comment]
I meant cherry picking it to 20.0

**Comment by fballiano** [comment]
I had an old command to regenerate the baseline, it created a .github/phpstan-baseline.neon file but now that's pushed it doesn't allow me to re-ament it.

hate this workflow

**Comment by fballiano** [comment]
but in 20.0 there are anyway all of these files

Screenshot 2022-12-20 alle 20 12 44

so probably we can leave it as it is for now

**Comment by sreichel** [comment]
> but in 20.0 there are anyway all of these files

Yep. #2765 was added one day after release. ;)

**Comment by sreichel** [comment]
> What is the gain from ignoring errors? Are they all false positives?

@tmotyl Maybe you can check this .... it seems neither phpstorm nor phpstan works correctly for `Mage::app()->someMethod()`. (this causes some of false positives)

**Comment by tmotyl** [comment]
@sreichel can you make an issue at https://github.com/macopedia/phpstan-magento1 with some info how to reproduce it?

**Comment by sreichel** [comment]
> @sreichel can you make an issue at https://github.com/macopedia/phpstan-magento1 with some info how to reproduce it? When I type `Mage::app()->` in phpstorm, I'm getting correct method proposals.

I'll do.

Mhh, i get not proposals for Mage::app() and also have no correct return value. E.g.

```
$store = Mage::app()->getStore();
(!$store) { # false psoitive here ...
```

Linux, PhpStorm 2022.2.2 Build #PS-222.4167.33, built on September 15, 2022

**Comment by tmotyl** [comment]
PhpStorm 2022.3 here.
getStore can return null, so the check is needed

**Comment by sreichel** [comment]
> getStore can return null, so the check is needed

This is right, but i have no return type. For phpstan this check is always true|false ("#Negated boolean expression ...")

**Comment by sreichel** [comment]
Cleared phpstorm cache and auto-complete works again. Will check phpstan later,

**Pull request merged**
