### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by fballiano**
Proposed rebranding of the official repository title.

I think it's time for OpenMage to be called OpenMage, not Magento LTS.

At the moment this change is just about the README file.

### CODE REVIEW

**Review by colinmollenhour — CHANGES_REQUESTED** [review]
I don't know that we want to say "that took over Magento 1" since although we may be the defacto or most popular continuation of the Magento 1 legacy, we did not acquire any special IP rights or license or blessing from Adobe. I think from a legal standpoint we should not make this claim or at least in these terms.

**Comment by fballiano** [comment]
what about instead of "took over Magento 1" it was "is continuing the free/libre open source development of Magento 1"?

**Comment by Flyingmana** [comment]
Generally I support the rebranding.

But also keep in mind how this affects "SEO", or better said, ways how people find us.
When choosing the wording, think of what would people search for. 
And especially as Adobe seems to phase out the usage of the Term "Magento" I would like to keep this special part.

image

**Review by kkrieger85 — APPROVED** [review]

**Comment by Flyingmana** [comment]
todo: check SEO requirements from https://github.com/OpenMage/magento-lts/issues/1070 after change

**Comment by fballiano** [comment]
I do not agree on the direction that being taken regarding the description of openmage and this repo, so I guess I'm not the right person to update the README.

Some PRs take ages to be checked and the description of the repo (which is quite important) gets changed in few hours... This project should have the same way of dealing with things for everything.

**Pull request closed without merging**
