### PR TITLE
Added ability to add target attribute for adminhtml menu items

### PR DESCRIPTION
**Pull request by Sekiphp**
### Description (*)
In OM there is currently now way how to open hyperlinks to new tabs / windows.

#### Usage
```xml
<menu_item translate="title">
    <title>Menu item label</title>
    <action>adminhtml/hello_world/foo</action>
    <target>_blank</target>
</menu_item>
```

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Comment by midlan** [comment]
What about _framename_ as target?
https://www.w3schools.com/tags/att_a_target.asp

**Comment by Sekiphp** [comment]
> What about _framename_ as target? https://www.w3schools.com/tags/att_a_target.asp

Until now, noone want it! This feature is added mainly for `_blank` option, which should be usable for multiple M1 websites. You are nitpicker, Milan! :-)

**Comment by midlan** [comment]
I am not nitpicker. When adding new feature I just would implement the complete current standard. By your argumentation you should just implement `_blank`, because you don't need the others 🙃

**Comment by Sekiphp** [comment]
> I am not nitpicker. When adding new feature I just would implement the complete current standard. By your argumentation you should just implement `_blank`, because you don't need the others 🙃

I'm not convienced about framename support, but I implement it.....

**Review by midlan — APPROVED** [review]

**Review by ADDISON74 — APPROVED** [review]

**Review by Sdfendor — APPROVED** [review]

**Review by tmewes — APPROVED** [review]

**Comment by xqiu** [comment]
commit https://github.com/OpenMage/magento-lts/commit/bc337911285ac60c5c77fd2f084997805847fe94  should not change the default function signature for _buildMenuArray, some plugin may depend on this function's default behavior (e.g. https://github.com/AOEpeople/Clean_SqlReports) .

**Pull request merged**
