### PR TITLE
Merge v19 -> v20

### PR DESCRIPTION
**Pull request by fballiano**
Cherry picking from https://github.com/OpenMage/magento-lts/compare/v19.4.18...1.9.4.x and fixing conflicts

### CODE REVIEW

**Comment by fballiano** [comment]
I'm having troubles merging https://github.com/OpenMage/magento-lts/pull/2591 I'll check later

**Comment by fballiano** [comment]
everything should be up to date now, also merged https://github.com/OpenMage/magento-lts/pull/2591 which was having a conflict

**Comment by fballiano** [comment]
@sreichel can you recognize why phpstan fails? maybe I screwed the baseline while fixing conflicts?

**Comment by sreichel** [comment]
I'm out with my dog for next hours ... and i can't see detailed checks in github app ...

Think easiest is to rebuild baseline (I also do this for larger PRs)

Run phpstan with

```
-b .github/phpstan-baseline.neon
```

**Comment by elidrissidev** [comment]
I think what's happening here is that the checks are being run with `20.0`'s baseline file, but I'm not sure I'll have to check later.

**Comment by elidrissidev** [comment]
nvm I have no idea what's happening 😆

**Comment by fballiano** [comment]
should be up to date again with all conflicts fixed

**Comment by fballiano** [comment]
updated, but need to merge https://github.com/OpenMage/magento-lts/pull/2636 cause the conflict is not trivial

**Comment by fballiano** [comment]
I've finished merging all of the commits, also including https://github.com/OpenMage/magento-lts/pull/2636 which had a conflict that wasn't super clean, if somebody wants to check it out, the file was app/code/core/Mage/Adminhtml/Block/Customer/Edit/Tab/View.php

**Review by kiatng — APPROVED** [review]
Time for new release.

**Review by elidrissidev — DISMISSED** [review]
I've rechecked some of the major changes in this release 🤞.

**Review by elidrissidev — APPROVED** [review]

**Review by kiatng — APPROVED** [review]

**Pull request merged**
