### PR TITLE
Do not calculate catalogrules when there are none

### PR DESCRIPTION
**Pull request by tmotyl**
### Description (*)
Add early return to applyAllRulesToProduct
to speed up product save when there are no catalog rules.
This prevents Magento from doing heavy db operations including
creating temporary tables just to find out they are empty.
Like: CREATE TEMPORARY TABLE `catalogrule_product_price_tmp`

### Fixed Issues (if relevant)

1. Relates: OpenMage/magento-lts#573

### Manual testing scenarios (*)

1. Given you have magento with no catalog rules and with rules
2. Check whether saving product from admin panel works

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by sreichel — DISMISSED** [review]
dupe ... see above

**Comment by colinmollenhour** [comment]
Have you also tested removing the last rule?

**Comment by tmotyl** [comment]
> I think there is no need to load rules ... how about this?
> 
> ```
> 
>         if (!$rules->getSize()) {
>             return $this;
>         }
> ```

if there are no rules, then count will not hurt, and when there are rules, they will be loaded anyway few lines later

**Comment by tmotyl** [comment]
> dupe ... see above

what do you mean?

**Comment by sreichel** [comment]
> 
> 
> > I think there is no need to load rules ... how about this?
> > ```
> > 
> >         if (!$rules->getSize()) {
> >             return $this;
> >         }
> > ```
> 
> if there are no rules, then count will not hurt, and when there are rules, they will be loaded anyway few lines later



> 
> 
> > dupe ... see above
> 
> what do you mean?

Accidently requested changes two times.

Can you please change `count()` to `getSize()`. I guess tools like MCG will complain about it.

**Comment by tmotyl** [comment]
> Can you please change `count()` to `getSize()`. I guess tools like MCG will complain about it.

It will add one query more. 
One to get size and one to load (if there are rules).

**Review by fballiano — APPROVED** [review]

**Review by ADDISON74 — APPROVED** [review]

**Pull request merged**
