### PR TITLE
Improved phpdoc of Credis_Client

### PR DESCRIPTION
**Pull request by midlan**
### Description (*)

1. `get` method returns false or string
2. `mGet` method returns false if empty array passed as parameter
3. `del` method accept also array as argument

### Manual testing scenarios (*)

1. `var_dump($credis->get('non-existing-key'));`
2. `var_dump($credis->mGet(array()));`
3. `var_dump($credis->del(array('key1', 'key2')));`

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Comment by midlan** [comment]
I discovered that `del` method accept also array of keys. Updated the doc.

**Comment by colinmollenhour** [comment]
Ideally changes to this library should go to https://github.com/colinmollenhour/credis

**Review by fballiano — APPROVED** [review]

**Comment by fballiano** [comment]
I'm approving but this has to be made in the original repo, since these file will be removed from ours sometime in the future.

**Comment by midlan** [comment]
posted into https://github.com/colinmollenhour/credis/pull/165

**Pull request closed without merging**
