### PR TITLE
Fix broken admin theme

### PR DESCRIPTION
**Pull request by Imaginaerum**
Fix broken admin theme when design/theme/layout config is not NULL

### CODE REVIEW

**Comment by elidrissidev** [comment]
Can you please elaborate on this issue and the fix you applied?

**Comment by Imaginaerum** [comment]
When you change theme layout config, admin theme is broken.

image

Result without patch is:

image

**Review by kkrieger85 — APPROVED** [review]

**Comment by elidrissidev** [comment]
Upon reviewing older pending PRs I found that this PR is a duplicate of #1216 which seems to be addressing the same issue. Sorry.

**Comment by ADDISON74** [comment]
@elidrissidev - From what I checked you closed this PR and made a reference to a reported issue. There is indeed PR #1229, but it is a draft. It has to be seen which of them solves the issue. This one here had an approval.

**Comment by elidrissidev** [comment]
I mistakenly linked to the issue instead of the PR. I will review the first PR this weekend since I've also been dealing with this issue for a long time.

**Pull request closed without merging**
