### PR TITLE
Fixed price filter when search by non-numeric value

### PR DESCRIPTION
**Pull request by sreichel**
### Fixed Issues (if relevant)

1. Fixes OpenMage/magento-lts#3135

### Manual testing scenarios (*)

1. go to admin manage products
2. filter price by non-numeric value

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Review by m-overlund — APPROVED** [review]
Fixes the issue

**Review by ADDISON74 — DISMISSED** [review]

**Review by luigifab — APPROVED** [review]
I can now filter by price with "a" and "b".
Only products with a price of 0 are displayed, instead of an error.

image

**Comment by fballiano** [comment]
this PR has to be rebased on `main`

**Review by m-overlund — APPROVED** [review]

**Comment by fballiano** [comment]
patches will be backported from main to the v19 branch. 1.9.4.x is to be deleted as soon as all PRs are rebased: https://github.com/OpenMage/rfcs/pull/10#issuecomment-1496199663

**Comment by sreichel** [comment]
I know why @colinmollenhour reverted this ... :P

**Review by ADDISON74 — APPROVED** [review]
I checked initially the reported issue. I confirm after testing that this PR solves it. Not only for NULL value but for others values like strings.

@luigifab - Filtering for price from a to b I am getting "No records found."

**Review by luigifab — DISMISSED** [review]
You're right no records found... with main branch, but I still get free products with my store. There may be other changes elsewhere.

**Comment by ADDISON74** [comment]
@luigifab - There is no need to do other checks. I confirm your issue here #3158.

**Comment by sreichel** [comment]
@ADDISON74 confirm this as _intended_. This PR was just to fix the error.

**Comment by ADDISON74** [comment]
@sreichel - I approved this PR created by you precisely because it solves the previously reported issue (#3135). I confirmed a new issue and I created a ticket in this regard, so that another PR can solve this one as well.

**Comment by fballiano** [comment]
Screenshot 2023-04-10 alle 16 16 55

can't merge on this branch

**Review by m-overlund — APPROVED** [review]

**Comment by sreichel** [comment]
Githubs "squash merge" should do the same. Not? Just reverted base branch off created mass.

**Comment by luigifab** [comment]
At localhost, I using `git rebase -i main other_branch`, then I remove lines of unneeded commits, then I change base branch on github, then I `push -f`.

**Comment by colinmollenhour** [comment]
> Githubs "squash merge" should do the same. Not? Just reverted base branch off created mass.

The potential for conflicts that git cannot auto-fix safely between 1.9.4.x and main is very high, but there are also many commit differences between 1.9.4.x and 20.0 (the origin of main) so when you change the PR base it shows hundreds of additional commits.. Unfortuantely I think the manual rebase is the only option, I couldn't find any other way. Creating a new PR with cherry-pick would be another way but I think that just creates more clutter in the issue tracker and divides the conversation.

**Comment by colinmollenhour** [comment]
https://user-images.githubusercontent.com/38738/231567465-2c59ab52-07a2-47d0-8d43-2f28341048ed.mp4

**Review by colinmollenhour — APPROVED** [review]

**Comment by colinmollenhour** [comment]
Ahh, Github actually let me force push on your branch.. So I went ahead and updated this PR.

**Review by luigifab — APPROVED** [review]

**Comment by fballiano** [comment]
@colinmollenhour how do you push? cause I get a 403 when I try

**Comment by colinmollenhour** [comment]
> @colinmollenhour how do you push? cause I get a 403 when I try

You had "mixed roles" so maybe that was the cause.. I removed the conflict favoring the more elevated role so maybe it will work now? You have to be a maintainer of some degree to push on other people's PRs and the author has to have to have selected "Allow edits and access to secrets by maintainers"

**Comment by sreichel** [comment]
> @colinmollenhour how do you push? cause I get a 403 when I try

Mhh, you should be able to push?!? Thanks @colinmollenhour .

**Comment by fballiano** [comment]
@colinmollenhour thanks Colin, sadly didn't fix it:

```
fab@MBP-Fab ~/P/magento-lts (patch-8)> gpp
remote: Permission to loekvangool/magento-lts.git denied to fballiano.
fatal: unable to access 'https://github.com/loekvangool/magento-lts.git/': The requested URL returned error: 403
```

I think it's something regarding the way I authenticate on github but I can't find any doc about that :-\

**Comment by colinmollenhour** [comment]
> I think it's something regarding the way I authenticate on github but I can't find any doc about that :-\

I always use SSH, not sure if that explains it.. I added the origin using the SSH url before pushing.

**Comment by sreichel** [comment]
@fballiano can please backport this?

**Comment by fballiano** [comment]
is this to be considered a significant regression or a vulnerability fix as per https://github.com/OpenMage/rfcs/blob/main/accepted/0002-release-schedule.md?

**Comment by sreichel** [comment]
Y, it is. Dont want to fix an error on admins catalog product grid?

**Comment by fballiano** [comment]
Thats not the point. Anyway you should have the privileges to cherry pick a commit to v19 branch

**Comment by ADDISON74** [comment]
... but we cannot tell those who still use v19 to cherry pick individually PRs.

**Comment by fballiano** [comment]
What? Sven can cherry pick and commit it if he desires, not users. He is a maintainer.

**Comment by sreichel** [comment]
> this PR has to be rebased on `main`

...

**Comment by fballiano** [comment]
you see, you keep reading everything in every post and just creating arguments. I've commented multiple times that I cannot (for some reason) push on other people's repo. so i cannot rebase it on main.

also, I'm more than willing to do that (if I could) for "normal users" but a maintainer (although you made it really clear we were not interested in collaborating with us anymore) can do it himself in 2 minutes.

**Comment by colinmollenhour** [comment]
@sreichel Fabrizio's comment saying it needed to be rebased on main was before it was merged. Anyway, I just cherry-picked it into v19.

In the future, after it has been merged into main if you want it backported please create a new PR for backporting (unless it is an urgent security matter then a maintainer will probably cherry-pick and backport immediately anyway). Perhaps we can use a label like "PATCH" to indicate if a PR should be backported at the time of merging.. 

But on that note, please observe that the RFC does state "functionality: if it doesn't fix a significant regression, it doesn't get a PATCH" - so I think it stretching a bit to justify a backport by that definition in this case. Let's try to adhere to the RFC more strictly going forward. Using the main branch is intended to be the way to take advantage of all of the various improvements whereas v19 is just on critical life support for those that are content with what they have and want minimal change. Of course there is always a third option which is to cherry-pick commits into your own repo to your liking, this is one reason we use Squash and Merge so that you can cherry-pick PRs easily. That's also useful for running unmerged fixes in production while we all argue about the minutia. 🤣

**Comment by colinmollenhour** [comment]
After just running into #3129 I understand this issue more now and it is definitely related to PHP 8+ which I somehow missed before - my apologies for overlooking this.

So this bug was not a regression so to speak but a result of support for a new PHP version - while this is not explicitly covered in the RFC I think it does make sense to treat bugs that are a result of forced PHP updates (7.4 is no longer supported so v19 must support at least PHP 8.0) the same as a regression and backport PATCH updates accordingly to ensure a supported version of PHP is always supported by supported versions of OpenMage.

In my opinion old MAJOR branches (e.g. v19) do *not* need to be updated to support bleeding edge PHP versions so when PHP 8.0 is EOL and PHP 8.3 is released on 26 Nov 2023, v19 should continue to receive updates to support PHP 8.1 and 8.2 (since it was already claimed to be supported at one point) but if PHP 8.3 requires significant updates these would not be considered PATCH updates so v19 will not support PHP 8.3.

As an aside, the single-command `dev/openmage/install.sh` dev environment was updated to support PHP 8.2 which is also the default.

**Pull request merged**
