### PR TITLE
Add --dev requirement captainhook & initial config

### PR DESCRIPTION
**Pull request by kkrieger85**
Proposal for automated code style linting

- Add [CaptianHook](https://captainhookphp.github.io/captainhook/hooks.html) to `--dev` requirements
- Add [PHPCS Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) to `--dev` requirements
- Add initial config file `captainhook.json` with `pre-commit` action 

- With commiting this changes, the git hook became active and fixes code in `app` folder with PSR2-Rules

Related:

- https://github.com/OpenMage/magento-lts/issues/947
- https://github.com/OpenMage/magento-lts/issues/982

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by kkrieger85** [comment]
@sreichel Just phpcs fixer

Going small steps:
- introduce CaptainHook
- add phpcs fixer

- add more and more dev features ;) (And use one PR for each captainhook integration)

**Comment by sreichel** [comment]
Can you please resolve conflicts?

@colinmollenhour @Flyingmana? Time to review?  Seems this is the PR that fixes most/all CS-issues as suggest in https://github.com/OpenMage/magento-lts/issues/982#issuecomment-632906295 (_Run it on all of the app/code code at once in one huge commit_) ...

With this added one, we can also add pre-commit-hooks to keep code clean .... ?!?

**Comment by kkrieger85** [comment]
@sreichel conflict resolved

**Comment by kkrieger85** [comment]
This PR will always run into conflicting files as this PR brings automated code formatting with it... 
How could we solve this? My Idea: Define a date on which we (personally me) could resolve the conflict and merge this change immediately into the main repo. 

Other ideas?

**Comment by tmotyl** [comment]
I would love to being able to separately review adding hook and fixer configuration from CGL change to the whole codebase.
For the review of CGL changes please  provide commands you run to get the same result as in the patch - so I can validate that the patch doesn't contain anything except from result of cgl-fixer

**Comment by kkrieger85** [comment]
Close as duplicate. See #1264

**Pull request closed without merging**
