### PR TITLE
Delete RELEASE_NOTES.txt

### PR DESCRIPTION
**Pull request by fballiano**
RELEASE_NOTES.txt file was removed because unmaintained.

https://github.com/OpenMage/magento-lts/issues/1465

### CODE REVIEW

**Review by Flyingmana — APPROVED** [review]

**Review by sreichel — APPROVED** [review]

**Comment by fballiano** [comment]
Can we merge this into 20.0? The file is still present there.

Do I have to create another PR?

**Comment by fballiano** [comment]
I created a new PR anyways to speed up the process

**Comment by Flyingmana** [comment]
This will happen automatically as part of the release process during the forward porting from 19 => 20

**Comment by fballiano** [comment]
when will it happen? my previous PR was in february? wouldn't it be better for these kind of merges to happen right away? otherwise the more time passes the more the merge could be problematic.

**Comment by fballiano** [comment]
Novermind my last comment, it was merged in 20.0.8. Sorry for that.

**Pull request merged**
