### PR TITLE
Switched DOCTYPE to HTML5 for adminhtml themes

### PR DESCRIPTION
**Pull request by fballiano**
In https://github.com/OpenMage/magento-lts/pull/3574 @m-overlund suggested to check also the adminhtml templates, this PR is for that reason.

### CODE REVIEW

**Comment by fballiano** [comment]
@ADDISON74 I've added the 3 files but it's better to test the email templates now because that's the most delicate

**Review by ADDISON74 — DISMISSED** [review]

**Comment by ADDISON74** [comment]
I made this change a long time ago in the email templates. There could be problems with very, very old email clients.

**Comment by ADDISON74** [comment]
To be sure, I will check today the modified email template with a very old email client. I guess that Outlook Express shipped with Windows XP could be the right choice.

**Comment by fballiano** [comment]
😅 prehistoric email client 😂

**Comment by ADDISON74** [comment]
Please separate that file from the email template in another PR because discussions are requested. The initial form was not suitable but it works. I have analyzed several email stand-alone clients and online messaging services and none of them use the original and modified version in the HTML part. The goal is to make sure that the message is not considered SPAM because of the chosen format.

**Comment by fballiano** [comment]
@ADDISON74 i've removed it from this PR

**Review by ADDISON74 — APPROVED** [review]

**Review by elidrissidev — APPROVED** [review]

**Pull request merged**
