### PR TITLE
Add gitpod online IDE config

### PR DESCRIPTION
**Pull request by Flyingmana**
Fixes OpenMage/magento-lts#1704

A preview of what changes are currently needed to support gitpod with our development setup.

### CODE REVIEW

**Comment by Flyingmana** [comment]
I needed to change some of our files in a non good way, but with them I got a ready workspace which took a minute to start up and then had the OpenMage homepage ready

**Review by kkrieger85 — DISMISSED** [review]

**Comment by Flyingmana** [comment]
updated the PR to only add new files instead of modifying any of the existing ones (to avoid side effects for now, and allow more flexibility for the initial experimental phase

**Comment by sreichel** [comment]
@Flyingmana how about https://github.com/apps/gitpod-io?

**Comment by Flyingmana** [comment]
oh that looks great. I dont think we need the prebuild part (and its needing a paid plan anyway) but the link on every pull request is very usefull.

**Comment by sreichel** [comment]
@Flyingmana can you please add this app (maybe Dependabot too)?

**Comment by sreichel** [comment]
@Flyingmana i've activated gitpod for my repo and it adds a link (in checks summary) to gitpod for every PR. No configuration needed.

**Comment by Flyingmana** [comment]
gitpod is already added to this repository as far as I see

**Comment by sreichel** [comment]
Mhh, in my repo i have i link to gitpod ...

gitpod

I cant see it here.

**Comment by Flyingmana** [comment]
gitpod is 95% of what is github codespaces.
It has a free tier which so far I never exceeded when tinkering and testing OpenMage things.

Does codespaces have a free tier by now?

But anyway, thanks for updating them, should work the same for gitpod, so will try it out as soon as my internet is working again

**Pull request merged**
