### PR TITLE
Updated composer.json to allow PHP 8.3

### PR DESCRIPTION
**Pull request by kyrena**
### Description

This PR allow to use PHP 8.3 with composer.
The list of changes is small: https://php.watch/versions/8.3

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)
 - [ ] Add yourself to contributors list

### CODE REVIEW

**Comment by elidrissidev** [comment]
Please run `composer update` after modifying `composer.json` to sync up `composer.lock` as well.

**Comment by ADDISON74** [comment]
We have to check what challenges await us in PHP 8.3

https://php.watch/versions/8.3
https://www.zend.com/blog/php-8-3

This PR should also have a note in the README file that we do not guarantee that it works for production. In the case of version 8.2 we still find errors and warnings.

**Comment by fballiano** [comment]
@ADDISON74 in the README we already have "PHP 7.4+ (PHP 8.0 is supported, PHP 8.1 supported but some warnings may be shown/logged, PHP 8.2 is usable but still being tested)" so I think it covers it.

we kinda have to allow this PR otherwise it's not even possible to test with php8.3, I don't think there's any other way

**Comment by ADDISON74** [comment]
For those who are using **DDEV** for testing, PHP 8.3 is available too

https://ddev.readthedocs.io/en/latest/users/configuration/config/#php_version

**Review by ADDISON74 — APPROVED** [review]

**Review by elidrissidev — APPROVED** [review]

**Comment by kyrena** [comment]
Yes sorry, I saw `composer update`, but I forgot.

**Pull request merged**
