### PR TITLE
Fix possible option id/label collisions in getOptionId()

### PR DESCRIPTION
**Pull request by edannenberg**
See https://gist.github.com/edannenberg/15c0eddfddad40eca32793708f67c331 for details.

### CODE REVIEW

**Comment by colinmollenhour** [comment]
A fix which for all intents and purposes is completely valid yet does *potentially* break backwards compatibility.. In my opinion these kinds of bugs are worth fixing if there is a very low probability of actually causing any harm, but I suspect others will want to stay by the more strict rule of no BC-breaking changes..

The only time this should break BC is if some code were to pass the option_id to getOptionId and expect back the same.. That makes no sense whatsoever since you would be using this method to get the value that you already have. So it is an absolutely terrible API.

However, it would be possible to half-fix the issue without completely breaking BC.. Like so:

```php
    public function getOptionId($value)
    {
        foreach ($this->getAllOptions() as $option) {
            if (strcasecmp($option['label'], $value)==0) {
                return $option['value'];
            }
        }
        // Keep support for the senseless behavior:
        foreach ($this->getAllOptions() as $option) {
            if ($option['value'] == $value) {
                return $option['value'];
            }
        }
        return null;
    }
```

Personally, I would accept this PR as-is though...

**Comment by alexkirsch** [comment]
I agree with you Colin;  I can not see an valid reason for returning the value that was passed in..   This looks like a bug to me.

I am okay with merging this PR as is.

**Comment by tmotyl** [comment]
Could we somehow detect the edge case and log the about breaking change in the log?

**Comment by edannenberg** [comment]
@tmotyl Not really, I guess we could log a notice before returning `null` but then again the fix only breaks pants-on-head silly code. Shouldn't be an issue in practice.

**Comment by colinmollenhour** [comment]
@Flyingmana I assume you mean if a value was matched *and* no label was matched?

**Comment by Flyingmana** [comment]
actually I dont know.
Because it would return the first find in original code. I first thought it may be good to log a notice when this wrong case would happen, but its probably unlikely that wrong usage AND a collision appear together, so your interpretation is I think the better one.

**Comment by edannenberg** [comment]
More importantly it minimizes false positive log spamming. Updated the PR, let me know if you want different wording.

**Comment by edannenberg** [comment]
We might as well use the fix proposed by @colinmollenhour then and save people the hassle. Full BC without possible collisions.

**Comment by colinmollenhour** [comment]
@LeeSaferite  and @Flyingmana are you on board with my proposed solution (first comment)? That is, two loops, second one keeps BC, no config flag added.

**Comment by Flyingmana** [comment]
yes

**Comment by edannenberg** [comment]
Still waiting for approval from @LeeSaferite before I update the PR again. In case my last edit went unnoticed: Using @colinmollenhour's solution could still lead to collisions when passing option ids. IMO this is a case where breaking BC is justified, it's clearly a bug and not a feature.

**Comment by LeeSaferite** [comment]
I was unaware this was waiting on input from me for almost a year. Yikes. FWIW, things like this just need 2 approvals to get merged.

**Comment by edannenberg** [comment]
And I was unaware this PR still existed, accidentally deleted the branch while cleaning up my fork.

**Pull request merged**
