### PR TITLE
Added getter for Mage_Adminhtml_Block_Widget_Grid_Column::getType()

### PR DESCRIPTION
**Pull request by sreichel**
### Description (*)

Update for php81

### Related Pull Requests

- OpenMage/magento-lts#2586 ... search for `getType` in changed files

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Review by Flyingmana — APPROVED** [review]

**Comment by sreichel** [comment]
This one got approved w/ phpstan errors ...

**Comment by fballiano** [comment]
I didn’t review just because it was set to draft (and I waa a bit busy these last few days)

**Comment by sreichel** [comment]
I set it to draft b/c phpstan errors ... No need to review at this stage :+1:

**Comment by elidrissidev** [comment]
I suggest closing this and reopening it. I tried editing the file to fix phpstan error but can't do it.

**Pull request closed without merging**
