### PR TITLE
Dashboard - Top 5 Search Terms link issue

### PR DESCRIPTION
**Pull request by ADDISON74**
Go to Dashboard page in Backend and take a look to the following blocks **Last 5 Search Terms** and **Top 5 Search Terms**. 

Now place your mouse pointer over a search term in **Last 5 Search Terms** list and take a look to the URL. Here is the link in my case https://www.mydomain.tld/index.php/admin/catalog_search/edit/id/41/key/5874688c27ec9781d42bacfd92420f0e/

Now place your mouse pointer over a search term in **Top 5 Search Terms** list and take a look to the URL. Here is the link in my case https://www.mydomain.tld/index.php/admin/catalog_search/edit/key/5874688c27ec9781d42bacfd92420f0e/

The last link has an issue. Comparing with the first one which redirects correctly to edit the search term this one is opening the page to create a new search query not editing the search term. This is happening because the link has missing two parameters id and id_number between /edit/ ... /key/

This PR fixes this issues and closes issue #1310 .

### CODE REVIEW

**Review by kiatng — DISMISSED** [review]
Tested and worked.

**Review by elidrissidev — DISMISSED** [review]
Tested, working well.

**Comment by Flyingmana** [comment]
@ADDISON74 be careful with the source branches for the PRs, this one contained also the changes from https://github.com/OpenMage/magento-lts/pull/1920

I still merged it, as we already merged the other one

**Comment by ADDISON74** [comment]
I know that but I did not want to close this PR. I will try to avoid such mistake in the future.

**Pull request merged**
