### PR TITLE
Follow coding-standard PER-CS2.0

### PR DESCRIPTION
**Pull request by sreichel**
### Description (*)

We run coding-rule checks since ages, but we never followed a common standard, We had some PSR2/12-rules for PHPCS, but settings for php-cs-fixer where different.

- follow https://www.php-fig.org/per/coding-style/
- use ONLY php-cs-fixer for codestyle-checks
- use PHPCS for ECG/PhpCompatibility checks

### CODE REVIEW

**Comment by addison74** [comment]
I wanted to check all the changes in the more than 3000 files. Although I have an extremely high-performance system, Chrome threw in the towel several times. The page already consumes 2.5 GB of RAM and is growing.

**Comment by sreichel** [comment]
No need to check manually.

Its only about code styling.

- adding comma to last array-element if its a multiline-list
- shorten empty classes
- ...

**Comment by sreichel** [comment]
> Chrome threw in the towel several times. The page already consumes 2.5 GB of RAM and is growing.

Sorry for offopic, but what are you working with?

I only have an Intel Xeon E3-1231 with 16GB RAMand everything runs smooth.

**Comment by kiatng** [comment]
Ref https://www.php.net/manual/en/functions.arguments.php, trailing comma only supports in PHP8.

I can understand trailing comma is to reduce version control diff noise but this PR actually add more noise. It's good for project under development, I don't see benefit applying here. Why is it good for OpenMage?

**Comment by sreichel** [comment]
> Ref https://www.php.net/manual/en/functions.arguments.php, trailing comma only supports in PHP8.

This is for funtion parameters only. (i am doing all that with php7.4 to avoid such errors)

> Why is it good for OpenMage?

We only had a couple of rules. Some from PSR2, some from PRS12. Not fish, not meat.

> [PSR-12](https://www.php-fig.org/psr/psr-12/) was accepted in 2019 and since then a number of changes have been made to PHP which have implications for coding style guidelines. Whilst [PSR-12](https://www.php-fig.org/psr/psr-12/) is very comprehensive of PHP functionality that existed at the time of writing, new functionality is very open to interpretation. This PER, therefore, seeks to clarify the content of PSR-12 in a more modern context with new functionality available, make the errata to PSR-12 binding and further update it according to new data and language changes.

https://www.php-fig.org/per/coding-style/

**Comment by sreichel** [comment]
> I can understand trailing comma is to reduce version control diff noise

Trailing comma is for better programming workflow!

You are on the last element of an array ... you hit `ctrl` + `d` to duplicate this line - to add an entry. How often you had to go to previous line to add that comma?

**Comment by kiatng** [comment]
I can't add comment in the code, my browser crashed. But I tested [here](https://onlinephp.io/c/0b1cf) for PHP7.4, which throws error.

**Comment by sreichel** [comment]
> But I tested [here](https://onlinephp.io/c/0b1cf) for PHP7.4, which throws error.

This is NOT part of the PR.

Trailing comma ...

Old ....

```php
$a = [
    [],
    [] # no trailing comma
];
```

New ...

```php
$a = [
    [],
    [], # trailing comma
];
```

**Comment by kiatng** [comment]
It's this, I managed to screenshot before my browser crashed:
image

**Comment by sreichel** [comment]
Thats not that problem ... in https://onlinephp.io/c/0b1cf the error is on line 2. The comma in test(), not that comma in explode().

**Comment by sreichel** [comment]
> It's this, I managed to screenshot before my browser crashed:

try https://patch-diff.githubusercontent.com/raw/OpenMage/magento-lts/pull/4372.diff

**Comment by sreichel** [comment]
Aggree - but for another PR. (requires some other changes. Delete workflow. Update CR. ...)

**Comment by sreichel** [comment]
Update config to work with php7.

**Comment by sreichel** [comment]
> I'm on-board with PER-CS2.0, but the Copyright year updates are annoying

There will be no more this year :smile: 

Please approvel. (should be part of next release)

**Review by addison74 — DISMISSED** [review]

**Review by kiatng — APPROVED** [review]

**Comment by sreichel** [comment]
I :heart:  these conficts.

**Review by kiatng — DISMISSED** [review]

**Comment by sreichel** [comment]
...

**Review by kiatng — APPROVED** [review]

**Review by addison74 — APPROVED** [review]

**Pull request merged**
