### PR TITLE
Small improvements to RWD's "toolbar"

### PR DESCRIPTION
**Pull request by fballiano**
At some resolutions the toolbar is shown with the pager on a new row:

Schermata 2022-09-30 alle 14 53 42

So I decided to do a bit of a cleanup of that part of the CSS, starting to use flexbox and removing everything that I could and that was not necessary anymore, the result is this (on a modern browser)

Schermata 2022-09-30 alle 14 09 44

and I still checked that IE8 works:

Schermata 2022-09-30 alle 14 09 32

To compile the CSS I used "compass compile" which, as far as I know, should be the right way to do it. This is the reason why there are quite some differences in the generated CSS.

### CODE REVIEW

**Comment by ADDISON74** [comment]
If it will be merged and taken to v20 we must not lose sight of the fact that in this version the support for IE has been removed. If there is a strict commit for IE modification then it won't be a problem. I have not checked, but such changes should be considered in the future to be easily identified.

**Comment by Flyingmana** [comment]
Is this a big enough issue for v19 to need a fix?

**Comment by fballiano** [comment]
no, but @sreichel wouldn't like it in v20 only :-D

**Comment by fballiano** [comment]
if it was for me, you know, i'll do everything v20

**Comment by elidrissidev** [comment]
I applied your change butunfortunately it seems that it conflicts with "List Mode" controls. You can test it by enabling it in: Configuration -> Catalog -> Frontend -> List Mode.


image

**Comment by fballiano** [comment]
interesting, I'll check it out asap!

**Pull request closed without merging**
