### PR TITLE
Pass delimiter char to preg_quote

### PR DESCRIPTION
**Pull request by MarcinNowakMacopedia**
### Description (*)
The most common used delimiters in PHP are /@#~,
which are not escaped by default
(by default preg_quote escapes .\+*?[^]$(){}=!<>|:-).

### CODE REVIEW

**Comment by Sdfendor** [comment]
There is #2047 and there is this PR. Which one is the correct one and which is the duplicate? Can you please abandon one of the PRs @MarcinNowakMacopedia?

**Comment by fballiano** [comment]
duplicate of https://github.com/OpenMage/magento-lts/pull/2047 (which is on v19 branch), there's no need for a PR on both branches because v19 is always merged into v20 :-)

**Comment by MarcinNowakMacopedia** [comment]
> duplicate of #2047 (which is on v19 branch), there's no need for a PR on both branches because v19 is always merged into v20 :-)
sorry I didn't know that :-)

**Comment by fballiano** [comment]
not a problem don't worry :-)

**Pull request closed without merging**
