### PR TITLE
Remove end class comment

### PR DESCRIPTION
**Pull request by luigifab**
### Description

This remove all? useless `// Class xyz End` comments.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Review by ADDISON74 — APPROVED** [review]

**Review by fballiano — APPROVED** [review]

**Review by kiatng — APPROVED** [review]

**Review by tmotyl — APPROVED** [review]

**Review by Sdfendor — APPROVED** [review]

**Comment by luigifab** [comment]
Wow, too much approve today! :)

**Comment by ADDISON74** [comment]
> Wow, too much approve today! :)

... and it was merged after half a day.

**Comment by luigifab** [comment]
I think you have "Merge pull request" instead of "Squash and merge"?
I think I read that some days ago on another PR.

If true, perhaps admin can uncheck to avoid this mistake:
image

**Comment by fballiano** [comment]
Yes we should always squash and merge 😊

**Comment by ADDISON74** [comment]
I am reverting the PR for being squash and merge. Sorry for merging without squash.

**Comment by justinbeaty** [comment]
Sometimes it's okay to not squash and merge if the PR author was intentional in making separate commits. It may need to be a judgement call by the maintainer. Also offtopic, but thanks to everyone for the recent work and new release. :tada:

**Pull request merged**
