### PR TITLE
Fixes configurable swatch color picker in legacy admin theme

### PR DESCRIPTION
**Pull request by sreichel**
### Description (*)

... one error left in Chrome. (maybe someone has an idea to fix it - i have not)

### Related Pull Requests
1. See OpenMage/magento-lts#3686

### Fixed Issues (if relevant)

1. Fixes OpenMage/magento-lts#4217

swatch

### CODE REVIEW

**Comment by sreichel** [comment]
@empiricompany ... maybe another improvement ... take the given color-string and automatically add the swatch-color.

https://stackoverflow.com/questions/48484767/javascript-check-if-string-is-valid-css-color

**Comment by ADDISON74** [comment]
Only one warning remains in the Chromium browsers console.

That delete button should be 21px height, to keep the same proportion with similar buttons (e.g. the ones in Product Edit > Custom Options). Even the [ x Delete] button at the end of the row is 21px.

**Review by ADDISON74 — APPROVED** [review]

**Comment by ADDISON74** [comment]
If you solve the warning it will be perfect.

**Comment by sreichel** [comment]
Nothing is perfect :P

I tried, but its not worth the time atm. Sorry.

**Comment by sreichel** [comment]
@empiricompany can you please check this? Re-used your code, only change template for legacy theme and added default value for swatch (to get rid of the browser errors)

**Review by kiatng — APPROVED** [review]

**Pull request merged**
