### PR TITLE
Replaced join() with implode()

### PR DESCRIPTION
**Pull request by sreichel**
Alias method ...

### CODE REVIEW

**Comment by tmotyl** [comment]
please exclude whitespace changes (just join->implode) so it doesn't conflict with other cleanup changes

**Comment by kkrieger85** [comment]
I don't understand the relation between https://github.com/OpenMage/magento-lts/pull/986/commits/8661e1adadb8dd5f5182c99e829d79ccec7585e7 and this ticket

**Comment by sreichel** [comment]
> 
> 
> I don't understand the relation between [8661e1a](https://github.com/OpenMage/magento-lts/commit/8661e1adadb8dd5f5182c99e829d79ccec7585e7) and this ticket

I have just resolved conflicts.

**Comment by sreichel** [comment]
> 
> 
> LGTM now

Cause of possible conflicts i'd leave it as draft for now, till doc changes are in ...

**Pull request closed without merging**
