### PR TITLE
Lazy load contributors images

### PR DESCRIPTION
**Pull request by luigifab**
### Description

This is an old bug. Each day I go to the [home](https://github.com/OpenMage/magento-lts) of the repository, my browser download 10 MB of avatars images. This is not acceptable. This PR add lazy attribute to lazy load images.

166199675-0a3a44ee-b49a-4e09-80c4-c3690f7ea396

For now, this is not working, Github remove the attribute.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by fballiano — APPROVED** [review]

**Review by Flyingmana — APPROVED** [review]

**Comment by fballiano** [comment]
Should I merge this @luigifab? I'm asking since the PR is still in draft.

**Comment by luigifab** [comment]
Oh yes, I sent a request to Github to get help for the attribute.

**Comment by elidrissidev** [comment]
Sadly it looks like GitHub is stripping the `loading` attribute from images, so they're still loading eagerly.

**Comment by Flyingmana** [comment]
huh, that might be something we could get fixed upstream.

**Comment by elidrissidev** [comment]
Here's [an issue I created on GitHub's flavored markdown repo](https://github.com/github/cmark-gfm/issues/262). Doesn't look to be much active though.

**Pull request merged**
