### PR TITLE
20.0 Newsletter Subscription Success - No Emails sent #822 

### PR DESCRIPTION
**Pull request by hejhog**
#822 
The above is related to Guest subscribers but also has the following "issues".
No check to evaluate if the the guest email is already in the subscriber list.
No check to evaluate if the guest has already confirmed.

The following resolves the issue:
/app/code/core/Mage/Newsletter/controllers/SunscribeController.php
Add to public function newAction() approx line 56

                //Check if  Guest User Email already exists
                $existingSubscriber = Mage::getModel('newsletter/subscriber')->loadByEmail($email)->getId();
                if (!empty($existingSubscriber) && !$customerSession->isLoggedIn()):
                    Mage::throwException($this->__('This email address is already registered.'));
                endif;

Replace public function confirmAction() with:

    public function confirmAction()
    {
        $id    = (int) $this->getRequest()->getParam('id');
        $code  = (string) $this->getRequest()->getParam('code');

        if ($id && $code) {
            $subscriber = Mage::getModel('newsletter/subscriber')->load($id);
            $session    = Mage::getSingleton('core/session');

            
            if ($subscriber->getStatus() == $subscriber::STATUS_SUBSCRIBED){ //Check if already confirmed
                $session->addNotice($this->__('This email address is already confirmed.'))
                      
            } elseif($subscriber->getId() && $subscriber->getCode()) {
                    if($subscriber->confirm($code)) {
                        $status = $subscriber->sendConfirmationSuccessEmail(); //Send Success email
                        $session->addSuccess($this->__('Your subscription has been confirmed.'));
                    } else {
                        $session->addError($this->__('Invalid subscription confirmation code.'));
                    }
            } else {
                $session->addError($this->__('Invalid subscription ID.'));
            }
        }

        $this->_redirectUrl(Mage::getBaseUrl());
    }

### CODE REVIEW

**Comment by fballiano** [comment]
it seems there's a problem with the PR, there are 680 modified files

**Comment by hejhog** [comment]
Someone requested I create a pull request for this issue in the comments.  Never created one before.  Pasted the issue into the comment section and posted - I am not sure why there are so many requested file changes.  The only file that needs amending is /app/code/core/Mage/Newsletter/controllers/SunscribeController.php

**Comment by elidrissidev** [comment]
The reason why all those files show as changed is because you created the PR from  `20.0` branch in your own fork.

**Comment by ADDISON74** [comment]
Do we have PR recreated somewhere?

**Comment by hejhog** [comment]
It was recreated but seems to have disappeared.  Probably due to my lack of ability in creating a PR!!

**Comment by ADDISON74** [comment]
@hejhog - can you post your PR here and @fballiano will create one for you? Just past the code between code markup.

**Comment by fballiano** [comment]
@ADDISON74 we already have the code in issue #822 but it's incomplete cause it's old

**Comment by ADDISON74** [comment]
It all right then.

**Comment by hejhog** [comment]
<?php
/**

    Magento
    NOTICE OF LICENSE
    This source file is subject to the Open Software License (OSL 3.0)
    that is bundled with this package in the file LICENSE.txt.
    It is also available through the world-wide-web at this URL:
    http://opensource.org/licenses/osl-3.0.php
    If you did not receive a copy of the license and are unable to
    obtain it through the world-wide-web, please send an email
    to license@magento.com so we can send you a copy immediately.
    DISCLAIMER
    Do not edit or add to this file if you wish to upgrade Magento to newer
    versions in the future. If you wish to customize Magento for your
    needs please refer to http://www.magento.com for more information.
    @category Mage
    @Package Mage_Newsletter
    @copyright Copyright (c) 2006-2020 Magento, Inc. (http://www.magento.com)
    @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
    */

/**

    Newsletter subscribe controller

    @category Mage

    @Package Mage_Newsletter

    @author Magento Core Team core@magentocommerce.com
    /
    class Mage_Newsletter_SubscriberController extends Mage_Core_Controller_Front_Action
    {
    /*
        Use CSRF validation flag from newsletter config
        */
        const XML_CSRF_USE_FLAG_CONFIG_PATH = 'newsletter/security/enable_form_key';

    /**

        New subscription action
        */
        public function newAction()
        {
        if (!$this->_validateFormKey()) {
        $this->_redirectReferer();
        return;
        }

        if ($this->getRequest()->isPost() && $this->getRequest()->getPost('email')) {
        $session = Mage::getSingleton('core/session');
        $customerSession = Mage::getSingleton('customer/session');
        $email = (string) $this->getRequest()->getPost('email');

        try {
            if (!Zend_Validate::is($email, 'EmailAddress')) {
                Mage::throwException($this->__('Please enter a valid email address.'));
            }

            if (Mage::getStoreConfig(Mage_Newsletter_Model_Subscriber::XML_PATH_ALLOW_GUEST_SUBSCRIBE_FLAG) != 1 &&
                !$customerSession->isLoggedIn()) {
                Mage::throwException($this->__('Sorry, but administrator denied subscription for guests. Please <a href="%s">register</a>.', Mage::helper('customer')->getRegisterUrl()));
            }

            //Check if Guest User Email already exists
            $existingSubscriber = Mage::getModel('newsletter/subscriber')->loadByEmail($email)->getId();
            if (!empty($existingSubscriber) && !$customerSession->isLoggedIn()) {
                Mage::throwException($this->__('This email address is already registered. Please contact us if you require any assistance.'));
            }

            $ownerId = Mage::getModel('customer/customer')
                    ->setWebsiteId(Mage::app()->getStore()->getWebsiteId())
                    ->loadByEmail($email)
                    ->getId();
            if ($ownerId !== null && $ownerId != $customerSession->getId()) {
                Mage::throwException($this->__('This email address is already assigned to another user.'));
            }

            $status = Mage::getModel('newsletter/subscriber')->subscribe($email);
            if ($status == Mage_Newsletter_Model_Subscriber::STATUS_NOT_ACTIVE) {
                $session->addSuccess($this->__('Confirmation request has been sent.'));
            } else {
                $session->addSuccess($this->__('Thank you for your subscription.'));
            }
        } catch (Mage_Core_Exception $e) {
            $session->addException($e, $this->__('There was a problem with the subscription: %s', $e->getMessage()));
        } catch (Exception $e) {
            $session->addException($e, $this->__('There was a problem with the subscription.'));
        }

        }
        $this->_redirectReferer();
        }

    /**

        Subscription confirm action
        */
        public function confirmAction()
        {
        $id = (int) $this->getRequest()->getParam('id');
        $code = (string) $this->getRequest()->getParam('code');

        if ($id && $code) {
        $subscriber = Mage::getModel('newsletter/subscriber')->load($id);
        $session = Mage::getSingleton('core/session');

         if ($subscriber->getStatus() == $subscriber::STATUS_SUBSCRIBED){ //Check if already confirmed
             $session->addNotice($this->__('This email address is already confirmed.'))

         } elseif($subscriber->getId() && $subscriber->getCode()) {
                 if($subscriber->confirm($code)) {
                     $status = $subscriber->sendConfirmationSuccessEmail(); //Send Success email
                     $session->addSuccess($this->__('Your subscription has been confirmed.'));
                 } else {
                     $session->addError($this->__('Invalid subscription confirmation code.'));
                 }
         } else {
             $session->addError($this->__('Invalid subscription ID.'));
         }

        }

        $this->_redirectUrl(Mage::getBaseUrl());
        }

    /**

        Unsubscribe newsletter
        */
        public function unsubscribeAction()
        {
        $id = (int) $this->getRequest()->getParam('id');
        $code = (string) $this->getRequest()->getParam('code');

        if ($id && $code) {
        $session = Mage::getSingleton('core/session');
        try {
        Mage::getModel('newsletter/subscriber')->load($id)
        ->setCheckCode($code)
        ->unsubscribe();
        $session->addSuccess($this->('You have been unsubscribed.'));
        } catch (Mage_Core_Exception $e) {
        $session->addException($e, $e->getMessage());
        } catch (Exception $e) {
        $session->addException($e, $this->('There was a problem with the un-subscription.'));
        }
        }
        $this->_redirectReferer();
        }

    /**
        Check if form key validation is enabled in newsletter config.
        @return bool
        */
        protected function _isFormKeyEnabled()
        {
        return Mage::getStoreConfigFlag(self::XML_CSRF_USE_FLAG_CONFIG_PATH);
        }
        }

**Comment by hejhog** [comment]
Download SubscribeController.php from 26th May 2022 and updated the code.  Please note I have not had time to test.

**Pull request closed without merging**
