### PR TITLE
PHP 7 support

### PR DESCRIPTION
**Pull request by drobinson**
Credit to Inchoo (https://github.com/Inchoo/Inchoo_PHP7) for the work - this is just a core implementation of the PHP 7 support module.

### CODE REVIEW

**Comment by Flyingmana** [comment]
in generell I support this changes, they dont have a major downside.

But please explain the changes of `app/code/core/Mage/Sales/etc/config.xml`

**Comment by MrGekko** [comment]
I am using this module to get PHP 7 support, so I support adding this.

The changes to `app/code/core/Mage/Sales/etc/config.xml` where orriginally made by:
> @durzel make sorting more consistent
https://github.com/danslo/Rubic_FixTotalSorting/commit/086ca9941285cdcbc2a347086148b28cd381b5a6

Hope that helps...

**Comment by Flyingmana** [comment]
I see, than I would like to see this excluded from the PR, as it is not related to php7 support, so it can/needs to be discussed separate.

**Comment by drobinson** [comment]
I made an assumption that PHP 7 also rewrote the sorting algorithm to make it stable (and therefore required this explicit calculation ordering) but I did not test it without this. I'll check it out.

**Comment by durzel** [comment]
PHP7 does change the sort behaviour. In my experience on an install that otherwise had no bespoke sorting code moving from PHP 5.3.3 to PHP 7 resulted in a calculation issue in the cart. 

This is discussed here:
http://stackoverflow.com/questions/34281113/the-different-behavior-of-the-function-uasort-in-php-5-5-and-php-7-0

..among other places.

**Comment by Flyingmana** [comment]
ok, that makes sense. In this case I give my ok. 
:+1:

**Comment by seansan** [comment]
Just to confirm - this Magento LTS branch 1.9.2.4 has php 7 support?

**Comment by tmotyl** [comment]
True. I'm using it on some projects already.

**Comment by luchiano1** [comment]
1

**Pull request merged**
