### PR TITLE
Bugfix to make exchange rate data with fixer.io work again

### PR DESCRIPTION
**Pull request by dbachmann**
### Description (*)
A customer of mine wanted to update the exchange rates in his shop. I wanted to use fixer.io but I got an error. So I looked into the code and looked into the documentation of fixer which is now part of apilayer.com. I changed the api url and a parameter name. When I entered my api key and tested this, everything worked like charm and I got the correct exchange rates.

### Manual testing scenarios (*)

1. Register at https://apilayer.com and get an api key
2. Go to System > Configuration > General > Currency Setup > Fixer API / Apilayer.com. Enable this and enter your api access key and save. 
3. Go to System > Manage Currency > Rates and select "Fixer API / Apilayer.com" as import service. Click on import.

### CODE REVIEW

**Comment by elidrissidev** [comment]
I'm looking at the documentation at https://fixer.io/documentation, and I can see they still mention the current URL in their examples. What error did you get when using it?


Screen Shot 2022-11-08 at 1 10 58 PM

**Comment by dbachmann** [comment]
@elidrissidev I've tried this url at first but it didn't work. When you want to get an api key from fixer.io you will be redirected to apilayer.com. So you have to use the new url.

**Comment by sreichel** [comment]
Tested and confirmed. @dbachmann  opened PR at your repo.

**Review by sreichel — APPROVED** [review]

**Review by fballiano — APPROVED** [review]

**Comment by dbachmann** [comment]
@sreichel Tested your code. Works perfectly. Good job.

**Pull request merged**
