### PR TITLE
removed Mage_Compiler

### PR DESCRIPTION
**Pull request by dng-dev**
Removed Mage_Compiler #525

### CODE REVIEW

**Comment by LeeSaferite** [comment]
Does it make sense to fix the autoloader at the same time?

It should be returning a false if the class isn't found. That would allow people to easily use composer autoloader in conjunction.

**Comment by dng-dev** [comment]
Will look over this later and implement it.

Am Freitag, 21. September 2018 schrieb Lee Saferite :

**Comment by dng-dev** [comment]
@seansan as mentioned i added the missing return statement for the autoloader.

**Comment by Flyingmana** [comment]
the __autoload function can get deleted completely. Since the Varien Autoloader uses the SPL autoloader, this one is never in use.

**Pull request merged**
