### PR TITLE
Fixed issue #2001, EAV datetime attribute can't save time.

### PR DESCRIPTION
**Pull request by kiatng**
### Description (*)
See issue #2001.

### Fixed Issues (if relevant)

1. Fixes OpenMage/magento-lts#2001

### Manual testing scenarios (*)
1. Add a catalog attribute with property `frontend_input` set to `datetime`.
2. Add the attribute to a Attribute Set `default`.
3. In backend product page, try saving the attribute with date and time value.
4. Without this commit, the time is not saved.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)
 - [ ] Add yourself to contributors list

### CODE REVIEW

**Comment by Hanmac** [comment]
there two things related to this Issue:
* `Mage_Eav_Model_Entity_Attribute_Frontend_Datetime` doesn't output the time, maybe make it depend on the input type?
* in Backend Attribute Configuration you can't choose the Frontend Input, should probably be added to Mage_Eav_Model_Adminhtml_System_Config_Source_Inputtype too

**Comment by kiatng** [comment]
> there two things related to this Issue:
> 
> * `Mage_Eav_Model_Entity_Attribute_Frontend_Datetime` doesn't output the time, maybe make it depend on the input type?
> * in Backend Attribute Configuration you can't choose the Frontend Input, should probably be added to `Mage_Eav_Model_Adminhtml_System_Config_Source_Inputtype` too

I think these can be in separate PRs. The broader the PR, the more time is required to get reviewed and merged.

**Comment by elidrissidev** [comment]
@Hanmac If the `datetime` input type isn't available while creating an attribute from the admin panel, then how did you come across this issue the first time? Or did you modify it manually from the database?

**Review by fballiano — APPROVED** [review]

**Comment by fballiano** [comment]
I checked this topic and, because in the catalog_product_entity_datetime the value is a datetime (with 00:00:00) saving a real datetime value doesn't introduce any BC so... approved

**Review by ADDISON74 — APPROVED** [review]

**Comment by fballiano** [comment]
> I checked this topic and, because in the catalog_product_entity_datetime the value is a datetime (with 00:00:00) saving a real datetime value doesn't introduce any BC so... approved

mmm unless somebody is expecting to have "00:00:00" in the database :-\ mah

**Comment by kiatng** [comment]
> > I checked this topic and, because in the catalog_product_entity_datetime the value is a datetime (with 00:00:00) saving a real datetime value doesn't introduce any BC so... approved
> 
> mmm unless somebody is expecting to have "00:00:00" in the database :-\ mah

That somebody should check that the attribute's `frontend_input` is `datetime`. If it's a `date`, then his/her expectation is valid.

I tested again for `frontend_input` = `date`, it was saved correctly:
image
Saved as:
```
  ["test_at"] => string(19) "2022-06-08 03:06:00"
  ["test_on"] => string(19) "2022-06-08 00:00:00"
```

**Pull request merged**
