### PR TITLE
Updated Code of Conduct to ver 2.1

### PR DESCRIPTION
**Pull request by kiatng**
### Description (*)
Current version is 1.4, time to update. Both versions have 5 standards, the major change is the addition of "apology":

> Accepting responsibility and apologizing to those affected by our mistakes, and learning from the experience

### CODE REVIEW

**Review by elidrissidev — APPROVED** [review]

**Comment by ADDISON74** [comment]
Just a personal opinion. At the beginning of August, when there were disputes of ideas between several members, those who have full rights in the organization and maintainers decided that no changes to the CoC are necessary. 

> The CoC ([Code of Conduct](https://github.com/OpenMage/magento-lts?tab=coc-ov-file)) is agreed to be acceptable and no changes are necessary at this time.

Maybe updating the CoC should have been preceded by an internal discussion first.

**Comment by empiricompany** [comment]
I agree, the resolution of August, for which we voted proposed by @colinmollenhour 

We had decided that it was not necessary to change the CoCs and on point 2 @ADDISON74 and @sreichel, for repeated violations of the CoC, they were confined to the state of triage, BUT after a short time all the powers to do everything have been restored and actually decide on all PRs the last word, close, open moderate and can  delete comments as before.

A decision had been made and now we are going back, breaking the promises made

**Comment by kiatng** [comment]
It was not my intention to revisit the 3 _Resolutions_ on the _OpenMage Damage Control - July 29, 2024_. 

> The CoC ([Code of Conduct](https://github.com/OpenMage/magento-lts?tab=coc-ov-file)) is agreed to be acceptable and **no changes are necessary at this time**.

The above was the first clause of Resolution 1. I reviewed the clause as best I can at the time. That's when I found out there is a newer CoC. Before I agree to it, I proposed to Colin to adopt the latest [version 2.1](https://www.contributor-covenant.org/version/2/1/code_of_conduct/). He persuaded me to not do that **at that time**. I would like to think that that time has passed, let us move forward.

> A decision had been made and now we are going back, breaking the promises made

If this PR breaks things, then we should stick with the current version 1.4, or change the PR to suit our needs. I may have missed something, please help me see.

Colin intended for us to start with a clean slate. I agree. I believe the new version can help us in this direction. It has 3 major things not in the current version:

1. The incorporation of apology in the _Standards_. 
2. The advise on communicating the reasons for moderation decisions in the _Responsibilities_.
3. New section on _Enforcement Guidelines_, which has 4 phases. The first phase _Correction_ is a **private**, written warning with **explanation** (thing 2) and may request a public apology (thing1). The second phase _Warning_ is serious, it prohibits all interactions for a specified time period, further violations of which could lead to ban (phases 3 and 4). 

I believe this version provides more clarity for the "authority" on how to do things and the "rights" of the offenders to undergo the 4 phases. 

This version is not perfect, it does not cover all the scenarios that happened in OpenMage. For example, there is no phase 5. If you object to this PR, if you can, please express your opinions without referencing old wounds.

**Comment by kiatng** [comment]
I put it in draft until it has "enough" approvals.

**Comment by empiricompany** [comment]
As for the update of the CoC, I agree with you.

However, I just wanted to highlight that it makes no sense to have a CoC if it's not followed, and here, there are no rules. I took the opportunity to write it here since I tried to contact @colinmollenhour privately on Discord a few days ago, but he hasn't responded.

The management of this community is very unclear, and there is no respect for any rules; a few people make all the decisions, and it certainly doesn't encourage contribution.
These kinds of discussions, which for me are just as important as decisions about the code, are silenced or hidden in complete silence from all the maintainers. It's really frustrating to contribute in such an environment where there's no respect for the work of others.

**Comment by kiatng** [comment]
@empiricompany You are on points! In summary

1. Community leaders. With the passing of time, we have only Colin now. We are so lucky, if he didn't step up, things would be quite different. Now that we are somewhat stabilize, we should start thinking so that we can maintain stability in the long run.
2. Enforcement. We need to establish legitimacy, if we are perceived as a dictator, for example, decisions made would be question. 
3. Role of maintainers. With inactive leaders, maintainers need to step up. As a maintainer myself, it was very unclear to me what I was to do with CoC. I read it once and promptly forgot everything. With this PR, I hope to bring more clarity for the maintainers  on how to do enforcement. It's not enough to say someone violate CoC. Reasons for moderation decisions must be communicated. This helps legitimacy, and hopefully fairness.

In terms of my role on CoC, I failed. I apologized. Onwards, I will do better. I start with this PR. Please review and if you agree this is the way forward, approve it.

**Comment by empiricompany** [comment]
The violation of the CoCs was discussed and voted by the main maintainers who in agreement decided to confine the offenders in the state of triage, but this decision was not respected

So what's the point of having rules?
Let's start from here, then we can improve, but if we votes one thing and then we do another it's a scam

**Comment by colinmollenhour** [comment]
As this is a change of policy and not a simple code change, I don't think it belongs as a PR now but rather as a discussion first, then a PR if agreed.
I am closing the PR for now so it can be discussed here: https://github.com/OpenMage/organizational-internal/discussions/33

**Pull request closed without merging**
