### PR TITLE
Added hadling of allowed_extensions for file uploads in backend's configuration section

### PR DESCRIPTION
**Pull request by eneiasramos**
Added support for tag `allowed_extensions` in file upload in backend system configuration.

### CODE REVIEW

**Comment by kiatng** [comment]
@eneiasramos It will me to review if you can provide the use case.

**Comment by ADDISON74** [comment]
@eneiasramos - Please provide more details about this PR. I have some time to test it.

**Comment by eneiasramos** [comment]
@kiatng @ADDISON74  my dears

The routine here filters the extension of a file being uploaded.

So if I upload a file with an extension different from .pfx, the system will display an error.

A use of case: I use the var folder to store PFX certificates used to communicate with a third party system:

https://github.com/gamuzatech/tolucastore-openmage/blob/f559a0e819a3124599b392fc3c4defe5c3803b68/app/code/local/Gamuza/Brazil/etc/system.xml#L400

image

**Comment by kiatng** [comment]
Somewhat related to PR #4079, extend functionalities of file upload in system config.

**Review by kiatng — APPROVED** [review]
LGTM. I like it.

**Review by fballiano — APPROVED** [review]
tested, working, thank you!

**Comment by eneiasramos** [comment]
@fballiano It's my pleasure. :)

**Pull request merged**
