### PR TITLE
Fixed incorrect datetime in block, ref #1525

### PR DESCRIPTION
**Pull request by sreichel**
### Description (*)

#1525 was added to 20.0 branch (instead of v19).

This PR adds same functionality w/o BC-breaking changes (changed method signatures)

### Related Pull Requests

1. See OpenMage/magento-lts#1525
2. See OpenMage/magento-lts#2940

### Tests

@kiatng only thing that needs to be check is admin - manage customer - create date

### CODE REVIEW

**Comment by ADDISON74** [comment]
I was left with the impression that PR #1525 is already in OpenMage v20. 

From the next branch, the following two PR should also be backported, because they concern security issues. I know they can create BC but the advantages with a good help are preferable.

[Added form key validation to Contacts form](https://github.com/OpenMage/magento-lts/pull/3146)  
Check `app/design/frontend/base/default/template/contacts/form.phtml` in your theme and be sure that you've `<?php echo $this->getBlockHtml('formkey') ?>` under the `<form` opening tag, [as shown here](https://github.com/OpenMage/magento-lts/pull/3146/files#diff-24566c45709e3e8559774b20e9258080a456999c3b02bef20feda95151a7f8df).

[Unified CSRF configuration](https://github.com/OpenMage/magento-lts/pull/3147)  
If you enabled CSRF in `System -> Configuration -> System` (which you should!) then it will be enabled for all your forms and the checkout.

**Comment by sreichel** [comment]
> I was left with the impression that PR #1525 is already in OpenMage v20.

Have to change the title. #1525 was added to v20 (instead of v19) b/c it had some breaking changes. #2940 was made to fix #466 w/o breaking changes.

**Comment by sreichel** [comment]
> From the next branch, the following two PR ...

Yep. I have it on screen, but wait for other PRs to get merged.

**Review by ADDISON74 — APPROVED** [review]

**Comment by kiatng** [comment]
Won't this PR break BC to PR #1525, which was merged 3 years ago?

**Comment by sreichel** [comment]
Dont think so ... (?)

It does not change your code. `formatDate()` is forwarded to your changed method.

**Review by kiatng — APPROVED** [review]

**Review by kiatng — APPROVED** [review]

**Pull request merged**
