### PR TITLE
Update Option.php

### LINKED ISSUE #1428: Warnings when customer add configurable product to cart
With OpenMage 20.0.6 and PHP 7.4.6, when a customer add a configurable product to his cart, we encounter the following errors in logs:

_strpos() expects parameter 1 to be string, object given_

image

_Illegal offset type in isset or empty_

image

To fix the problem, [we have revert this change](https://github.com/OpenMage/magento-lts/commit/2fe965826a26bf6cfe36b4edba0d51d5e3f31491).

### PR DESCRIPTION
**Pull request by matteorossi-thespacesm**
Part of change to fix bug #1428 on OpenMage LTS 19.4.10

### Description (*)

Add method getProduct to class

### Related Pull Requests

Add method getProduct to Mage_Catalog_Model_Product_Configuration_Item_Option_Interface interface

### Fixed Issues (if relevant)

1. Fixes #1428 on OpenMage LTS 19.4.10

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by kkrieger85 — APPROVED** [review]

**Comment by fballiano** [comment]
is this still a problem today?

**Comment by fballiano** [comment]
Fixed conflict with this PR, @sreichel what do you think about this?

**Comment by sreichel** [comment]
> what do you think about this?

I'd love to have _steps to reproduce_ ... :P

**Comment by fballiano** [comment]
https://github.com/OpenMage/magento-lts/issues/1428 was already fixed and since we don't have steps to reproduce the error nor feedback, I'm closing this.

Feel free to reopen in case you have more info.

**Pull request closed without merging**
