### PR TITLE
Updated TinyMCE to 6.8.4

### PR DESCRIPTION
**Pull request by fballiano**

### CODE REVIEW

**Comment by ADDISON74** [comment]
Only 33 files? The last update v6.8.2 changed 99 files.

**Comment by fballiano** [comment]
https://github.com/OpenMage/magento-lts/pull/3837/files was 47 files because it had the languages, but the update is so extremely minor

**Review by ADDISON74 — APPROVED** [review]

**Comment by ADDISON74** [comment]
Tthank you for the clarification. The upgrade to v6 of this editor was huge step and important change in OpenMage. I like how it looks and I appreciate that I didn't find any errors in the browser console. The buttons are well chosen and logically positioned, as are the menus. Great job.

**Comment by fballiano** [comment]
:-) I guess we'll stay with 6.8 for another 10 years ehhehe

**Comment by fballiano** [comment]
6.8.3 was already in openpage before, try with some ctrl+f5 ;-)

**Pull request merged**
