### PR TITLE
Fixed call to a member function setOnclick() on false in Mage_Adminhtml_Block_Sales_Order_View_Giftmessage

### PR DESCRIPTION
**Pull request by fballiano**
Fixes https://github.com/OpenMage/magento-lts/issues/3814

### CODE REVIEW

**Comment by kiatng** [comment]
Intuitively, if save button is missing, not able to edit and save the gift message, then isn't it correct to throw an error?

**Comment by fballiano** [comment]
@kiatng I don't know how you do it but you got it right, and then debugging I found 2 instances of Mage_Gitftmessage instead of Mage_GiftMessage, which were there reason why this issue was happening.

**Review by kiatng — APPROVED** [review]
Good catch!

**Comment by pquerner** [comment]
Magicento boys ;)

**Review by ADDISON74 — APPROVED** [review]

**Pull request merged**
