### PR TITLE
Install TinyMCE 7.5 via composer

### PR DESCRIPTION
**Pull request by sreichel**
### Description (*)

I've updated the copy-plugin to work if you install OpenMage as composer dependency.

### Related Pull Requests
- see OpenMage/magento-lts#3658
- see OpenMage/magento-lts#3705
- closes OpenMage/magento-lts#4403 

### Update

- moved block classes from Adminhtml/Cms to Cms/Adminhtml (and deprecated old ones)

### Todo

- for another PR ... add another config option to always use editor
- for another PR ... disable editor if TinyMce is not installed

### CODE REVIEW

**Comment by ADDISON74** [comment]
Very good idea, but @fballiano, @empiricompany and I worked on a custom version for TinyMCE which is now available in version 20. Installing TinyMCE with Composer will benefit the version we have already in OpenMage or do we need some patches for Composer?

**Comment by sreichel** [comment]
@ADDISON74 i have seen no changes made to TinyMCE itself, so the files are the same as currently used.

**Comment by ADDISON74** [comment]
@sreichel - This is good. I will come back with a feedback after testing.

**Comment by sreichel** [comment]
@ADDISON74 note: when you install OM as composer dependency, you have to install that plugin too.

**Comment by sreichel** [comment]
Waiting for final response from TinyMCE, but it looks like we CAN use v7 ...

Maybe some is really familiar with licensing ... answer so far.

> 
> GPL Version 2 or later grants users the freedom to use, modify, and distribute software, as long as any derivative works are also distributed under the same license and the source code is made available to recipients.
> 
> In simplified terms, this means that when distributing an app containing GPL licensed code, the whole app will inherit the GPL license and the source code must be made available to the community. This is usually a no-go in a commercial use case.

OM is no derivative work from TinyMCE, so we dont have to put it under GPL itself.

We use it in a non-commercial project. We follow (inherit?) GPL and all code is available to the community.

From my understanding ... if someone uses a OM-fork as commercial product, HE had to put it under GPL - not we.

Waiting for response, but v7 seems to work ...

**Comment by ADDISON74** [comment]
I didn't think to contact them, but what you say there seems to make sense. If we get an official answer that we can use version 7, that would be wonderful. If I'm not mistaken, Magento 2 is still at version 5.

**Comment by ADDISON74** [comment]
@sreichel - Did you get any reply from TinyMCE regarding using v7 in OpenMage?

**Comment by sreichel** [comment]
@ADDISON74 i dont know ... my email-account is currently locked and seems not so easy to get it unlock.

With this PR we are prepared for a possible 6.8.5 release that will come "for sure" (6.8 is supported till next year).

**Comment by sreichel** [comment]
No answer till now ... 

Ready to review?

**Review by colinmollenhour — APPROVED** [review]
Looks good, but what release should it go in?

**Comment by sreichel** [comment]
It would only replace current tinymce 6.8.4 we already have ... `main` branch/release?

**Comment by empiricompany** [comment]
I like the idea of this PR, but there are two critical issues that come to mind that need to be resolved:

1. The composer plugin "sreichel/composer-plugin-file-copy" is a dev-develop version, but what concerns me more is that it's not under the OpenMage umbrella. What if this gets removed in the future? This remains a critical issue for any additional tools created by the community, such as documentation and others.

2. More importantly, the license of the new TinyMCE version is GPL, which is not compatible with our OSL. This issue has been raised multiple times by @fballiano in the past.

IMHO The best thing in the future is to remove TinyMCE in favor of a minimal editor with only bold, italic, underline, etc.
My clients have never used all the 'word-style' tools in TinyMCE, and when they did, they only created messes in the code. Every modern e-commerce platform is moving in this direction.

**Comment by sreichel** [comment]
1. Make a release is not a problem, but till then you can also add the hash for a specific commit.

OpenMage can fork it, but I don't want to move it. It's not tied to OpenMage.

2. We can't use v7, but v6 is supported till mid next year. Using composer has the advantage `composer audit` warns about security issues and we can "vendor patches" to fix them.

However ... you're right. Removing or replacing or make TinyMce optional is something we have to think about.

**Comment by empiricompany** [comment]
1. It is currently used only on OpenMage and is a tool specifically created for OpenMage. This sets it apart from other packages we have in Composer. The core is tightly dependent on this package; in my opinion, it should be officially supported by OpenMage.

2. The issue is not about the support but the GPL license, which is incompatible with the OSL.

**Below are some points raised by an LLM such as Claude:**

_Integrating GPL (GNU General Public License) licensed code into an OSL (Open Software License) project can lead to several complications due to the differences in these licenses. Here are the main issues:_

1. _License incompatibility: GPL and OSL are generally considered incompatible licenses. This means that combining code under these licenses in the same project can create legal conflicts._
2. _Copyleft nature of GPL: GPL is a strong copyleft license, which means that any derivative work must also be distributed under the GPL. This could force the entire OSL project to adopt the GPL license, which may not be desired or possible._
3. _Distribution requirements: GPL requires that the source code of the entire program be made available when distributing the software. This might conflict with the OSL's distribution terms._
4. _Contributor agreements: If your project has contributor agreements based on the OSL, introducing GPL code could invalidate or complicate these agreements._
5. _Legal uncertainty: The lack of clear legal precedents on mixing these specific licenses can lead to uncertainty about the legal status of the resulting software._
6. _Commercial use restrictions: GPL can impose restrictions on commercial use that may not align with the goals of an OSL-licensed project._
7. _Difficulty in future licensing changes: Once GPL code is incorporated, it becomes very difficult to change the license of the project in the future._
8. _Potential need for code segregation: To avoid these issues, you might need to strictly segregate the GPL code, which can lead to architectural complications and maintenance challenges._

**I encourage all of you to focus particularly on point 2**

**Comment by ADDISON74** [comment]
This is what GNU recommends on its website _"We urge you not to use the Open Software License for software you write. However, there is no reason to avoid running programs that have been released under this license."_

I don't know if Magento 1 was licensed to use TinyMCE, but OpenMage inherited it. At this moment TinyMCE v6 runs in OpenMage and can be removed at the request of the developer.

Being a discussion with legal implications, it would be necessary to consult some lawyers. If there is an explicit agreement to use TinyMCE in Magento 1, there should be no problems. If there is none, an agreement from TinyMCE should be requested by our maintainers.

**Comment by sreichel** [comment]
@empiricompany that plug-in has a few hundred downloads and I doubt it comes from Openmage users. It has only 3 lines of code that are related to Openmage (check for magento-root-dir).

TinyMCE v6 is released under MIT license, so it should be safe to use.

Only v7 changed to GPL3 that's not compatible.

I got no reply from customer support till now and made an official request some minutes ago.

**Comment by empiricompany** [comment]
There has been some confusion in the Tinymce community about the license change. 
A few days ago there was a thread about it:

This seems to be the last official comment:
https://github.com/tinymce/tinymce/issues/9453#issuecomment-2327646149

It seems that the versions before 7 maintain the old licenses, even if the repository is the same and shows the GPL license

**Comment by sreichel** [comment]
Request already made there ... https://pi.tiny.cloud/l/2202/2024-04-25/dgy4qt

**Comment by ADDISON74** [comment]
The discussions that I read in the TinyMCE repository will not remain without result. Magento 2 still uses version 5, we can continue to use version 6 in OpenMage without problems even after its EOL. In addition, there will be forks if the license policy is not changed. At this moment I would say let others decide, because things will not stay like this regarding v7, TinyMCE risks losing many supporters very fast. If they didn't block the conversation, opinions would still flow today.

**Comment by sreichel** [comment]
Thanks to @colinmollenhour who helps to finish that ...

> Hi Colin,
> 
> I hope you are well. 
> 
> Kate here; I lead partnerships for TinyMCE.
> 
> Sven shared your email with me and suggested discussing our "TinyMCE for Open Source Program" with you. 
> Sven filled out the application form sharing information about OpenMage, and based on the form, OpenMage qualifies for the program. 
> 
> So, I want to connect with one of the project representatives to walk your team through the program terms so you can evaluate whether it's a fit for you. 
> After the call, I'll send you the licensing agreement to review. 

:heart:

**Comment by colinmollenhour** [comment]
Quick update: I met with Kate, everything sounded very straightforward and reasonable. There will be no cost to us or our users unless and until we approach/surpass $2mm annual revenue. She sent a license for review. I will look over it next week. Sven also has it in his email.

**Comment by sreichel** [comment]
Thanks Colin.

> There will be no cost to us or our users unless and until we approach/surpass $2mm annual revenue.

We have no controlll over users revenue.

I'd suggest to ship OM with v7, but leave a WebNotification that they either have to downgrade to v6.8 or "get in contact" with TinyMCE to pay the fees if the pass the anual $2mm ...

That leads to "How to handle"  zip-archive?

- add v6.8 by default
- drop zip-archive (prefered)
- make TinyMCE opztional for all

**Comment by ADDISON74** [comment]
Good job folks.

We can continue with 6.8 version because it will benefit from support for a while and then there will surely be active forks, as happened with ZF1-Future.

We can offer the option to install version 7 mentioning that if annual revenue is over 2 million USD then either pay a fee or downgrade to 6.8.

By the way, Magento 2 still uses version 5.

**Comment by sreichel** [comment]
This license request was for to not stay on v6. (???)

**Comment by colinmollenhour** [comment]
I don't think we need to continue to offer v6. The $2mm revenue is in reference to OpenMage's revenue, not our users.

**Comment by sreichel** [comment]
Okay. Lets test.

**Comment by sreichel** [comment]
Oh nooo ... v7.3 looked good, but 7.4 causes some trouble.

**Comment by ADDISON74** [comment]
You can change to version 7.3 and stay there for a while.

**Comment by sreichel** [comment]
Seems to be a cache problem ... 7.4 works

tinymce
tinymce2

**Comment by sreichel** [comment]
Phpstan can be ignored here ... fixed in another PR.

**Review by ADDISON74 — APPROVED** [review]

**Review by ADDISON74 — APPROVED** [review]

**Comment by sreichel** [comment]
Has some time to test?

**Comment by addison74** [comment]
I will do a test in the next days. We can change the title to 7.5.

**Comment by addison74** [comment]
I wasn't using OpenMage versions installed with Composer, so I did the following steps to test, based on the information I found in the README file.

1. I created a directory then used DDEV as a test environment, ```ddev config```.

2. I edited the .ddev/config.yaml file and changed the values ​​for **php_version** (8.4) and **webserver_type** (apache-fpm) and started DDEV ```ddev start```

3. I used these commands from the README file

```
ddev composer init
ddev composer config --json extra.enable-patching true
ddev composer config extra.magento-core-package-type magento-source
ddev composer config extra.magento-root-dir /var/www/html

```

4. I added a few lines into my composer.json file, this is the final version

```json
{
    "name": "ubuntu/openmage",
    "authors": [
        {
            "name": "DDEV User",
            "email": "nobody@example.com"
        }
    ],
    "require": {
        "aydin-hassan/magento-core-composer-installer": "^2.1.0",
        "openmage/magento-lts": "^20.10.2",
        "mklkj/tinymce-i18n": "^24.11",
        "sreichel/composer-plugin-file-copy": "^1.1",
        "tinymce/tinymce": "^7.5"
    },
    "extra": {
        "enable-patching": true,
        "magento-core-package-type": "magento-source",
        "magento-root-dir": "/var/www/html",
        "file-copy" : [{
            "source": "tinymce/tinymce",
            "target": "js/tinymce"
        }, {
            "source": "mklkj/tinymce-i18n/langs7",
            "target": "js/tinymce/langs"
        }]
    },
    "config": {
        "allow-plugins": {
            "aydin-hassan/magento-core-composer-installer": true,
            "cweagans/composer-patches": true,
            "magento-hackathon/magento-composer-installer": true,
            "sreichel/composer-plugin-file-copy": true
        }
    }
}
```

5. I used this command to install ```ddev composer install```. No errors.

6. Loading the website in the browser I followed the steps to install OpenMage. 

7. I edited a CMS page. Enabling the editor TinyMCE version is 6.8.4.

Looking into js/tinymce directory there are the old files, the ones that ship with OpenMage. Based on the Composer file they should be replaced by the files from these two directories:

- tinymce/tinymce
- mklkj/tinymce-i18n/langs7

I renamed js/tinymce then copied the files from the directories above. I managed to run the latest version 7.5.1.

Maybe I missed a step but I tried to keep the testing as simple as possible.

**Comment by addison74** [comment]
I used the ```debug: true``` in file-copy to understand what is happening behind. The path for magento root was wrong. I changed it from /var/www/html to .

TinyMCE shows in the browser console this warning

```tinymce.min.js:385 TinyMCE is running in evaluation mode. Provide a valid license key or add license_key: 'gpl' to the init config to agree to the open source license terms. Read more at https://www.tiny.cloud/license-key/
```

but you already fixed it.

You need to update the composer.lock file.

**Comment by colinmollenhour** [comment]
As per our agreement with Tiny, the custom license file needs to be included with distributions of the source code so here was my proposal:
> Our preferred method of including the software will be to include it via the composer.json file which references the "[tinymce/tinymce](https://packagist.org/packages/tinymce/tinymce)" package which appears to source from https://github.com/tinymce/tinymce-dist which contains a [license.md](https://github.com/tinymce/tinymce-dist/blob/master/license.md) file which references GPLv2. ...
> I think we can implement a composer patch that adds to or replaces this license.md file after it is downloaded from packagist with a custom one containing the notice from section 3.ii so that when the user visits the vendor/tinymce/tinymce directory they will see the correct license. I plan to also add a LICENSE_TINYMCE.txt to the root of the repo for greater visibility. Do you see any issue with my understanding here or the proposed method of inclusion?

Can you devise a method to inject the notice in section 3.ii into the vendor/tinymce/tinymce directory after a `composer update`?

Here is the notice text:

```
THE USE OF TINYMCE IN THIS PROJECT IS POSSIBLE ON THE BASIS OF THE AGREEMENT CONCLUDED BETWEEN
THE OWNER OF TINYMCE AND THE COMMUNITY OF THIS OPEN-SOURCE PROJECT. UNDER THE CONCLUDED
AGREEMENT, IT IS PROHIBITED TO USE TINYMCE OUTSIDE OF THIS PROJECT. IF THIS IS THE CASE, TINYMCE MUST
BE USED IN LINE WITH THE ORIGINAL OPEN-SOURCE LICENSE.
```

Please also add the following to LICENSE_TINYMCE.txt to the project root:

```
THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL TINYMCE OR ITS LICENSORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR
THE USE OR OTHER DEALINGS IN THE SOFTWARE.
```

**Comment by sreichel** [comment]
@colinmollenhour solved issues.

Ive replaced file copier plugin with new openmage composer plugin.

- no need to add copy instructions to composer.json
- works with TinyMce v6 and 7
- for v7 license files are set after compoer update

Not tested with composer installed OpenMage yet.

**Comment by sreichel** [comment]
> Looking into js/tinymce directory there are the old files, the ones that ship with OpenMage. Based on the Composer file they should be replaced by the files from these two directories:
> 
>     * tinymce/tinymce
> 
>     * mklkj/tinymce-i18n/langs7
> 
> 
> I renamed js/tinymce then copied the files from the directories above. I managed to run the latest version 7.5.1.

@addison74 sorry for late reply.

The old files are there because you started with v.20.10.2. They are removed with this PR.

Example composer.json for tests ...

```json
{
    "name": "sr/test-om-composer-tinymce",
    "type": "project",
    "description": "Test for TinyMCE 7.5",
    "license": "proprietary",
    "require": {
        "openmage/magento-lts": "dev-tinymce",
        "aydin-hassan/magento-core-composer-installer": "~2.0.0 || ^2.1.0"
    },
    "extra": {
        "magento-root-dir": "public_test",
        "enable-patching": true,
        "magento-core-package-type": "magento-source"
    },
    "config": {
        "allow-plugins": {
            "cweagans/composer-patches": true,
            "magento-hackathon/magento-composer-installer": true,
            "aydin-hassan/magento-core-composer-installer": true,
            "openmage/composer-plugin": true
        }
    },
    "repositories": {
        "auto-currency-switcher": {
            "type": "git",
            "url": "git@github.com:sreichel/magento-lts.git"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

Plugin is now also tests with composer + `magento-root-dir` set.

**Comment by sreichel** [comment]
I dont think its required to test TinyMCE itself, as Tiny-Support told that there are no BC-breaking changes.

If install works correctly, please move on!

**Comment by kiatng** [comment]
I'm not sure how to test. What I did in DDEV:

1. [bash] `gb pr checkout 4113`
2. [bash] `composer upgrade`
3. [browser] OpenMage admin > CMS > Pages > select any page > Show Editor > Help > Version

I get: "You are using TinyMCE 6.8.4" but I expect 7.5. What am I missing?

**Comment by addison74** [comment]
@kiatng - How did you install OpenMage in the directory configured to use DDEV?

**Comment by sreichel** [comment]
Ahhh ... i forget to commit some changes to composer-plugin. Also a template change is missing.

**Comment by sreichel** [comment]
Sorry for missing commit.

Tested again.

Github install (checkout repo + composer install)
tiny--om

Composer install with custom magento-root-dir (as nin config above)
tiny--om--composer

If it still shows v6.8 please run `composer install -v` to show tinymce version or `-vv` to see copy paths.

**Comment by sreichel** [comment]
> I get: "You are using TinyMCE 6.8.4" but I expect 7.5. What am I missing?

You still have old - and now gitignored - files in js/tinymce and the new ones went to "var/www/html/www". 

Should be fixed now.

**Comment by sreichel** [comment]
> @kiatng - How did you install OpenMage in the directory configured to use DDEV?

Think either installed before, or w/ "." ddev-docroot ...

If you want to install with ddev command, please check this code ... https://github.com/OpenMage/magento-lts/pull/4407

To make DDEV commands available for composer installs, they move to a ddev-addon. Later.

**Review by kiatng — DISMISSED** [review]

**Review by addison74 — DISMISSED** [review]

**Comment by sreichel** [comment]
... conflicts fixed ... grrr

**Review by kiatng — APPROVED** [review]

**Review by addison74 — APPROVED** [review]

**Comment by sreichel** [comment]
We did it. :+1:

**Pull request merged**
