### PR TITLE
Replaced Zend_Mail_Transport_Sendmail with Laminas\Mail\Transport\Sendmail

### PR DESCRIPTION
**Pull request by fballiano**
After https://github.com/OpenMage/magento-lts/issues/3174 () I thought that maybe Zend_mail would be a good candidate for a replacement with a more modern implementation so I made a test.

- this PR only replaces Zend_Mail_Transport_Sendmail with its Laminas counterpart
- this PR does not replace the entire Zend_Mail (at the moment, let's see what the reception of this code and decide what to do next)
- I've tested the email sending and it works correctly
- I've also tested installing aschroder/smtp_pro to see if this change was breaking it but it seems not to break it
- I've targeted this PR to `main` since it doesn't seem at the moment to be breaking anything, maybe it should be considered BC and targeted to `next`?

**How to test?** be sure to be using sendmail on your server, install the PR, composer install, try to send a "forgot password" email

What do you think about this idea?

### CODE REVIEW

**Comment by fballiano** [comment]
exactly, from what I've seen zf1future is not super quick in fixing problems (it's probably also a good thing to be careful, for sure) which could be a bit of a problem. it is also used by a limited amount of people compared to laminas or symfony.

and thanks to composer we're facilitated in adding different vendors, if needed.

laminas is mostly compatible with zend framework, there are still many differences, but in this case the syntax was the same.

I think that, without the zf1future step (which we will require for long time anyway), we wouldn't be able to do something like this specific PR.

So let's see :-)

**Comment by fballiano** [comment]
I've done some more work trying to rewrite the whole Zend_Mail dependency but... I don't know... the whole paradigm has changed and you've to call a `$transport->send()` instead of `$mail->send($transport)` and to send a text/html email you've to do https://docs.laminas.dev/laminas-mail/message/attachments/

So, I don't know, is it worth the risk? Or better stick with the zf1f implementation and maybe add a new "zf1f patch" to our composer for the moment?

**Comment by ADDISON74** [comment]
Maybe we should "force" the change in ZF1-Future. If they don't want to accept it, a patch can be implemented as @sreichel did with other changes. We take the parts we need from Laminas-Mail and implement them to solve the issue. 

I haven't checked, but what we were using before ZF1-Future would have created trobule with PHP 8.x?

**Comment by fballiano** [comment]
> I haven't checked, but what we were using before ZF1-Future would have created trobule with PHP 8.x?

No idea actually, i can imagine it would have

**Comment by fballiano** [comment]
it was an interesting chat to have anyway :-)

**Comment by ADDISON74** [comment]
Indeed we discovered Laminas.

**Pull request closed without merging**
