### PR TITLE
Fix qty for bundles items

### PR DESCRIPTION
**Pull request by luigifab**
### Description

Fix qty_invoiced qty_shipped qty_refunded for bundle order items, qty for bundle invoice/shipment/creditmemo items.
Fix qty_refunded for configurable order items, qty for configurable creditmemo items.

todo: better description

### Fixed Issues
1. Fixes OpenMage/magento-lts#2310

### Manual testing scenarios

Create a bundle product (sku _-646_ on screenshots) associated with:
- a simple product, qty 1 (sku _-140_ on screenshots)
- a simple product, qty 2 (sku _-141_ on screenshots)
- a simple product, qty 3 (sku _-552_ on screenshots)
- a downloadable product, qty 1 (sku _FPDF_ on screenshots)
- a downloadable product, qty 2 (sku _-PDF_ on screenshots)

Create also a configurable product (sku _-125-M_ on screenshots).

Some screenshots (before/after):

Create invoice + shipment + refund from API:
[0-api-simple-before](https://user-images.githubusercontent.com/31816829/183735103-4eab364e-7621-4ee0-a0a4-807c22bef157.png)
[1-api-simple-after](https://user-images.githubusercontent.com/31816829/183735110-cdba5e35-3029-4704-9e74-b16080f7a33e.png)

Create invoice + shipment + refund from backend:
[2-backend-simple-before](https://user-images.githubusercontent.com/31816829/183735116-266391b4-1ebb-42a6-8ed5-bf2223486852.png)
[3-backend-simple-after](https://user-images.githubusercontent.com/31816829/183735120-fc61f58c-18ee-407e-b743-c53d44bf01a5.png)

Create invoice + shipment + refund on invoice from backend:
[4-backend-simple-before-ref-inv](https://user-images.githubusercontent.com/31816829/183735125-210c6713-935f-41dd-a4cc-2956256c03b8.png)
[5-backend-simple-after-ref-inv](https://user-images.githubusercontent.com/31816829/183735127-0be8be6f-cf69-499c-9fbb-17ccefa5ca76.png)

Create invoice + shipment + refund from API:
[6-api-double-before](https://user-images.githubusercontent.com/31816829/183735134-e484e04b-6d0e-47ca-8a01-4d453f8ed54c.png)
[7-api-double-after](https://user-images.githubusercontent.com/31816829/183735140-c21e2a89-daa6-435b-9783-3525766cefc4.png)

Create invoice + shipment + refund from backend:
[8-backend-double-before](https://user-images.githubusercontent.com/31816829/183735144-8c7815cb-c487-47d7-84d4-e01d106140cb.png)
[9-backend-double-after](https://user-images.githubusercontent.com/31816829/183735152-20be3e8d-82b1-4619-98c6-3d3b44823e03.png)

Create invoice + shipment + refund on invoice from backend:
[10-backend-double-before-ref-inv](https://user-images.githubusercontent.com/31816829/183735154-9ef35a03-6ffc-40f3-8f4e-8e28a1439019.png)
[11-backend-double-after-ref-inv](https://user-images.githubusercontent.com/31816829/183735161-78dfc603-d714-4dbc-9f1a-b0bb17aae155.png)

Create invoice + shipment + refund from backend:
[12-backend-double-2x-before](https://user-images.githubusercontent.com/31816829/183735165-e035dd4e-7b26-49a6-bf32-fcbc94175fc7.png)
[13-backend-double-2x-after](https://user-images.githubusercontent.com/31816829/183735173-df31cc6c-0ce8-4345-bc76-373f13431695.png)

Create invoice + shipment + refund on invoice from backend:
[14-backend-double-2x-before-ref-inv](https://user-images.githubusercontent.com/31816829/183735180-57c74d98-5deb-4226-a4d3-aa168d3c903d.png)
[15-backend-double-2x-after-ref-inv](https://user-images.githubusercontent.com/31816829/183735184-0df53ef4-ebe2-4213-8825-cdbff0781eb1.png)

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Comment by luigifab** [comment]
The description is not good, but fully working (for me) since 5 months.

**Comment by sreichel** [comment]
Duplicated code parts could move to a new method?

**Comment by luigifab** [comment]
All changes are not exactly same, and I prefer to not touch.

**Comment by luigifab** [comment]
For next?

**Comment by fballiano** [comment]
@luigifab I'd love to review this but could you just write a description for me to understand it better?

**Comment by luigifab** [comment]
Hum, to summarize, this PR fix qty decrementation in sales tables, when an order is invoiced, shipped, refunded, from backend, from API.

You can try my scenario to visualize qty columns with and without changes.

**Comment by ADDISON74** [comment]
@luigifab - any reasons for closing this PR?

**Comment by JonLaliberte** [comment]
@addison74 Should this still be open?

**Pull request closed without merging**
