### PR TITLE
Update Emulation.php

### PR DESCRIPTION
**Pull request by Schrank**
https://magento.stackexchange.com/a/25617/217
Emulation doesn't load frontend translation, so we do it.

### CODE REVIEW

**Comment by colinmollenhour** [comment]
Should this line then be removed so init is not called twice?

https://github.com/OpenMage/magento-lts/blob/1.9.4.x/app/code/core/Mage/ProductAlert/Model/Email.php#L258

**Comment by Schrank** [comment]
Ah, thanks! You already have a fix - the problem is, that most likely it doesn't cover all emails, so I decided to put it directly in the emulation.
I can remove all (if there are more than the one) calls or close the PR - as you wish :-)

**Comment by stijnhau** [comment]
seems like a good fix

**Comment by colinmollenhour** [comment]
Can you remove the line https://github.com/OpenMage/magento-lts/blob/1.9.4.x/app/code/core/Mage/ProductAlert/Model/Email.php#L258 and then I think this could be merged.

**Pull request merged**
