### PR TITLE
Replaced isAvailable() with isSalable() so events are considered

### PR DESCRIPTION
**Pull request by woutersamaey**
### Description (*)
Replaced isAvailable() with isSalable() so event are considered.

I have a store that has more complex logic for determining "salability". This block does not consider event-driven salability.

I have this code running in production for 2 years, now I'm contibuting it.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by colinmollenhour** [comment]
Thanks @woutersamaey ! Is there any scenario you can think of where this would not be the behavior expected by someone? Is there any difference on a vanilla installation?

**Comment by woutersamaey** [comment]
Not really. This change should be harmless, but it's essential if you're changing salability using events.
Changing salability using events works well, except in this single instance.

**Comment by colinmollenhour** [comment]
I think I would agree with the change, but perhaps it belongs in the 20.0 branch.

**Comment by woutersamaey** [comment]
Moved to 20 branch. Can we get this merged?

**Review by Flyingmana — APPROVED** [review]

**Review by Sekiphp — APPROVED** [review]
I investigating the diferrence between `isAvailable` and `isSalable` and It looks, that this should work properly.

**Pull request merged**
