### PR TITLE
Do not render action or massaction column in totals row in adminhtml grid

### PR DESCRIPTION
**Pull request by theroch**
### Description (*)
If you have an grid with a totals row and action and/or massaction columns,
this patch prevents that the action or massaction column is rendered in the totals row.

### Manual testing scenarios (*)

1. Create a grid with totals and actions or massaction
2. View totals row if action or massaction column is rendered (it shouldn't be)

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by luigifab** [comment]
Do you have a code snippet to test it?

**Comment by theroch** [comment]
> Do you have a code snippet to test it?

You can edit the following file to test a Grid with and without this fix:
Change "app/code/core/Mage/Adminhtml/Block/Catalog/Product/Grid.php"
from
```
$this->addColumn('price',
            array(
                'header'=> Mage::helper('catalog')->__('Price'),
                'type'  => 'price',
                'currency_code' => $store->getBaseCurrency()->getCode(),
                'index' => 'price',
                'total' => 'sum'
        ));
```
to
```
$this->addColumn('price',
            array(
                'header'=> Mage::helper('catalog')->__('Price'),
                'type'  => 'price',
                'currency_code' => $store->getBaseCurrency()->getCode(),
                'index' => 'price',
                'total' => 'sum'
        ));

        $this->setCountTotals(true);
        $this->setTotals(new Varien_Object(['price' => 1000]));
```

**Review by luigifab — CHANGES_REQUESTED** [review]
You have forgotten a space after the if `if(` and you need to remove the ; of `<?php endif; ?>`.
Perhaps you can avoid unnecessary parentheses for `($_column->hasTotalsLabel()) ? ...`.

**Review by luigifab — DISMISSED** [review]

**Comment by luigifab** [comment]
My bad, there is now a ; for `<?php endforeach; ?>` 😭.

**Review by luigifab — APPROVED** [review]

**Review by kiatng — APPROVED** [review]

**Review by fballiano — APPROVED** [review]

**Pull request merged**
