### PR TITLE
Fixed whitespace for docblocks

### PR DESCRIPTION
**Pull request by fballiano**
Continuing to fix whitespace and formatting for docblock, also switched http to https for license links.

### CODE REVIEW

**Review by sreichel — APPROVED** [review]

**Comment by sreichel** [comment]
How many PRs left? :rofl:

**Comment by fballiano** [comment]
> How many PRs left? 🤣

a couple for app/code/core but then there's app/design (which I hope should be easier)

**Comment by luigifab** [comment]
You made a little mistake on some files, if I read correctly the `git blame`.
For example [persistent.xml](https://github.com/OpenMage/magento-lts/blame/2fe3145fe9e01b75c390244cdcd45ad234215d9c/app/code/core/Mage/Persistent/etc/persistent.xml):

```
@license    http://opensource.org/licenses/afl-3.0.php s+Academic Free License (AFL 3.0)
```

**Comment by fballiano** [comment]
Thanks, i'll fix right now

**Pull request merged**
