### PR TITLE
Removed Mage_PageCache

### PR DESCRIPTION
**Pull request by sreichel**
### Description (*)

`Mage_PageCache` was removed for v20 only. Created composer module to keep functionality if needed.

### Related Pull Requests

1. See OpenMage/magento-lts#2258

Can be reinstalled with `composer require openmage/module-mage-pagecache:dev-master`

### Questions or comments

@fballiano should we add these modules to releasebuilder?

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Comment by fballiano** [comment]
if we backport everything we should just merge v20 in v19 and call it a day ;-)

**Comment by sreichel** [comment]
That would be to easy :laughing:

**Comment by fballiano** [comment]
that is what i mean when i say to drop v19 in favour of v20

**Comment by fballiano** [comment]
I've created https://github.com/OpenMage/module-mage-pagecache for you ;-)

**Comment by sreichel** [comment]
Pushed.

**Review by fballiano — DISMISSED** [review]

**Comment by fballiano** [comment]
about adding it to the release builder, I wouldn't do that (my personal opinion) for these reason:
- I wouldn't want it in v20
- it is easy to install it
- if people using the "built" zip file "overwrite" the core with the new versions (without deleting folders firts) they wouldn't even recognise that's gone (I know, that would be the same with CM modules but those are much more important in my opinion)

**Review by fballiano — APPROVED** [review]

**Review by ADDISON74 — APPROVED** [review]

**Pull request merged**
