### PR TITLE
Re-move CM from composer

### PR DESCRIPTION
**Pull request by sreichel**
### Description (*)

Removed Cm_Chache from composer until symlik/submodules error is fixed.

(Added `cweagans/composer-patches` & `symplify/vendor-patches` for ZF1-future)

### Related Pull Requests

1. See OpenMage/magento-lts#2766

### Fixed Issues (if relevant)

1. See OpenMage/magento-lts#2781

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Comment by fballiano** [comment]
I don't think this is necessary, I've done some tests for https://github.com/OpenMage/magento-lts/pull/2165 and `credis` is already installed as some dependency in `vendor` so there's no need for it to be in `lib/Credis` (it's not the best that the folder is created empty but anyway...).

I've also checked that redis connection works and that the `vendor/colinmollenhour/credis/Client.php` is actually used, and it is.

So I don't think this is necessary.

**Comment by sreichel** [comment]
For some reason the class was not found, but it works now.

But ... should we really add it with that symlink error?

**Comment by fballiano** [comment]
In my opinion redis modules should be in our composer suggest instead of bundled in but... I don't know.

Anyway either we keep all of them or remove all of them, the symlink shouldn't be a "problem", although it's not looking great the software should work.

**Comment by sreichel** [comment]
> In my opinion redis modules should be in our composer suggest

Sounds good to me, but `composer suggest` does not work for the "own" project. It will not be shown when you clone this repo and run `composer install`. It would work only for `composer require OpenMage/magento-lts` ...

However ... remove CM and add some info to README?

**Comment by fballiano** [comment]
> It would work only for `composer require OpenMage/magento-lts` ...

well that should be the right way for people anyway right?

> However ... remove CM and add some info to README?

mmm thinking about it, it's been many years that the CM redis modules are bundled and people kinda expect the funcionality, if we remove those some people (the ones not using composer) will have problems updating so... I'd kinda leave things as they are now

**Comment by sreichel** [comment]
> well that should be the right way for people anyway right?

yep, was just an info that suggestions are not shown for the own project/repo.

... lets keep it. :)

**Pull request closed without merging**
