### PR TITLE
Fixed logging too many exceptions for payment methods

### PR DESCRIPTION
**Pull request by fballiano**
In https://github.com/OpenMage/magento-lts/issues/3179 @ADDISON74 pointed out that, using the backend, and opening an order detail page, some exceptions were logged about missing payment methods.

This is because the list of payment methods tries to load the model (for the payment method) and logs an exception if it's not found.

This is ok in some cases (when the order was paid with a method that has been removed later) but not in all the other cases.

So I thought to kinda rewrite the getPaymentMethodList method of Mage_Payment_Helper_Data.

If I'm not mistaken the before/after output of the getPaymentMethodList method stays the same:
before:
Screenshot 2023-04-15 alle 16 33 49

after:
Screenshot 2023-04-15 alle 16 33 21

### Related Pull Requests
https://github.com/OpenMage/magento-lts/pull/2939

### Fixed Issues
1. Fixes https://github.com/OpenMage/magento-lts/issues/3179

### CODE REVIEW

**Comment by ADDISON74** [comment]
This PR fixes **Sales > Orders > View** any order. No more lines in exceptions.log.

We still have the same issue in **Customers > Manage Customers > Edit any customer**. Will you create a new PR for Customers?

(PHP 8.1)

**Comment by fballiano** [comment]
I thought it was the same but I’ll check it out asap!

**Comment by fballiano** [comment]
@ADDISON74 I've added the fix for the customer detail page in this PR because it was sharing part of the code ;-)

**Review by ADDISON74 — DISMISSED** [review]
Tested. No more warnings in the exceptions.log file related to the missing payment methods. For both sections in Backend (View Order and Edit Customer).

**Review by ADDISON74 — APPROVED** [review]

**Review by elidrissidev — APPROVED** [review]

**Pull request merged**
