### PR TITLE
Upgraded ZF1Future 1.22.1, Credis 1.15 and some minor dependencies

### PR DESCRIPTION
**Pull request by fballiano**
ZF1F released a new version with one of our patches

### CODE REVIEW

**Review by kiatng — APPROVED** [review]

**Comment by ADDISON74** [comment]
Did we make custom changes in OpenMage related to this issue? If yes, we should remove that PR because ZF1-Future just fixed it in a new release. More details here

**Comment by fballiano** [comment]
This pr already removes one of the patches 😉

**Comment by ADDISON74** [comment]
I'm sorry, I reformulated the paragraph

Did we make custom changes in OpenMage related to this issue?

 - https://github.com/Shardj/zf1-future/issues/274

If yes, we should remove that PR because ZF1-Future just fixed it in a new release. More details here

**Comment by fballiano** [comment]
That one qas just released in zf1f 1.23 one hour ago 😅 but wasnt released in time for this pr so for the time being everything is ok, will check 1.23 in a few days when I’m back 😉

**Pull request merged**
