### PR TITLE
Fix README.md contributors badge

### PR DESCRIPTION
**Pull request by mehdichaouch**
Fix README.md contributors badge, causing the display of badge url code.

### CODE REVIEW

**Comment by colinmollenhour** [comment]
I don't know much about this badge but I think the "101" part of the url is basically meant to be dynamically replaced by the All Contributors bot so this PR would break that. Granted, it is already broken! 😄 #1614

**Comment by mehdichaouch** [comment]
> I don't know much about this badge but I think the "101" part of the url is basically meant to be dynamically replaced by the All Contributors bot so this PR would break that. Granted, it is already broken! 😄 #1614

Oh I understand, by fixing this I maybe brake the bot in charge of changing this dynamically.

**Comment by mehdichaouch** [comment]
**_DON'T MERGE MY PULL REQUEST._**

I read more about **_all-contributors-bot config_**, I think [installation](https://allcontributors.org/docs/en/bot/installation) have to be checked and workflow to [add contributor](https://allcontributors.org/docs/en/bot/usage) was not respected.

**Comment by Flyingmana** [comment]
@mehdichaouch yes there is somewhere a related ticket. We did not "install" the all contributors bot, because it needs write access to the repository, which could be used in a possible supply-chain-attack

**Comment by mehdichaouch** [comment]
So what about the badge, do you have a solution do fix it?
Should I close my PR or not?

**Comment by colinmollenhour** [comment]
> Means, it needs to be manually run and used to create PullRequests

Is this something you could document somewhere very briefly like an internal wiki?

**Comment by fballiano** [comment]
what are we doing with this? it's really ugly to have a broken README

**Comment by Flyingmana** [comment]
Iam ok with merging it for now to fix the obvious error and take care of the automatism separately

**Review by Flyingmana — APPROVED** [review]

**Review by Flyingmana — APPROVED** [review]

**Comment by sreichel** [comment]
@all-contributors add @mehdichaouch doc

**Comment by sreichel** [comment]
@all-contributors add @mehdichaouch doc

**Pull request merged**
