### PR TITLE
Better error handling when store is disabled

### PR DESCRIPTION
**Pull request by luigifab**
This PR add an error message when a store is disabled.

### CODE REVIEW

**Comment by colinmollenhour** [comment]
No objection except, should this be wrapped with the translations helper since it extends `Mage_Core_Exception`?

**Review by kkrieger85 — APPROVED** [review]
LGTM. Thx

**Comment by sreichel** [comment]
> 
> 
> No objection except, should this be wrapped with the translations helper since it extends `Mage_Core_Exception`?

... so translations should be added to csv too.

**Comment by luigifab** [comment]
I added translation.

**Review by sreichel — APPROVED** [review]

**Review by kiatng — APPROVED** [review]

**Review by kkrieger85 — APPROVED** [review]

**Pull request merged**
