### PR TITLE
Fixed broken grids caused by PR #2545

### PR DESCRIPTION
**Pull request by fballiano**
All explained in https://github.com/OpenMage/magento-lts/issues/2545

### CODE REVIEW

**Comment by sreichel** [comment]
Thanks.

Had changed it to for less changes ...

```        /** @var Mage_Eav_Model_Resource_Entity_Attribute_Collection $resource */
        $resource = Mage::getResourceModel($entityType->getEntityAttributeCollection());
        $attributesInfo = $resource
```

**Comment by ADDISON74** [comment]
Tested and it fixes the issue.

**Review by ADDISON74 — APPROVED** [review]

**Review by sreichel — APPROVED** [review]

**Comment by fballiano** [comment]
> Thanks.
> 
> Had changed it to for less changes ...
> 
> ```
>         $resource = Mage::getResourceModel($entityType->getEntityAttributeCollection());
>         $attributesInfo = $resource
> ```

sorry man but i don't get what you said.

I would have re-used the same $attributesInfo variable but it didn't seem that clean (since there's the typehint) so I created attributesInfoData...

**Review by Flyingmana — APPROVED** [review]

**Comment by sreichel** [comment]
@fballiano :+1:

**Pull request merged**
