### PR TITLE
Use FONT_HELVETICA intsead of LinLibertineFont in PDF, ref #86

### PR DESCRIPTION
**Pull request by sreichel**
Credits to @seansan, just merged #272 and #274 and removed commented lines from #86.

### CODE REVIEW

**Comment by tomekjordan** [comment]
does it support all international chars? because I saw som problems and many PDF invoice extensions use Dejavu Sans ...

**Comment by sreichel** [comment]
Not sure about this. #86 is already merged, so this is just to complete/fix this PR.

**Comment by sreichel** [comment]
Not sure about this. #86 is already merged, so this is just to complete/fix this PR.

Think this PR is OK since it fixes (at least) the files size problem.

According to https://magento.stackexchange.com/questions/166205/problem-no1-solved-of-invoice-but-how-to-solve-problem2/166244 magentos `Libertine ` doesnt support all chars too, so its another thing that should be fixed.

**Comment by sreichel** [comment]
I think this could be merged, because it only fixes/completes #86.

If there are any problems with international chars (i guess there are), you can add a new issue.

**Comment by seansan** [comment]
+1 can be merged

Font has always been a problem ;) So one could argue that if using in a very specific language and having formatting issues : that in this case one can manually (re)set the font  

For 99% HELVETICA should work fine

**Pull request merged**
