### PR TITLE
Revert changes in getOrderItem in Mage_Bundle

### LINKED ISSUE #513: getOrderItem don't always return OrderItem
https://github.com/OpenMage/magento-lts/blob/34afee089b4f4c80bf0340fb0c6c9b761b04d48b/app/code/core/Mage/Bundle/Block/Adminhtml/Sales/Order/Items/Renderer.php#L180

If you check this code, I think the logic is not correct.
In the `getValueHtml()` we have the line : 
`$result .= " " . $this->getOrderItem()->getOrder()->formatPrice($attributes['price']);`

And with this call, I have this error : 
```
PHP Fatal error:  Call to a member function formatPrice() on null in .../app/code/core/Mage/Bundle/Block/Adminhtml/Sales/Order/Items/Renderer.php on line 203
```

It seems logic because the `getOrderItem` does not always return an `OrderItem`

### PR DESCRIPTION
**Pull request by maximehuran**
fixes #513

### CODE REVIEW

**Comment by sreichel** [comment]
This was changed because `Mage_Sales_Order_Item` isnt a valid class. I've tested this with different bundled products from our shop and got no errors.

I've no time to teset until the weekend ... instead of revert it, can you please try to change

```
return $this->getItem();
```

to

```
return $this->getItem()->getOrderItem();
```

Thanks.

**Comment by maximehuran** [comment]
Did you try in forcing `isChildCalculated` to false ? 
Because in my case, this is the value of that.

I don't understand the change you want, can you provide a more information ?
You want the change on my code or on the initial ?

**Comment by maximehuran** [comment]
I have the same problem in another project. I will check another time what we can do with this issue

**Comment by maximehuran** [comment]
@sreichel what do you think about my new pull request ?

**Comment by sreichel** [comment]
@maximehuran thanks for this. LGTM. Only annotation seems to be wrong. (should be `Mage_Sales_Model_Order_Item`?)

**Comment by maximehuran** [comment]
@sreichel updated 🎉

**Comment by sreichel** [comment]
Sorry for introducing this with https://github.com/OpenMage/magento-lts/commit/9312e9f6693b9d17fe2927222a7079a1f38c5606 ... none of my product matchedthe criteria. :(

**Comment by sreichel** [comment]
@Flyingmana 

I tired to fix non-existing classs - `if ($this->getItem() instanceof Mage_Sales_Order_Item)`, but did not change the next lines from

    return $this->getItem();

to

    return $this->getItem()->getOrderItem();

It's correct to remove the orignal wrong check against a non existing class.

**Comment by rafaelpatro** [comment]
Hi guys! Will it be reverted?
After applying commit 9312e9f6693b9d17fe2927222a7079a1f38c5606 I'm facing the same issue in my bundle products.
```log
PHP Fatal error:  Uncaught Error: Call to a member function formatPrice() on null in /var/www/app/code/core/Mage/Bundle/Block/Adminhtml/Sales/Order/Items/Renderer.php:203

**Pull request merged**
