### PR TITLE
Theme RWD : transform in M2 LUMA theme and optimize for mobile

### PR DESCRIPTION
**Pull request by Danieleeffe1**
Goodmorning everyone.

Not being a developer my possibilities to contribute to the project are limited however I have converted the RWD theme to a version very close to that of the Magento2 LUMA template

I also tweaked some details to make the template more usable with mobile devices.

You can see an example here

http://test.monsterbox.it

attached the files to be replaced in the RWD template.

The first:
app / design / frontend / rwd / default / themplate / page / html / header.phtml

the second is:
skin / frontend / rwd / default / css / style.css

The third:
skin / frontend / rwd / default / js / app.js

I have not created a complete package to facilitate any checks on modified files

I hope it will be appreciated.

Good work to you all
[styles (1).zip](https://github.com/OpenMage/magento-lts/files/6345247/styles.1.zip)
[app.zip](https://github.com/OpenMage/magento-lts/files/6344415/app.zip)
[header.phtml.zip](https://github.com/OpenMage/magento-lts/files/6344377/header.phtml.zip)

### CODE REVIEW

**Comment by Flyingmana** [comment]
Hi, it seems you messed something up while creating this PullRequest, it uses our 20.0 branch as source for the changes.
Do you have these changes somewhere on Github?

**Comment by Danieleeffe1** [comment]
i don't know how to use github and i don't know how to contribute, this
channel seemed to me the most correct

Il mar 20 apr 2021, 23:28 Daniel Fahlke ***@***.***> ha
scritto:

**Comment by Flyingmana** [comment]
It may be useful to read through https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests as i already suggested in https://github.com/OpenMage/magento-lts/pull/1521
Maybe its also useful to read in general through how to use Git and Github.

As the changes you describe are no simple bugfixes, but more like a redesign I also want to make you aware, that we would not simple modify the existing theme, but it would need to be added as a new theme.

The Pull Request in its current form can not be accepted, and could even lead to mess up things, in case someone would press the "merge" button, so I have to close it.
If you cant apply the changes yourself to create a proper Pull Request, I may ask you to instead do this via an Issue, so one of the other developers can pick it up and cleanly apply it.

**Comment by Danieleeffe1** [comment]
Ti ringrazio

Proverò ad aprire un issues

io affronto il problema della lingua inglese (che conosco ma non così
affondo) essa non mi permette di comprendere a pieno i regolamenti github,
ti ho voluto dare un esempio delle estreme difficoltà scrivendoti nella mia
lingua, inoltre per quel che ho capito la schedulazione che implica la
collaborazione per la realizzazione di un qualsiasi progetto non collima
con me, non ho la "forma mentis" (latino) per fare quello che fate voi.

ho modificato il tema di magento 1 per me per rinnovare quello attuale.

se li volete i file sono quelli da sostituire agli originali.


Il giorno mer 21 apr 2021 alle ore 12:16 Daniel Fahlke <
***@***.***> ha scritto:

**Pull request closed without merging**
