### PR TITLE
[WIP] Remove mysql4 classes

### PR DESCRIPTION
**Pull request by sreichel**
### Description (*)

Just an idea to remove that deprecated mysql4-classes ...

Requires: #2165 

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Comment by ADDISON74** [comment]
It is similar to this one https://github.com/OpenMage/magento-lts/pull/1470. I prefer yours because you created a backup in a repository for all the deleted files to prevent issues with BC. 

You have to agree with @luigifab which one will remain open.

**Comment by fballiano** [comment]
ah! nice idea :-)

and we remove the "require" of this new repo from v20?

**Comment by sreichel** [comment]
> and we remove the "require" of this new repo from v20?
> 
> EDIT: actually why should this be in v19?

Go away :angry: 

I prefer the current workflow with 19.x as the main branch, but it seems that i'm alone. It's WIP ... I'll join discussion about braning later :)

**Comment by ADDISON74** [comment]
However, a migration script and clear and concise information are mandatory. Please check the other PR where this script was also included. A combination of ideas is welcome.

**Comment by sreichel** [comment]
@fballiano i would neither add it to 19.x, nor 20.x.

I'd add it to your release-builder to maintain BC. Everyone who uses composer can add it if necessary.

**Comment by sreichel** [comment]
> However, a migration script and clear and concise information are mandatory. Please check the other PR where this script was also included. A combination of ideas is welcome.

i'm aware of #1470. I think we move into same direction ...

- https://github.com/OpenMage/magento-lts/pull/2526 is part of it (is requierd for my approach)
- https://github.com/OpenMage/magento-lts/pull/2527 is same, i just re-added this classes to an extension

So two things are left. Removal of deprecated xml nodes and migration script?

**Pull request closed without merging**
