### PR TITLE
Added missing functionality for getThumbnailUrl

### PR DESCRIPTION
**Pull request by sreichel**
Return thumbnail URL instead of empty string.

### CODE REVIEW

**Comment by cieslix** [comment]
+1

tested, it works like Mage_Catalog_Helper_Product::getSmallImageUrl or Mage_Catalog_Helper_Product::getImageUrl

**Comment by sreichel** [comment]
Same here ... please check and include into 1.9.3.3 ... it's just the same code that is used for other image URLs.

**Comment by akira28** [comment]
@colinmollenhour shouldn't it be merged in 1.9.3.x branch?

**Comment by colinmollenhour** [comment]
Ahh yes, good catch. Merged.

**Pull request merged**
