### PR TITLE
Mage_Report: Migrate hardcoded cron expressions to configurable field…

### PR DESCRIPTION
**Pull request by sreichel**
### Description (*)

Unable to rebase #1869 i opened a new PR. Thanks @Sekiphp.

### Related Pull Requests

1. Closes OpenMage/magento-lts#1869
2. See OpenMage/magento-lts#2610

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ADDISON74** [comment]
You may close the other one. There is no rush to approve it. I have a few comments related to that PR.

**Comment by elidrissidev** [comment]
Note that Most Viewed cron job is not available in v19, since #1829 was merged to `20.0`.

**Comment by sreichel** [comment]
Then we should port it to 1.9.

**Comment by ADDISON74** [comment]
You can do a cherry pick, there are only two commits.

**Comment by sreichel** [comment]
> You may close the other one. There is no rush to approve it. I have a few comments related to that PR.

I've read your comments ...

- removed "Cron Definition" prefix, but also
- reverted "Cron Settings" to lowercase

ToDo: translation csv

**Comment by sreichel** [comment]
@fballiano why force-pushing ... ???

**Comment by fballiano** [comment]
this does it

Schermata 2022-09-23 alle 20 55 54

**Comment by elidrissidev** [comment]
FYI there's no need to update the branch unless it depends on a commit that was just merged, or if it has a conflict.

**Comment by sreichel** [comment]
I'd prefer merge for already shared commits/PRs ...

**Comment by fballiano** [comment]
You prefer merge but in the past i was told not to use merge cause it creates another commit so you know.. whatever.

**Comment by sreichel** [comment]
https://medium.com/@fredrikmorken/why-you-should-stop-using-git-rebase-5552bee4fed1

**Comment by fballiano** [comment]
Again, not my opinion and there is no official rule for that.
Anyway github checks for conflicts before so at least the first half of the article is not really applicable.
I try to follow what maintainers tell, and for maaaany things there are no rule, but then everybody complains anyway.

**Comment by sreichel** [comment]
> Again, not my opinion and there is no official rule for that. 

This is why i just said _i'd prefer_ .... whatever.

**Comment by fballiano** [comment]
It’s confusing and frustrating to get told different things when you just want to follow and honor previously made work.
A lot of things should be decided by maintainers and told in a clear way to the others.
When you comment like “why did you do that” with three exclamation marks it’s like the other person did such a stupid mistake, and it’s simply not the case.

**Comment by sreichel** [comment]
@fballiano big sorry. It was not meant rude. I justed wondered why "force-push" is used since some time. If someone suggested to use this ... okay.

**Comment by ADDISON74** [comment]
@sreichel - Why did you close this PR?

**Comment by sreichel** [comment]
It was closed after deleting my fork.

**Comment by ADDISON74** [comment]
10 PRs closed instantly. Will we miss you again?

**Comment by sreichel** [comment]
Dont know yet ... depends on @Flyingmana.

One thing is for sure this time, there is no going back.

**Comment by fballiano** [comment]
@sreichel I think I can speak for some of us here and we love and appreciate what you did all this time, it is in immense work. I sincerely hope you may want to stay for all of us instead of leaving for one. I'll write you tomorrow morning.

**Comment by sreichel** [comment]
Thanks. You may not know, i dont run a OM store. I'm not employeed to work on OM stores. This is 100% spare time activity.

**Comment by kiatng** [comment]
@sreichel https://open.spotify.com/track/5WUgOOaTk00PnksDekcgcg?si=2f76306137f84076

**Comment by sreichel** [comment]
@kiatng :heart: 

I love this community, it's fun to move the project forward, but it's not fun to be bothered with "stuff" like this. Thank you.

**Comment by sreichel** [comment]
5zm1j9

... not this time. Good luck guys.

(at Daniel ... last year i retiered for same reason. You claim to be to the most important, doing things that nobody sees - but not doing things that everybody sees. When i asked for the sponsorship-button you was the first and only one who wanted to get listed ...)

**Pull request closed without merging**
