### PR TITLE
Updated PHPStan to 1.11.2

### PR DESCRIPTION
**Pull request by fballiano**

### CODE REVIEW

**Comment by fballiano** [comment]
@Flyingmana @Sdfendor @kiatng could you take a look at this?

**Review by boesbo — APPROVED** [review]

**Comment by fballiano** [comment]
I've retested this (mostly where the parent::construct() was removed, becuase the parent contructor is empty), just to be safe, can't see any problem.

I'll merge it.

**Comment by F1Red5** [comment]
@fballiano we have a modified abstract class Mage_Catalog_Model_Product_Type_Abstract with some custom code in save() method. With the removal of parent::construct() it does not work anymore. Can you please revert it?

**Comment by fballiano** [comment]
@F1Red5 could you override also the child class? I've removed it because phpstan complained that it's useless

**Pull request merged**
