### PR TITLE
Fix doc getCountry - returning string instead of int

### PR DESCRIPTION
**Pull request by Sekiphp**
### Description (*)
Fixing wrong ducumentation of method `getCountry`. This method returing `string` instead of `int`.

image

Database definition:
```mysql
`country_id` varchar(2) DEFAULT NULL COMMENT 'Country Id',
```
### Manual testing scenarios (*)
*not necessary*

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by kiatng — APPROVED** [review]

**Comment by luigifab** [comment]
Why you have pushed 5 commits? 👀

**Comment by midlan** [comment]
worth to note that it might return string that contains integer

**Comment by sreichel** [comment]
Thanks.

I know, not all of the DOC block changes/additions have been tested. This was just not possible for thousands of changes.

Correction/fixess are planed (#784) , but  there is no time ATM. Thanks for your commit, :)

**Review by sreichel — APPROVED** [review]

**Review by LukasCesal — APPROVED** [review]

**Review by colinmollenhour — APPROVED** [review]

**Review by fballiano — APPROVED** [review]

**Comment by fballiano** [comment]
let's merge it and get rid of it no?

**Pull request merged**
