### PR TITLE
Github workflows now run on PHP 8.1

### PR DESCRIPTION
**Pull request by fballiano**
If https://github.com/OpenMage/magento-lts/pull/3160 gets approved then this PR will change all github workflows to run on PHP 8.1 minimum.

### CODE REVIEW

**Comment by sreichel** [comment]
As long as 7.4 is supported, id not change this.

**Comment by fballiano** [comment]
as I wrote in the PR description, if https://github.com/OpenMage/magento-lts/pull/3160 gets approved.

**Comment by sreichel** [comment]
So we have differentt workflows for "main" and "next" (and "v19")?

**Comment by fballiano** [comment]
the push/pr workflows run on their own branch configuration

**Comment by fballiano** [comment]
this is why this PR's "checks" have only php 8.1/8.2 while the others stay normal with php 7.4

**Review by kiatng — APPROVED** [review]

**Pull request merged**
