### PR TITLE
Add PHPMD to workflow

### PR DESCRIPTION
**Pull request by sreichel**
### Description (*)

Added PHPMD to worklow.

### Related Pull Requests

1. See OpenMage/magento-lts#2771

### Manual testing scenarios (*)

1. `ddev phpmd <path>`

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Comment by ADDISON74** [comment]
@sreichel - Nice to see you creating PRs. Please note there are 1225 warnings reported by PHPMD. Is it OK?

**Comment by sreichel** [comment]
@ADDISON74 it's okay. Warnings should be fixed before it gets merged, but ... I recognized that I can't comment or even review PRs made by fab ... I'm done.

**Comment by ADDISON74** [comment]
@sreichel - This year has been the most challenging for me so far. Even though I have an age and life experience I can say I was not prepared for this but I must survive and try to find my balance. It is damn hard. The day when one of the most important people in my life died, I had the strength to post here. He liked to know that I was involved in various projects and through what I do I honor his memory. In addition, his loss produced a revelation for me, I saw for the first time things that, although I felt, I never gave importance to them.

What is more important to you? To offer your experience and dedication in a project like OpenMage or rivalry with certain people? Evolution does not mean running away every time there are problems, but facing them and being better with yourself and others.

**Comment by fballiano** [comment]
I don't have any rivarly, I blocked him because I was insulted many, many, many times by hum publicly and I had to deal with the stress of this behavior. Did I receive an apology or something? Z.E.R.O.
At least this way I don't have to receive notifications of his sarcastic comments at midnight, screwing with my sleep and life.

**Comment by ADDISON74** [comment]
My opinion is that both of you would do well to reflect on your actions. If there is a God, I honestly appreciate how HE can love us all unconditionally no matter how stupid we do. I will delete these messages in a few days.

**Comment by sreichel** [comment]
@ADDISON74 i can't comment or review PRs from fab ... that's a no-go.

**Comment by ADDISON74** [comment]
@sreichel - I am sorry about this. 

@fballiano - I hope you don't mind me, but I try to be impartial. The decision to exclude Sven had to be discussed in the community, based on the accusations brought against him and to have a point of view from his side. I was left with the impression that @Flyingmana banned him for a short time, but I note that it is permanent and is based on your unilateral decision. I didn't hesitate to express my opinion and I tried to be the best possible mediator, but we have to make a distinction between the project and personal feelings. however, some of Sven's statements were correct, I approved some PRs without doing a more in-depth analysis of them. I corrected that in the meantime, but I didn't mind his observation in any way. There was a small guy in a galaxy far, far away who said that hatred brings suffering, we should return to peaceful feelings. A lesson for everyone.

**Comment by fballiano** [comment]
MY UNILATERAL DECISION!!!!??????????????????? THIS IS TRULY BECOMING NUTS!!!!!!!!!!!!!!!!!

I DIDN'T DO ANYTHING ABOUT THAT!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

I'M TIRED OF THIS SHIT!!!!!!!!!!

I WAS INSULTED MULTIPLE TIMES AND YOU ARE ACCUSING ME!!!!!!!!!!?????????????????''

**Comment by fballiano** [comment]
WHAT CAN YOU BOTH NOT UNDERSTAND ABOUT "I BLOCKED HIM ON MY PERSONAL ACCOUNT" BECAUSE OF HIS MULTIPLE INSULTS?????

MY
PERSONAL
ACCOUNT!!!

DO I HAVE ANY FREEDOM OF STOPPING SOMEBODY FROM KEEPING INSULTING ME?????

**Comment by fballiano** [comment]
@colinmollenhour @Flyingmana @kiatng @elidrissidev @tmotyl this has to be addressed now.

**Comment by sreichel** [comment]
@fballiano you can block me on your personal accout, but actually i cant even review or comment your PRs in this repo.

**Comment by ADDISON74** [comment]
@fballiano - I am sorry to hear that. If he insulted you in private, you could block him there, not in the project. Also, you could open a discussion on this topic with proves that he attacks you in private. 

I didn't accuse you of anything and I don't like that you write the word "shit" in a reply to me. I don't deserve such an answer and I have no claim to any apology over a while. If you ended up writing in capital letters and making it a personal problem, it means that things are irremediable. Sven is not Baba Yaga, I can't believe how far this discussion has come.

As for me, I will take a break for a while, it was an unpleasant experience that happened today. At any time I or someone else can end up in the same situation of being excluded, and then why do we contribute?

**Comment by Flyingmana** [comment]
> I was left with the impression that @Flyingmana banned him for a short time, but I note that it is permanent and is based on your unilateral decision.

@ADDISON74 please contact me via Discord or Mail about this (I dont have your direct contact on hand)
There is apparently a strong misunderstanding, and this is not the right place to discuss such things.

**Pull request closed without merging**
