### PR TITLE
Cosmetic changes to backend footer

### PR DESCRIPTION
**Pull request by fballiano**
@ADDISON74 suggested some changes to the footer of the backend, which I liked a lot coded in this PR.

Screenshot of before and after here in the original discussion https://github.com/OpenMage/magento-lts/discussions/2428

This is taken now from my local dev environment:
Schermata 2022-08-23 alle 23 00 22

Notes:
- I cleaned a minor detail in the javascripts (there was a js changing the target of the links... I removed that)
- the strings changed weren't in any CSV file, so at the moment I didn't put them in any

### CODE REVIEW

**Review by sreichel — DISMISSED** [review]

**Comment by ADDISON74** [comment]
Please add translations for the new strings. Maybe there are some who want to translate the links.

**Comment by ADDISON74** [comment]
Please correct the capital letter for A: "Report **A** Bug" => "Report **a** Bug". It looks ugly and in the interface short words 1 - 2 letters are not capitalized.

**Comment by fballiano** [comment]
done, but I kinda don't like the uncapitalized "a", or better said, I don't like the uppercase "Bug" actually

**Review by ADDISON74 — APPROVED** [review]

**Comment by ADDISON74** [comment]
Just analyze all the strings in the Backend. The Magento team used words in sentences that start with a capital letter, for example "Enable Contact Us". Even if I don't agree, I tried not to feel my presence where I made changes, still there are people who have been using the platform for maybe 12 years and then immediately notice the changes and are not exactly happy.

**Comment by sreichel** [comment]
> I don't like the uppercase "Bug" actually

The uppercase B is for "BIG Bugs only" ... :rofl:

**Comment by ADDISON74** [comment]
Report Bugs ... Bunny.

**Comment by fballiano** [comment]
makes sense

**Review by sreichel — APPROVED** [review]

**Comment by ADDISON74** [comment]
I think it's better to remove that "a" from the sentence. "Report Bug" is more appropriate.

**Comment by sreichel** [comment]
- Report a Bug
- Report Bug
- Report Bugs
- Report any Bug

This is not Starship Troopers :point_up: 

I'm [Buggin out](https://www.youtube.com/watch?v=P9oTCzWRuvQ) :P

PS: agree with @ADDISON74

**Comment by ADDISON74** [comment]
Maybe we should leave the PRs to ferment for at least 1-2 days and not put them in the oven too quickly.

**Comment by fballiano** [comment]
true, sometimes we move to fast, sometimes too slow :-)

I'll do another small PR and we can decide the wording we like best :-)

**Pull request merged**
