### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by sreichel**
### Description (*)

Some minor changes.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Review by ADDISON74 — APPROVED** [review]

**Comment by ADDISON74** [comment]
In my case I am not a maintainer who has responsabilities. The actual role is just fine.

**Comment by sreichel** [comment]
You are also responsible with every review or comment you do :stuck_out_tongue:

**Comment by elidrissidev** [comment]
Thanks :)

**Review by fballiano — APPROVED** [review]

**Comment by fballiano** [comment]
directly merged this to 20.0 too since there were no conflicts

**Pull request merged**
