### PR TITLE
Better wording for adminhtml footer

### PR DESCRIPTION
**Pull request by fballiano**
In https://github.com/OpenMage/magento-lts/pull/2482 we changed adminhtml's footer a little bit, but at the end we didn't like the "Report a Bug" wording, which is fine as a meaning, but not very beautiful to see (because of the lowercase "a"), so with this PR we're trying to address this word.

This is my idea:
Schermata 2022-08-24 alle 11 20 15

Alternatives:
- Report Bug (I don't know why but the singular "bug" sounds weird in my head without the "a" in front)
- Report Bugs (my first choice for this PR)
- Bug Report (now that I see I probably prefer this among all of them)

let's see :-)

### CODE REVIEW

**Comment by sreichel** [comment]
> Alternatives:

Uppercase "bug/bugs"? :rofl: 

> Bug Report (now that I see I probably prefer this among all of them)

I'd prefer this to.

**Comment by fballiano** [comment]
Switched to "Bug Report"

**Comment by ADDISON74** [comment]
The meaning is slightly different "Report Bug" refers to an action you can take, while "Bug Report" refers to a bug report, something existing, listed. This is where I think of my old friend named Bugtracker.

The form Bug is preferable to Bugs.

As a great programmer well said, often the little things kill us.

**Review by kiatng — APPROVED** [review]

**Comment by fballiano** [comment]
then I don't know what to do :-D

**Comment by sreichel** [comment]
> while "Bug Report"

@ADDISON74  :+1:  For my reading this link tells me DO a bug report ...

**Comment by ADDISON74** [comment]
If we approve it now we will certainly come up with another change. We can still advise each other in the meantime, honestly speaking I noticed that the initial wording "Report a Bug" doesn't look good at all in the link, So I got here, but I don't have a final solution. it is true that this wording "Report a Bug" was the most appropriate, clear and concise. 

However, if I look at the two links, one refers to a community and the other to a report, it would also go to Bug Report. If I were to go further, we are not particularly interested in a bug, as that implies an error in the code, but rather to report any issue that has arisen, another wording would be "**Report Issues**".

**Comment by fballiano** [comment]
To me "Bug Report", "Report Bugs" or "Report Issues" are same so any of those is totally fine with me :-)

**Comment by ADDISON74** [comment]
I haven't checked the link which page loads, but of course it should direct here ```https://github.com/OpenMage/magento-lts/issues```.

We have the word issues in the link, in the name of the GitHub section, in which case I would go with the option "Report Issues". Issues is a word that covers many aspects.

**Comment by fballiano** [comment]
yes the link is to https://github.com/OpenMage/magento-lts/issues is "Report Issues" makes total sense, I switched the code already

**Comment by ADDISON74** [comment]
Related to the first link. I noticed that it takes me to the https://www.openmage.org page, then it could be renamed as "OpenMage Project". If it is about community then I think it would be more appropriate to take it to the GitHub Discussions section.

**Comment by fballiano** [comment]
actually, since the website is really less maintained... I'd prefer a "OpenMage Project" that directly links to https://github.com/OpenMage/magento-lts/

**Comment by ADDISON74** [comment]
@fballiano - Please add the changes for the first link (OpenMage Project). What I am seeing in this PR are only two files changed related to the second link.

**Comment by ADDISON74** [comment]
In file ```/app/design/adminhtml/default/default/template/page/footer.phtml``` I would change in **line 25**: 

```php
<a href="<?php echo $this->getConnectWithOpenMageUrl() ?>" target="_blank"><?php echo $this->__('OpenMage Project') ?></a> |
```

In file ```/app/design/adminhtml/default/default/layout/main.xml``` I would change in **line 130**: 

```xml
<action method="setConnectWithOpenMageUrl"><url>https://github.com/OpenMage/magento-lts</url></action>
```

A summary of the changes:

OpenMage Community => OpenMage Project

getConnectwithMagentoUrl() => getConnectwithOpenMageUrl()

https://www.openmage.org/ => https://github.com/OpenMage/magento-lts

**Comment by fballiano** [comment]
done, let's see what people think about this :-)

**Comment by ADDISON74** [comment]
This method name should be changed from setConnectWithMagentoUrl to setConnectWith
OpenMageUrl. Please check my previous post.

**Comment by fballiano** [comment]
changing method names always get people upset, don't know

**Comment by sreichel** [comment]
- add new method
- mark old as deprecated and forward to new one

(Sorry for short answer... writing from phone)

**Comment by fballiano** [comment]
> * add new method
> * mark old as deprecated and forward to new one

super nice.

in this case not needed (sorry, a little tired now), since it's not a real method but a getter/setter call, so I've changed both in the xml and the phtml, shoudln't be a problem.

**Review by kiatng — DISMISSED** [review]
I love it.

**Comment by sreichel** [comment]
> > * add new method
> > * mark old as deprecated and forward to new one
> 
> super nice.
> 
> in this case not needed (sorry, a little tired now), since it's not a real method but a getter/setter call, so I've changed both in the xml and the phtml, shoudln't be a problem.



> > * add new method
> > * mark old as deprecated and forward to new one
> 
> super nice.
> 
> in this case not needed (sorry, a little tired now), since it's not a real method but a getter/setter call, so I've changed both in the xml and the phtml, shoudln't be a problem.

What about other admin themes that have used `getConnectWithMagentoUrl()` in footer?

**Comment by sreichel** [comment]
> done, let's see what people think about this :-)

What i think ... someone spent a lot of time for bringing up openmage.org, but it seems unmaintained :(

Any ideas how to show at least release notes there?

**Review by kiatng — DISMISSED** [review]
Nice.

**Comment by ADDISON74** [comment]
I agree that changing a method is a wrong practice related to Magento, but in this case it is questionable only in terms of whether it is used somewhere else. There are very, very small chances to be used by someone in any theme or extension. However, I appreciate that the initial form has been preserved and new methods have been added. I think this PR is backed. Any other suggestions?

**Comment by fballiano** [comment]
Thanks @sreichel for the changes, you're on a whole other level 😊

I'd like to pause just a sec about changing the link to the openmage.org to the github, I don't want to downplay the official website, it's just that there's obviously less effort put into it compared to the github activity and it's probably nice to click on the link and see that the project is super alive. But I don't want to force this change or upset somebody else over this so let's do it only if we think it's a benefit for the people that are going to click on the link and for openmage itself :-)

**Comment by sreichel** [comment]
> but in this case it is questionable only in terms of whether it is used somewhere else. There are very, very small chances to be used by someone in any theme or extension.

My objection did not come from nowhere. Someone may have a custom footer, with internal links added. 

> I don't want to downplay the official website

I deleted my comment b/c it was not related to your PR. It was just a general observation. I completly okay with linking to github.

**Comment by Sdfendor** [comment]
I for one would have been affected by this change without having the deprecated old methods. We have an overriden `footer.phtml`. Thanks @sreichel.  I like the current solution.

**Comment by ADDISON74** [comment]
If I look at the last version of this PR, changes have already been made and new methods have been created for the links. Those using custom versions of footer.phtml should not be affected. I did a test and I didn't identify any issue between the initial version that I used as custom and the version in this PR.

**Comment by ADDISON74** [comment]
The only aspect I would like to discuss before approval would be the link to the OpenMage Project. 80% of my decision are for https://www.openmage.org. Practically on this page there is a presentation of the project, at the same time there is also a link to other resources such as GitHub. I would like to hear @flyingmana's opinion.

**Comment by fballiano** [comment]
I've reverted the link back to openmage.org, changing that link target should probably be discussed elsewhere :-)
I think this PR is safe now and could be merged

**Review by ADDISON74 — APPROVED** [review]

**Review by sreichel — APPROVED** [review]

**Pull request merged**
