### PR TITLE
Fixed row click issue in product's upsell/crosssell/related grids

### PR DESCRIPTION
**Pull request by ADDISON74**
When you add/remove/set position in the **Related Products / Up-sells / Cross-sells** grids, you may face an important issue without realizing it. As the grid functionality was thought by the Magento team, when you click on a row, regardless of the position where the mouse pointer is, the row will be checked or unchecked. As soon as you press any of the [Save] buttons, products may appear or disappear in the grid by mistake. I faced this issue many times when I was editing the position and I didn't click exactly in the box but a little next to it.

related

This PR solves the issue and limits the row click strictly to the grid cell where the checkbox is (the first column). Unlike the Products grid, where the box must be checked strictly in the square, otherwise the product editing page is loaded, this modification is more permissive and the click can be in the entire cell where the box is located (td element).

### CODE REVIEW

**Comment by ADDISON74** [comment]
@fballiano - I created this PR directly in Github. There are two commits coming from a previous PR. Please fix this issue for me. Thank you.

**Comment by ADDISON74** [comment]
For this one 

/js/mage/adminhtml/grid.js

**Comment by ADDISON74** [comment]
Many thanks. This one is ready for testing.

**Review by andrewcbi — APPROVED** [review]

**Comment by andrewcbi** [comment]
Thank you for this one!

**Review by fballiano — APPROVED** [review]
tested, works. couldn't find any other grid affected by this change

**Pull request merged**
