### PR TITLE
prepare Travis for release of php 7.3

### PR DESCRIPTION
**Pull request by Flyingmana**
not sure if it is already supported by travis, but having the PR does not hurt and makes it easy to check

### CODE REVIEW

**Comment by Flyingmana** [comment]
so php 7.3 is not ready yet
`The command "phpenv global 7.3" failed and exited with 1 during .`

so waiting for https://github.com/travis-ci/travis-ci/issues/9717 I guess

**Comment by colinmollenhour** [comment]
Looks like 7.3 is not supported or otherwise broken on Travis:

```
7.3 is not pre-installed; installing
Downloading archive: https://s3.amazonaws.com/travis-php-archives/binaries/ubuntu/14.04/x86_64/php-7.3.tar.bz2
0.17s$ curl -s -o archive.tar.bz2 $archive_url && tar xjf archive.tar.bz2 --directory /
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

**Comment by Flyingmana** [comment]
Yeah, will probably still take some time, the linked Issue is still open. I would say we wait and test from time to time if travis runs through

**Comment by Flyingmana** [comment]
support is in on travis side now.
We just need to remove the __autoload function now from source

**Comment by colinmollenhour** [comment]
Just FYI, `__autoload` is removed in #557

**Pull request merged**
