### PR TITLE
Remove the word section

### PR DESCRIPTION
**Pull request by luigifab**
### Description

This useless PR remove the word section in System / Permissions / Roles / Role Resources, and it reduce number of translations used in OpenMage

before after

So, we have the same names here and in System / Configuration.
Next PR is to sort them same.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Comment by fballiano** [comment]
will this break every language pack?

**Comment by luigifab** [comment]
No, all translations already exists. Same idea as #1359.

**Comment by ADDISON74** [comment]
A good remark for most of us who have learned with some Backend visual errors. I agree with the removal of the word Section because it is simply useless.

**Comment by fballiano** [comment]
> No, all translations already exists. Same idea as #1359.

mmm it seems to me that, done this way, all language packs will be broken.

**Comment by luigifab** [comment]
Why? I replace some strings with other existing strings, and I removed unused translations.

**Comment by fballiano** [comment]
But existing language packs won't have those keys so they'll lose those translation, if I'm not mistaken.

**Comment by luigifab** [comment]
Yes, but if they have "Catalog Section" (used 1 time) and not "Catalog" (used multiple times), that's a scandalous.

**Review by fballiano — APPROVED** [review]

**Review by ADDISON74 — DISMISSED** [review]

**Comment by luigifab** [comment]
Conflict resolved!

**Review by ADDISON74 — APPROVED** [review]

**Review by fballiano — APPROVED** [review]

**Pull request merged**
