### PR TITLE
Apc to apcu

### PR DESCRIPTION
**Pull request by f1-outsourcing**
### Description (*)
changes for apcu

### Fixed Issues (if relevant)

1. Fixes OpenMage/magento-lts#<issue_number>

### Manual testing scenarios (*)
Just enabling the apc backend in the config like this, should give you some caching already.

     28 <config>
     29     <global>
     30         
     32         <cache>
     33             <backend>apc</backend>
     34             <prefix>uo_</prefix>
     35             <auto_refresh_fast_cache>0</auto_refresh_fast_cache>
     36         </cache>

apcu

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)
 - [ ] Add yourself to contributors list

### CODE REVIEW

**Comment by Flyingmana** [comment]
you need to keep the changes in different branches, for different Pull Requests. It seems you mixed in another change here.

**Comment by f1-outsourcing** [comment]
> you need to keep the changes in different branches, for different Pull Requests. It seems you mixed in another change here.

any idea how to correct this?

**Comment by elidrissidev** [comment]
@f1-outsourcing `git checkout -b update-apc-to-apcu upstream/1.9.4.x` then add and commit your change.
This will create branch `update-apc-to-apcu` from `1.9.4.x` branch in a remote called `upstream`(replace if you named it differently)

**Comment by elidrissidev** [comment]
@f1-outsourcing `git reset HEAD~2`, this will remove the last two commits and keep the changes in your working tree. You then have to remove the other template variable change and do a commit. Then force-push `git push -f`

**Comment by elidrissidev** [comment]
You may wanna consider adding your author details to git in your machine before doing the above, so commits are properly attributed to you if a PR is merged.
`git config user.name "your name"`
`git config user.email "your email"`

**Comment by ADDISON74** [comment]
We need to look at this PR in detail before it is merged. apc word appears in many files. Changing **apc_fetch** to **apcu_fetch** could affect functionality as apc_fetch I found it in this file lib/Zend/File/Transfer/Adapter/Http.php.

**Pull request closed without merging**
