### PR TITLE
:heart: for contributors

### PR DESCRIPTION
**Pull request by kkrieger85**
Add all-contributors-bot config
Add placeholder to README.md
Add contributors as they are listed in https://github.com/OpenMage/magento-lts/graphs/contributors

### CODE REVIEW

**Comment by sreichel** [comment]
Nice one :heart:

**Comment by tmotyl** [comment]
How does it work, what is the benfit over github contributors page of the repo?

**Comment by sreichel** [comment]
> 
> 
> How does it work, what is the benfit over github contributors page of the repo?

It looks like .... https://github.com/kkrieger85/firegento-debug (end the and of the page)

Benefit .... an automated - nicer - contributer list. If i had time for, i'd had made same PR on my own.

**Comment by sreichel** [comment]
Someone should have get a request for installing this bot here ...

**Comment by kkrieger85** [comment]
> Someone should have get a request for installing this bot here ...

@Flyingmana

**Comment by kkrieger85** [comment]
@sreichel not yet automated. I'll look for the github workflow to automate this

**Comment by kkrieger85** [comment]
After the bot is installed, you can let the bot create PR to add more contributors:

Basic usage: Add comment to PR/Issue  `@all-contributors please add <username> for <contributions>`

Contribution types are listed there: https://allcontributors.org/docs/en/emoji-key
We could also define custom types

**Comment by kkrieger85** [comment]
@Flyingmana @tmotyl enough reviews. Please merge

**Comment by boesbo** [comment]
@sreichel How can I request my inclusion among the contributors?

**Comment by sreichel** [comment]
@boesbo the contributors-bot ins't installed (yet). Please check #1126 for updates .... but I guess you'll be added automatically.

**Comment by kkrieger85** [comment]
@boesbo unfortunately the contributors-bot is not working as expected for this repository. 
I'll add a guide on how to manually add yourself

**Comment by kkrieger85** [comment]
@all-contributors please add @boesbo  for code

**Pull request merged**
