### PR TITLE
Mage_Report: Migrated hardcoded cron expressions to configurable fields

### PR DESCRIPTION
**Pull request by Sekiphp**
### Description (*)
Replaced hardcoded cron expressions to system configurable with same default values. Please, see the image below:
image

### Related Pull Requests
https://github.com/OpenMage/magento-lts/pull/1829

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)
 - [ ] Add yourself to contributors list

### CODE REVIEW

**Comment by elidrissidev** [comment]
The related PR is merged, you may now rebase and comment out the other changes

**Review by luigifab — COMMENTED** [review]
Can you add the new translations in CSV files?
Can you add a dot at the end of comments?
Can you add in comments the default value?
Edit: since, #2148, can you remove `<frontend_type>text</frontend_type>` for added configuration?

**Comment by fballiano** [comment]
> The related PR is merged, you may now rebase and comment out the other changes

rebased

**Comment by ADDISON74** [comment]
I would revise the labels and comments for this PR. @luigifab also requested a few good changes.

Once we agree the labels and comments we can add the translation phrases.

**Comment by fballiano** [comment]
I've removed the frontend_type and uncommented the commented part of the xml

**Comment by fballiano** [comment]
> Can you add the new translations in CSV files?

This point still has to be done

**Comment by ADDISON74** [comment]
I'm also waiting for the small change requested from "Cron settings" to "Cron Settings" but I have to insist because it is left to wait..

**Comment by fballiano** [comment]
I did it for you (you could do it anyway since this PR is modificable)

**Comment by ADDISON74** [comment]
Indeed, I can create a commit with the change. Good tip.

Before adding new translations, it would be good to discuss their wording. Since we are in a cron setting section I don't think there is a need for "Cron definition -" prefix. Bestsellers is just fine. Maybe the labels under the boxes need to be analyzed, maybe even removed.

**Comment by sreichel** [comment]
Can this be merged to 19.x?

**Comment by ADDISON74** [comment]
> Can this be merged to 19.x?

I don't think it would create a problem. a rebase must be done.

I will take care of the Backend part because it requires some additions.

**Comment by sreichel** [comment]
Ii'm to stupid to rebase this. :(

How to change target version for PRs?

**Comment by fballiano** [comment]
To v19?

**Comment by sreichel** [comment]
Yes.

**Comment by fballiano** [comment]
I guess you tries already editing the PR with the github web and broke everything right?

**Comment by sreichel** [comment]
Tried different things ... last error as i tried to update upstream repo .... `[remote rejected] (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/static-code-analyses.yml` without `workflow` scope)`

It would take 2 min to edit 7 files manually ... lol.

**Comment by elidrissidev** [comment]
> last error as i tried to update upstream repo .... `[remote rejected] (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/static-code-analyses.yml`without`workflow` scope)`

Your personal access token is lacking the `workflow` permission

**Comment by ADDISON74** [comment]
There is no rush to approve it. I'll have a few comments related to that PR.

**Comment by ADDISON74** [comment]
Sven created another PR here https://github.com/OpenMage/magento-lts/pull/2595 that had all the changes, but he chose to close it. I allowed myself to make the necessary changes to move forward.

Here you can see the image as it looks in the Backend. 

screenshot

In my opinion, it is fine, but there are two other aspects that I would like to discuss.

1. That VS I think refers to versus. "vs" should be written in lowercase letters

2. Shouldn't we have a default value for the "Most Viewed" field, similar to the others?

If we clarify these aspects, it can be approved.

**Comment by ADDISON74** [comment]
Shipping should be replaced by Shipped.

**Comment by ADDISON74** [comment]
The interface looks good now. See the screenshot above.

The only issue I would like to discuss before approving is related to the **"Most Viewed"** field. Shouldn't we set up a default value for it?

From what I can see, it takes the value from this PR #1823, but I think it's better to put a value in the box, similar to the others.

**Comment by fballiano** [comment]
@ADDISON74 I implemented this change also for the most_viewed report:

Screenshot 2023-07-12 alle 12 10 44

;-)

**Review by fballiano — APPROVED** [review]

**Comment by ADDISON74** [comment]
Excellent. I will test today if those values work when they are changed then I will approve it.

**Comment by ADDISON74** [comment]
We can merge this PR, it works as expected.

**I changed all values to ```*/2 * * * *``` in order to run the cron every 2 minutes.**

screenshot_1

**cron_schedule table has a lot of records like aggregate_**

screenshot_2

**By reloading the "Refresh Statistics" page on the "Update At" column the time is changing**

screenshot_3

**Review by ADDISON74 — APPROVED** [review]

**Comment by ADDISON74** [comment]
Shall we mention for every field in comment the default value 0 0 * * *? I have to take a look in the Backend for similar fields.

**Pull request merged**
