### PR TITLE
Prevent bad controller to expose adminhtml URL

### PR DESCRIPTION
**Pull request by fballiano**
This PR is replacing https://github.com/OpenMage/magento-lts/pull/1077 to implement the modifications requested by other maintainers.

As explained from the original author this PR is to avoid to expose the adminhtml login url from a controller.

### CODE REVIEW

**Comment by kiatng** [comment]
How to test this?

**Comment by luigifab** [comment]
I tried, but I don't understand how it is possible to see login page:

```diff
diff --git a/app/code/community/Cm/Test/controllers/Test1Controller.php b/app/code/community/Cm/Test/controllers/Test1Controller.php
new file mode 100644
index 0000000000..50b43325ba
--- /dev/null
+++ b/app/code/community/Cm/Test/controllers/Test1Controller.php
@@ -0,0 +1,9 @@
+<?php
+
+class Cm_Test_Test1Controller extends Mage_Adminhtml_Controller_Action
+{
+    public function testAction()
+    {
+        $this->getResponse()->setBody('test1 back');
+    }
+}
diff --git a/app/code/community/Cm/Test/controllers/Test2Controller.php b/app/code/community/Cm/Test/controllers/Test2Controller.php
new file mode 100644
index 0000000000..950dbb0a32
--- /dev/null
+++ b/app/code/community/Cm/Test/controllers/Test2Controller.php
@@ -0,0 +1,9 @@
+<?php
+
+class Cm_Test_Test2Controller extends Mage_Core_Controller_Front_Action
+{
+    public function testAction()
+    {
+        $this->getResponse()->setBody('test2 front');
+    }
+}
diff --git a/app/code/community/Cm/Test/etc/config.xml b/app/code/community/Cm/Test/etc/config.xml
new file mode 100644
index 0000000000..015ffb4d6e
--- /dev/null
+++ b/app/code/community/Cm/Test/etc/config.xml
@@ -0,0 +1,30 @@
+<?xml version="1.0"?>
+<config>
+    <modules>
+        <Cm_Test>
+            <version>1.0.0</version>
+        </Cm_Test>
+    </modules>
+    <admin>
+        <routers>
+            <route_name>
+                <use>admin</use>
+                <args>
+                    <module>Cm_Test</module>
+                    <frontName>routeback</frontName>
+                </args>
+            </route_name>
+        </routers>
+    </admin>
+    <frontend>
+        <routers>
+            <route_name>
+                <use>standard</use>
+                <args>
+                    <module>Cm_Test</module>
+                    <frontName>routefront</frontName>
+                </args>
+            </route_name>
+        </routers>
+    </frontend>
+</config>
\ No newline at end of file
diff --git a/app/etc/modules/Cm_Test.xml b/app/etc/modules/Cm_Test.xml
new file mode 100644
index 0000000000..bc26c8ef51
--- /dev/null
+++ b/app/etc/modules/Cm_Test.xml
@@ -0,0 +1,8 @@
+<config>
+  <modules>
+    <Cm_Test>
+      <active>true</active>
+      <codePool>community</codePool>
+    </Cm_Test>
+  </modules>
+</config>
```
(bellow default is the store code)
- https://.../test1/index.php/default/routeback/test1/test/ => 404
- https://.../test1/index.php/default/routefront/test2/test/ => 200 ok

**Comment by fballiano** [comment]
I tried to reproduce the problem in the previous PR and couldn't. Since I can't understand exactly what the original PR and the comments are about, I'm closing it.

Thanks @luigifab for your comment on this.

**Comment by ADDISON74** [comment]
As I see this PR did not include @colinmollenhour suggestion from PR #1077. Unfortunately I did not analyze that PR to express a personal opinion. If Colin would enlighten us a little in this regard we would make a safe decision to maintain or close this PR which could prevent a security breach.

**Comment by colinmollenhour** [comment]
I don't know how to reproduce the claimed vulnerability either.. So not sure what to say... @wexo-team can you opine?

**Pull request closed without merging**
