### PR TITLE
Admin config: added input validation & hide disabled options

### PR DESCRIPTION
**Pull request by sreichel**
Do not render options for disabled sections (e.g. disabled payment methods).

Added some input-validation to enforce number/digit imput.

### CODE REVIEW

**Comment by empiricompany** [comment]
please provide a description including the reason of this PR

**Comment by ADDISON74** [comment]
Nice work. This PR makes some changes in the **Backend > System > Configuration**. for example in **Google Sitemap > CMS Pages Options** section. If Frequency = "Do not show in sitemap" Priority and Show lastmod are displayed, although they should not be displayed.

**Before**

before

**After**

after

Similarly in the same section for **Generation Settings**, if it is not enabled, its 5 options are no longer displayed.

I will check all the sections so that nothing is omitted and then I will approve it.

**Comment by ADDISON74** [comment]
The following sections need an evaluation:

**Catalog > Catalog > Product Alerts**
Do we need to display **Price Alert Email Template** and **Stock Alert Email Template**  dropdowns if both **Allow Alert When Product Comes Back to ...** are No?

**Sales > Shipping Methods > UPS**
If **Enabled for checkout** is No there are 7 inputs which are still visible. This is not happening for USPS, FedEx, DHL.

**Comment by sreichel** [comment]
> Do we need to display **Price Alert Email Template** and **Stock Alert Email Template** dropdowns if both **Allow Alert When Product Comes Back to ...** are No?

I have hidden the template selector. 

> Sales > Shipping Methods > UPS
If Enabled for checkout is No there are 7 inputs which are still visible. This is not happening for USPS, FedEx, DHL.

The `<depends>` node is there. I dont know where its coming from.

**Comment by ADDISON74** [comment]
The first issue is solved. The second one needs a solution, all those 7 inputs depends on the first one.

image
=

**Comment by ADDISON74** [comment]
Just delete a node inside <ups>, for example the first one access_license_number, then reload the page. By setting "Enable for Checkout to No", all inputs disappear. There is something strange in the <ups> node.

**Comment by sreichel** [comment]
I think there is some javascript that disables the input for the 7 fields.

I'd leave it as it is.

**Comment by sreichel** [comment]
Missed your last comment ... I have an idea. Will test it later.

**Comment by sreichel** [comment]
Can confirm deleting "access_license_number" works.

Lets fix it another time. Create issue for it.

**Review by ADDISON74 — APPROVED** [review]

**Review by kiatng — APPROVED** [review]

**Pull request merged**
