### PR TITLE
Removed phpstan.dist.issues.neon

### PR DESCRIPTION
**Pull request by sreichel**
### Description (*)

Re-added some supressed phpstan-errors.

This also hides newly introduced errors ...

```
    # Level 2
    - "#Variable \\$+[a-zA-Z_]+ might not be defined.#"
```

### Related Pull Requests

1. See OpenMage/magento-lts#3255

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Comment by fballiano** [comment]
I was wondering why phphstand didn't say anything about that variable. good idea. needs to fix conflict tho

**Comment by ADDISON74** [comment]
I would like to approve this PR but there is a conflict to be solved.

**Comment by fballiano** [comment]
worked on the conflicts, hope I didn't break anything, let's see if phpstan runs in the workflows

**Comment by fballiano** [comment]
if I run it in local I get a lot of errors but I never had a totally working phpstan so I don't trust my local run

**Review by ADDISON74 — APPROVED** [review]

**Comment by fballiano** [comment]
We have to force phpstan to run before approving it

**Comment by ADDISON74** [comment]
OK - let's wait for green.

**Comment by fballiano** [comment]
so ok there are some errors, i'll try to fix them later

**Comment by fballiano** [comment]
all green now
Screenshot 2023-07-19 alle 16 21 46

**Review by ADDISON74 — APPROVED** [review]

**Comment by ADDISON74** [comment]
Good job. Thank you.

**Pull request merged**
