### PR TITLE
Made sitemap more flexible

### PR DESCRIPTION
**Pull request by sreichel**
### Description (*)

https://www.sitemaps.org/protocol.html

For sitemaps `lastmod`, `changefreq` and `priority` are optional,  but actually its not possible to remove these nodes from generated xml.

Code for `getSitemapRow()` is a simplified M2 backport.

changed behavior: if you set changefreq or priority to zero, the xml node is removed.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Review by fballiano — DISMISSED** [review]

**Comment by ADDISON74** [comment]
@fballiano - Did you tested this PR?

**Comment by fballiano** [comment]
Tested and working, the only question I have is that the default now is not to have the "lastmod", @sreichel should we switch it back to enabled by default?

**Comment by sreichel** [comment]
Defalut config value is set to ````1````. It should be enabled?!

**Comment by fballiano** [comment]
when i tested your PR the "lastmod" wasn't generated, but if it was generated by default before the PR maybe it would be correct to keep the same behaviour?

**Comment by sreichel** [comment]
Have you cleared config cache? I've no time to test it, sorry.

**Comment by fballiano** [comment]
> Have you cleared config cache? I've no time to test it, sorry.

aaaaand you're totally right, I didn't clear cache the first time i pulled the pr 🤦🏻‍♂️

**Review by fballiano — DISMISSED** [review]

**Comment by ADDISON74** [comment]
I will test this PR and come back with a feedback.

This label doesn't have a translation in a CSV file ```Mage::helper('sitemap')->__('Do not show in sitemap')```

**Comment by sreichel** [comment]
This PR isn't complete. Translation string is missing. README needs update... maybe someone can do that in a new PR?

**Review by fballiano — DISMISSED** [review]

**Comment by sreichel** [comment]
> modified readme and added translation, although i'm not sure about the readme, it didn't seem that necessary

README has a section for new config options ;)

**Comment by fballiano** [comment]
done!

**Review by fballiano — APPROVED** [review]

**Review by elidrissidev — APPROVED** [review]
Add the missing translation for "Show lastmod", also tested and it works as expected.

**Review by fballiano — APPROVED** [review]

**Review by ADDISON74 — APPROVED** [review]

**Comment by ADDISON74** [comment]
Special invitation for merging this PR.

**Pull request merged**
