### PR TITLE
Worklflow: update copyright monthly

### PR DESCRIPTION
**Pull request by sreichel**
### Description (*)

Added workflow to create a PR to update copyrights once a month.

### Related Pull Requests

- https://github.com/OpenMage/magento-lts/pulls?q=is%3Apr+%22updated+copyright%22
- https://github.com/OpenMage/dev-copyright

### Test

- https://github.com/openmage-strict/openmage-future/pull/41

### CODE REVIEW

**Comment by ADDISON74** [comment]
This is a good idea.

**Review by ADDISON74 — APPROVED** [review]

**Review by ADDISON74 — APPROVED** [review]

**Comment by kiatng** [comment]
Isn't copyright update a yearly thing?

**Comment by sreichel** [comment]
This script updates copyright info based on files last commit date.

It's often missed to update it along a PR. So monthly check seems okay to me.

Do you suggest to update all files at the beginning of a year?

**Review by mattdavenport — APPROVED** [review]
LGTM. I think basing off of the last commit is best, as it is also an indicator of the activity of the project itself. For instance, going to an old website you can tell sometimes if it hasn't been updated based on the copyright tag.

**Pull request merged**
