### PR TITLE
Bugfix #1885 - Add to cart only accepts 1 item

### PR DESCRIPTION
**Pull request by gdemarsico**
### Fixed Issues

1. Fixes OpenMage/magento-lts#1885

### CODE REVIEW

**Review by kiatng — APPROVED** [review]
Ref PR https://github.com/magento/zf1/pull/9

**Review by Flyingmana — APPROVED** [review]

**Comment by luigifab** [comment]
No, I disagree.
`</decimalFormat>>`

**Comment by ADDISON74** [comment]
It was merged with a mistake in a tag as @luigifab mentioned before.

**Comment by kiatng** [comment]
> No, I disagree. `</decimalFormat>>` 😅

My bad. Eyeballing failed. We need a bot for it.

**Pull request merged**
