### PR TITLE
Avoided some "notices" in Mage_GoogleAnalytics_Block_Ga

### PR DESCRIPTION
**Pull request by fballiano**
Since https://github.com/OpenMage/magento-lts/pull/3305 we've a few notices in the log files:

```
ERR (3): Notice: Only variables should be passed by reference  in app/code/core/Mage/GoogleAnalytics/Block/Ga.php on line 301
ERR (3): Notice: Only variables should be passed by reference  in app/code/core/Mage/GoogleAnalytics/Block/Ga.php on line 406
```

This PR solves those

### CODE REVIEW

**Review by ADDISON74 — APPROVED** [review]

**Comment by fballiano** [comment]
@empiricompany could you check this one?

**Comment by empiricompany** [comment]
> @empiricompany could you check this one?
please check this commit
https://github.com/OpenMage/magento-lts/commit/db60c7b29e801f4e33092e521b17ada7b00d217f

**Comment by fballiano** [comment]
@empiricompany I've checked your commit but I'd kinda approve this PR and then create your separate PR since it's slightly different, ok?

**Comment by empiricompany** [comment]
> @empiricompany I've checked your commit but I'd kinda approve this PR and then create your separate PR since it's slightly different, ok?

ok

**Review by empiricompany — APPROVED** [review]

**Comment by fballiano** [comment]
closed in favor of https://github.com/OpenMage/magento-lts/pull/3342

**Pull request closed without merging**
