### PR TITLE
Some more room for the category menu

### PR DESCRIPTION
**Pull request by loekvangool**
And replacing the background image with a border.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by loekvangool** [comment]
Before:

image

After:

image

**Comment by jouriy** [comment]
In my opinion skin/adminhtml/default/openmage/scss/override.scss would be a better place for all new CSS improvements instead of direct modifications in fallback legacy theme.

**Comment by ADDISON74** [comment]
Personally, I encourage solving bugs in the default theme rather than changes that look like and can be operated in a single file, in this case styles.css. This is because appearance changes are often a subjective matter and without a UX / UI team in the background a detailed analysis of the changes cannot be performed.

At this point there is a nice theme for the Magento backend that I tested and it offered several look options. I don't remember if it was available a SCSS file or not with this theme.

After 12 years of using the Magento interface, I came to learn about its pros and cons. I consider a real improvement for example the ascending sorting of the attributes or their search in the editing page of a set of attributes than a visual improvement.

**Comment by loekvangool** [comment]
>I consider a real improvement for example the ascending sorting of the attributes or their search in the editing page of a set of attributes than a visual improvement.

I would love to have that.

**Comment by ADDISON74** [comment]
@loekvangool: please take a look to this post: https://github.com/OpenMage/magento-lts/issues/1289.

**Review by fballiano — APPROVED** [review]
I made the border lighter but I think this is a good PR

**Review by ADDISON74 — APPROVED** [review]

**Comment by ADDISON74** [comment]
If it were up to me I would have removed the dividing line between the category tree and the grid. It looks much better without it. Only if the width for the category tree container was allowed to be resized then I would have kept a line with a thickness of 2px (half of the header page bottom border). I guess I saw a PR which implements this future.

This is the vertical line:

```css
.columns {background:url(https://www.mydomain.tld/skin/adminhtml/default/default/images/side_col_bg.gif) repeat-y 217px 0;;}
```

I'm not a fan of the bottom borders under the header either, that has 4px. I consider this line useless, eliminating it would solve more visual problems. It is obvious that the interface was designed for the times when it was an obsession to separate the content as much as possible. Much like the gradient buttons, animated gifs, flash content.

category_page

**Comment by luigifab** [comment]
There is something wrong.
It "destroy" the system configuration menu (before/after):

image image

**Comment by ADDISON74** [comment]
If I am not mistaken there is a JavaScript-based solution that allows resizing the category tree block. That is the best option because you can adjust it as you wish. It won't work only from CSS because you will not be able to solve all situations, some will have too much space, others too small.

In this case I suggest reverting this PR. That right border looks ugly. I also don't like to see those left side tabs so wide. It is clear that I approved this PR without testing it enough. These are situations when things that are not at all complicated at first glance can cause problems.

**Comment by ADDISON74** [comment]
I tested this PR and I confirm the issue reported by @luigifab . The change was made in a class that affects in the Backend all the left side columns. Here's what the change implemented in some sections of the Backend looks like:

**Categories**

categories

**Products**

products

**Configuration**

system

The width of the tabs changes and becomes unsightly, we have an extra vertical line, the right border of the container is thickened. This PR must be reversed at once. As I said in my previous post, who has the issue with the lack of space in categories, either makes a personal change or looks for that module which uses JavaScript in the resizing of the container by pulling the gray edge to its right.

**Comment by fballiano** [comment]
I don't see what you see but I'm working on a fix

**Comment by fballiano** [comment]
done, please check https://github.com/OpenMage/magento-lts/pull/2251

**Comment by loekvangool** [comment]
Strange, I don't remember running into these issues. I'm not interested in pursuing this old issue though, let's leave it to rest.

**Comment by fballiano** [comment]
It was merged so we can't leave it as it is

**Comment by ADDISON74** [comment]
This extension seems to do the resize of the category tree in a better way than using fixed value in CSS files.

https://github.com/yireo-magento1/Yireo_CategoryTreeResizable

It can be customized by removing some JS files as long as JQuery v1 is shipped with OpenMage.

Anyway I will analyze this issue and I will come back later with a better default value for the width of the container.

**Pull request merged**
