### PR TITLE
Fixes `Mage_Core_Helper_Url::removeRequestParam()` for `___SID`/`SID`

### PR DESCRIPTION
**Pull request by sreichel**
### Description (*)

`Mage_Core_Helper_Url::removeRequestParam()` uses `preg_replace` or `str_replace` that can lead to malformed urls for partial matches.

### Fixed Issues (if relevant)

1. Fixes OpenMage/magento-lts#4294

### Manual testing scenarios (*)

```php
$url = 'https://example.com?___SID=S&SID=S&foo=bar&boo=baz';
Mage::helper('core/url')->removeRequestParam(
    $url,
    Mage::getSingleton('core/session')->getSessionIdQueryParam()
);
```

`getSessionIdQueryParam()` returns `SID`, that should be removed.

#### Expected

`https://example.com?___SID=S&foo=bar&boo=baz`

#### Current

`https://example.com?___foo=bar&boo=baz`

### CODE REVIEW

**Comment by ADDISON74** [comment]
@Hanmac - is this PR solving your issue? I tested and it works.

**Comment by sreichel** [comment]
THe PR only fixes building correct URLs, but there ist another problem ...

Default session-ID parameter is `SID`, but in some cases `___SID` is used.

**Comment by Hanmac** [comment]
Maybe return early if the URL doesn't have '?'

**Comment by sreichel** [comment]
Yep. Updated.

**Review by Hanmac — APPROVED** [review]

**Review by ADDISON74 — APPROVED** [review]

**Review by kiatng — APPROVED** [review]

**Pull request merged**
