### PR TITLE
Bump dev-meta-package to 1.0.2

### PR DESCRIPTION
**Pull request by fballiano**
This should fix the PHPCS errors we're getting when workflows run.

### CODE REVIEW

**Comment by fballiano** [comment]
I've no idea why it doesn't work

**Comment by elidrissidev** [comment]
Seems like it's still installing the package from the old HEAD (https://github.com/OpenMage/dev-translations/commit/cace35f0901a3be333b6b09ca78a36c207ce3c5b):
```log
- Installing openmage/dev-translations (dev-main cace35f): Extracting archive
```
I suspect a cache somewhere is causing this.

**Comment by elidrissidev** [comment]
I think I found the problem, you need to explicitly update the translations package as well `composer update openmage/dev-meta-package`, because the old commit id is still being referenced from `composer.lock`.

**Comment by fballiano** [comment]
to generate this PR I run exactly `/usr/local/opt/php@7.4/bin/php /usr/local/bin/composer update openmage/dev-meta-package` and if I run it again the diff is empty :-\

**Comment by elidrissidev** [comment]
Oops sorry I meant `openmage/dev-translations`, update my comment.

**Comment by fballiano** [comment]
mmmm interesting, I did a `/usr/local/opt/php@7.4/bin/php /usr/local/bin/composer update openmage/dev-translation` but again no diff :-\

**Comment by elidrissidev** [comment]
Weird, it's updating `composer.lock` for me when I run it:


Screen Shot 2023-03-22 at 5 45 55 PM

**Comment by elidrissidev** [comment]
It's only doing that because I discarded the version upgrade of `dev-meta-package` from my `composer.lock` that I did a few minutes ago, it shouldn't do that normally. I'll try pushing the update.

**Review by elidrissidev — APPROVED** [review]

**Review by ADDISON74 — APPROVED** [review]

**Comment by fballiano** [comment]
merged and 20ed!

**Pull request merged**
