### PR TITLE
Fix cache : Config Cache Corruption Fix - 100 Router Match Iterations…

### PR DESCRIPTION
**Pull request by seansan**
… - Object Caching and Race Conditions

Config Cache Corruption Fix - 100 Router Match Iterations - Object Caching and Race Conditions

https://github.com/convenient/magento-ce-ee-config-corruption-bug/blob/master/IMPROVEMENTS.md

**Please check my code additions**

### CODE REVIEW

**Comment by seansan** [comment]
Our server ran into this issue last night: quite terrible!

**Comment by LeeSaferite** [comment]
While I like the idea, I take issue with how you made the changes. You've put the proprty in the middle of the class and even worse you split the method docblock away from the method to do this.

Please clean up the PR by moving the new property into the top of the class. Also, I think having a single link to the ratiional behind the fix is sufficient. I would suggest you attach a good description and link to the docblock for the property itself.

If you can clean up the PR I'll review it and have some others do the same. Assuming it doesn't break things (doesn't initially look like it would) then I'll merge the PR.

Thanks!

**Comment by seansan** [comment]
Please check again

https://github.com/OpenMage/magento-lts/pull/77/files

**Comment by seansan** [comment]
@LeeSaferite would be great to merge

**Comment by LeeSaferite** [comment]
@drobinson @Flyingmana Do you guys see any issues here? Can I merge this?

**Comment by tmotyl** [comment]
I had this fix (https://github.com/convenient/magento-ce-ee-config-corruption-bug/blob/master/IMPROVEMENTS.md) applied in one project and it fixed the issue.

**Comment by seansan** [comment]
Posting an easier and more confirmed fix

**Comment by tmotyl** [comment]
Maybe the chmod was a soultion in that particular case, but the race condition issue still exists.

**Comment by seansan** [comment]
Hmmm may be true. Did you find an acceptable fix?






Sent from my iPhone.

On 16 Aug 2016, at 09:57, Tymoteusz Motylewski <notifications@github.com> wrote:

Maybe the chmod was a soultion in that particular case, but the race condition issue still exists.

**Comment by tmotyl** [comment]
see above - https://github.com/convenient/magento-ce-ee-config-corruption-bug/blob/master/IMPROVEMENTS.md

**Comment by seansan** [comment]
should we add this as a pull request?

seems 2 changes: 1 fix, 1 improvement

**Pull request closed without merging**
