### PR TITLE
Fix SOAP error

### PR DESCRIPTION
**Pull request by drobinson**
See http://magento.stackexchange.com/questions/140761/soap-connection-problems-after-1-9-3-0-update

### CODE REVIEW

**Comment by infabo** [comment]
could be an array?

**Comment by infabo** [comment]
could be an array?

**Comment by colinmollenhour** [comment]
Yes, so:

~~~
if (is_string($row)) {
 ...
} else if (is_array($row)) {
 ...
}
~~~

**Comment by infabo** [comment]
Yes, for the first if. for the second one just

```php
if(is_string($result)) {...}
```

**Comment by cieslix** [comment]
the **processingRow** is using internally **preg_replace_callback** it accepts just array or string if $row is an array it calls **processingMethodResult** (recursion), so the following method should be fine.

```
    public function processingMethodResult($result)
    {
        if (is_array($result)) {
            foreach ($result as &$row) {
                $row = $this->processingMethodResult($row);
            }
        } elseif (is_string($result)) {
            $result = $this->processingRow($result);
        }
        return $result;
    }
```

@drobinson can you check if this work as intended ?

**Comment by colinmollenhour** [comment]
Was fixed in 1.9.3.1

**Pull request closed without merging**
