### PR TITLE
Replacing Admin Notifications feed URL

### PR DESCRIPTION
**Pull request by netalico**
This will allow us to control the Feed so that only relevant/important notifications are displayed to merchants.

### CODE REVIEW

**Comment by kkrieger85** [comment]
@colinmollenhour @Flyingmana Could you please review?

**Comment by Flyingmana** [comment]
could please someone check how it works and post a screenshot here?

**Comment by spinsch** [comment]
> could please someone check how it works and post a screenshot here?

it works when the flag "use_https" is set.
http request returns 301 to redirect https and this will broken the feed update.

Configuration___System___Magento_Admin

**Comment by Flyingmana** [comment]
ahh yes, I enforce https on the website (for reasons)
is Magento using http by default?

the ReadMore is a link to the post, or showing post content inside Magento?

but in general, seems to work, thats good :)

**Comment by spinsch** [comment]
yes magento use "http" by default.

"Read detail" goto => https://openmage.github.io/Web_Notifications//2019/06/24/OpenMage.html

**Pull request merged**
