### PR TITLE
Dropped useless semicolons

### PR DESCRIPTION
**Pull request by sreichel**

### CODE REVIEW

**Comment by Flyingmana** [comment]
For this specific change, Iam against.
But maybe I do not understand the benefit.
Which Coding Style/Tool does recommend removing them, and for what reason?

**Comment by sreichel** [comment]
> For this specific change, Iam against.
> But maybe I do not understand the benefit.
> Which Coding Style/Tool does recommend removing them, and for what reason?

Oh, thought this is a no-brainer ... These semicolons are superfluous and i guess nobody would write code like this. Also phpStorm shows a weak warning for.

IMHO ... M1 is EoL very soon, so why not fix also small code style issues?

**Comment by tmotyl** [comment]
@Flyingmana to valiate you can run php lint on these classes.
I also think this is a nobrainer

**Comment by kiatng** [comment]
The benefit is coding style consistency.

**Pull request merged**
