### PR TITLE
Remove files from lib/Zend that exist in Magentos core/Zend

### PR DESCRIPTION
**Pull request by sreichel**
### Description (*)

Remove files from `lib/Zend` that are loaded from `app/code/core/Zend`

### Fixed Issues (if relevant)

- https://github.com/OpenMage/magento-lts/issues/374#issuecomment-348444227

### Questions or comments

I hope this doesn't interfere with plans to remove old Zend classes.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ADDISON74** [comment]
Why this commit was closed? It should be merged in OpenMage.

**Review by colinmollenhour — APPROVED** [review]

**Review by luigifab — APPROVED** [review]

**Comment by fballiano** [comment]
can't merge because of conflicts

**Comment by ADDISON74** [comment]
Probably changes are needed to adapt ZF1-Future to OpenMage. We can keep /app/code/core/Zend directory with new files customized and update only ZF1-Future in /lib/Zend. If new changes are necessary in /app/code/core/Zend we can do it by PR's. It won't be a problem to check immediately from one version to another if it is something new in ZF1-Future to determine us to the customized files.

**Comment by sreichel** [comment]
Done with #2827

**Pull request closed without merging**
