### PR TITLE
Fixed check if ConfigurableSwatches is enabled

### PR DESCRIPTION
**Pull request by luigifab**
### Description

If you use configurable swatches, but not in product list, it's not useful to execute `productListCollectionLoadAfter`. Found with Blackfire many weeks ago.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

### CODE REVIEW

**Comment by fballiano** [comment]
Mage_ConfigurableSwatches_Helper_Data::isEnabled() checks something similar:

Screenshot 2022-11-17 alle 16 50 17

isn't it working or should maybe the isEnabled() method be fixed?

**Comment by luigifab** [comment]
I will check that.

**Comment by luigifab** [comment]
Without the current PR I have:
image

With the PR, I have:
image

**Comment by luigifab** [comment]
Perhaps we can modify `isEnabled`:
```php
    public function isEnabled()
    {
        if (is_null($this->_enabled)) {
            $this->_enabled = (
                Mage::getStoreConfigFlag(self::CONFIG_PATH_ENABLED)
                && !empty(Mage::getStoreConfig(Mage_ConfigurableSwatches_Helper_Data::CONFIG_PATH_LIST_SWATCH_ATTRIBUTE))
                && Mage::helper('configurableswatches/productlist')->getSwatchAttribute()
            );
        }
        return $this->_enabled;
    }
```
I didn't search who calls `isEnabled`. Perhaps this break swatches on product page.

**Review by fballiano — APPROVED** [review]
I've debugged and rewrote this PR, it works and I think it's in a good form now.

**Review by empiricompany — APPROVED** [review]

**Review by kiatng — APPROVED** [review]

**Comment by ADDISON74** [comment]
@DegrizNet - could you please post two screenshots, before and after the change?

**Comment by DegrizNet** [comment]
> && Mage::helper('configurableswatches/productlist')->getSwatchAttribute

Here is video:
https://screenrec.com/share/NDwebU75tY

It is a little weird and maybe can be related only to this shop (v20.5.0) as I have also tested and it is working with getSwatchAttributeId on my demo shop (v20.3.0). Also tested with rwd theme and same results.

**Comment by ADDISON74** [comment]
I used the following test environment

- OpenMage 20.5.0
- Magento Sample Data
- RWD Theme
- DDEV (Apache + PHP 8.3 + MariaDB)

This is before - **getSwatchAttributeId()**

before

This is after - **getSwatchAttribute()**

after


In my opinion this PR has no visual effect in Frontend.

**Comment by ADDISON74** [comment]
Let's go further and do the following configuration in Backend

configuration

This is the Frontend for **getSwatchAttributeId()**

bug

I confirm the bug reported by @DegrizNet. We have to revert this PR.

**Pull request merged**
