### PR TITLE
Fixed null parameter warning in Mage_Catalog_Model_Layer_Filter_Attribute

### PR DESCRIPTION
**Pull request by fballiano**
Fixes https://github.com/OpenMage/magento-lts/issues/3925

### CODE REVIEW

**Comment by ioweb-gr** [comment]
Nope it didn't work for me for a URL of the type 

/mobile-phones?core_count=41&gdiktia=168&nfcsosto=376&ram=50%2C54

or 
/mobile-phones?core_count=41&gdiktia=168&nfcsosto=376&ram=50,54

**Comment by ioweb-gr** [comment]
That's because _getOptionText returns false

**Comment by ioweb-gr** [comment]
How about this ? 

```php
        $text = $this->_getOptionText($filter);
        if ($filter && !empty($text)) {
            $this->_getResource()->applyFilterToCollection($this, $filter);
            $this->getLayer()->getState()->addFilter($this->_createItem($text, $filter));
            $this->_items = [];
        }
```

**Comment by fballiano** [comment]
right, can you check this new version?

it seems to me that $text really needs to be a string for:
`$this->getLayer()->getState()->addFilter($this->_createItem($text, $filter));`
to work

**Comment by ioweb-gr** [comment]
That also works

**Comment by fballiano** [comment]
if you confirm me that it works I'll merge it right away and release a 20.6

**Comment by ioweb-gr** [comment]
Yeah I already checked it, it didn't throw the error.

**Comment by fballiano** [comment]
let's consider this as a review and merge it

**Pull request merged**
