### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by sreichel**
### Description (*)

Removed maintainers sections, thats not up 2 date.

### CODE REVIEW

**Comment by Axepih** [comment]
Hello, Can you update the discord link if it's still in use?

**Comment by sreichel** [comment]
> Hello, Can you update the discord link if it's still in use?

Umm. I dont use Discord at all. @Flyingmana told me he will close it, but i never checked.

Removed links.

**Comment by justinbeaty** [comment]
https://discord.gg/R2q5WadstX

**Comment by sreichel** [comment]
Still maintained by Daniel?

**Comment by justinbeaty** [comment]
idk, he hasn't posted there in a long time, but there's still activity.

**Review by colinmollenhour — APPROVED** [review]
I started doing this a while back, was going to add an email address that would notify the maintainers channel in Discord, but couldn't get it working... This is good, though. Thanks!

**Review by addison74 — APPROVED** [review]

**Pull request merged**
