### PR TITLE
Switched DOCTYPE to HTML5 for base theme

### PR DESCRIPTION
**Pull request by fballiano**
I thought it may be time to migrate away from XHTML 1.0 and switch the doctype for base templates to HTML5.

### CODE REVIEW

**Review by ADDISON74 — APPROVED** [review]

**Comment by Flyingmana** [comment]
lets hope there is no odd xhtml feature we did rely on

**Review by Flyingmana — APPROVED** [review]

**Review by m-overlund — APPROVED** [review]

**Comment by m-overlund** [comment]
Should admin be fixed too?

**Comment by fballiano** [comment]
thanks guys!
@m-overlund I'll check admin ASAP

**Comment by ADDISON74** [comment]
Indeed, there are 15 files remaining 

https://github.com/search?q=repo%3AOpenMage%2Fmagento-lts%20PUBLIC%20%22-%2F%2FW3C%2F%2FDTD%20XHTML%201.0%20Strict%2F%2FEN%22%20%22http%3A%2F%2Fwww.w3.org%2FTR%2Fxhtml1%2FDTD%2Fxhtml1-strict.dtd%22&type=code

**Comment by fballiano** [comment]
@ADDISON74 https://github.com/OpenMage/magento-lts/pull/3579 ;-)

**Comment by ADDISON74** [comment]
There are three files more

/app/design/install/default/default/template/page.phtml
/app/locale/en_US/template/email/html/header.html
/errors/default/page.phtml

**Pull request merged**
