### PR TITLE
Openmage admin theme: Change background-color for active sections

### PR DESCRIPTION
**Pull request by sreichel**
### Description (*)

Lightgrey background for active sections.

No changes for legacy theme. Dont want to work with plain CSS files.

Maybe someone wants to add SCSS-files for it .... there are some online converters, that do it.

### Fixed Issues (if relevant)

1. Fixes OpenMage/magento-lts#4207

### CODE REVIEW

**Comment by ADDISON74** [comment]
I am not using the OpenMage Backend theme but I will give it a try. Please post a few screenshots to understand what is wrong and how looks the fix.

**Comment by sreichel** [comment]
Neither in legacy nor in openmage theme active section /menu is highlighted. There is only a hover-effect.

After this PR the active section/menu is not white, its lightgrey.

over

**Comment by ADDISON74** [comment]
It works as expected for the OpenMage theme.

For Magento legacy theme there was a discussion here https://github.com/OpenMage/magento-lts/issues/3452#issuecomment-1685092144.

**Review by ADDISON74 — APPROVED** [review]

**Comment by sreichel** [comment]
For legacy theme, please add SCSS files ;)

Here you go https://jsonformatter.org/css-to-scss ...

**Review by kiatng — APPROVED** [review]

**Pull request merged**
