### PR TITLE
ensure value is string to avoid type error in used library

### PR DESCRIPTION
**Pull request by Flyingmana**
### Description (*)
There was an error on PHP 8.2 about urlencode() expecting a string.
Should probably get fixed upstream in `\Zend_Locale_Data::getList` / `vendor/shardj/zf1-future/library/Zend/Locale/Data.php`

### Related Pull Requests
https://github.com/OpenMage/magento-lts/pull/3234 (resolves an error reported there)

### Fixed Issues (if relevant)

1. Fixes OpenMage/magento-lts#<issue_number>

### Manual testing scenarios (*)
have error reporting -1
cleared cache
login into admin area

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)
 - [ ] Add yourself to contributors list

### CODE REVIEW

**Comment by Flyingmana** [comment]
although Iam not sure why we have this issue, as we depend on a version which should already have this fix https://github.com/Shardj/zf1-future/blob/release-1.23.5/library/Zend/Locale/Data.php#L336

**Comment by fballiano** [comment]
I can't seem to reproduce the error, the version of the file that I have already has the cast to string:

Screenshot 2023-10-01 alle 21 37 24

**Comment by Flyingmana** [comment]
yeah, not sure, maybe updating the source without updating the composer dependencies(thats what happened for me when I tested it first).

It was reported, so I think its at least worth to consider fixing it there, even as in theory it should not be possible to happen.

**Comment by fballiano** [comment]
maybe it was using a OM version before the one when we strictly required zf1f version?

**Comment by fballiano** [comment]
At the moment I'll close this, still can't reproduce, probably it's being fixed in a previous release ;-)

**Pull request closed without merging**
